### PR TITLE
Add random delays to communication to server

### PR DESCRIPTION
**Pull request by tomtor**
in times of failure due to high load.

This overlaps with https://github.com/glinscott/fishtest/pull/150
but has slightly different characteristics

### CODE REVIEW

**Comment by xoto10** [comment]
This makes sense, and covers my comments on #150. You have used lower values than I would ... but that might be OK - up to 60s is considerably longer than the current sleep.

**Comment by Stefano80** [comment]
@tomtor :  looks good, but you have to update the worker version, please check previous commits, you'll see what I mean. I will have some time over the week-end to merge this.

**Comment by tomtor** [comment]
@Stefano80 Do you just mean bump it to 62?

No problem, but shouldn't you do that when merging, because authors don't know when their PRs are merged and what the current number will be?

**Comment by tomtor** [comment]
@Stefano80 Bumped version to 62 for ease of merging

**Comment by Stefano80** [comment]
@tomtor : you're right, I somehow disclosed my plan of merging this first. I prefer your version and I will close mine. If I don't hear anything from @ppigazzini I will merge.

**Comment by Stefano80** [comment]
Closed, [merged](https://github.com/glinscott/fishtest/commit/13b84dbfdff55b661f529498d870f537db9c11fa), server successfully restarted, [worker thread on fish cooking bumped](https://groups.google.com/forum/?fromgroups=#!searchin/fishcooking/stefano$20update%7Csort:date/fishcooking/UPirLLJg8ZM/uIB8poTmAgAJ).

**Comment by xoto10** [comment]
Great! This should solve the problem of the server slowing down when there isn't much work. :-)

I am monitoring the time to retrieve the main tests page so will see if it helps.

**Pull request merged**
