### PR TITLE
More task diagnostics and fix reallocated worker logic

### PR DESCRIPTION
**Pull request by tomtor**

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor DEV updated, started some workers.

**Comment by tomtor** [comment]
Add test on `unique_key` after merge of #858

**Comment by ppigazzini** [comment]
DEV updated, the workers are running fine.

**Comment by ppigazzini** [comment]
@tomtor Travis errors
```
======================================================================
ERROR: test_failed_task (test_api.TestApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/glinscott/fishtest/server/tests/test_api.py", line 233, in test_failed_task
    response = ApiView(request).failed_task()
  File "/home/travis/build/glinscott/fishtest/server/fishtest/api.py", line 185, in failed_task
    return self.request.rundb.failed_task(self.run_id(), self.task_id(), self.get_unique_key())
  File "/home/travis/build/glinscott/fishtest/server/fishtest/api.py", line 61, in get_unique_key
    return self.request.json_body["worker_info"]["unique_key"]
KeyError: 'worker_info'
======================================================================
ERROR: test_request_spsa (test_api.TestApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/glinscott/fishtest/server/tests/test_api.py", line 319, in test_request_spsa
    response = ApiView(request).request_spsa()
  File "/home/travis/build/glinscott/fishtest/server/fishtest/api.py", line 258, in request_spsa
    return self.request.rundb.request_spsa(self.run_id(), self.task_id())
  File "/home/travis/build/glinscott/fishtest/server/fishtest/rundb.py", line 986, in request_spsa
    run["_id"], task["worker_info"]["unique_key"], result["w_params"]
KeyError: 'worker_info'
----------------------------------------------------------------------
Ran 21 tests in 11.640s
```

**Comment by ppigazzini** [comment]
DEV updated, all it's working fine.

**Comment by tomtor** [comment]
@ppigazzini Fixed travis API test and formatting

**Comment by ppigazzini** [comment]
DEV updated, server and workers are fine (the workers errors are due to the mongodb sync)

```
sudo journalctl -u fishtest@6543 --since today

...
Nov 07 09:43:23 vps1572612706 pserve[10365]: dead task: run: https://tests.stockfishchess.org/tests/view/5fa61038936c54e11ec9956d task_id: 97 worker: ChessDBCN-8cores-91
Nov 07 09:43:23 vps1572612706 pserve[10365]: dead task: run: https://tests.stockfishchess.org/tests/view/5fa61038936c54e11ec9956d task_id: 98 worker: ChessDBCN-16cores-92
Nov 07 09:43:23 vps1572612706 pserve[10365]: dead task: run: https://tests.stockfishchess.org/tests/view/5fa61038936c54e11ec9956d task_id: 99 worker: ChessDBCN-16cores-93
Nov 07 09:43:23 vps1572612706 pserve[10365]: dead task: run: https://tests.stockfishchess.org/tests/view/5fa584db936c54e11ec9950a task_id: 371 worker: dew-4cores-9
Nov 07 09:43:23 vps1572612706 pserve[10365]: dead task: run: https://tests.stockfishchess.org/tests/view/5fa584db936c54e11ec9950a task_id: 372 worker: JojoM-7cores-6
Nov 07 09:43:23 vps1572612706 pserve[10365]: dead task: run: https://tests.stockfishchess.org/tests/view/5fa584db936c54e11ec9950a task_id: 377 worker: tvijlbrief-16cores-2
Nov 07 09:43:23 vps1572612706 pserve[10365]: dead task: run: https://tests.stockfishchess.org/tests/view/5fa584db936c54e11ec9950a task_id: 378 worker: ChessDBCN-16cores-94
Nov 07 09:53:59 vps1572612706 pserve[10365]: Inactive: https://tests.stockfishchess.org/tests/view/5fa66c11c83763bec00f6e82 1 user00-3cores
Nov 07 09:54:26 vps1572612706 pserve[10365]: Inactive: https://tests.stockfishchess.org/tests/view/5fa66c11c83763bec00f6e82 1 user00-5cores-1
Nov 07 10:07:35 vps1572612706 systemd[1]: Stopping Fishtest Server port 6543...
Nov 07 10:07:35 vps1572612706 pserve[10365]: flush
Nov 07 10:07:35 vps1572612706 pserve[10365]: .done
Nov 07 10:07:36 vps1572612706 systemd[1]: Stopped Fishtest Server port 6543.
Nov 07 10:08:22 vps1572612706 systemd[1]: Started Fishtest Server port 6543.
Nov 07 10:15:46 vps1572612706 systemd[1]: Stopping Fishtest Server port 6543...
Nov 07 10:15:46 vps1572612706 pserve[12238]: Starting server in PID 12238.
Nov 07 10:15:46 vps1572612706 pserve[12238]: Serving on http://localhost:6543
Nov 07 10:15:46 vps1572612706 pserve[12238]: flush
Nov 07 10:15:46 vps1572612706 pserve[12238]: done
Nov 07 10:15:47 vps1572612706 systemd[1]: Stopped Fishtest Server port 6543.
Nov 07 10:16:30 vps1572612706 systemd[1]: Started Fishtest Server port 6543.
Nov 07 10:34:10 vps1572612706 pserve[13050]: Starting server in PID 13050.
Nov 07 10:34:10 vps1572612706 pserve[13050]: Serving on http://localhost:6543
Nov 07 10:34:10 vps1572612706 pserve[13050]: flush
Nov 07 10:34:10 vps1572612706 systemd[1]: Stopping Fishtest Server port 6543...
Nov 07 10:34:10 vps1572612706 pserve[13050]: .done
Nov 07 10:34:12 vps1572612706 systemd[1]: Stopped Fishtest Server port 6543.
Nov 07 10:34:55 vps1572612706 systemd[1]: Started Fishtest Server port 6543.

```

**Comment by ppigazzini** [comment]
@tomtor I will return online in 3 hours

**Comment by tomtor** [comment]
@ppigazzini I could squash the last 2 commits, but they are not really related.

**Comment by ppigazzini** [comment]
This is the log
```
Nov 07 15:00:41 vps1572612706 pserve[30874]: Traceback (most recent call last):
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/tweens.py", line 13, in _error_handler
Nov 07 15:00:41 vps1572612706 pserve[30874]:     response = request.invoke_exception_view(exc_info)
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/view.py", line 779, in invoke_exception_view
Nov 07 15:00:41 vps1572612706 pserve[30874]:     raise HTTPNotFound
Nov 07 15:00:41 vps1572612706 pserve[30874]: pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
Nov 07 15:00:41 vps1572612706 pserve[30874]: During handling of the above exception, another exception occurred:
Nov 07 15:00:41 vps1572612706 pserve[30874]: Traceback (most recent call last):
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/waitress/channel.py", line 350, in service
Nov 07 15:00:41 vps1572612706 pserve[30874]:     task.service()
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/waitress/task.py", line 171, in service
Nov 07 15:00:41 vps1572612706 pserve[30874]:     self.execute()
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/waitress/task.py", line 441, in execute
Nov 07 15:00:41 vps1572612706 pserve[30874]:     app_iter = self.channel.server.application(environ, start_response)
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/waitress/proxy_headers.py", line 65, in translate_proxy_headers
Nov 07 15:00:41 vps1572612706 pserve[30874]:     return app(environ, start_response)
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/router.py", line 270, in __call__
Nov 07 15:00:41 vps1572612706 pserve[30874]:     response = self.execution_policy(environ, self)
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/router.py", line 279, in default_execution_policy
Nov 07 15:00:41 vps1572612706 pserve[30874]:     return request.invoke_exception_view(reraise=True)
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/view.py", line 778, in invoke_exception_view
Nov 07 15:00:41 vps1572612706 pserve[30874]:     reraise_(*exc_info)
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/compat.py", line 179, in reraise
Nov 07 15:00:41 vps1572612706 pserve[30874]:     raise value
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/router.py", line 277, in default_execution_policy
Nov 07 15:00:41 vps1572612706 pserve[30874]:     return router.invoke_request(request)
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/router.py", line 249, in invoke_request
Nov 07 15:00:41 vps1572612706 pserve[30874]:     response = handle_request(request)
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/tweens.py", line 43, in excview_tween
Nov 07 15:00:41 vps1572612706 pserve[30874]:     response = _error_handler(request, exc)
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/tweens.py", line 17, in _error_handler
Nov 07 15:00:41 vps1572612706 pserve[30874]:     reraise(*exc_info)
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/compat.py", line 179, in reraise
Nov 07 15:00:41 vps1572612706 pserve[30874]:     raise value
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/tweens.py", line 41, in excview_tween
Nov 07 15:00:41 vps1572612706 pserve[30874]:     response = handler(request)
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/router.py", line 147, in handle_request
Nov 07 15:00:41 vps1572612706 pserve[30874]:     response = _call_view(
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/view.py", line 667, in _call_view
Nov 07 15:00:41 vps1572612706 pserve[30874]:     response = view_callable(context, request)
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
Nov 07 15:00:41 vps1572612706 pserve[30874]:     result = view(context, request)
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid/viewderivers.py", line 116, in _class_requestonly_view
Nov 07 15:00:41 vps1572612706 pserve[30874]:     response = getattr(inst, attr)()
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/fishtest/api.py", line 180, in update_task
Nov 07 15:00:41 vps1572612706 pserve[30874]:     unique_key=self.get_unique_key()
Nov 07 15:00:41 vps1572612706 pserve[30874]:   File "/home/usr00/fishtest/server/fishtest/api.py", line 61, in get_unique_key
Nov 07 15:00:41 vps1572612706 pserve[30874]:     return self.request.json_body["worker_info"]["unique_key"]
Nov 07 15:00:41 vps1572612706 pserve[30874]: KeyError: 'worker_info'
Nov 07 15:00:56 vps1572612706 pserve[30874]: Inactive: https://tests.stockfishchess.org/tests/view/5fa66be0c83763bec00f6e80 154 user00-5cores-4
Nov 07 15:01:19 vps1572612706 pserve[30874]: Inactive: https://tests.stockfishchess.org/tests/view/5fa66bc5c83763bec00f6e7e 186 user00-5cores-4
```

**Comment by tomtor** [comment]
@ppigazzini I updated #860 to add a fix for the error.

**Comment by ppigazzini** [comment]
@tomtor DEV and workers updated.

Travis error:
```
======================================================================
FAIL: test_beat (test_api.TestApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/glinscott/fishtest/server/tests/test_api.py", line 347, in test_beat
    self.assertEqual("Pleased to hear from you...", response)
AssertionError: 'Pleased to hear from you...' != '-'
- Pleased to hear from you...
+ -
----------------------------------------------------------------------
Ran 21 tests in 11.385s
FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=21 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=21 errors=0 failures=1>
The command "./test_server.sh" exited with 1.
```

**Comment by ppigazzini** [comment]
DEV and workers updated (also with #861 and #862).

**Comment by ppigazzini** [comment]
PROD updated, thank you @tomtor :)

**Review by ppigazzini — APPROVED** [review]

**Pull request merged**
