### PR TITLE
Rename fishtest server code dir

### PR DESCRIPTION
**Pull request by tomtor**
@ppigazzini This fixes a ton of problems for Vscode IDE and some mentals problems for me with the old nested `fishtest/fishtest` directory naming.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor `fishtest/fishtest/fishtest`, triple level on the VPS :)
I double check the setup script, crontab, nginx etc.

**Comment by ppigazzini** [comment]
@tomtor DEV running with the PR, 7 changes required.

Please change this:
https://github.com/glinscott/fishtest/blob/e521fcc06200ff060c4086aeb2e502718ad0a828/.gitignore#L4-L5

**Comment by ppigazzini** [comment]
@tomtor PROD updated by hand, please rebase and fix `.gitignore`.

**Comment by tomtor** [comment]
@ppigazzini merged and installed on prod.

**Comment by tomtor** [comment]
@ppigazzini no restart yet, so old modifications by hand will still be active.

**Comment by tomtor** [comment]
@ppigazzini Old files in `server.old`, moved `env/` to new `server` dir.

**Comment by ppigazzini** [comment]
Wiki scripts updated.
Here are the changes required:
1. `/etc/nginx/sites-available/fishtest.conf`
    location ~ ^/(css|html|img|js|favicon.ico|robots.txt) {
        root        /home/fishtest/fishtest/**fishtest**/fishtest/static;

2. `/home/fishtest/.profile`
export VENV="$HOME/fishtest/**fishtest**/env"

3. `crontab -e`
VENV=/home/fishtest/fishtest/**fishtest**/env
UPATH=/home/fishtest/fishtest/**fishtest**/utils

4. `/home/fishtest/fishtest/.gitignore`
**fishtest**/env
**fishtest**/fishtest_server.egg-info

5. /home/fishtest/x/update_fishtest.sh
${VENV}/bin/python3 -m pip install --upgrade pip setuptools wheel
cd ${HOME}/fishtest/**fishtest**
${VENV}/bin/python3 -m pip install -e .

6. `/etc/systemd/system/fishtest@.service`
ExecStart=/home/fishtest/fishtest/**fishtest**/env/bin/pserve production.ini http_port=%i
Restart=on-failure
RestartSec=3
User=fishtest
WorkingDirectory=/home/fishtest/fishtest/**fishtest**

7. `/etc/systemd/system/fishtest_dbg.service`
ExecStart=/home/fishtest/fishtest/**fishtest**/env/bin/pserve development.ini --reload
User=fishtest
WorkingDirectory=/home/fishtest/fishtest/**fishtest**

**Pull request merged**
