### PR TITLE
Get rid of worker_key altogether.

### PR DESCRIPTION
**Pull request by vdbergh**
This should be a non functional conceptual simplification.

The worker key tries to solve two unrelated problems:

(1) Long ago workers did not have to a unique key, so a substitute has to be provided for the chi2 test.

(2) The unique key is not suitable for displaying, and perhaps should be kept secret as well. So the worker key is displayed instead.

Now we simply provide two functions

unique_key(worker_info)
worker_name(worker_info)

corresponding to (1,2).

Not live tested.

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated, looks good to me.

**Comment by vdbergh** [comment]
This one gives an exception for me 

https://dfts-0.pigazzini.it/tests/view/5172effe8f0c3e2dd765907a

**Comment by ppigazzini** [comment]
@vdbergh sorry, I was trying some code live. That test is working fine.
The very old one no because the already here bug. eg
https://dfts-0.pigazzini.it/tests/view/511c69688f0c3e39b3913639

```
Sep 17 11:50:18 vps1572612706 pserve[23607]:   File "/home/usr00/fishtest/server/fishtest/util.py", line 133, in calculate_residuals
Sep 17 11:50:18 vps1572612706 pserve[23607]:     if unique_key(task["worker_info"]) in bad_users:
Sep 17 11:50:18 vps1572612706 pserve[23607]: KeyError: 'worker_info'
```

**Comment by vdbergh** [comment]
Maybe the last update fixes it.

**Comment by ppigazzini** [comment]
Problem with missing "worker_info" key in other files.

```
Sep 17 12:02:08 vps1572612706 pserve[24967]: Traceback (most recent call last):
Sep 17 12:02:08 vps1572612706 pserve[24967]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid_mako/__init__.py", line 148, in __call__
Sep 17 12:02:08 vps1572612706 pserve[24967]:     result = template.render_unicode(**system)
Sep 17 12:02:08 vps1572612706 pserve[24967]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/mako/template.py", line 478, in render_unicode
Sep 17 12:02:08 vps1572612706 pserve[24967]:     return runtime._render(
Sep 17 12:02:08 vps1572612706 pserve[24967]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/mako/runtime.py", line 878, in _render
Sep 17 12:02:08 vps1572612706 pserve[24967]:     _render_context(
Sep 17 12:02:08 vps1572612706 pserve[24967]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/mako/runtime.py", line 920, in _render_context
Sep 17 12:02:08 vps1572612706 pserve[24967]:     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
Sep 17 12:02:08 vps1572612706 pserve[24967]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/mako/runtime.py", line 947, in _exec_template
Sep 17 12:02:08 vps1572612706 pserve[24967]:     callable_(context, *args, **kwargs)
Sep 17 12:02:08 vps1572612706 pserve[24967]:   File "/home/usr00/fishtest/server/fishtest/templates/base.mak", line 121, in render_body
Sep 17 12:02:08 vps1572612706 pserve[24967]:     <main>${self.body()}</main>
Sep 17 12:02:08 vps1572612706 pserve[24967]:   File "/home/usr00/fishtest/server/fishtest/templates/tests_view.mak", line 286, in render_body
Sep 17 12:02:08 vps1572612706 pserve[24967]:     ${worker_name(task['worker_info'])}
Sep 17 12:02:08 vps1572612706 pserve[24967]: KeyError: 'worker_info'
```

**Comment by vdbergh** [comment]
Yek. Without worker_info one cannot compute anything. Can you perhaps print the offending task?

**Comment by ppigazzini** [comment]
First test working (March 3, 2013) https://dfts-0.pigazzini.it/tests/view/5131f1ff8f0c3e15976829ac
The first 59 tests saved in db haven't 'worker_info'.

**Comment by ppigazzini** [comment]
DEV updated

**Comment by vdbergh** [comment]
For now I am just skipping (so no tasks are printed). For a better solution one needs to know what fields appear in tasks in those days.

**Comment by ppigazzini** [comment]
This the info for the first test https://dfts-0.pigazzini.it/tests/view/511c69688f0c3e39b3913639

```
run:
{'_id': ObjectId('511c69688f0c3e39b3913639'), 'results_info': {'style': '#44EB44', 'info': ['ELO: 4.73 +-3.1 (95%) LOS: 99.9%', 'Total: 20000 W: 4166 L: 3894 D: 11940']}, 'tasks': [{'active': False, 'stats': {'wins': 4166, 'losses': 3894, 'draws': 11940}, 'num_games': 1000, 'pending': False, 'last_updated': datetime.datetime(1, 1, 1, 0, 0)}], 'last_updated': datetime.datetime(2013, 2, 13, 5, 44, 17, 724000), 'results_stale': False, 'start_time': datetime.datetime(2013, 2, 13, 5, 44, 17, 724000), 'args': {'base_tag': 'simplify_eval', 'num_games': 20000, 'resolved_new': '3922ac2fe48806b75580892d48b9ddc545531402', 'priority': 0, 'resolved_base': 'a72710c66038f3c5abc8ba84d6a36c49c55d1b6c', 'new_tag': 'bishop_pin_clop', 'tc': '40/3+0.1'}, 'results': {'wins': 4166, 'losses': 3894, 'draws': 11940}, 'finished': True, 'worker_results': [{'active': False, 'stats': {'wins': 4166, 'losses': 3894, 'draws': 11940}, 'num_games': 1000, 'pending': False}], 'tc_base': 40.0}
task:
{'active': False, 'stats': {'wins': 4166, 'losses': 3894, 'draws': 11940}, 'num_games': 1000, 'pending': False, 'last_updated': datetime.datetime(1, 1, 1, 0, 0)}
```

**Comment by ppigazzini** [comment]
This the info for the last test without "worker_info" https://dfts-0.pigazzini.it/tests/view/51251e398f0c3e5b3742696f

```
run:
{'_id': ObjectId('51251e398f0c3e5b3742696f'), 'results_info': {'style': '#44EB44', 'info': ['ELO: 4.50 +-2.8 (95%) LOS: 99.9%', 'Total: 20000 W: 3507 L: 3248 D: 13245']}, 'tasks': [{'active': False, 'stats': {'wins': 207, 'losses': 141, 'draws': 652}, 'num_games': 1000, 'pending': False, 'last_updated': datetime.datetime(1, 1, 1, 0, 0)}, {'active': False, 'stats': {'wins': 200, 'losses': 162, 'draws': 638}, 'num_games': 1000, 'pending': False, 'last_updated': datetime.datetime(1, 1, 1, 0, 0)}, {'active': False, 'stats': {'wins': 184, 'losses': 163, 'draws': 653}, 'num_games': 1000, 'pending': False, 'last_updated': datetime.datetime(1, 1, 1, 0, 0)}, {'active': False, 'stats': {'wins': 184, 'losses': 169, 'draws': 647}, 'num_games': 1000, 'pending': False, 'last_updated': datetime.datetime(1, 1, 1, 0, 0)}, {'active': False, 'stats': {'wins': 179, 'losses': 161, 'draws': 660}, 'num_games': 1000, 'pending': False, 'last_updated': datetime.datetime(1, 1, 1, 0, 0)}, {'active': False, 'stats': {'wins': 151, 'losses': 150, 'draws': 699}, 'num_games': 1000, 'pending': False, 'last_updated': datetime.datetime(1, 1, 1, 0, 0)}, {'active': False, 'stats': {'wins': 163, 'losses': 153, 'draws': 684}, 'num_games': 1000, 'pending': False, 'last_updated': datetime.datetime(1, 1, 1, 0, 0)}, {'active': False, 'stats': {'wins': 180, 'losses': 177, 'draws': 643}, 'num_games': 1000, 'pending': False, 'last_updated': datetime.datetime(1, 1, 1, 0, 0)}, {'active': False, 'stats': {'wins': 166, 'losses': 160, 'draws': 674}, 'num_games': 1000, 'pending': False, 'last_updated': datetime.datetime(1, 1, 1, 0, 0)}, {'active': False, 'stats': {'wins': 159, 'losses': 151, 'draws': 690}, 'num_games': 1000, 'pending': False, 'last_updated': datetime.datetime(1, 1, 1, 0, 0)}, {'stats': {'wins': 154, 'losses': 146, 'draws': 700}, 'num_games': 1000, 'worker_info': {'uname': ['Linux', 'blackjack', '2.6.32-220.el6.x86_64', '#1 SMP Tue Dec 6 19:48:22 GMT 2011', 'x86_64', 'x86_64'], 'concurrency': '3'}, 'active': False, 'last_updated': datetime.datetime(2013, 3, 4, 2, 10, 9, 581000), 'pending': False}, {'last_updated': datetime.datetime(2013, 3, 3, 18, 44, 4, 225000), 'num_games': 1000, 'worker_info': {'uname': ['Linux', 'fishtest1', '2.6.32-220.el6.x86_64', '#1 SMP Tue Dec 6 19:48:22 GMT 2011', 'x86_64', 'x86_64'], 'concurrency': '23'}, 'active': False, 'stats': {'wins': 186, 'losses': 177, 'draws': 637}, 'pending': False}, {'stats': {'wins': 159, 'losses': 178, 'draws': 663}, 'num_games': 1000, 'worker_info': {'uname': ['Linux', 'fishtest1', '2.6.32-220.el6.x86_64', '#1 SMP Tue Dec 6 19:48:22 GMT 2011', 'x86_64', 'x86_64'], 'concurrency': '23'}, 'active': False, 'last_updated': datetime.datetime(2013, 3, 3, 19, 58, 45, 400000), 'pending': False}, {'last_updated': datetime.datetime(2013, 3, 3, 21, 13, 44, 556000), 'num_games': 1000, 'worker_info': {'uname': ['Linux', 'fishtest1', '2.6.32-220.el6.x86_64', '#1 SMP Tue Dec 6 19:48:22 GMT 2011', 'x86_64', 'x86_64'], 'concurrency': '23'}, 'active': False, 'stats': {'wins': 193, 'losses': 163, 'draws': 644}, 'pending': False}, {'stats': {'wins': 166, 'losses': 175, 'draws': 659}, 'num_games': 1000, 'worker_info': {'uname': ['Linux', 'fishtest1', '2.6.32-220.el6.x86_64', '#1 SMP Tue Dec 6 19:48:22 GMT 2011', 'x86_64', 'x86_64'], 'concurrency': '23'}, 'active': False, 'last_updated': datetime.datetime(2013, 3, 3, 22, 28, 43, 950000), 'pending': False}, {'last_updated': datetime.datetime(2013, 3, 3, 23, 42, 34, 919000), 'num_games': 1000, 'worker_info': {'uname': ['Linux', 'fishtest1', '2.6.32-220.el6.x86_64', '#1 SMP Tue Dec 6 19:48:22 GMT 2011', 'x86_64', 'x86_64'], 'concurrency': '23'}, 'active': False, 'stats': {'wins': 172, 'losses': 162, 'draws': 666}, 'pending': False}, {'stats': {'wins': 178, 'losses': 184, 'draws': 638}, 'num_games': 1000, 'worker_info': {'uname': ['Linux', 'fishtest1', '2.6.32-220.el6.x86_64', '#1 SMP Tue Dec 6 19:48:22 GMT 2011', 'x86_64', 'x86_64'], 'concurrency': '23'}, 'active': False, 'last_updated': datetime.datetime(2013, 3, 4, 0, 56, 50, 759000), 'pending': False}, {'stats': {'wins': 189, 'losses': 162, 'draws': 649}, 'num_games': 1000, 'worker_info': {'uname': ['Linux', 'fishtest1', '2.6.32-220.el6.x86_64', '#1 SMP Tue Dec 6 19:48:22 GMT 2011', 'x86_64', 'x86_64'], 'concurrency': '23'}, 'active': False, 'last_updated': datetime.datetime(2013, 3, 4, 2, 11, 38, 268000), 'pending': False}, {'stats': {'wins': 166, 'losses': 133, 'draws': 701}, 'num_games': 1000, 'worker_info': {'uname': ['Linux', 'blackjack', '2.6.32-220.el6.x86_64', '#1 SMP Tue Dec 6 19:48:22 GMT 2011', 'x86_64', 'x86_64'], 'concurrency': '3'}, 'active': False, 'last_updated': datetime.datetime(2013, 3, 4, 11, 26, 55, 662000), 'pending': False}, {'last_updated': datetime.datetime(2013, 3, 4, 3, 26, 51, 466000), 'num_games': 1000, 'worker_info': {'uname': ['Linux', 'fishtest1', '2.6.32-220.el6.x86_64', '#1 SMP Tue Dec 6 19:48:22 GMT 2011', 'x86_64', 'x86_64'], 'concurrency': '23'}, 'active': False, 'stats': {'wins': 171, 'losses': 181, 'draws': 648}, 'pending': False}], 'last_updated': datetime.datetime(2013, 3, 4, 11, 26, 55, 662000), 'results_stale': False, 'start_time': datetime.datetime(2013, 2, 20, 19, 4, 25, 487000), 'args': {'info': 'Another regression test at long TC but with "bishop pin" patch applied', 'priority': 0, 'base_tag': 'sf_2.3.1_base', 'num_games': 20000, 'resolved_new': '9a1d5f0f1d8a12a85b198688d4f1d636a146eb7a', 'new_signature': '4917064', 'base_signature': '5423738', 'resolved_base': '1cb2722c955405d6354a1eebcea8652f52b94bdd', 'new_tag': 'master', 'tc': '60+0.05', 'name': ''}, 'results': {'wins': 3507, 'losses': 3248, 'draws': 13245}, 'finished': True, 'worker_results': [{'active': False, 'stats': {'wins': 207, 'losses': 141, 'draws': 652}, 'num_games': 1000, 'pending': False}, {'active': False, 'stats': {'wins': 200, 'losses': 162, 'draws': 638}, 'num_games': 1000, 'pending': False}, {'active': False, 'stats': {'wins': 184, 'losses': 163, 'draws': 653}, 'num_games': 1000, 'pending': False}, {'active': False, 'stats': {'wins': 184, 'losses': 169, 'draws': 647}, 'num_games': 1000, 'pending': False}, {'active': False, 'stats': {'wins': 179, 'losses': 161, 'draws': 660}, 'num_games': 1000, 'pending': False}, {'active': False, 'stats': {'wins': 151, 'losses': 150, 'draws': 699}, 'num_games': 1000, 'pending': False}, {'active': False, 'stats': {'wins': 163, 'losses': 153, 'draws': 684}, 'num_games': 1000, 'pending': False}, {'active': False, 'stats': {'wins': 180, 'losses': 177, 'draws': 643}, 'num_games': 1000, 'pending': False}, {'active': False, 'stats': {'wins': 166, 'losses': 160, 'draws': 674}, 'num_games': 1000, 'pending': False}, {'active': False, 'stats': {'wins': 159, 'losses': 151, 'draws': 690}, 'num_games': 1000, 'pending': False}, {'active': False, 'num_games': 1000, 'pending': True}, {'active': False, 'num_games': 1000, 'pending': True}, {'active': False, 'num_games': 1000, 'pending': True}, {'active': False, 'num_games': 1000, 'pending': True}, {'active': False, 'num_games': 1000, 'pending': True}, {'active': False, 'num_games': 1000, 'pending': True}, {'active': False, 'num_games': 1000, 'pending': True}, {'active': False, 'num_games': 1000, 'pending': True}, {'active': False, 'num_games': 1000, 'pending': True}, {'active': False, 'num_games': 1000, 'pending': True}], 'tc_base': 60.0}
task:
{'active': False, 'stats': {'wins': 159, 'losses': 151, 'draws': 690}, 'num_games': 1000, 'pending': False, 'last_updated': datetime.datetime(1, 1, 1, 0, 0)}
```

**Comment by vdbergh** [comment]
Thanks. So there is simply no information about the worker.... Now I am trying to just print "Unknown worker".

**Review by ppigazzini — APPROVED** [review]

**Comment by vdbergh** [comment]
Hmm I seem to have forgotten to push the fix for the very old tests (printing "Unknown worker" for the name). 

I will make a new PR (it's only a few lines).

**Comment by ppigazzini** [comment]
I merged because I'm testing on DEV a future PR with all the .mak files reformatted.

PROD updated :)

**Comment by vdbergh** [comment]
Ok I'll wait for the reformatting.

**Comment by ppigazzini** [comment]
Reformat merged.

**Pull request merged**
