### PR TITLE
Show number of cores for active tests

### PR DESCRIPTION
**Pull request by tomtor**
So one does not have to visit the individual test page

### CODE REVIEW

**Comment by tomtor** [comment]
@ppigazzini I improved the layout "cores:" always on a new line, that should look better...

Can you please restart the test server?

**Comment by ppigazzini** [comment]
@tomtor done, probable bug.

**Comment by tomtor** [comment]
Hmm, yes certainly. I pushed again....

**Comment by ppigazzini** [comment]
@tomtor server updated

**Pull request merged**
