### PR TITLE
Remove bad alignments in the the users page.

### PR DESCRIPTION
**Pull request by peregrineshahin**

### CODE REVIEW

**Comment by ppigazzini** [comment]
IMO, the firts version of the PR introduced 4 alignment issues.

image

**Comment by peregrineshahin** [comment]
Yes they fixed in the last versions. I was experimenting and pushing.

**Comment by peregrineshahin** [comment]
What do you think about making cards/tiles for the above table info? just like home page?

**Comment by vdbergh** [comment]
> What do you think about making cards/tiles for the above table info? just like home page?

Sounds good.

**Comment by ppigazzini** [comment]
I'm loading the last DB backup to try to have "minutes ago" as well.

**Comment by peregrineshahin** [comment]
> > What do you think about making cards/tiles for the above table info? just like home page?
> 
> Sounds good.

I will look into that in a different PR, now closing as per the feedback of two admins.

**Pull request closed without merging**
