### PR TITLE
Replace jquery http source with https and make worker https ready

### LINKED ISSUE #133: use https on fishtest
as requested by @Stefano80 and discussed here

https://github.com/official-stockfish/Stockfish/issues/1267#issuecomment-360198514

Get rid of the warning (using firefox 57.0.4):
https://support.mozilla.org/en-US/kb/insecure-password-warning-firefox?as=u&utm_source=inproduct
I think using a let's encrypt certificate is the right idea.

### PR DESCRIPTION
**Pull request by tomtor**
Should fix #133 issue:

Mixed Content: The page at 'https://dfts-0.pigazzini.it/tests' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-1.8.3.js'. This request has been blocked; the content must be served over HTTPS.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor it's work.
To run the worker I set https in 
https://github.com/glinscott/fishtest/blob/2f512618dbfba0605f4bdbf4b813d0773e40440e/worker/worker.py#L208
and started the worker with --port 443

**Comment by tomtor** [comment]
Nice! I think we should change the default port to 443 in:

https://github.com/glinscott/fishtest/blob/2f512618dbfba0605f4bdbf4b813d0773e40440e/worker/worker.py#L60

I will add that to the PR...

Op vr 30 aug. 2019 om 14:22 schreef ppigazzini <notifications@github.com>:

**Comment by tomtor** [comment]
@ppigazzini Just a note that when introducing https on the official server, we must have a transition period where we allow both http and https for /api requests untill all workers have updated to a new worker version which uses https.

The current setup on the test server does not allow http api calls:

    $ curl http://dfts-0.pigazzini.it/api/active_runs
    <html>
    <head><title>301 Moved Permanently</title></head>
    <body bgcolor="white">
    <center><h1>301 Moved Permanently</h1></center>
    <hr><center>nginx/1.14.0 (Ubuntu)</center>
    </body>
    </html>

**Comment by ppigazzini** [comment]
@tomtor now should work, I simply chose in certbot to no redirect port 80.

**Comment by ppigazzini** [comment]
@tomtor the worker changes of this PR will create a little problem for fishtest developers.
I wrote 3 fishtest server setup scripts w/ these nginx configurations:
  - http/https w/ let's encrypt: this requires a DNS and work w/ a worker using http/https [(draft)](https://gist.github.com/ppigazzini/bee3ee4b2c296a22bef108ed4287f646)
  - http: this works only w/ a worker using http:80 [(draft)](https://gist.github.com/ppigazzini/4759b75743e6a70ef4ae439866ba8d8e)
  - http/https w/ self signed certificate: works using http:80 [(draft)](https://gist.github.com/ppigazzini/5510b76a533c58a05647069b4e493b0a) but fails using https (worker connection error due to the self signed certificate, view below).

A solution could be:
 - add in the wiki:
   - the developer fishtest setup script w/ only the http configuration
   - the production fishtest setup script w/ let's encrypt
 - adding a worker command line switch to use http:80

I'm interested to know your opinion as fishtest developer :)

```
Worker started in /root/_git/__fishtest_ssl/fishtest/worker ...

Memory: 34025091072
Worker version 69 connecting to https://172.18.93.228:443
Fetch task...
Exception accessing host:
Traceback (most recent call last):
  File "/root/_git/__fishtest_ssl/fishtest/worker/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/root/_git/__fishtest_ssl/fishtest/worker/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/root/_git/__fishtest_ssl/fishtest/worker/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/root/_git/__fishtest_ssl/fishtest/worker/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/root/_git/__fishtest_ssl/fishtest/worker/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/_git/__fishtest_ssl/fishtest/worker/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/root/_git/__fishtest_ssl/fishtest/worker/requests/packages/urllib3/connectionpool.py", line 621, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "worker.py", line 93, in worker
    req = requests.post(remote + '/api/request_version', data=json.dumps(payload), headers={'Content-type': 'application/json'}, timeout=HTTP_TIMEOUT)
  File "/root/_git/__fishtest_ssl/fishtest/worker/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/root/_git/__fishtest_ssl/fishtest/worker/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/_git/__fishtest_ssl/fishtest/worker/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/_git/__fishtest_ssl/fishtest/worker/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/root/_git/__fishtest_ssl/fishtest/worker/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
```
A

**Comment by tomtor** [comment]
> A solution could be:
> 
> * add in the wiki:
>   
>   * the developer fishtest setup script w/ only the http configuration
>   * the production fishtest setup script w/ let's encrypt
> * adding a worker command line switch to use http:80

@ppigazzini I think that this is OK.

Note that the self-signed error can be fixed by adding the certificate to the CA-trust-store.

**Comment by tomtor** [comment]
@ppigazzini See https://stackoverflow.com/questions/42982143/python-requests-how-to-use-system-ca-certificates-debian-ubuntu

**Comment by ppigazzini** [comment]
@tomtor I need to test the worker code on several platforms (aka Windows/WSL):
 - on Windows it's a nightmare to resolve .local addresses
 - Hyper-V setup a mshome.net domain to resolve the VM hostnames
 - WSL (w/ default configuration) doesn't resolve .local or mshome.net addresses :)

I'm trying to set up an easy path for a new developer willing to contribute to fishtest, to both of us is easy to deal w/ the rough edges of fishtest during coding/testing.

IMO w/ your interesting insides the local fishtest server w/ a self signed certificate is not that useful:
  - it requires complex configuration that could be platform dependent (windows, linux distros, msys2, WSL)
  - a https bug in a new PR should be easily caught w/ testing w/ the dev server (e.g. https://github.com/glinscott/fishtest/pull/383/commits/e8eeecef7a90ddb34f7e7b0aced31f7fd71c5ce4)

**Comment by tomtor** [comment]
> Searching for the "only one obvious way" to check the proto I found something interesting about ConfigParse:

@ppigazzini I do not see a way in the configparser doc to check for http(s) as only valid values, but perhaps I missed that? Your code improvement is obviously more robust, I will copy it.

**Comment by ppigazzini** [comment]
@tomtor 

1. the PR works fine w/ any http/https port combinations
2. using '-P http -p 6542' we connect to waitress w/ development.ini (when started) bypassing nginx 
3. learned the short switches (-p -P) :)
4. ConfigParse has -h --help switches, but these provide a wrong usage info (missing user and password). Fixing this could be over engineering this PR
```
$ python3 worker.py --help
Worker started in /home/usr00/_git/__fishtest/fishtest/worker ...

Memory: 34025091072
Usage: worker.py [options]

Options:
  -h, --help            show this help message and exit
  -n HOST, --host=HOST
  -p PORT, --port=PORT
  -c CONCURRENCY, --concurrency=CONCURRENCY
  -m MAX_MEMORY, --max_memory=MAX_MEMORY
  -t MIN_THREADS, --min_threads=MIN_THREADS
  -P PROTO, --proto=PROTO
```

Non functional things:
 - we should move any line w/ 'proto' before 'host' and 'port' lines to conform to the right order :)
 - I lack the development experience to decide if 'proto' is an acceptable shortcut for 'protocol' (cutechess uses this). Up to you.

[DEFAULT] section:
The past night I throw an eye on ConfigParse documentation, no code experiment, so I could be wrong.
After the transitory phase w/ https we should have only two use cases:
  - CPU contributor: only https connection, use [DEFAULT] values, command line switches '--proto' '--port' not used
  - developer: use [DEFAULT] value to test the worker behavior w/ the dev server, use '--proto' '--port' values only if present a the command line switch '--devel'

ps: I googled until 03:00 AM the only one obviously right style (to a Dutch eye), and I failed :)

> Edit: note that
> not xxxx in yyyy
> is considered bad Python style (learned that a few days ago), better is
> xxxx not in yyyy

**Comment by tomtor** [comment]
@ppigazzini I also thought about protocol instead of proto, so I was happy to change it.

`if not a in 'a':`

gives in my editor:

`test.py|1 col 4 C| E713 test for membership should be 'not in' [pep8]`

**Comment by ppigazzini** [comment]
@tomtor to me this PR is ready. Great work Tom.

I look forward to hearing from @glinscott for the server upgrade to Ubuntu 18.04 :)

ps: you are right: `is not` is an operator, not a combo (why `elif` and not `isnot` is another question...). I should have a look at the official documentation instead of wasting time on StackOverflow 
https://docs.python.org/3/library/stdtypes.html?highlight=__contains__#comparisons

**Comment by ppigazzini** [comment]
@tomtor if I may ask, what editor are you using?

**Comment by tomtor** [comment]
@ppigazzini I use https://github.com/python-mode/python-mode on Linux command line.

I also use vscode (https://code.visualstudio.com/) with Python plugin on my work Windows-10 laptop. Note that this is also running fine on the Linux desktop.

**Comment by ppigazzini** [comment]
@tomtor in the next days I will play a bit with this PR to refresh my memory about the impact on the workers. Then I will configure the https on the VPS and merge this PR.

**Pull request merged**
