### PR TITLE
Add simple purge (audit) log

### PR DESCRIPTION
**Pull request by tomtor**
See #489

### CODE REVIEW

**Comment by tomtor** [comment]
Not sure if adding more info from chi2 is usefull?

**Comment by ppigazzini** [comment]
DEV updated, test running (p-value raised to trigger the autopurge). chi2 < p-value before purge, so already known info.

**Comment by ppigazzini** [comment]
@tomtor the test looks good to me
https://dfts-0.pigazzini.it/tests/view/5e1fb28850feaf395dd551e6

@vdbergh @vondele @snicolet suggestions before merging?

**Comment by vondele** [comment]
Ideally, the list of tasks has a visual indication of the purged workers (e.g. they appear red or some such thing)...

**Comment by vdbergh** [comment]
Ideally ```run['args']['purged']``` could just contain the deleted task, which would then be printed on the test page, after the non-deleted tasks, with some visual clue, e.g. between ```<del></del>``` tags: https://www.w3schools.com/tags/tag_del.asp .

**Comment by tomtor** [comment]
@ppigazzini Could you redeploy to test at a convenient time?

I flag the tasks with a `bad` attribute and keep the `stats` so they are shown inline striked-through. Have to skip these tasks at various spots with a test for `bad`, where they were skipped due to the removed `stats` originally. Hope I did that at all required places.

**Comment by vdbergh** [comment]
@tomtor It was precisely for this reason that I suggested to transferring the bad tasks to a different array. Then other code iterating over tasks would not be affected.

If future code iterates over tasks and accidentally ignores the 'bad' attribute it might go unnoticed.

**Comment by vdbergh** [comment]
Of course I understand if you choose to do it differently!

**Comment by tomtor** [comment]
@vdbergh I agree that a separate array is more robust. I will change the PR soon.

**Comment by ppigazzini** [comment]
@tomtor DEV updated, started a test to trigger the autopurge.

**Comment by vdbergh** [comment]
Strange. The ```<del>``` tag appears not to be doing anything for me on Firefox and Chrome (although it is present in the page source).

**Comment by tomtor** [comment]
@vdbergh The `<del>` is overruled by the `<tr class="">`, fix pushed.

I looked at the code and showing the deleted tasks inline without adding/testing the flag is not trivial. Showing them together below the task list in a separate list is perhaps visual less attractive, but somewhat cleaner code.

**Comment by vdbergh** [comment]
Perhaps I am under estimating the difficulty but wouldn't it just be something like

```%for idx, task in enumerate(run['tasks']+run['deleted_tasks']):```

assuming that the bad tasks have been moved from ```run['tasks']``` to ```run['deleted_tasks']```?

**Comment by vdbergh** [comment]
I guess the deleted tasks could then still have the 'bad' attribute to be recognizable as such.

**Comment by vdbergh** [comment]
Ok I see that this is what you are suggesting. Sorry. I actually favor having the bad tasks as a group at the end.

**Comment by ppigazzini** [comment]
DEV updated, workers running a new test (p-value raised to 0.01)

**Comment by tomtor** [comment]
@ppigazzini No need to run new tests now: https://dfts-0.pigazzini.it/tests/view/5e21a408d9fde0ce31f84e76 shows the strike though.

It looks a bit messy now that strike through works. I think I will list them at the end as @vdbergh suggested and color them red...

**Comment by vdbergh** [comment]
Yes strike through is unfortunately not as nice as I had expected.

**Comment by ppigazzini** [comment]
I just realized that we are using not so good colors combination for colorblind people.

**Comment by tomtor** [comment]
And https://dfts-0.pigazzini.it/tests/view/5e22278c2be917449ac0d549 gives an error because 'bad_tasks' is not always existing...

**Comment by ppigazzini** [comment]
DEV updated

**Comment by tomtor** [comment]
> I just realized that we are using not so good colors combination for colorblind people.

Well, I am surprised that the red text in the most right column is still readable because the red background is a bit less saturated. 😁

**Comment by vdbergh** [comment]
Maybe the existing colors should be overridden in the bad_tasks. Maybe just black letters on a red background?

**Comment by ppigazzini** [comment]
For colorblind people red/green is very hard. Without changing colors combination we should switch to dark_red/light_green or light_red/dark_green scheme.

**Comment by ppigazzini** [comment]
@tomtor "Bad background for red tasks" :)

**Comment by tomtor** [comment]
@ppigazzini Color are here: https://github.com/glinscott/fishtest/blob/e309261afd8369c15e6137f0ba0e59466eae402b/fishtest/fishtest/views.py#L825

Perhaps that should be a separate PR? Adding these colors to a .css would be even better

**Comment by ppigazzini** [comment]
@tomtor of course, I'm not suggesting to correct the colors in this PR.

**Comment by ppigazzini** [comment]
@tomtor @vdbergh I like more the red fonts, the red background is very hard on my eyes.

**Comment by vdbergh** [comment]
I like the colored background since it affects the whole row and not just the text. But it does not have to be _bright_ red.

**Comment by ppigazzini** [comment]
Light pink.

**Comment by vdbergh** [comment]
It seems the background color is affected somehow by the striping.

**Comment by vdbergh** [comment]
It seems bootstrap has predefined row classes.

https://getbootstrap.com/docs/4.0/content/tables/

Perhaps 

```<tr class="table-danger">...</tr>```

might fit the bill.

**Comment by ppigazzini** [comment]
@vdbergh I wrote this but it doesn't work. Our bootstrap 2.2.2  is no longer officially supported...
```
  %if 'bad' in task:
  <tr class="table-danger">
```

**Comment by vdbergh** [comment]
Too bad. 

Until something better is found we could specify the background color as ```!important``` to override the bootstrap striping

https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Comment by vdbergh** [comment]
But actually that doesn't make sense. Inline styles override anything else. So ```<tr style="background-color: #ffebeb">``` should work AFAICS.

**Comment by vdbergh** [comment]
Ok I looked at the CSS and it appears that there is a more specific rule that sets the background color of the ```<td>``` elements. So it overrides our inline styling applied to ```<tr>```.
```
.table-striped tbody > tr:nth-child(2n+1) > td, 
.table-striped tbody > tr:nth-child(2n+1) > th {
    background-color: #f9f9f9;
}
```
We have to override the bootstrap styling. Maybe with class added to ```<tr>``` and then a ```.class td``` rule?

**Comment by tomtor** [comment]
We could line-through just the worker-name? That would look OK?

**Comment by tomtor** [comment]
https://dfts-0.pigazzini.it/tests/view/5e22290c6ff8d1034359d109 has an issue with the gauges display? No text is shown.

**Comment by vdbergh** [comment]
Yek. 

https://dfts-0.pigazzini.it/api/get_elo/5e22290c6ff8d1034359d109

shows

> Internal Server Error
> 
> The server encountered an unexpected internal server error
> 
> (generated by waitress)

I guess one needs to look at the logs to debug this.

The raw statistics page appears to be fine so it should not be a problem with the math.

**Comment by Chess13234** [comment]
> I just realized that we are using not so good colors combination for colorblind people.

Could these indicators be replaced with CSS borders(dotted/solid/dashed) instead of color?
e.g. .dotted{border-style: dotted; }
it also can replace strike-through,
instead make a special css border around the cell.

**Comment by tomtor** [comment]
> I guess one needs to look at the logs to debug this.

@vdbergh `strip_run` should remove `bad_tasks`, pushed a fix.

**Comment by vdbergh** [comment]
@tomtor Thanks. However I do not see why the presence of ```run['bad_tasks']``` causes a crash. Does the JSON rendering break?

**Comment by tomtor** [comment]
> However I do not see why the presence of `run['bad_tasks']` causes a crash. Does the JSON rendering break?

Yes, I remember when adding the API that was an issue.

**Comment by vdbergh** [comment]
I had some bad experiences with strip_run modifying the run object in place (the modified object finding its way into the database). One has to remember to pass it a copy of the run object. 

I think it would be better if strip_run would itself make a copy of its argument. I think that was the intention in the first place.

**Comment by ppigazzini** [comment]
I reload on DEV the original PR.
Here is a snippet of the log (the log for fishtest@6543 is clean):
```
sudo journalctl -u fishtest@6543

Jan 18 11:25:21 vps1572612706 pserve[25495]: TypeError: Object of type 'datetime' is not JSON serializable
Jan 18 11:25:42 vps1572612706 pserve[25495]: 2020-01-18 11:25:42,534 ERROR [waitress][waitress] Exception while serving /api/get_elo/5e22290c6ff8d1034359d109
Jan 18 11:25:42 vps1572612706 pserve[25495]: Traceback (most recent call last):
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
Jan 18 11:25:42 vps1572612706 pserve[25495]:     response = request.invoke_exception_view(exc_info)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 779, in invoke_exception_view
Jan 18 11:25:42 vps1572612706 pserve[25495]:     raise HTTPNotFound
Jan 18 11:25:42 vps1572612706 pserve[25495]: pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
Jan 18 11:25:42 vps1572612706 pserve[25495]: During handling of the above exception, another exception occurred:
Jan 18 11:25:42 vps1572612706 pserve[25495]: Traceback (most recent call last):
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/channel.py", line 349, in service
Jan 18 11:25:42 vps1572612706 pserve[25495]:     task.service()
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 169, in service
Jan 18 11:25:42 vps1572612706 pserve[25495]:     self.execute()
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 439, in execute
Jan 18 11:25:42 vps1572612706 pserve[25495]:     app_iter = self.channel.server.application(environ, start_response)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/proxy_headers.py", line 65, in translate_proxy_headers
Jan 18 11:25:42 vps1572612706 pserve[25495]:     return app(environ, start_response)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
Jan 18 11:25:42 vps1572612706 pserve[25495]:     response = self.execution_policy(environ, self)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 279, in default_execution_policy
Jan 18 11:25:42 vps1572612706 pserve[25495]:     return request.invoke_exception_view(reraise=True)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 778, in invoke_exception_view
Jan 18 11:25:42 vps1572612706 pserve[25495]:     reraise_(*exc_info)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Jan 18 11:25:42 vps1572612706 pserve[25495]:     raise value
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 277, in default_execution_policy
Jan 18 11:25:42 vps1572612706 pserve[25495]:     return router.invoke_request(request)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
Jan 18 11:25:42 vps1572612706 pserve[25495]:     response = handle_request(request)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
Jan 18 11:25:42 vps1572612706 pserve[25495]:     response = _error_handler(request, exc)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
Jan 18 11:25:42 vps1572612706 pserve[25495]:     reraise(*exc_info)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Jan 18 11:25:42 vps1572612706 pserve[25495]:     raise value
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
Jan 18 11:25:42 vps1572612706 pserve[25495]:     response = handler(request)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
Jan 18 11:25:42 vps1572612706 pserve[25495]:     registry, request, context, context_iface, view_name
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
Jan 18 11:25:42 vps1572612706 pserve[25495]:     response = view_callable(context, request)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
Jan 18 11:25:42 vps1572612706 pserve[25495]:     result = view(context, request)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
Jan 18 11:25:42 vps1572612706 pserve[25495]:     response = view(request)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/home/usr00/fishtest/fishtest/fishtest/api.py", line 78, in get_elo
Jan 18 11:25:42 vps1572612706 pserve[25495]:     return json.dumps(run)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
Jan 18 11:25:42 vps1572612706 pserve[25495]:     return _default_encoder.encode(obj)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
Jan 18 11:25:42 vps1572612706 pserve[25495]:     chunks = self.iterencode(o, _one_shot=True)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
Jan 18 11:25:42 vps1572612706 pserve[25495]:     return _iterencode(o, 0)
Jan 18 11:25:42 vps1572612706 pserve[25495]:   File "/usr/lib/python3.6/json/encoder.py", line 180, in default
Jan 18 11:25:42 vps1572612706 pserve[25495]:     o.__class__.__name__)
Jan 18 11:25:42 vps1572612706 pserve[25495]: TypeError: Object of type 'datetime' is not JSON serializable
```

**Comment by Chess13234** [comment]
@ppigazzini That test also can't be loaded from browser,
http://tests.stockfishchess.org/tests/view/5e22290c6ff8d1034359d109 
gives internal server error.

**Comment by tomtor** [comment]
I did a line-through in the wrong column :/

**Comment by ppigazzini** [comment]
@Chess13234 that is the error is reported when asking for non existent test id, are you sure that test exists? Here the log

```
$ journalctl -u fishtest@6543

Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]: 2020-01-18 11:37:32,942 ERROR [waitress][waitress] Exception while serving /tests/view/5e22290c6ff8d1034359d109
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]: Traceback (most recent call last):
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     response = request.invoke_exception_view(exc_info)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 779, in invoke_exception_view
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     raise HTTPNotFound
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]: pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]: During handling of the above exception, another exception occurred:
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]: Traceback (most recent call last):
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/channel.py", line 349, in service
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     task.service()
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 169, in service
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     self.execute()
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 439, in execute
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     app_iter = self.channel.server.application(environ, start_response)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/proxy_headers.py", line 65, in translate_proxy_headers
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     return app(environ, start_response)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     response = self.execution_policy(environ, self)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 279, in default_execution_policy
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     return request.invoke_exception_view(reraise=True)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 778, in invoke_exception_view
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     reraise_(*exc_info)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     raise value
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 277, in default_execution_policy
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     return router.invoke_request(request)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     response = handle_request(request)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     response = _error_handler(request, exc)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     reraise(*exc_info)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     raise value
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     response = handler(request)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     registry, request, context, context_iface, view_name
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     response = view_callable(context, request)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     result = view(context, request)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     response = view(request)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 863, in tests_view
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     results = request.rundb.get_results(run)
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:   File "/home/fishtest/fishtest/fishtest/fishtest/rundb.py", line 253, in get_results
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]:     if not run['results_stale']:
Jan 18 11:37:32 tests.stockfishchess.org pserve[7818]: TypeError: 'NoneType' object is not subscriptable
```

**Comment by tomtor** [comment]
> @ppigazzini That test also can't be loaded from browser,
> http://tests.stockfishchess.org/tests/view/5e22290c6ff8d1034359d109
> gives internal server error.

You load from PROD?

**Comment by ppigazzini** [comment]
DEV updated after https://github.com/glinscott/fishtest/pull/509/commits/d2286e15646bffb41bdcc352d747e6b10c9daf0b

**Comment by Chess13234** [comment]
@tomtor i was thinking the hash is from a test that was on both servers (i didn't think it was from DEV server, just being debugged there) so i loaded it in browser to see if it was working.Sorry for confusion.

**Comment by vdbergh** [comment]
But the fact that http://tests.stockfishchess.org/tests/view/5e22290c6ff8d1034359d109 gives an internal server error is not so nice IMHO. It would be better to give a meaningful error message.

**Comment by tomtor** [comment]
> I think it would be better if strip_run would itself make a copy of its argument. I think that was the intention in the first place.

@vdbergh Fixed in last commit

**Comment by vdbergh** [comment]
@tomtor Thanks!

**Comment by ppigazzini** [comment]
DEV updated with https://github.com/glinscott/fishtest/pull/509/commits/8045c7b6f19083e6fe0878992004385fbe00bb2b

**Comment by ppigazzini** [comment]
Now the backgorund-color works fine:
```html
   %if 'bad' in task:
     <td style="text-decoration:line-through; background-color:#ffebeb">
```

**Comment by tomtor** [comment]
> It would be better to give a meaningful error message.

Return 404 now after the last commit. @ppigazzini I squashed all the others...

**Comment by tomtor** [comment]
> Now the backgorund-color works fine:
> 
> ```
>    %if 'bad' in task:
>      <td style="text-decoration:line-through; background-color:#ffebeb">
> ```

Thanks, looks good, I will add it.

**Comment by ppigazzini** [comment]
DEV updated with https://github.com/glinscott/fishtest/pull/509/commits/cdb4f23c8f9fb9bdcb24dfccd8b6a62307f3a56e

**Comment by tomtor** [comment]
@ppigazzini Copied the 404 error to #513

**Comment by ppigazzini** [comment]
PROD updated, thanks to @vdbergh @vondele @Chess13234 for suggestions/reviews.
Thanks to @tomtor for the hard work :)

**Comment by ppigazzini** [comment]
@tomtor I forgot to test with the manual purge, it works :)
https://dfts-0.pigazzini.it/tests/view/5e22f71ed8df75bc5cca5326

**Pull request merged**
