### PR TITLE
Get mongodb monitoring url with new format

### PR DESCRIPTION
**Pull request by ppigazzini**

### CODE REVIEW

**Comment by vdbergh** [comment]
Hmmm this broke my local fishtest
```
pyramid_mako.MakoRenderingException: 

Traceback (most recent call last):
  File "/home/fishtest/fishtest/server/env/lib/python3.10/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/home/fishtest/fishtest/server/env/lib/python3.10/site-packages/mako/template.py", line 444, in render_unicode
    return runtime._render(
  File "/home/fishtest/fishtest/server/env/lib/python3.10/site-packages/mako/runtime.py", line 874, in _render
    _render_context(
  File "/home/fishtest/fishtest/server/env/lib/python3.10/site-packages/mako/runtime.py", line 916, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/fishtest/fishtest/server/env/lib/python3.10/site-packages/mako/runtime.py", line 943, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/fishtest/fishtest/server/fishtest/templates/base.mak", line 181, in render_body
    % if monitoring["debug"]["state"] == 'enabled' and monitoring_url:
KeyError: 'debug'
```

I can debug it later tonight if necessary.

**Comment by ppigazzini** [comment]
It changed with the update to mongodb v6.0.6

**Comment by ppigazzini** [comment]
You can try this on the fly
```python
% if 'debug' in monitoring and 'state' in monitoring["debug"] and monitoring["debug"]["state"] == 'enabled' and monitoring_url:
```

**Comment by ppigazzini** [comment]
@vdbergh it should be fixed by https://github.com/glinscott/fishtest/pull/1696

**Comment by vdbergh** [comment]
Yes it seems to work now. Thanks!

**Pull request merged**
