### PR TITLE
Add error check for time control

### PR DESCRIPTION
**Pull request by tomtor**
See #690

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor DEV updated, it rejects only bad TCs starting with chars, not TCs with chars following a number. Is it the indented behavior?
e.g. bad TC accepted:
- 10xxx+xxx
- 10xxx/xxx
- 10+xxx
- 10/xxx
- 10/

**Comment by tomtor** [comment]
@ppigazzini No that is not intended :-)
Will fix

**Comment by tomtor** [comment]
@ppigazzini Did test it now myself, should be much more robust now.

**Comment by ppigazzini** [comment]
@tomtor it rejects also <n_games_in_floating>/<tc> :)

**Comment by ppigazzini** [comment]
PROD updated, thank you @tomtor :)

**Comment by tomtor** [comment]
> it rejects also 6.66/6.66 :)

And 0/40

**Comment by ppigazzini** [comment]
> > it rejects also 6.66/6.66 :)
> 
> And 0/40

Great suggestion: 0+0 and 1/0 accepted :)

**Comment by tomtor** [comment]
> and 1/0 accepted

That one is easy to fix...

**Pull request merged**
