### PR TITLE
[WIP] Make it possible to use a github proxy.

### PR DESCRIPTION
**Pull request by vdbergh**
Following #1192 

Alas it does not work (yet?)
```
$ python worker.py --ghproxy true
...
Exception in requests.get():
403 Client Error: FORBIDDEN for url: https://ghproxy.com/https://api.github.com/repos/official-stockfish/Stockfish/zipball/e4b7403f127a36a35bbace9f833ab43babd98a6c
```

### CODE REVIEW

**Comment by noobpwnftw** [comment]
It allows only the specific forms of link:

https://github.com/hunshcn/gh-proxy/blob/master/app/main.py

**Comment by vdbergh** [comment]
Hmm these seem to be the links that are accepted
```
exp1 = re.compile(r'^(?:https?://)?github\.com/(?P<author>.+?)/(?P<repo>.+?)/(?:releases|archive|suites)/.*$')
exp2 = re.compile(r'^(?:https?://)?github\.com/(?P<author>.+?)/(?P<repo>.+?)/(?:blob|raw)/.*$')
exp3 = re.compile(r'^(?:https?://)?github\.com/(?P<author>.+?)/(?P<repo>.+?)/(?:info|git-).*$')
exp4 = re.compile(r'^(?:https?://)?raw\.(?:githubusercontent|github)\.com/(?P<author>.+?)/(?P<repo>.+?)/.+?/.+$')
exp5 = re.compile(r'^(?:https?://)?gist\.(?:githubusercontent|github)\.com/(?P<author>.+?)/.+?/.+$')
```
So IIUC no `api.github.com`. So it is more complicated than I anticipated.

**Comment by vdbergh** [comment]
Maybe add a tag "Help requested".

**Comment by vdbergh** [comment]
Maybe just running a standard proxy would be better. I see that nginx can do it.

**Comment by vdbergh** [comment]
This would be better solved by a standard proxy (only proxying the specific github URLs needed by the worker). Closing.

**Pull request closed without merging**
