### PR TITLE
Fix error on modify/approve test when not logged in

### PR DESCRIPTION
**Pull request by tomtor**
Fix error on approve/modify test when not logged in

After login return to the main page.

Without this fix:

    Internal Server Error

    The server encountered an unexpected internal server error

    (generated by waitress)

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor please suggest the steps to replicate the problem on the dev server (I tried unsuccessfully some combination)

**Comment by tomtor** [comment]
@ppigazzini On the unpatched fishtest:
- logout
- try modify an existing test

**Comment by vondele** [comment]
actually a similar error happens when trying to approve a test when not logged in. Maybe this fix also fixes that, otherwise would be great if you could look into that as well.

**Comment by ppigazzini** [comment]
@tomtor yes, I stopped always at step 3.
Sorry for the late answer but I wrote a little patch to unblock the default users on the dev server and update the install scripts :-)

official server updated.

**Pull request merged**
