### PR TITLE
Don't show base branch comparison message for old finished tests

### PR DESCRIPTION
**Pull request by linrock**
@ppigazzini can you see if this fixes the issue you mentioned? i'm unable to test on my dev server
https://github.com/glinscott/fishtest/pull/559#issuecomment-610654540

these are the two test pages you mentioned:
https://tests.stockfishchess.org/tests/view/5214a8390ebc59160a0182f6
https://tests.stockfishchess.org/tests/view/5214ce9a0ebc59160a0182f8

### CODE REVIEW

**Comment by ppigazzini** [comment]
@linrock  DEV updated, unfortunately this don't fix the problem
https://dfts-0.pigazzini.it/tests/view/5214a8390ebc59160a0182f6

```bash
git log --oneline -n 6
1e0e59c (HEAD -> master) Merge commit 'refs/pull/567/head' of https://github.com/glinscott/fishtest
ba235df Merge commit 'refs/pull/566/head' of https://github.com/glinscott/fishtest
1508976 Don't show base branch comparison message for old finished tests
a06dff1 Show number of github comments on the diff when viewing tests
52b37f0 (origin/master, origin/HEAD) Make sure book exists in official repo when validating tests
e04e8e4 Show # active tests on homepage. Move active machines section
```

**Comment by linrock** [comment]
@ppigazzini ah oops, i'd missed something but fixed it. please try now

**Comment by ppigazzini** [comment]
PROD updated, thank you @linrock :)

Until 20 minutes ago the API calls on PROD and DEV weren't working, I suppose we hit the 60 calls limit.

**Comment by ppigazzini** [comment]
@linrock bedtime here in Italy ;)

**Comment by linrock** [comment]
@ppigazzini no prob, good night! i'll submit a PR for an API limit fix

**Pull request merged**
