### PR TITLE
Add page navigation at bottom

### PR DESCRIPTION
**Pull request by ianfab**
When scrolling through the test results I think it would be convenient to also have a pagination at the bottom, because you otherwise have to scroll back to the top before you can go to the next page.

### CODE REVIEW

**Comment by Stefano80** [comment]
Do you have a link or a screenshot to see how it will look like? (I still have to install my development server, sorry).

**Comment by ppigazzini** [comment]
@Stefano80 check the [multi variant fishtest](http://35.161.250.236:6543/tests)

**Comment by ianfab** [comment]
Yes, I have already merged all of my PRs to multi-variant fishtest some time ago, so you can check how it looks and behaves there.

**Comment by ppigazzini** [comment]
... and all my PRs too ;)

**Comment by Stefano80** [comment]
Merged https://github.com/glinscott/fishtest/pull/119. @ppigazzini : could you merge on the server? After our last email exchange, I am not sure I want to be the one to do it.

**Comment by ppigazzini** [comment]
@Stefano80 I missed this message, sorry. The server is up-to-date, so I think that you have already synced the repos.

**Pull request merged**
