### PR TITLE
Allow FRC testing

### PR DESCRIPTION
**Pull request by G-Lorenz**
This patch set the variant by reading book's name.
Based on: https://github.com/AndyGrant/OpenBench/commit/b9f86691b1be19c7f0a3a9f40c74fe0394b3f3aa

Comments on Discord: https://discord.com/channels/435943710472011776/900771437177094156/929026322913689662

### CODE REVIEW

**Comment by vondele** [comment]
to test this, I need to merge the book first: https://github.com/official-stockfish/books/pull/23

**Comment by ppigazzini** [comment]
Yes, I know :)
Test workers waiting.

**Comment by vondele** [comment]
merged..

**Comment by ppigazzini** [comment]
@vondele please refresh my memory about the SF book depth option to be used with startpos_chess960.epd

**Comment by vondele** [comment]
nothing, should not be shown for .epd ?

**Comment by ppigazzini** [comment]
with that book I got:
```
Warning: Can't open opening suite startpos_chess960.epd
Warning: Invalid value for option "-openings": "file=startpos_chess960.epd format=epd order=random plies=16 start=146"
```

**Comment by vondele** [comment]
Ok, it is a mistake in the zipping of the book:
```
$ unzip startpos_chess960.epd.zip 
Archive:  startpos_chess960.epd.zip
  inflating: chess960.epd            
```
doesn't inflate to the right name, I'll make an update

**Comment by ppigazzini** [comment]
Ok, thank you :)

**Comment by vondele** [comment]
should be fixed now.

**Comment by ppigazzini** [comment]
Fixed,

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated to trigger the workers update, thank you @G-Lorenz :)

**Pull request merged**
