### PR TITLE
Upload pgn file also for tasks that weren't finished.

### PR DESCRIPTION
**Pull request by vdbergh**
This will hopefully help with debugging the "unclean finish" of tasks.

### CODE REVIEW

**Comment by ppigazzini** [comment]
I don't know what means "unclean finish" for cutechess-cli...

**Comment by ppigazzini** [comment]
Ah, sorry, it's a fishtest message.

**Comment by ppigazzini** [comment]
These some machines with "Unclean Finish", linux/windows, no pattern:


Time | Username | Run/User | Action
-- | -- | -- | --
21-10-21 19:37:31 | bcross | sanityCheck6 | failed task: task_id: 15, worker: bcross-15cores-f1a3a701, reason: 'Finished match uncleanly'
21-10-21 13:32:12 | grandphish2 | prunePAWN | failed task: task_id: 1576, worker: grandphish2-16cores-f1cd7a45, reason: 'Finished match uncleanly'
21-10-21 09:28:59 | gvreuls | prunePAWN | failed task: task_id: 1080, worker: gvreuls-4cores-158e9e32, reason: 'Finished match uncleanly'
21-10-21 05:59:40 | ChessDBCN | singular31^ | failed task: task_id: 364, worker: ChessDBCN-16cores-c2e4b27c, reason: 'Finished match uncleanly'

**Comment by vdbergh** [comment]
First of all this PR fixes a bug. Currently (for example) if the match finishes uncleanly the pgn isn’t uploaded. This is wrong.

Secondly there is the “unclean finish” issue itself. 

We have to establish if it is the worker’s fault or cutechess’. With this PR we can see 

- if cutechess has really played the number games it was asked to (since we have the pgn now); 
- the results of those games. 

For example if there are games with result “-“ then this would lead to an unclean finish, which would be expected.

**Pull request merged**
