### PR TITLE
Fix variable shadowing

### PR DESCRIPTION
**Pull request by noobpwnftw**

### CODE REVIEW

**Comment by tomtor** [comment]
Good catch! @noobpwnftw

**Comment by tomtor** [comment]
Will restart after mongodump finishes (around 10:20)

**Comment by ppigazzini** [comment]
@tomtor I use `bash x/sync_repo.sh` to automate the server update, why should you wait the backup finish? (just asking for information).

**Comment by tomtor** [comment]
> why should you wait the backup finish?

A few days ago I noticed that a restart of fishtest also restarted MongoDb in the syslog (That suprised me, I do not see that now in the last syslog). I was afraid that a restart of mongodb might interfere with a running mongodump.

**Comment by ppigazzini** [comment]
> > why should you wait the backup finish?
> 
> A few days ago I noticed that a restart of fishtest also restarted MongoDb in the syslog (That suprised me, I do not see that now in the last syslog). I was afraid that a restart of mongodb might interfere with a running mongodump.

A few day ago I restated mongod by hand to try to debug the workers idling problem :)
Neither `x/sync_repo.sh` nor `x/update_fishtest.sh` restart mongod.

**Comment by tomtor** [comment]
> A few day ago I restated mongod by hand to try to debug the workers idling problem

Ahh, I see, I was surprised to see that in the log.
So, without a restart of mongodb there is indeed no reason to wait for mongodump to finish....

**Pull request merged**
