### PR TITLE
Replace homebrew by scipy functions.

### PR DESCRIPTION
**Pull request by vdbergh**
As the subjects says.

### CODE REVIEW

**Comment by vdbergh** [comment]
Sorry. The raw statistics pages gives an exception now (I only ran the unit tests in stat_util.py and they worked fine). I'll check it out.

**Comment by vdbergh** [comment]
Should be fixed now. I changed phi to Phi as it is more standard, but I forgot to do it in one of the templates.

**Comment by ppigazzini** [comment]
@vdbergh DEV updated, it's fixed :)

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh !

**Pull request merged**
