### PR TITLE
Add User Management for approvers

### PR DESCRIPTION
**Pull request by tomtor**
Block/Unblock users and show eMail information

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor after updating the dev-server and the workers I have this error message:
```
Worker version 62 connecting to http://94.198.98.239:80
Will fetch task soon...
Exception accessing host:
Traceback (most recent call last):
  File "worker.py", line 72, in worker
    req = json.loads(req.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by tomtor** [comment]
@ppigazzini I got that one too. It looks like the standard error when the server cannot be accessed?

I found a functional bug however, the task hyperlinks point to the wrong user. I'll fix that soon....

**Comment by tomtor** [comment]
@ppigazzini Fixed...

**Comment by tomtor** [comment]
@ppigazzini I have still the worker message. Will look at that...

**Comment by ppigazzini** [comment]
@tomtor I confirm the error message with the dev-server

**Comment by tomtor** [comment]
@ppigazzini Sorry, for the trouble. It should work now. Note that in userdb.py is some old code at the end of the file:

        # TODO: hook the blocked info into the database
        blocked = [ 'garry561', 'EthanOConnor', 'IamLupo', 'waykohler' ]
        if worker_info['remote_addr'] in blocked or worker_info['username'] in blocked:
          return True

that could be removed once we merge this PR and add block this users from the GUI

**Comment by ppigazzini** [comment]
@tomtor dev-server and workers updated, ATM all is working fine.

**Comment by ppigazzini** [comment]
@tomtor after blocking an user the worker has this output:
* when running
```
Started game 428 of 975 (base vs stockfish)
Finished game 426 (base vs stockfish): 1/2-1/2 {Draw by adjudication}
Score of stockfish vs base: 140 - 145 - 141  [0.494] 426
Exception from calling update_task:
Traceback (most recent call last):
  File "/root/_git/fishtest/worker/games.py", line 248, in run_game
    if not req['task_alive']:
KeyError: 'task_alive'
Started game 429 of 975 (stockfish vs base)
Finished game 428 (base vs stockfish): 1-0 {White wins by adjudication}
Score of stockfish vs base: 140 - 146 - 141  [0.493] 427
Exception from calling update_task:
Traceback (most recent call last):
  File "/root/_git/fishtest/worker/games.py", line 248, in run_game
    if not req['task_alive']:
KeyError: 'task_alive'
Started game 430 of 975 (base vs stockfish)
Finished game 427 (stockfish vs base): 0-1 {Black wins by adjudication}
Score of stockfish vs base: 140 - 147 - 141  [0.492] 428
Exception from calling update_task:
Traceback (most recent call last):
  File "/root/_git/fishtest/worker/games.py", line 248, in run_game
    if not req['task_alive']:
KeyError: 'task_alive'
```
  * after finishing a job
```
Exception running games:
Traceback (most recent call last):
  File "worker.py", line 91, in worker
    run_games(worker_info, password, remote, run, task_id)
  File "/home/ppadmin/_git/fishtest/worker/games.py", line 449, in run_games
    task_status = launch_cutechess(cmd, remote, result, spsa_tuning, games_to_play, tc_limit * games_to_play / min(games_to_play, games_concurrency))
  File "/home/ppadmin/_git/fishtest/worker/games.py", line 282, in launch_cutechess
    w_params = req['w_params']
KeyError: 'w_params'
Task exited
Will fetch task soon...
Incorrect username/password
Exception accessing host:
Traceback (most recent call last):
  File "worker.py", line 65, in worker
    sys.exit(1)
SystemExit: 1
```

**Comment by vondele** [comment]
I think this is a good idea, but it should be really used sparingly by approvers, and in particular, before blocking a user, they should really drop an email to that user to discuss this first.

**Comment by vondele** [comment]
@ppigazzini seems like a reasonable policy to me.

**Comment by snicolet** [comment]
It looks like a reasonable process to me too.

I have added the FAQ section at the end of the wiki page:
https://github.com/glinscott/fishtest/wiki/Fishtest-server-setup

**Comment by Stefano80** [comment]
Hi @tomtor, played around in the test server looks really good to me. The usual question: can we somehow test this on travis CI?

**Comment by Stefano80** [comment]
You're right, we should merge as it is without quick-and-dirty solutions. 

On the other side, if we cannot make simple tests for this kind of changes, maybe the overall design of fishtest still have some flaws.

**Comment by ppigazzini** [comment]
@tomtor @Stefano80 official server updated and restarted
@snicolet as SF maintainer in charge you should inform all the approvers about the new feature :)

**Comment by ppigazzini** [comment]
@snicolet of course, you can try on the [dev-server](http://94.198.98.239/tests): block/unblock some of the users.
1. login with your username/password
2. click on a run
3. all the workers names are now a hyperlink for the approvers (and only for the approvers)
4. click on a worker
5. you view some info about the user: e.g. the email
6. you can block/unblock the user. If blocked the user cannot login in fishtest (e.g. submitting a test) and the workers cannot join the framework

This features is now in production on the official server.

**Comment by ppigazzini** [comment]
@snicolet the fishtest maintainers can change the db content on the production server using a python script or the mongo console. Sorry to ruin your dream of omnipotence :)

**Comment by snicolet** [comment]
@ppigazzini I don't have the credentials to do anything server-wise :-)

**Comment by ppigazzini** [comment]
@snicolet yes, right, you are only the SF maintainer, division of the powers to keep the play honest :-)
The message is that if an approver should go nuts blocking all users/approvers, the fishtest maintainers can block the crazy approver and unblock the other users/approvers.

**Comment by tomtor** [comment]
Fishtest security is very weak,  I wont list the details here,  but if we find it a concern then it could be improved with some additional code. We also need a change in new user policy if security is a concern. A user should have to enter a valid e-mail to which fishtest sends a mail with a confirmation link. Step two would be that an approver activates this user or we could auto improve after eg 60 minutes.
The current blocking option is mainly intended to stop a faulty worker which has been misconfigured in some way.

**Pull request merged**
