### PR TITLE
Regularly purge stale notifications.

### PR DESCRIPTION
**Pull request by vdbergh**
Stale notifications are notifications for finished runs. They are harmless but they needlessly load the server (forever with the current implementation).

Stale notifications can for example be created by subscribing to a finished run in a browser tab that was not refreshed.

Purging will happen every 5.5 hours on average and uses the active_runs api to detect finished but still subscribed runs.

### CODE REVIEW

**Comment by vdbergh** [comment]
I tested this as follows.

Set the interval to 20s instead of 5.5 hours.
Open Firefox and Chrome and create a new test in one of the browsers. 
Refresh the browsers.
Delete the test in Chrome.
Subscribe in Firefox.
Watch the console to see the purging message appear.

**Comment by vdbergh** [comment]
Drafted. Just saw a bug.

**Comment by vdbergh** [comment]
Undrafted.

**Review by ppigazzini — APPROVED** [review]
LGTM on my tests.

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
