### PR TITLE
Fix order for purging PGNs

### PR DESCRIPTION
**Pull request by tomtor**
See #642

### CODE REVIEW

**Comment by tomtor** [comment]
@ppigazzini I am still testing this so not ready to merge...

**Comment by tomtor** [comment]
@ppigazzini On prod it is now busy removing PGNs (added some logging) but storage is not shrinking fast. Not sure how/when MongoDb frees/compacts storage...

**Comment by tomtor** [comment]
@ppigazzini Do we need a "compact" command?

https://dzone.com/articles/reclaiming-disk-space-from-mongodb

**Comment by ppigazzini** [comment]
@tomtor with the old server I always walked the safe way with `mongodump` `mongorestore`

**Comment by tomtor** [comment]
testing:

```
use fishtest_new
switched to db fishtest_new
db.runCommand({compact:'pgns'})
```

This frees the space!

**Comment by tomtor** [comment]
@ppigazzini On prod now:

```
Filesystem         Size  Used Avail Use% Mounted on
/dev/ploop12245p1   99G   63G   32G  67% /
```
I will rerun the purge script because I stopped it to run the compact command

**Comment by ppigazzini** [comment]
@tomtor 
https://docs.mongodb.com/manual/reference/command/compact/
"compact only blocks operations for the database it is currently operating on. Only use compact during scheduled maintenance periods."

I wrote this x file:

```bash
# sudo compact_pgns.sh | tee compact_pgns.sh.log
user_name='fishtest'

systemctl stop cron
systemctl stop fishtest@{6543..6544}

sleep 120 # waiting for running jobs

sudo -i -u ${user_name} << 'EOF000'
mongo << EOF
use fishtest_new
db.runCommand({compact:'pgns'})
exit
EOF
EOF000

systemctl start cron
systemctl start fishtest@{6543..6544}
```

**Comment by tomtor** [comment]
I do not think compacting is needed in normal operations.
Only now when cleaning up the backlog...

**Comment by ppigazzini** [comment]
> I do not think compacting is needed in normal operations.
> Only now when cleaning up the backlog...

Correct, I wrote the script in "x" folder ;)

**Comment by tomtor** [comment]
Must also look at the 'pgn_100' api.

It might need an update too.

**Comment by tomtor** [comment]
> Must also look at the 'pgn_100' api.

That looks OK (explicit sort on `id` descending)

@linrock I wonder why the purge pgn script broke?
It used to sort on descending run `id` by default but that property was somehow lost.
Anyway, explicitly sorting on `last-updated` is better

@ppigazzini Purge script is still busy purging. I will let you know when to run the compact script later this day.

**Comment by tomtor** [comment]
@ppigazzini Purge script is finished. Please run your `compact` script and merge this PR at a convenient time.

**Comment by ppigazzini** [comment]
PROD updated, `pgns` compacted, thank you @tomtor :)
- before
```
> db.pgns.stats()
{
        "ns" : "fishtest_new.pgns",
        "size" : 79297209417,
        "count" : 498640,
        "avgObjSize" : 159026,
        "storageSize" : 80386555904,
```
- after
```
> db.pgns.stats()
{
        "ns" : "fishtest_new.pgns",
        "size" : 13706136005,
        "count" : 88222,
        "avgObjSize" : 155359,
        "storageSize" : 16841424896,
```

**Pull request merged**
