### PR TITLE
Add sorting to table headers

### PR DESCRIPTION
**Pull request by tomtor**
Other part of #293

### CODE REVIEW

**Comment by tomtor** [comment]
Does not work on mobile. Will have a look at that...

**Comment by tomtor** [comment]
It DID work on mobile after all, but I changed it so sorting works on any table on each page by clicking the table headers.

**Comment by ppigazzini** [comment]
@tomtor let me know if this is ready to be merged.

**Comment by tomtor** [comment]
@ppigazzini Ready

**Comment by ppigazzini** [comment]
Production server updated.
@tomtor Thank you!

**Pull request merged**
