### PR TITLE
Make the notification toggle disappear after a finished test.

### PR DESCRIPTION
**Pull request by vdbergh**
Also fix a small bug in the last PR.

### CODE REVIEW

**Comment by vdbergh** [comment]
The toggle will disappear immediately if the user was following the test (and hence was notified). If the user is not following then after enabling the toggle he will get a final notification and then the toggle will disappear as well.

**Comment by vdbergh** [comment]
Yes I see how this can happen. It is due to the interaction between the browser tabs (they realize that a run is finished at different times). I need to think about a better solution.

**Comment by vdbergh** [comment]
I hope it is fixed.

**Comment by ppigazzini** [comment]
Tests started.

**Comment by ppigazzini** [comment]
Clicking very fast on the unfollowed test icon I was able to get 2 notifications on Firefox before the icon grayed out. The other 3 browser were more smart, though.
On Android I got 2 notification by the SPSA, but the browser goes in sleep mode on mobile.
I opened a big number of tabs in any browser.

LGTM :)

image

**Review by ppigazzini — APPROVED** [review]

**Comment by vdbergh** [comment]
Yes there are some race conditions. With fast clicking or a lot of tabs open they are more likely to be triggered I guess. An occasional double notification under stringent conditions is not the end of the world.

To get rid of the race conditions the communication between the tabs should be sanitized. But not now....

**Comment by vdbergh** [comment]
If a tab is sleeping  while receiving a message then I guess strange things might be happening. I did not consider this possibility.

**Comment by ppigazzini** [comment]
I will merge the PR as soon as in "Ready for review" mode.

**Comment by vdbergh** [comment]
> I will merge the PR as soon as in "Ready for review" mode.

Ah forgotten that I had put it into draft mode. Undrafted.

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
