### PR TITLE
Lazy-load machines table on homepage if hidden by user

### PR DESCRIPTION
**Pull request by linrock**
@tomtor as we discussed in https://github.com/glinscott/fishtest/pull/581, this is what i was thinking:
- if the user has the machines table hidden by default, it won't be rendered upon pageload
- if the user clicks "Show" while the table doesn't exist, the table is fetched and then rendered

the idea is to speed up the homepage by doing less work on both client and server when not needed, but there are still a lot of calculations done for the homepage on each request.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@linrock Internal server error trying to show the machines 
```
-- Logs begin at Mon 2020-04-13 02:41:46 CEST, end at Mon 2020-04-13 02:42:21 CEST. --
Apr 13 02:42:15 vps1572612706 pserve[14365]: 2020-04-13 02:42:15,281 ERROR [waitress][waitress] Exception while serving /tests
Apr 13 02:42:15 vps1572612706 pserve[14365]: Traceback (most recent call last):
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
Apr 13 02:42:15 vps1572612706 pserve[14365]:     response = request.invoke_exception_view(exc_info)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 779, in invoke_exception_view
Apr 13 02:42:15 vps1572612706 pserve[14365]:     raise HTTPNotFound
Apr 13 02:42:15 vps1572612706 pserve[14365]: pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
Apr 13 02:42:15 vps1572612706 pserve[14365]: During handling of the above exception, another exception occurred:
Apr 13 02:42:15 vps1572612706 pserve[14365]: Traceback (most recent call last):
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/channel.py", line 349, in service
Apr 13 02:42:15 vps1572612706 pserve[14365]:     task.service()
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 169, in service
Apr 13 02:42:15 vps1572612706 pserve[14365]:     self.execute()
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 439, in execute
Apr 13 02:42:15 vps1572612706 pserve[14365]:     app_iter = self.channel.server.application(environ, start_response)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/proxy_headers.py", line 65, in translate_proxy_headers
Apr 13 02:42:15 vps1572612706 pserve[14365]:     return app(environ, start_response)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
Apr 13 02:42:15 vps1572612706 pserve[14365]:     response = self.execution_policy(environ, self)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 279, in default_execution_policy
Apr 13 02:42:15 vps1572612706 pserve[14365]:     return request.invoke_exception_view(reraise=True)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 778, in invoke_exception_view
Apr 13 02:42:15 vps1572612706 pserve[14365]:     reraise_(*exc_info)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Apr 13 02:42:15 vps1572612706 pserve[14365]:     raise value
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 277, in default_execution_policy
Apr 13 02:42:15 vps1572612706 pserve[14365]:     return router.invoke_request(request)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
Apr 13 02:42:15 vps1572612706 pserve[14365]:     response = handle_request(request)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
Apr 13 02:42:15 vps1572612706 pserve[14365]:     response = _error_handler(request, exc)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
Apr 13 02:42:15 vps1572612706 pserve[14365]:     reraise(*exc_info)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Apr 13 02:42:15 vps1572612706 pserve[14365]:     raise value
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
Apr 13 02:42:15 vps1572612706 pserve[14365]:     response = handler(request)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
Apr 13 02:42:15 vps1572612706 pserve[14365]:     registry, request, context, context_iface, view_name
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
Apr 13 02:42:15 vps1572612706 pserve[14365]:     response = view_callable(context, request)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 460, in rendered_view
Apr 13 02:42:15 vps1572612706 pserve[14365]:     request, result, view_inst, context
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/renderers.py", line 451, in render_view
Apr 13 02:42:15 vps1572612706 pserve[14365]:     return self.render_to_response(response, system, request=request)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/renderers.py", line 474, in render_to_response
Apr 13 02:42:15 vps1572612706 pserve[14365]:     result = self.render(value, system_values, request=request)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/renderers.py", line 470, in render
Apr 13 02:42:15 vps1572612706 pserve[14365]:     result = renderer(value, system_values)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid_mako/__init__.py", line 156, in __call__
Apr 13 02:42:15 vps1572612706 pserve[14365]:     reraise(MakoRenderingException(errtext), None, exc_info[2])
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid_mako/compat.py", line 74, in reraise
Apr 13 02:42:15 vps1572612706 pserve[14365]:     raise value.with_traceback(tb)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid_mako/__init__.py", line 148, in __call__
Apr 13 02:42:15 vps1572612706 pserve[14365]:     result = template.render_unicode(**system)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/template.py", line 482, in render_unicode
Apr 13 02:42:15 vps1572612706 pserve[14365]:     self, self.callable_, args, data, as_unicode=True
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 883, in _render
Apr 13 02:42:15 vps1572612706 pserve[14365]:     **_kwargs_for_callable(callable_, data)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 920, in _render_context
Apr 13 02:42:15 vps1572612706 pserve[14365]:     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 947, in _exec_template
Apr 13 02:42:15 vps1572612706 pserve[14365]:     callable_(context, *args, **kwargs)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "base_mak", line 57, in render_body
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "tests_mak", line 67, in render_body
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 782, in _include_file
Apr 13 02:42:15 vps1572612706 pserve[14365]:     template = _lookup_template(context, uri, calling_uri)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 841, in _lookup_template
Apr 13 02:42:15 vps1572612706 pserve[14365]:     raise exceptions.TemplateLookupException(str(compat.exception_as()))
Apr 13 02:42:15 vps1572612706 pserve[14365]: pyramid_mako.MakoRenderingException:
Apr 13 02:42:15 vps1572612706 pserve[14365]: Traceback (most recent call last):
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid_mako/__init__.py", line 148, in __call__
Apr 13 02:42:15 vps1572612706 pserve[14365]:     result = template.render_unicode(**system)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/template.py", line 482, in render_unicode
Apr 13 02:42:15 vps1572612706 pserve[14365]:     self, self.callable_, args, data, as_unicode=True
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 883, in _render
Apr 13 02:42:15 vps1572612706 pserve[14365]:     **_kwargs_for_callable(callable_, data)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 920, in _render_context
Apr 13 02:42:15 vps1572612706 pserve[14365]:     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 947, in _exec_template
Apr 13 02:42:15 vps1572612706 pserve[14365]:     callable_(context, *args, **kwargs)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/fishtest/templates/base.mak", line 87, in render_body
Apr 13 02:42:15 vps1572612706 pserve[14365]:     <main>${self.body()}</main>
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/fishtest/templates/tests.mak", line 25, in render_body
Apr 13 02:42:15 vps1572612706 pserve[14365]:     <%include file="machines_table.mak" args="machines=machines"/>
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 782, in _include_file
Apr 13 02:42:15 vps1572612706 pserve[14365]:     template = _lookup_template(context, uri, calling_uri)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 841, in _lookup_template
Apr 13 02:42:15 vps1572612706 pserve[14365]:     raise exceptions.TemplateLookupException(str(compat.exception_as()))
Apr 13 02:42:15 vps1572612706 pserve[14365]: TemplateLookupException: Cant locate template for uri 'machines_table.mak'
Apr 13 02:42:15 vps1572612706 pserve[14365]: 2020-04-13 02:42:15,695 ERROR [waitress][waitress] Exception while serving /tests
Apr 13 02:42:15 vps1572612706 pserve[14365]: Traceback (most recent call last):
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
Apr 13 02:42:15 vps1572612706 pserve[14365]:     response = request.invoke_exception_view(exc_info)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 779, in invoke_exception_view
Apr 13 02:42:15 vps1572612706 pserve[14365]:     raise HTTPNotFound
Apr 13 02:42:15 vps1572612706 pserve[14365]: pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
Apr 13 02:42:15 vps1572612706 pserve[14365]: During handling of the above exception, another exception occurred:
Apr 13 02:42:15 vps1572612706 pserve[14365]: Traceback (most recent call last):
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/channel.py", line 349, in service
Apr 13 02:42:15 vps1572612706 pserve[14365]:     task.service()
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 169, in service
Apr 13 02:42:15 vps1572612706 pserve[14365]:     self.execute()
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 439, in execute
Apr 13 02:42:15 vps1572612706 pserve[14365]:     app_iter = self.channel.server.application(environ, start_response)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/proxy_headers.py", line 65, in translate_proxy_headers
Apr 13 02:42:15 vps1572612706 pserve[14365]:     return app(environ, start_response)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
Apr 13 02:42:15 vps1572612706 pserve[14365]:     response = self.execution_policy(environ, self)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 279, in default_execution_policy
Apr 13 02:42:15 vps1572612706 pserve[14365]:     return request.invoke_exception_view(reraise=True)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 778, in invoke_exception_view
Apr 13 02:42:15 vps1572612706 pserve[14365]:     reraise_(*exc_info)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Apr 13 02:42:15 vps1572612706 pserve[14365]:     raise value
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 277, in default_execution_policy
Apr 13 02:42:15 vps1572612706 pserve[14365]:     return router.invoke_request(request)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
Apr 13 02:42:15 vps1572612706 pserve[14365]:     response = handle_request(request)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
Apr 13 02:42:15 vps1572612706 pserve[14365]:     response = _error_handler(request, exc)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
Apr 13 02:42:15 vps1572612706 pserve[14365]:     reraise(*exc_info)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Apr 13 02:42:15 vps1572612706 pserve[14365]:     raise value
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
Apr 13 02:42:15 vps1572612706 pserve[14365]:     response = handler(request)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
Apr 13 02:42:15 vps1572612706 pserve[14365]:     registry, request, context, context_iface, view_name
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
Apr 13 02:42:15 vps1572612706 pserve[14365]:     response = view_callable(context, request)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 460, in rendered_view
Apr 13 02:42:15 vps1572612706 pserve[14365]:     request, result, view_inst, context
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/renderers.py", line 451, in render_view
Apr 13 02:42:15 vps1572612706 pserve[14365]:     return self.render_to_response(response, system, request=request)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/renderers.py", line 474, in render_to_response
Apr 13 02:42:15 vps1572612706 pserve[14365]:     result = self.render(value, system_values, request=request)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/renderers.py", line 470, in render
Apr 13 02:42:15 vps1572612706 pserve[14365]:     result = renderer(value, system_values)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid_mako/__init__.py", line 156, in __call__
Apr 13 02:42:15 vps1572612706 pserve[14365]:     reraise(MakoRenderingException(errtext), None, exc_info[2])
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid_mako/compat.py", line 74, in reraise
Apr 13 02:42:15 vps1572612706 pserve[14365]:     raise value.with_traceback(tb)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid_mako/__init__.py", line 148, in __call__
Apr 13 02:42:15 vps1572612706 pserve[14365]:     result = template.render_unicode(**system)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/template.py", line 482, in render_unicode
Apr 13 02:42:15 vps1572612706 pserve[14365]:     self, self.callable_, args, data, as_unicode=True
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 883, in _render
Apr 13 02:42:15 vps1572612706 pserve[14365]:     **_kwargs_for_callable(callable_, data)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 920, in _render_context
Apr 13 02:42:15 vps1572612706 pserve[14365]:     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 947, in _exec_template
Apr 13 02:42:15 vps1572612706 pserve[14365]:     callable_(context, *args, **kwargs)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "base_mak", line 57, in render_body
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "tests_mak", line 67, in render_body
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 782, in _include_file
Apr 13 02:42:15 vps1572612706 pserve[14365]:     template = _lookup_template(context, uri, calling_uri)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 841, in _lookup_template
Apr 13 02:42:15 vps1572612706 pserve[14365]:     raise exceptions.TemplateLookupException(str(compat.exception_as()))
Apr 13 02:42:15 vps1572612706 pserve[14365]: pyramid_mako.MakoRenderingException:
Apr 13 02:42:15 vps1572612706 pserve[14365]: Traceback (most recent call last):
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid_mako/__init__.py", line 148, in __call__
Apr 13 02:42:15 vps1572612706 pserve[14365]:     result = template.render_unicode(**system)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/template.py", line 482, in render_unicode
Apr 13 02:42:15 vps1572612706 pserve[14365]:     self, self.callable_, args, data, as_unicode=True
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 883, in _render
Apr 13 02:42:15 vps1572612706 pserve[14365]:     **_kwargs_for_callable(callable_, data)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 920, in _render_context
Apr 13 02:42:15 vps1572612706 pserve[14365]:     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 947, in _exec_template
Apr 13 02:42:15 vps1572612706 pserve[14365]:     callable_(context, *args, **kwargs)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/fishtest/templates/base.mak", line 87, in render_body
Apr 13 02:42:15 vps1572612706 pserve[14365]:     <main>${self.body()}</main>
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/fishtest/templates/tests.mak", line 25, in render_body
Apr 13 02:42:15 vps1572612706 pserve[14365]:     <%include file="machines_table.mak" args="machines=machines"/>
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 782, in _include_file
Apr 13 02:42:15 vps1572612706 pserve[14365]:     template = _lookup_template(context, uri, calling_uri)
Apr 13 02:42:15 vps1572612706 pserve[14365]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/mako/runtime.py", line 841, in _lookup_template
Apr 13 02:42:15 vps1572612706 pserve[14365]:     raise exceptions.TemplateLookupException(str(compat.exception_as()))
Apr 13 02:42:15 vps1572612706 pserve[14365]: TemplateLookupException: Cant locate template for uri 'machines_table.mak'
```

**Comment by linrock** [comment]
oops, i forgot to check in the template file 🤦 fixed now

**Comment by ppigazzini** [comment]
DEV updated, looks good.

**Comment by ppigazzini** [comment]
I will wait review/suggestions by @tomtor before merging (03:11 AM in our TZ)

**Comment by tomtor** [comment]
@linrock Nice feature! Thanks

@ppigazzini Ok to merge!

**Comment by ppigazzini** [comment]
PROD updated, thank you @linrock :)

**Pull request merged**
