### PR TITLE
Handle users which are not logged in

### LINKED ISSUE #400: Internal error when rescheduling not logged in
When not being logged in, pressing reschedule or new generates:
```
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```
previously one would get a redirect to the login page, IIRC.

### PR DESCRIPTION
**Pull request by tomtor**
This was broken by
https://github.com/glinscott/fishtest/pull/392

and should fix #400

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor some problems detected during tests.

 * not logged, pushing:
   * `Modify`, `Reschedule` -> redirection to `/login`
   * `Purge` -> redirection to `/tests/purge` w/ the login form

 * logged as normal user, pushing:
   * `Modify` -> redirection to `/tests` w/ message 'Unable to modify another users run!'
   * `Purge` -> redirection to `/tests/purge` w/ the login form w/ message 'Permission Required. Creating or modifying tests requires you to be logged in.'

 * when not logged or logged as normal user -> pushing `Purge` -> redirection to `/tests/purge` -> login as approver, got:
```Internal Server Error
The server encountered an unexpected internal server error
(generated by waitress)```

**Comment by tomtor** [comment]
> * when not logged or logged as normal user -> pushing `Purge` -> redirection to `/tests/purge` -> login as approver, got:

This must be VERY old behaviour (eg never tested). Should be fixed now by latest push.

I wonder if "approve" when not being logged in (as approver) behaves correctly, or just shows the /tests page without any errors/warning? I cannot easily test this, because I am on the road. If behaviour is not OK then I change that also...

**Comment by ppigazzini** [comment]
@tomtor I badly missed the `Approve` button. I take full responsibility for my actions in the matter. I apologize to the fans, to my family for the embarrassment I have caused them. I ask you all for your forgiveness. This is not the example I want to set. It's my hope that we work to move forward from this event, and never let something like this happen again.

 * normal user or not logged -> push `Approve` -> redirection to `/tests/approve` w/ login form -> login as approver -> redirection to `/tests` (if login as normal user -> message 'Permission required...')

https://github.com/glinscott/fishtest/pull/401/commits/27ba5d8ed9ef5db92c8b9285cd0d4609c88b2334 works fine, so let me know if this is ready to be merged.

**Comment by tomtor** [comment]
@ppigazzini Thanks for all the tests! 
Ok, to merge

**Comment by ppigazzini** [comment]
Done, the prod server seems OK.
Thank you @tomtor

**Pull request merged**
