### PR TITLE
Keep the trinomial and pentanomial frequencies in sync (worker change).

### PR DESCRIPTION
**Pull request by vdbergh**
This was suggested by @vondele at fishcooking.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@vdbergh testing on DEV, at the moment looks good.

**Comment by ppigazzini** [comment]
@vdbergh SPSA tests seems wrong, the workers do nothing. I tested several SPSA tests from the past and load a fresh DB to try with a SPSA tune running fine now on PROD.
```
Task exited
Fetch task...
Worker version checked successfully in 0.161566s
Task requested in 0.176435s
Verifying signature of stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39 ...
Verifying signature of stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39 ...
CPU factor : 0.914518 - tc adjusted to 0.91+0.01
Running TuneEvalComponents vs TuneEvalComponents
Fetched SPSA parameters successfully in 0.182173s
['/home/usr00/_git/__test_folder00/fishtest/worker/testing/cutechess-cli', '-repeat', '-rounds', '8', '-tournament', 'gauntlet', '-site', 'https://tests.stockfishchess.org/tests/view/5e2de96a17eac1bf20fa2cf8', '-event', 'Batch 1: TuneEvalComponents vs TuneEvalComponents', '-srand', '72359515', '-resign', 'movecount=3', 'score=400', '-draw', 'movenumber=34', 'movecount=8', 'score=20', '-concurrency', '4', '-openings', 'file=noob_3moves.epd', 'format=epd', 'order=random', 'plies=16', '-engine', 'name=New-d6ab17e', 'cmd=stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39', 'option.Hash=128', 'option.nodestime=600', 'option.factors[0]=72', 'option.factors[1]=56', 'option.factors[2]=56', 'option.factors[3]=56', 'option.factors[4]=56', 'option.factors[5]=72', 'option.factors[6]=72', 'option.factors[7]=72', 'option.factors[8]=56', 'option.factors[9]=72', 'option.factors[10]=56', 'option.factors[11]=24', '-engine', 'name=Base-d6ab17e', 'cmd=stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39', 'option.Hash=128', 'option.nodestime=600', 'option.factors[0]=56', 'option.factors[1]=72', 'option.factors[2]=72', 'option.factors[3]=72', 'option.factors[4]=72', 'option.factors[5]=56', 'option.factors[6]=56', 'option.factors[7]=56', 'option.factors[8]=72', 'option.factors[9]=56', 'option.factors[10]=72', 'option.factors[11]=40', '-each', 'proto=uci', 'tc=0.91+0.01', 'timemargin=10000', 'option.Threads=1']
TC limit 18.29035481002037 End time: 2020-01-26 20:39:47.511076
Warning: 2 opening repetitions vs 1 games per encounter
Indexing opening suite...
Started game 1 of 8 (New-d6ab17e vs Base-d6ab17e)
Started game 2 of 8 (Base-d6ab17e vs New-d6ab17e)
Started game 3 of 8 (New-d6ab17e vs Base-d6ab17e)
Started game 4 of 8 (Base-d6ab17e vs New-d6ab17e)
Finished game 1 (New-d6ab17e vs Base-d6ab17e): 1-0 {White wins by adjudication}
Score of New-d6ab17e vs Base-d6ab17e: 1 - 0 - 0  [1.000] 1
Task updated successfully in 0.17825s
Server told us task is no longer needed
Wait 1 seconds before upload of PGN...
Task exited
Fetch task...
Worker version checked successfully in 0.162543s
Task requested in 0.179591s
Verifying signature of stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39 ...
Verifying signature of stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39 ...
CPU factor : 1.087049 - tc adjusted to 1.09+0.01
Running TuneEvalComponents vs TuneEvalComponents
Fetched SPSA parameters successfully in 0.154901s
['/home/usr00/_git/__test_folder00/fishtest/worker/testing/cutechess-cli', '-repeat', '-rounds', '8', '-tournament', 'gauntlet', '-site', 'https://tests.stockfishchess.org/tests/view/5e2de96a17eac1bf20fa2cf8', '-event', 'Batch 1: TuneEvalComponents vs TuneEvalComponents', '-srand', '3118090320', '-resign', 'movecount=3', 'score=400', '-draw', 'movenumber=34', 'movecount=8', 'score=20', '-concurrency', '4', '-openings', 'file=noob_3moves.epd', 'format=epd', 'order=random', 'plies=16', '-engine', 'name=New-d6ab17e', 'cmd=stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39', 'option.Hash=128', 'option.nodestime=600', 'option.factors[0]=72', 'option.factors[1]=72', 'option.factors[2]=56', 'option.factors[3]=56', 'option.factors[4]=72', 'option.factors[5]=72', 'option.factors[6]=56', 'option.factors[7]=56', 'option.factors[8]=56', 'option.factors[9]=56', 'option.factors[10]=72', 'option.factors[11]=24', '-engine', 'name=Base-d6ab17e', 'cmd=stockfish_d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39', 'option.Hash=128', 'option.nodestime=600', 'option.factors[0]=56', 'option.factors[1]=56', 'option.factors[2]=72', 'option.factors[3]=72', 'option.factors[4]=56', 'option.factors[5]=56', 'option.factors[6]=72', 'option.factors[7]=72', 'option.factors[8]=72', 'option.factors[9]=72', 'option.factors[10]=56', 'option.factors[11]=40', '-each', 'proto=uci', 'tc=1.09+0.01', 'timemargin=10000', 'option.Threads=1']
TC limit 21.740976645435246 End time: 2020-01-26 20:40:13.721021
Warning: 2 opening repetitions vs 1 games per encounter
Indexing opening suite...
Started game 1 of 8 (New-d6ab17e vs Base-d6ab17e)
Started game 2 of 8 (Base-d6ab17e vs New-d6ab17e)
Started game 3 of 8 (New-d6ab17e vs Base-d6ab17e)
Started game 4 of 8 (Base-d6ab17e vs New-d6ab17e)
Finished game 1 (New-d6ab17e vs Base-d6ab17e): 0-1 {Black wins by adjudication}
Score of New-d6ab17e vs Base-d6ab17e: 0 - 1 - 0  [0.000] 1
Task updated successfully in 0.159247s
Server told us task is no longer needed
Wait 4 seconds before upload of PGN...
Task exited
Fetch task..
```

**Comment by ppigazzini** [comment]
@vdbergh 
https://dfts-0.pigazzini.it/tests/view/5e2de96a17eac1bf20fa2cf8
https://tests.stockfishchess.org/tests/view/5e2dade6ab2d69d58394fb5e

**Comment by vdbergh** [comment]
I hadn't considered that SPSA might be different.

However in this particular case the worker appears to be crashing during compile. Can you check if you have a similar issue?

**Comment by vdbergh** [comment]
```Exception running games:
Traceback (most recent call last):
  File "/home/fishtest/fishtest/worker/games.py", line 133, in setup_engine
    subprocess.check_call(MAKE_CMD + ' -j %s' % (concurrency) + ' profile-build', shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'make COMP=gcc ARCH=x86-64-modern -j 2 profile-build' returned non-zero exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "worker.py", line 130, in worker
    pgn_file = run_games(worker_info, password, remote, run, task_id)
  File "/home/fishtest/fishtest/worker/games.py", line 478, in run_games
    setup_engine(new_engine, worker_dir, sha_new, repo_url, worker_info['concurrency'])
  File "/home/fishtest/fishtest/worker/games.py", line 142, in setup_engine
    raise Exception('Failed to setup engine for %s' % (sha))
Exception: Failed to setup engine for d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39
Task exited
```

**Comment by vdbergh** [comment]
Compiling d6ab17ece8c6db3a3c4d63bc93b2643b3dc96e39 directly I get
```
gcc --version

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
make COMP=gcc ARCH=x86-64-modern -j 2 profile-build

lto1: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
lto-wrapper: fatal error: g++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
Makefile:500: recipe for target 'stockfish' failed
make[2]: *** [stockfish] Error 1
make[2]: Leaving directory '/home/vdbergh/Stockfish/src'
Makefile:522: recipe for target 'gcc-profile-use' failed
make[1]: *** [gcc-profile-use] Error 2
make[1]: Leaving directory '/home/vdbergh/Stockfish/src'
Makefile:420: recipe for target 'profile-build' failed
make: *** [profile-build] Error 2
```

**Comment by ppigazzini** [comment]
@vdbergh my workers are able to run that SPSA test without this PR.

**Comment by vdbergh** [comment]
Hmm... it seems I cannot compile this patch. Normally I can compile SF fine. Apparently not the tuning branch.

However I do understand what is wrong. In SPSA tests games are not paired. Since the worker now only counts paired games, it doesn't move.

**Comment by ppigazzini** [comment]
The tuning branch triggered a gcc 5 bug on Ubuntu (when using profile-build) , view
https://groups.google.com/forum/#!topic/fishcooking/7dSHuDbZMMw

I wrote a little this wiki section on how to install several gcc on Ubuntu:
https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Linux#install-several-gcc-versions-on-ubuntu

**Comment by vdbergh** [comment]
I now disabled the syncing for SPSA tests.

**Comment by ppigazzini** [comment]
Started new tests on DEV to use only workers updated with this PR.
SPSA test runs fine now after https://github.com/glinscott/fishtest/pull/523/commits/0353bfcfaa2be6dc6b5ba88a8a80948e91d9610a  :)

**Pull request merged**
