### PR TITLE
Do not use absolute pathname for net.

### PR DESCRIPTION
**Pull request by vdbergh**
SF cannot handle paths with non-ascii characters on windows.

### CODE REVIEW

**Comment by vondele** [comment]
actually, this might not work cutechess-cli requires the absolute path, since the working directory of the binary is $TEMP or similar. (IIRC).

**Comment by vdbergh** [comment]
It does work on Linux though... Of course I do not really know if SF picked up the net from the working instead of from the executable's directory.

**Comment by vdbergh** [comment]
But I did check that when cutechess-cli is started, the current directory is the testing directory, if that is what you mean.

**Comment by vondele** [comment]
when cutechess-cli is started the current directory is the testing directory, but cutechess itself executes the stockfish process in a different directory ($TEMP).

**Comment by vdbergh** [comment]
Ok. I will have to take your work for it. A more robust solution then is to embed the net.

**Comment by vdbergh** [comment]
Embedding the net works fine but this blows up the size of the executable of course.

**Comment by vdbergh** [comment]
It seems one can specify the working directory of the engine on the command line.

**Comment by ppigazzini** [comment]
Actually all the workers are running fine with this PR and cutechess-cli runs in "testing" folder, see:

https://github.com/glinscott/fishtest/blob/dc7b9bf13875eb08479f5dcb3fffdb4843128f96/worker/games.py#L1166-L1168

https://github.com/glinscott/fishtest/blob/dc7b9bf13875eb08479f5dcb3fffdb4843128f96/worker/updater.py#L61-L64

**Comment by vdbergh** [comment]
@ppigazzini  What @vondele says is that cutechess-cli changes the working directory to a temporary directory before starting the engine. I checked in the cutechess-cli source that it is correct.

However this can be overridden by specifying the working directory on the command line. This is what I did in the latest push.

**Comment by vdbergh** [comment]
@ppigazzini Perhaps you can try to run this in a directory with a non-ascii name? Here is how to enter unicode characters in windows 

> To insert a Unicode character, type the character code, press ALT, and then press X. For example, to type a dollar symbol ($), type 0024, press ALT, and then press X. For more Unicode character codes, see Unicode character code charts by script.

I assume you can also enter special characters with the usual tool.

**Comment by ppigazzini** [comment]
Restarted all the workers, queued fresh tests.

**Comment by vdbergh** [comment]
I did check that it works on Linux with a non-ascii directory. But I guess SF supports UTF-8 out of the box.

**Comment by ppigazzini** [comment]
I'm trying to enter a UTF-8 char on Windows, these instructions don't work.
I enter ASCII code with the numeric pad, eg ALT+96 for `

**Comment by ppigazzini** [comment]
Ok, I used the character map, now the msys2 worker is running this PR in `/home/usr00/_git/__test_folder00/fishtestжӖӚӋѼѾ/worker`

**Comment by vdbergh** [comment]
> Ok, I used the character map, now the msys2 worker is running this PR in `/home/usr00/_git/__test_folder00/fishtestжӖӚӋѼѾ/worker`

Great!!! Can you also check that master does **not** work?

**Comment by ppigazzini** [comment]
Master doesn't work in `/home/usr00/_git/__test_folder00/fishtestݴڞۚٸۚ۳۩ݾڣڝکڰۋ۝۬ۙې/worker` :

```
Finished game 98 (Base-ad926d34c0 vs New-ad926d34c0): 0-1 {White disconnects}
Score of New-ad926d34c0 vs Base-ad926d34c0: 49 - 49 - 0  [0.500] 98
Started game 99 of 176 (New-ad926d34c0 vs Base-ad926d34c0)
Started game 100 of 176 (Base-ad926d34c0 vs New-ad926d34c0)
Terminating process of engine New-ad926d34c0(98)
Finished game 99 (New-ad926d34c0 vs Base-ad926d34c0): 0-1 {White disconnects}
Score of New-ad926d34c0 vs Base-ad926d34c0: 49 - 50 - 0  [0.495] 99
Terminating process of engine Base-ad926d34c0(99)
Finished game 100 (Base-ad926d34c0 vs New-ad926d34c0): 0-1 {White disconnects}
Score of New-ad926d34c0 vs Base-ad926d34c0: 50 - 50 - 0  [0.500] 100
```

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
Triggered the worker update, thank you @vdbergh @vondele :)

**Pull request merged**
