### PR TITLE
Retire worker reconnect logic

### PR DESCRIPTION
**Pull request by tomtor**
This is open for discussion. If anyone is a fan of the current code I'd like
to hear why it is useful.

When a worker disconnects from fishtest because of errors
and reconnects without being restarted (it gets a new ID
on restart) it is handed it's old job, unless it was
already assigned to another worker.

This situation is rare and the logic requires scanning all
tasks handed out.

https://github.com/glinscott/fishtest/pull/186 increased
the speed by remembering active task for each worker,
but this information is lost on a fishtest reboot.

Benefit from the current code is minimal so retire it.

### CODE REVIEW

**Comment by Stefano80** [comment]
I am not sure of why it is that way. Actually, I also do not understand why batches are assigned to other workers and would retire this as well.

**Comment by tomtor** [comment]
@Stefano80 Partial competed task slots disturb the number of games and priority calculations. So that's the reason batches are reassigned to other workers. For some reason this does not work for spsa like http://tests.stockfishchess.org/tests/view/5ab621870ebc590295d884ef

So we have to manually increase the number of to be played games in that situation. By the way, it would be nice if I got moderator rights on fishtest so I would be able to adjust things if needed and approve tests

**Comment by ppigazzini** [comment]
@tomtor I think that the decision about the approver's rights is on @snicolet, the maintainer of Stockfish.
I will be very glad to update your profile, of course :)

**Comment by snicolet** [comment]
@ppigazzini 

It is of course OK, in my opinion, if all of the fishtest maintenance team members, and more generally all the people who have improved the fishtest server significantly in the last few weeks, get approver's rights for tests in fishtest. 

So you can add at least these ones:
@tomtor 
@Stefano80 
@ppigazzini 
@xoto10 
@ianfab

And while we are at it, I would like to propose to...
@Rocky640
@syzygy1 
@noobpwnftw
@jerrydonaldwatson
... if they would accept to become approvers on fishtest too.

The task is mainly to verify that the proposed tests do not have a security hole for the workers machine, and politely ask the authors to adjust the workload of the server in the 1% of the cases which are not handled automatically.

**Comment by ppigazzini** [comment]
@snicolet OK, I started adding the fishtest approver rights to @tomtor
For other people I wait their acceptance: anyway I need to know their fishtest username.

**Comment by jerrydonaldwatson** [comment]
@snicolet @ppigazzini 
I would be honoured to be an approver. My fishtest username is: jdonald

**Comment by ppigazzini** [comment]
@snicolet added fishtest approver rights to @jerrydonaldwatson

**Comment by jerrydonaldwatson** [comment]
Thank you!

**Comment by syzygy1** [comment]
@snicolet 
I accept to become an approver.

**Comment by ppigazzini** [comment]
@snicolet added fishtest approver rights to @syzygy1 (fishtest username: syzygy)

**Comment by xoto10** [comment]
No thanks, guys, although it's nice of you to offer. (Apologies for being
quiet recently, I have had a high temperature and headaches for the last 6
days. And I still have it.)

It was good to help get fishtest working quicker, although it did start to
feel a bit like work at times.

My current plans are to keep working on stockfish now and then, but this
may change later in the year/or sometime, so I'd rather not add extra roles.

Cheers!

**Comment by ppigazzini** [comment]
@tomtor @Stefano80 is this ready to be merged?

**Comment by tomtor** [comment]
@ppigazzini  Yes, for me it is ready...

**Comment by ppigazzini** [comment]
Official server updated.
Thank you @tomtor

**Comment by Vizvezdenec** [comment]
I think that fishtest needs more approvers from USA/Canada since usually there is a trouble with no patches approval at the time of like 5 am CEST. (like it is now, for example https://i.imgur.com/KahEb9z.png )
Maybe add @AndyGrant ?

**Pull request merged**
