### PR TITLE
Include "worker_info" in all POST api's used by the worker.

### PR DESCRIPTION
**Pull request by vdbergh**
This will make validation on the server more straightforward.

Also: list the api's used by the worker.

### CODE REVIEW

**Comment by ppigazzini** [comment]
Dev workers updated.

**Comment by ppigazzini** [comment]
If I'm not wrong there are some workers stuck with an old version not able to update.

I added some debug print to the server (masked username and password):
```
Nov 28 10:56:48 tests.stockfishchess.org pserve[11979]: request['worker_info'] is missing
Nov 28 10:56:48 tests.stockfishchess.org pserve[11979]: {'username': 'USER001', 'password': 'PWD001', 'unique_key': '34717cfb-41f7-4e8f-b940-a4c335581c32', 'run_id': '61950b02cd645dc8291c87e6', 'task_id': 519}
Nov 28 10:56:53 tests.stockfishchess.org pserve[11979]: request['worker_info'] is missing
Nov 28 10:56:53 tests.stockfishchess.org pserve[11979]: {'username': 'USER000', 'password': 'PWD000', 'unique_key': '192a9d30-9727-47ca-83eb-2fc4e661a987', 'run_id': '619ae0e36a83de5e8cf537cb', 'task_id': 107}
Nov 28 10:57:48 tests.stockfishchess.org pserve[11979]: request['worker_info'] is missing
Nov 28 10:57:48 tests.stockfishchess.org pserve[11979]: {'username': 'USER002', 'password': 'PWD002', 'unique_key': 'a2666454-0e47-4f85-b715-be334ab6f825', 'run_id': '612a666262d20cf82b5ad2d6', 'task_id': 158}
```

The 3 runs are already finished:
https://tests.stockfishchess.org/tests/view/61950b02cd645dc8291c87e6
https://tests.stockfishchess.org/tests/view/619ae0e36a83de5e8cf537cb
https://tests.stockfishchess.org/tests/view/612a666262d20cf82b5ad2d6

The workers are connecting every minute:
```
Nov 28 11:35:00 'run_id': '612a666262d20cf82b5ad2d6', 'task_id': 158}
Nov 28 11:36:00 'run_id': '612a666262d20cf82b5ad2d6', 'task_id': 158}
Nov 28 11:37:01 'run_id': '612a666262d20cf82b5ad2d6', 'task_id': 158}
Nov 28 11:38:01 'run_id': '612a666262d20cf82b5ad2d6', 'task_id': 158}
Nov 28 11:39:01 'run_id': '612a666262d20cf82b5ad2d6', 'task_id': 158}


Nov 28 11:35:58 'run_id': '619ae0e36a83de5e8cf537cb', 'task_id': 107}
Nov 28 11:36:58 'run_id': '619ae0e36a83de5e8cf537cb', 'task_id': 107}
Nov 28 11:37:58 'run_id': '619ae0e36a83de5e8cf537cb', 'task_id': 107}
Nov 28 11:38:58 'run_id': '619ae0e36a83de5e8cf537cb', 'task_id': 107}
Nov 28 11:39:59 'run_id': '619ae0e36a83de5e8cf537cb', 'task_id': 107}


Nov 28 11:38:45 'run_id': '61950b02cd645dc8291c87e6', 'task_id': 519}
Nov 28 11:39:46 'run_id': '61950b02cd645dc8291c87e6', 'task_id': 519}
Nov 28 11:40:48 'run_id': '61950b02cd645dc8291c87e6', 'task_id': 519}
Nov 28 11:41:49 'run_id': '61950b02cd645dc8291c87e6', 'task_id': 519}
Nov 28 11:42:51 'run_id': '61950b02cd645dc8291c87e6', 'task_id': 519}
```

**Comment by vdbergh** [comment]
Right now I do not see what could prevent these workers from upgrading. Ild workers are no longer compatible with the new master (i.e. they can not do anything useful). However the "/api/request_version" call should still work and that is enough to trigger the upgrade.

**Comment by ppigazzini** [comment]
It seems that they are stuck trying to update the task.

**Comment by vdbergh** [comment]
> It seems that they are stuck trying to update the task.

In that case they should try five times and quit...

**Comment by ppigazzini** [comment]
They are connecting since yesterday night.

**Comment by ppigazzini** [comment]
BTW the 'Too many failed update attempts' flooding in the Actions log it's a my bad attempt to unlock those 3 workers :(

**Comment by vdbergh** [comment]
What is very strange is that the delay of 1 minute does not correspond to HTTP_TIMEOUT (which is 15 seconds).

**Comment by vdbergh** [comment]
Ok `60=4x15` which corresponds to trying 5 times.

**Comment by vdbergh** [comment]
Actually if I read the code correctly then there is delay of 15s after every failed update attempt. So the total delay should be `5x15=75`.

**Comment by ppigazzini** [comment]
I agree with 75 seconds. Please remember that it's a my hypothesis that they are stuck calling `update_task`

**Comment by vdbergh** [comment]
I don't understand this at all.

Did you try to make worker_info temporarily an optional key in api.py? That get rid of the missing `request['worker_info']` error.
```
    schema = {
        "password": str,
        optional_key("run_id"): str,
        optional_key("task_id"): int,
        optional_key("pgn"): str,
        optional_key("message"): str,
        optional_key("ARCH"): str,
        optional_key("nps"): float,
        optional_key("worker_info"): {     <-------------------------
            "uname": str,
            "architecture": [str, str],
            "concurrency": int,
            "max_memory": int,
            "min_threads": int,
            "username": str,
            "version": str,
            "gcc_version": str,
            "unique_key": str,
            optional_key("rate"): {"limit": int, "remaining": int},
        },
        optional_key("spsa"): {
            "wins": int,
            "losses": int,
            "draws": int,
            "num_games": int,
        },
       optional_key("stats"): {
            "wins": int,
            "losses": int,
            "draws": int,
            "crashes": int,
            "time_losses": int,
            "pentanomial": [int, int, int, int, int],
        },
}
```

**Comment by vdbergh** [comment]
Actually that would probably not work since the server now relies on `worker_info` being present. That was the point of making it obligatory, to simplify the code on the server side.

**Comment by ppigazzini** [comment]
Yes, but I was scared by the number of Pyramid exceptions, so I reverted it immediately.

**Comment by vdbergh** [comment]
I do not see how the worker can be stuck at `/api/update_task`.

Since I have no idea how this can possibly happen, the only solution I see it to ask the users to restart the worker (and maybe give a sample of the worker output).

**Comment by ppigazzini** [comment]
Ok

**Comment by ppigazzini** [comment]
60 seconds should be the `beat`

**Comment by vdbergh** [comment]
> 60 seconds should be the `beat`

:+1:

**Comment by vdbergh** [comment]
That's why it's bad to not include the caller in error messages.... I have now a version that includes the actual api call in every error message.

Still this does not explain everything. Every four hours (at most) the workers should try to get a new task which should trigger an upgrade.

**Comment by ppigazzini** [comment]
I'm wondering if this `validate_request()` can prevent the update:
https://github.com/glinscott/fishtest/blob/fe03894e8961872e197c99f699f6415d1fd52069/server/fishtest/api.py#L419-L422

**Comment by vdbergh** [comment]
It should not. Unless there are some very old workers that do not send `worker_info` as part of the payload. 

I do not know if that was ever the case.

**Comment by ppigazzini** [comment]
Bingo! The tests are very old, they finished:
- 2021.09.01   https://tests.stockfishchess.org/tests/view/612a666262d20cf82b5ad2d6
- 2021.11.18   https://tests.stockfishchess.org/tests/view/61950b02cd645dc8291c87e6
- 2021.11.22   https://tests.stockfishchess.org/tests/view/619ae0e36a83de5e8cf537cb

**Comment by vdbergh** [comment]
I just checked worker version 98. It does not update.

**Comment by vdbergh** [comment]
I understand it. The worker should not only include `worker_info` but the `worker_info` should have all the mandatory fields. So workers from before `gcc_version` was introduced will not be able to connect.

**Comment by vdbergh** [comment]
But this missing field should have been logged on the server....

**Comment by ppigazzini** [comment]
`optional("gcc_version"): str,` can do the trick?

**Comment by vdbergh** [comment]
It would. But I would only do it very temporarily. Just to get these workers to upgrade.

**Comment by ppigazzini** [comment]
> But this missing field should have been logged on the server....

Without additional debug printing the log is this
```
Nov 28 13:18:39 tests.stockfishchess.org pserve[20643]: request['worker_info'] is missing
Nov 28 13:19:07 tests.stockfishchess.org pserve[20643]: request['worker_info'] is missing
Nov 28 13:19:12 tests.stockfishchess.org pserve[20643]: request['worker_info'] is missing
Nov 28 13:19:39 tests.stockfishchess.org pserve[20643]: request['worker_info'] is missing
Nov 28 13:20:08 tests.stockfishchess.org pserve[20643]: request['worker_info'] is missing
Nov 28 13:20:13 tests.stockfishchess.org pserve[20643]: request['worker_info'] is missing
Nov 28 13:20:40 tests.stockfishchess.org pserve[20643]: request['worker_info'] is missing
```

**Comment by vdbergh** [comment]
That's weird again then. I will try to connect to dev with my worker 98. Then we can see if there are any messages.

**Comment by vdbergh** [comment]
This is what worker98 get's back when trying to connect
```
{'error': "request['worker_info']['gcc_version'] is missing"}
```

**Comment by ppigazzini** [comment]
PROD is running with `gcc_version` optional:
```
            "version": str,
            optional_key("gcc_version"): str,
            "unique_key": str,
            optional_key("rate"): {"limit": int, "remaining": int},
        },
```

**Comment by vdbergh** [comment]
Ok. Let's see if that unstucks the workers.

**Comment by ppigazzini** [comment]
At the moment no, but the workers could have a big `time.sleep()` in place.
```
Nov 28 13:36:31 tests.stockfishchess.org pserve[22346]: request['worker_info'] is missing
Nov 28 13:36:31 tests.stockfishchess.org pserve[22346]: {'username': 'USER00', 'password': 'PWD00', 'unique_key': '34717cfb-41f7-4e8f-b940-a4c335581c32', 'run_id': '61950b02cd645dc8291c87e6', 'task_id': 519}
Nov 28 13:36:45 tests.stockfishchess.org pserve[22346]: request['worker_info'] is missing
Nov 28 13:36:45 tests.stockfishchess.org pserve[22346]: {'username': 'USER01', 'password': 'PWD01', 'unique_key': 'a2666454-0e47-4f85-b715-be334ab6f825', 'run_id': '612a666262d20cf82b5ad2d6', 'task_id': 158}
Nov 28 13:37:15 tests.stockfishchess.org pserve[22346]: request['worker_info'] is missing
Nov 28 13:37:15 tests.stockfishchess.org pserve[22346]: {'username': 'USER02', 'password': 'PWD02', 'unique_key': '192a9d30-9727-47ca-83eb-2fc4e661a987', 'run_id': '619ae0e36a83de5e8cf537cb', 'task_id': 107}
```

**Comment by vdbergh** [comment]
Actually I having second thoughts about this. If `/api/request_version` fails then the worker quits. So it would not generate the kind of loop we are seeing.

**Comment by ppigazzini** [comment]
Then is only the heartbeat process running until the next reboot...

**Comment by vdbergh** [comment]
What could be happening is that these workers are not able to contact the server (i.e. are getting an error by the request package), but that the `/api/beat` somehow succeeds. If that's the case then nothing can be done, except blocking the ip addresses.

**Comment by vdbergh** [comment]
I recall that we once had 2 ghost workers by noob that perhaps exhibited similar behaviour (it's hard to be sure since at that time there was task migration).

**Comment by vdbergh** [comment]
BTW the latest worker will no longer send a heartbeat when it is sleeping.

**Comment by ppigazzini** [comment]
I helped Techonologov on Discord to reboot his worker (stuck since September with the ). All the 3 workers have the last update yesterday. The remaining 2 stuck workers seem to provide the gcc version, though.

158 | technologov-48cores-a2666454 | os: Linux 4.15.0-143-generic; ram: 32033MiB; gcc: ?; arch: ? | 2021-11-27 23:10:41 | 000 / 200 | [0, 0, 0, 0, 0] | - | - | -
-- | -- | -- | -- | -- | -- | -- | -- | --

107 | dew-3cores-192a9d30 | os: Windows 7; ram: 4078MiB; gcc: 11.2.0; arch: ? | 2021-11-27 23:10:14 | 000 / 088 | [0, 0, 0, 0, 0] | - | - | -
-- | -- | -- | -- | -- | -- | -- | -- | --

519 | user213718-1cores-34717cfb | os: Windows 2008ServerR2; ram: 1024MiB; gcc: 10.3.0; arch: 64bit SSE41 SSSE3 SSE2 POPCNT | 2021-11-27 23:10:12 | 016 / 032 | [0, 1, 6, 1, 0] | 0 | 0 | 0.326
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by vdbergh** [comment]
I guess it was yesterday that PROD was updated with the latest PR. So till yesterday the heartbeat thread could update the task. Now the old workers cannot update the task anymore since they are not sending `worker_info` with `/api/beat`. That's why `last_update` is stuck yesterday.

I had already decided that it cannot be due to a missing `gcc_version` as I explained above.  
What is happening I think is that `/api/update_version` fails because of a network problem (so it does not reach the server at all). In that case the worker will try again after a delay, which gets progressively longer.

Now how it would be possible that `/api/update_version` can experience a network problem and not `/api/beat` I don't know.

**Comment by vdbergh** [comment]
In any case if the scenario I sketched about is possible, then it will no longer be a problem since the new worker will not send a heartbeat if the worker is not working on a task and the hypothesis was that a network problem prevents the worker getting a new task.

**Comment by vdbergh** [comment]
It occurred to me that this code in `worker.py` could also be the culprit
```
    print("Waiting for the heartbeat thread to finish...")
    heartbeat_thread.join()
```
If `current_state["alive"]` for some reason happens to be `True` here (because the main thread crashes in some weird way which is not foreseen by the code) then this will block forever.

I have now made `heartbeat_thread` a daemon thread (yeah...) and replaced it by
```
    print("Waiting for the heartbeat thread to finish...")
    heartbeat_thread.join(HTTP_TIMEOUT)
```

**Comment by ppigazzini** [comment]
@d3vv One of your workers is stuck to the task Idx 107 of this test:
https://tests.stockfishchess.org/tests/view/619ae0e36a83de5e8cf537cb

There is the possibility that it's a zombie "heartbeat" process, so please reboot the PC and in any case restart the worker (it should updated itself to the latest version). Thank you :)

Information to identify the worker: 
name: dew-3cores-192a9d30
UUID: 192a9d30-9727-47ca-83eb-2fc4e661a987
os: Windows 7
ram: 4078MiB
gcc: 11.2.0
arch: ?

**Comment by ppigazzini** [comment]
I sent an e-mail to the users, the "user213718"'s e-mail address suggests that the mailbox could be not checked very often, though.

**Comment by d3vv** [comment]
@ppigazzini Thank You for suggestion. I will do it as soon as possible

**Pull request closed without merging**
