### PR TITLE
Give useful information in the event log of a finished run.

### PR DESCRIPTION
**Pull request by vdbergh**
Example
```
Result:green Elo:147.17[87.73,206.61] LOS:100%
```

### CODE REVIEW

**Comment by vdbergh** [comment]
The vision is that the browser will be able to query the even log (via an api) and provide appropriate notifications.

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
I wonder about having "finished_run" as well.

image

**Comment by vdbergh** [comment]
Done!

**Comment by ppigazzini** [comment]
Updating DEV (check the new maintenance page)

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
