### PR TITLE
Iterate through runs using range queries in delta_update_users.py

### PR DESCRIPTION
**Pull request by linrock**
`delta_update_users.py` runs every 15 minutes. Using `skip` for mongodb collections is inefficient and CPU-intensive for iterating through large collections. It's much more efficient to use range queries on an indexed field.

See https://docs.mongodb.com/manual/reference/method/cursor.skip/#using-range-queries

A quick benchmark on a $5 VPS:

Before:
```
Num runs processed: 74887
Successfully updated 1200 users

real	1m46.332s
user	0m22.695s
sys	0m0.744s
```

After:
```
Num runs processed: 74887
Successfully updated 1200 users

real	0m19.514s
user	0m15.732s
sys	0m0.397s
```

### CODE REVIEW

**Comment by tomtor** [comment]
On prod the script currently takes about 17 seconds:

https://tests.stockfishchess.org/actions?action=update_stats&user=

@linrock Note that about a year ago this was many minutes (no delta updates), but additional speedup is always welcomed!

**Comment by ppigazzini** [comment]
mmm, my benches on DEV (I made 3 tries and taken the median, after `sudo systemctl stop cron`) don't show any speedup, and pypy3 is a little slowdown :(

#### python3
- master
```
Successfully updated 1360 users

real    0m13.002s
user    0m10.183s
sys     0m1.353s
```

- pr
```
Successfully updated 1360 users

real    0m13.150s
user    0m10.307s
sys     0m1.453s
```

#### pypy3
- master
```
Successfully updated 1360 users

real    0m17.716s
user    0m15.393s
sys     0m1.085s
```

- pr
```
Successfully updated 1360 users

real    0m16.308s
user    0m14.063s
sys     0m1.015s
```

**Comment by tomtor** [comment]
> and pypy3 is a little slowdown :(

That is expected. It is Mongodb intensive code, no gain can be expected from the pypy compiler.

**Comment by ppigazzini** [comment]
> > and pypy3 is a little slowdown :(
> 
> That is expected. It is Mongodb intensive code, no gain can be expected from the pypy compiler.

Sure, but I hadn't expecting a 23% slowdown too.

**Comment by ppigazzini** [comment]
@tomtor @linrock to return in topic, I'm fine merging this PR like a mongodb best practice, but I would like a change of the commit, something like this should work.

**Use mongodb best practices for delta_update_users.py**

delta_update_users.py runs every 15 minutes. Using skip for mongodb collections is inefficient and CPU-intensive for iterating through large collections. It's much more efficient to use range queries on an indexed field.

See https://docs.mongodb.com/manual/reference/method/cursor.skip/#using-range-queries

In some conditions this can result in a speedup, see this quick benchmark on a $5 VPS:

Before:
```
Num runs processed: 74887
Successfully updated 1200 users

real	1m46.332s
user	0m22.695s
sys	0m0.744s
```
After:
```
Num runs processed: 74887
Successfully updated 1200 users

real	0m19.514s
user	0m15.732s
sys	0m0.397s
```

**Comment by linrock** [comment]
hmm, in prod, the # of documents being iterated through is probably not large enough to see a performance improvement.

i've updated the commit and PR title to reflect a code change instead of a performance improvement since it looks to have no speedup in prod.

**Comment by linrock** [comment]
i updated the `update_users.py` script too. it's not being used currently, but in case someone does use it, it should now have a large speedup in dev and prod since it iterates through the entire runs collection.

**Comment by ppigazzini** [comment]
@tomtor do we could drop `update_users.py`?

**Comment by ppigazzini** [comment]
@linrock big speedup (tried 2 times) scanning all users ;)
* master:
```
time ${VENV}/bin/python fishtest/fishtest/utils/delta_update_users.py all
scan all
Successfully updated 1360 users

real    26m33.732s
user    2m21.219s
sys     0m4.885s
```
* pr:
```
time ${VENV}/bin/python fishtest/fishtest/utils/delta_update_users.py all
scan all
Successfully updated 1360 users

real    2m30.753s
user    2m19.093s
sys     0m4.499s
```

**Comment by linrock** [comment]
nice, that's a significant speedup if anyone has to go through the entire collection with the script

**Comment by tomtor** [comment]
> @tomtor do we could drop `update_users.py`?

Yes, the delta script when called with `all` flag should do the same.

**Comment by ppigazzini** [comment]
PROD updated, thank you @linrock :)

**Pull request merged**
