### PR TITLE
Prevent sqrt of negative or divide by zero.

### PR DESCRIPTION
**Pull request by xoto10**
Prevent sqrt of negative number or divide by zero.

### CODE REVIEW

**Comment by ppigazzini** [comment]
PROD updated, thank you @xoto10 :)

**Comment by tomtor** [comment]
@ppigazzini @xoto10 Oops, this crashes: 

Nov 27 18:42:04 tests pserve[8657]:   File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 876, in tests_view                            Nov 27 18:42:04 tests pserve[8657]:     return { 'run': run, 'run_args': run_args, 'chi2': calculate_residuals(run),                                Nov 27 18:42:04 tests pserve[8657]:   File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 765, in calculate_residuals                   Nov 27 18:42:04 tests pserve[8657]:     chi2 = get_chi2(run['tasks'], bad_users)                                                                    Nov 27 18:42:04 tests pserve[8657]:   File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 749, in get_chi2                              Nov 27 18:42:04 tests pserve[8657]:     if expected * adj <= 0:                                                                                     Nov 27 18:42:04 tests pserve[8657]: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by tomtor** [comment]
I did an emergency edit and restart....

@ppigazzini @xoto10

**Comment by tomtor** [comment]
@xoto10 Just test for `expected <= 0` ?

**Comment by ppigazzini** [comment]
Thanks @tomtor, I updated the DEV but w/o workers, the change looked innocent. I need to learn a bit of numpy to understand the error.

**Comment by tomtor** [comment]
@ppigazzini Workers are not needed, you cannot view any test...

Best to revert for now?

**Comment by xoto10** [comment]
Apologies if there's an error there. afk just now

**Comment by ppigazzini** [comment]
`expected` and `adj` are matrix, fixed in #449

**Comment by xoto10** [comment]
Yes I realised that after the problem occurred. I was intending to look at
it this evening but I see you have already. Thanks for all your work! :-)

**Pull request merged**
