### PR TITLE
Try to find a new run for a worker in request_task().

### PR DESCRIPTION
**Pull request by vdbergh**
Currently there is the issue that high core workers always get the same run while their residual keeps steadily rising.

This is not good. We want a good hardware mix for every test.

This PR moves the last run seen by the worker to the end of the queue.

Not live tested.

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated, started a 31 cores worker.

**Comment by ppigazzini** [comment]
Started 10 tests (1 NumGames with 200% throughput, the others with equal itp), a 31 worker and several 2 workers. I'm expecting than the 31 worker switches between tests,

**Comment by ppigazzini** [comment]
The 31 cores worker switches tests. I stopped it and started 2 workers at 15 cores to have more balanced core counts.

**Comment by vdbergh** [comment]
I think there is another bug. I think it was there before also but invisible because of the task migration.

I think that with the current code request_task() can return a task for a finished SPRT test (because of the caching of task_runs). Of course the worker will not be able to do any updates on this task so it will become a zero games task.

**Comment by vdbergh** [comment]
I added the fix to the PR.

**Comment by ppigazzini** [comment]
I'm commuting now, I will able to update in 2 hours. Feel free to suggest ways to test the PR.

**Comment by ppigazzini** [comment]
DEV updated

**Comment by vdbergh** [comment]
Went to see the new Dune movie :)

The PR seems to be behaving as advertised. The two 15 core workers where migrating between the different runs, with the higher priority runs (SPRT) generally seeing more of them. This is what one would want I think.

**Comment by ppigazzini** [comment]
Yes, and it works fine also with only 1 test at high priority (other tests stay paused).

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

Hoping you liked the movie :)

**Comment by ppigazzini** [comment]
linrock-100cores is stuck to this test, no it should switch
https://tests.stockfishchess.org/tests/view/6142172c7315e7c73204a614

**Comment by vdbergh** [comment]
> linrock-100cores is stuck to this test, no it should switch
> https://tests.stockfishchess.org/tests/view/6142172c7315e7c73204a614

I think so…

**Comment by vdbergh** [comment]
It did not, but that’s because of the server restart. The dictionary keeping track of the worker runs is now empty again. Next time it should really switch.

**Comment by ppigazzini** [comment]
Switched !
https://tests.stockfishchess.org/tests/view/614279aa7315e7c73204a6af

**Comment by ppigazzini** [comment]
technologov-56cores-30-43fe85ce switched too :)

**Comment by vdbergh** [comment]
:)

**Pull request merged**
