### PR TITLE
Find clang props

### PR DESCRIPTION
**Pull request by ppigazzini**

### CODE REVIEW

**Comment by ppigazzini** [comment]
@RaimundHeid please at your convenient time test this PR with apple x86_64 (g++/clang++) and apple silicon (g++/clang++) joining your workers to https://dfts-0.pigazzini.it/tests

In case of issues report the output of `clang++ -E - -march=native -###`

**Comment by RaimundHeid** [comment]
The worker runs with fine clang, however the output of clang++ -E - -march=native -### is as follows:

raimundheid@Mac-mini ~ % clang++ -E - -march=native -### < /dev/null
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
clang: error: the clang compiler does not support '-march=native'
 "/Library/Developer/CommandLineTools/usr/bin/clang" "-cc1" "-triple" "arm64-apple-macosx12.0.0" "-Wundef-prefix=TARGET_OS_" "-Wdeprecated-objc-isa-usage" "-Werror=deprecated-objc-isa-usage" "-Werror=implicit-function-declaration" "-E" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "-" "-mrelocation-model" "pic" "-pic-level" "2" "-mframe-pointer=non-leaf" "-fno-strict-return" "-fno-rounding-math" "-munwind-tables" "-target-sdk-version=12.1" "-fvisibility-inlines-hidden-static-local-var" "-target-cpu" "apple-m1" "-target-feature" "+neon" "-target-abi" "darwinpcs" "-fallow-half-arguments-and-returns" "-debugger-tuning=lldb" "-target-linker-version" "711" "-resource-dir" "/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" "-I/usr/local/include" "-internal-isystem" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include" "-internal-isystem" "/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include" "-internal-externc-isystem" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include" "-internal-externc-isystem" "/Library/Developer/CommandLineTools/usr/include" "-Wno-reorder-init-list" "-Wno-implicit-int-float-conversion" "-Wno-c99-designator" "-Wno-final-dtor-non-final-class" "-Wno-extra-semi-stmt" "-Wno-misleading-indentation" "-Wno-quoted-include-in-framework-header" "-Wno-implicit-fallthrough" "-Wno-enum-enum-conversion" "-Wno-enum-float-conversion" "-Wno-elaborated-enum-base" "-fdebug-compilation-dir" "/Users/raimundheid" "-ferror-limit" "19" "-stack-protector" "1" "-fstack-check" "-mdarwin-stkchk-strong-link" "-fblocks" "-fencode-extended-block-signature" "-fregister-global-dtors-with-atexit" "-fgnuc-version=4.2.1" "-fmax-type-align=16" "-fcommon" "-fcolor-diagnostics" "-clang-vendor-feature=+nullptrToBoolConversion" "-clang-vendor-feature=+messageToSelfInClassMethodIdReturnType" "-clang-vendor-feature=+disableInferNewAvailabilityFromInit" "-clang-vendor-feature=+disableNeonImmediateRangeCheck" "-clang-vendor-feature=+disableNonDependentMemberExprInCurrentInstantiation" "-fno-odr-hash-protocols" "-clang-vendor-feature=+revert09abecef7bbf" "-mllvm" "-disable-aligned-alloc-awareness=1" "-mllvm" "-enable-dse-memoryssa=0" "-o" "-" "-x" "c" "-"

**Comment by ppigazzini** [comment]
Thank you! I needed a double check for the `-target-cpu` and for the output on the stderr.

**Comment by RaimundHeid** [comment]
Testing x86-64 currently. Expect results in about 30 mins.

**Comment by RaimundHeid** [comment]
Compiler output:

clang++ -E - -march=native -### < /dev/null
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/clang" "-cc1" "-triple" "x86_64-apple-macosx11.3.0" "-Wdeprecated-objc-isa-usage" "-Werror=deprecated-objc-isa-usage" "-Werror=implicit-function-declaration" "-E" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "-" "-mrelocation-model" "pic" "-pic-level" "2" "-mframe-pointer=all" "-fno-strict-return" "-fno-rounding-math" "-munwind-tables" "-target-sdk-version=11.3" "-fvisibility-inlines-hidden-static-local-var" "-target-cpu" "skylake" "-target-feature" "+sse2" "-target-feature" "-tsxldtrk" "-target-feature" "+cx16" "-target-feature" "+sahf" "-target-feature" "-tbm" "-target-feature" "-avx512ifma" "-target-feature" "-sha" "-target-feature" "-gfni" "-target-feature" "-fma4" "-target-feature" "-vpclmulqdq" "-target-feature" "+prfchw" "-target-feature" "+bmi2" "-target-feature" "-cldemote" "-target-feature" "+fsgsbase" "-target-feature" "-ptwrite" "-target-feature" "-amx-tile" "-target-feature" "-avx512bf16" "-target-feature" "+popcnt" "-target-feature" "+aes" "-target-feature" "-avx512bitalg" "-target-feature" "-movdiri" "-target-feature" "+xsaves" "-target-feature" "-avx512er" "-target-feature" "+xsavec" "-target-feature" "-avx512vnni" "-target-feature" "-amx-bf16" "-target-feature" "-avx512vpopcntdq" "-target-feature" "-pconfig" "-target-feature" "-clwb" "-target-feature" "-avx512f" "-target-feature" "-clzero" "-target-feature" "-pku" "-target-feature" "+mmx" "-target-feature" "-lwp" "-target-feature" "-rdpid" "-target-feature" "-xop" "-target-feature" "+rdseed" "-target-feature" "-waitpkg" "-target-feature" "-movdir64b" "-target-feature" "-sse4a" "-target-feature" "-avx512bw" "-target-feature" "+clflushopt" "-target-feature" "+xsave" "-target-feature" "-avx512vbmi2" "-target-feature" "+64bit" "-target-feature" "-avx512vl" "-target-feature" "-serialize" "-target-feature" "+invpcid" "-target-feature" "-avx512cd" "-target-feature" "+avx" "-target-feature" "-vaes" "-target-feature" "+cx8" "-target-feature" "+fma" "-target-feature" "-rtm" "-target-feature" "+bmi" "-target-feature" "-enqcmd" "-target-feature" "+rdrnd" "-target-feature" "-mwaitx" "-target-feature" "+sse4.1" "-target-feature" "+sse4.2" "-target-feature" "+avx2" "-target-feature" "+fxsr" "-target-feature" "-wbnoinvd" "-target-feature" "+sse" "-target-feature" "+lzcnt" "-target-feature" "+pclmul" "-target-feature" "-prefetchwt1" "-target-feature" "+f16c" "-target-feature" "+ssse3" "-target-feature" "+sgx" "-target-feature" "-shstk" "-target-feature" "+cmov" "-target-feature" "-avx512vbmi" "-target-feature" "-amx-int8" "-target-feature" "+movbe" "-target-feature" "-avx512vp2intersect" "-target-feature" "+xsaveopt" "-target-feature" "-avx512dq" "-target-feature" "+adx" "-target-feature" "-avx512pf" "-target-feature" "+sse3" "-debugger-tuning=lldb" "-target-linker-version" "650.9" "-resource-dir" "/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" "-I/usr/local/include" "-internal-isystem" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include" "-internal-isystem" "/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include" "-internal-externc-isystem" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include" "-internal-externc-isystem" "/Library/Developer/CommandLineTools/usr/include" "-Wno-reorder-init-list" "-Wno-implicit-int-float-conversion" "-Wno-c99-designator" "-Wno-final-dtor-non-final-class" "-Wno-extra-semi-stmt" "-Wno-misleading-indentation" "-Wno-quoted-include-in-framework-header" "-Wno-implicit-fallthrough" "-Wno-enum-enum-conversion" "-Wno-enum-float-conversion" "-Wno-elaborated-enum-base" "-fdebug-compilation-dir" "/Users/raimundheid" "-ferror-limit" "19" "-stack-protector" "1" "-fstack-check" "-mdarwin-stkchk-strong-link" "-fblocks" "-fencode-extended-block-signature" "-fregister-global-dtors-with-atexit" "-fgnuc-version=4.2.1" "-fmax-type-align=16" "-fcommon" "-fcolor-diagnostics" "-clang-vendor-feature=+disableNonDependentMemberExprInCurrentInstantiation" "-fno-odr-hash-protocols" "-mllvm" "-disable-aligned-alloc-awareness=1" "-o" "-" "-x" "c" "-"

**Comment by RaimundHeid** [comment]
x86-64: g++ runs into a problem - will investigate: 

...
Config:
debug: 'no'
sanitize: 'none'
optimize: 'yes'
arch: 'x86_64'
bits: '64'
kernel: 'Darwin'
os: ''
prefetch: 'yes'
popcnt: 'yes'
pext: 'yes'
sse: 'yes'
mmx: 'no'
sse2: 'yes'
ssse3: 'yes'
sse41: 'yes'
avx2: 'yes'
avxvnni: 'no'
avx512: 'no'
vnni256: 'no'
vnni512: 'no'
neon: 'no'
arm_version: '0'

Flags:
CXX: g++
CXXFLAGS: -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -mmacosx-version-min=10.14 -arch x86_64 -DUSE_PTHREADS -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -DUSE_PEXT -mbmi2 -flto
LDFLAGS:  -m64 -mmacosx-version-min=10.14 -arch x86_64 -lpthread -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -mmacosx-version-min=10.14 -arch x86_64 -DUSE_PTHREADS -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -DUSE_PEXT -mbmi2 -flto -flto=jobserver

Testing config sanity. If this fails, try 'make help' ...


Step 1/4. Building instrumented executable ...
/Library/Developer/CommandLineTools/usr/bin/make ARCH=x86-64-bmi2 COMP=gcc gcc-profile-make
/Library/Developer/CommandLineTools/usr/bin/make ARCH=x86-64-bmi2 COMP=gcc \
	EXTRACXXFLAGS='-fprofile-generate=profdir' \
	EXTRACXXFLAGS+=-fvisibility=hidden \
	EXTRALDFLAGS='-lgcov' \
	all
g++ -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -mmacosx-version-min=10.14 -arch x86_64 -DUSE_PTHREADS -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -DUSE_PEXT -mbmi2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -mmacosx-version-min=10.14 -arch x86_64 -DUSE_PTHREADS -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -DUSE_PEXT -mbmi2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate=profdir -fvisibility=hidden -pedantic -Wextra -Wshadow -m64 -mmacosx-version-min=10.14 -arch x86_64 -DUSE_PTHREADS -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -DUSE_PEXT -mbmi2 -flto -I/usr/local/opt/openjdk@11/include  -c -o benchmark.o benchmark.cpp

Exception running games:
Executing make COMP=gcc ARCH=x86-64-bmi2 -j 1 profile-build failed. Error: ['In file included from /usr/local/Cellar/gcc/11.2.0_3/include/c++/11/bits/postypes.h:40,\n', '                 from /usr/local/Cellar/gcc/11.2.0_3/include/c++/11/iosfwd:40,\n', '                 from /usr/local/Cellar/gcc/11.2.0_3/include/c++/11/ios:38,\n', '                 from /usr/local/Cellar/gcc/11.2.0_3/include/c++/11/istream:38,\n', '                 from /usr/local/Cellar/gcc/11.2.0_3/include/c++/11/fstream:38,\n', '                 from benchmark.cpp:19:\n', '/usr/local/Cellar/gcc/11.2.0_3/include/c++/11/cwchar:44:10: fatal error: wchar.h: No such file or directory\n', '   44 | #include <wchar.h>\n', '      |          ^~~~~~~~~\n', 'compilation terminated.\n', 'make[2]: *** [benchmark.o] Error 1\n', 'make[1]: *** [gcc-profile-make] Error 2\n', 'make: *** [profile-build] Error 2\n']
Informing the server
Post request https://tests.stockfishchess.org:443/api/failed_task handled in 100.19ms (server: 2.81ms)
Task exited

**Comment by RaimundHeid** [comment]
Had to cleanup my developer tools and reinstall Homebrew. Now everything runs fine with x86-64 and gcc/g++. g++ also 'Determined the best architecture to be  x86-64-bmi2', which is the best for my hardware. So everything seems to be OK with this PR on my machines. Good job!

**Comment by ppigazzini** [comment]
Thank you for the tests, very appreciated :)

**Comment by ppigazzini** [comment]
Many thank to @d3vv for the suggestions/code about Mac :)

**Comment by d3vv** [comment]
> Many thank to @d3vv for the suggestions/code about Mac :)

you're welcome :)

**Pull request merged**
