### PR TITLE
PR4: Add a free text search field to the event log page.

### PR DESCRIPTION
**Pull request by vdbergh**
For this to work one needs to run

utils/create_indexes.py actions

to create a text index on the string fields of an event:

action, username, worker, message, run, nn.

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
DEV updated on the fly.

**Comment by vdbergh** [comment]
> DEV updated. Creating indexes... done. LGTM, but it seems that are required at least 4 letters to start a search,

MongoDb text indices are a bit limited.  You can only search for full words (e.g. when searching for `user01-2cores-9e48562f-f444*` you can search for `9e48562f` but not for `9e4856`). An alternative for text search is regex search but this cannot use an index.

**Comment by ppigazzini** [comment]
The search with the incomplete word "fail" works, though.
https://dfts-0.pigazzini.it/actions?action=&user=ChessDBCN&text=fail

**Comment by vdbergh** [comment]
> The search with the incomplete word "fail" works, though. https://dfts-0.pigazzini.it/actions?action=&user=ChessDBCN&text=fail

Yes there seems to be an undocumented exception that you can do partial word matches on the start of a field...

**Comment by vdbergh** [comment]
On the internet I saw some recommendations to redo a text search using regex search in case the text search returns nothing. However if the regex search also doesn't match anything then this means scanning the whole collection (even with a paginated search) which will be very slow.

**Comment by vdbergh** [comment]
There are still a few bugs with escaping/unescaping the test field. I will look at it tonight. For now I am marking this as draft.

**Comment by vdbergh** [comment]
> BTW I was asking only to understand how to use the search field.

Yes I agree it is not very discoverable (although it is similar to Google search). I think it will be best to add a dialog box with some explanations. A good model is the dialog box for the autoselect SPSA parameters.

**Comment by vdbergh** [comment]
Undrafted. I think I fixed the quoting issues and I also added a message box with some information about the free text search.

**Comment by vdbergh** [comment]
Hmm still not fully fixed.

**Comment by vdbergh** [comment]
Hopefully it is fixed now.

**Comment by ppigazzini** [comment]
DEV update on the fly before running to take the train :)

**Comment by vdbergh** [comment]
> DEV update on the fly before running to take the train :)

Thanks!

**Comment by vdbergh** [comment]
I changed the index to have no default language (so it should be regenerated with the script). Otherwise the text search does some funky stuff with stemming which may be useful for large text databases but which in our context is only confusing.

**Comment by ppigazzini** [comment]
DEV updated, actions indexes rebuilt.

**Comment by vdbergh** [comment]
> DEV updated, actions indexes rebuilt.
> 
> Now the search returns only for a whole word of any length: https://dfts-0.pigazzini.it/actions?action=&user=&text=to
> 
> The info box is a classy touch :)
> 
> > When passed a search string that only contains negated words, text search will not match any documents
> 
> :(

Yeah I got to dislike a mongodb a bit for all these arbitrary restrictions. But we have to live with it!

Anyway I think the PR is fine now.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD and indexes updated, thank you @vdbergh :)

**Pull request merged**
