### PR TITLE
Update bounds when clicking STC/LTC buttons

### LINKED ISSUE #405: LTC button
Maybe i'm the only one who gets caught with this but...

When we reschedule a STC test, and press LTC, time and hash are changed correctly,
but sprt stays the same which is unexpected behaviour.

if sprt was 0.5...4.5 (STC) it should change to 0....3.5 (LTC)

### PR DESCRIPTION
**Pull request by tomtor**
Should fix #405

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor I don't view difference after applying this PR to the [dev server](https://dfts-0.pigazzini.it)

By the way I think that @Rocky640 is asking to auto set the "SPRT bounds" after pushing the "Long (LTC)" time control button.

**Comment by tomtor** [comment]
> By the way I think that @Rocky640 is asking to auto set the "SPRT bounds" after pushing the "Long (LTC)" time control button.

I do both. If you had STC bounds and press LTC you get LTC bounds. If you have LTC bounds and press STC you get STC-bounds. I wonder why it is not working for you. Browser cache refresh?

**Comment by ppigazzini** [comment]
@tomtor after clicking "Reschedule" you get "Custom bounds"

**Comment by tomtor** [comment]
> after clicking "Reschedule" you get "Custom bounds"

Ok, then nothing changes. Only when you have selected STC and press LTC bounds change.

**Comment by tomtor** [comment]
@ppigazzini please test again

**Comment by ppigazzini** [comment]
@tomtor it works when rescheduling a STC test.
If I'm not wrong the code is only about the STC case (in other words: it doesn't work when rescheduling a LTC test)

**Comment by tomtor** [comment]
> If I'm not wrong the code is only about the STC case (in other words: it doesn't work when rescheduling a LTC test)

Now I am confused. If you reschedule a test that was already LTC then all bounds are already correct?

**Comment by ppigazzini** [comment]
@tomtor LTC reschedule -> new test form w/ "custom bounds" "0.0 - 3.5".
Pushing "short STC", "long LTC" buttons, time and hash change, but SPRT bounds are always fixed to "custom bounds" "0.0 - 3.5"

**Comment by tomtor** [comment]
@ppigazzini I got it this time (I hope :D ), thanks for the feedback!

**Comment by ppigazzini** [comment]
@tomtor LTC doesn't work, check the dev server.

> Sounds like something that could happen to me ;-)

It happened, you are Tom before learning to code :D

**Comment by tomtor** [comment]
@ppigazzini It works for me, after rescheduling eg https://dfts-0.pigazzini.it/tests/run?id=5d8938130ebc59600ae5649f I can toggle with the STC/LTC buttons?!

**Comment by ppigazzini** [comment]
@tomtor rescheduling a STC and pushing "long LTC" change the bounds.
Rescheduling a LTC and pushing "short STC" doesn't change the bounds.

https://dfts-0.pigazzini.it/tests/view/5d8fb8b0612e02ce742bf20b

**Comment by tomtor** [comment]
@ppigazzini Ah, it was '0' vs '0.0' when rescheduling an existing LTC test....

Please test again, fingers crossed.

**Comment by ppigazzini** [comment]
@tomtor it works! :)
Can I merge?

**Comment by tomtor** [comment]
> Can I merge?

Yes, please do! Thanks again for your thorough testing!

Perhaps I should convert the fields to floats, but it is OK for me now.

**Comment by ppigazzini** [comment]
Done, thanks @tomtor :)

**Pull request merged**
