### PR TITLE
Fix showing LLR bounds for pending runs

### PR DESCRIPTION
**Pull request by tomtor**
when no runs are active

This is a minor fix

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor @Stefano80 @snicolet [dev-server](http://94.198.98.239/tests) updated. Let me know if this is corrett.

**Comment by tomtor** [comment]
http://94.198.98.239/tests does now show [0,5] below Pending... when no active workers so it is OK for me.

**Comment by ppigazzini** [comment]
official server updated.

**Comment by Stefano80** [comment]
Hi, I am just back at home. I noticed that the display of the remaining time is there for the production server and removed on the development server. Is this thought to be so.

**Pull request merged**
