### PR TITLE
Rewrite live_elo.js using async/await.

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV update, started some workers.

In this test the Elo Gauge the red/green zones are missing...
https://dfts-0.pigazzini.it/tests/live_elo/63ab646a77ef25e68d3be6b0

image

**Comment by vdbergh** [comment]
That's also in master. Basically the confidence interval (which would be green) is "too far out" to be visible.

**Comment by ppigazzini** [comment]
LGTM

**Comment by vdbergh** [comment]
I wonder if the notify stuff still works. I do not know how to test it.

**Comment by ppigazzini** [comment]
> I wonder if the notify stuff still works. I do not know how to test it as I don't know what it is supposed to do. Also my local fishtest is on http and Notify does not work over http.

:)

image

**Comment by vdbergh** [comment]
In that case I think things work as they should!

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
