### PR TITLE
Use blue instead of green for passed simplifications

### PR DESCRIPTION
**Pull request by snicolet**
Use blue instead of green for passed simplifications

### CODE REVIEW

**Comment by ppigazzini** [comment]
@snicolet [dev-server](https://dfts-0.pigazzini.it) updated. I think that we should also change:
- the color for "tests" pages
- the menu voice from "Greens" to "Passed" or "Accepted"

@tomtor suggestions?

**Comment by ianfab** [comment]
Due to a hack in the displaying of the list of succesful tests using the color, this change also needs to be reflected there: https://github.com/glinscott/fishtest/blob/a227e3953bb98f4e26d2f4eb1e59fd888d6428d3/fishtest/fishtest/rundb.py#L225-227

**Comment by tomtor** [comment]
Its obvious that the fishtest colouring needs some refactoring love if more colours are introduced.
If we agree on the blue colour then it's easy to change the PR in an agile way so that:

> * the color for "tests" pages
I propose that only NEW tests get the blue color

> * the menu voice from "Greens" to "Passed" or "Accepted"
Just let this unchanged, so Greens returns only the greens (and not the blues :-)

**Comment by ppigazzini** [comment]
Prod server updated, thank you @snicolet

**Comment by snicolet** [comment]
thanks :-)

**Pull request merged**
