### PR TITLE
Make sure that the left pane does not disappear during scrolling.

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated, LGTM on Chrome and Edge.

**Comment by vdbergh** [comment]
I bug: a string, intended as a mako comment appears on the page. Need to check.

**Comment by ppigazzini** [comment]
https://docs.makotemplates.org/en/latest/syntax.html#comments

> The single line comment uses ## as the first non-space characters on a line

**Comment by vdbergh** [comment]
Fixed. I think.

**Comment by ppigazzini** [comment]
DEV updated, comment fixed, firefox OK.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
