### PR TITLE
Upgrade bootstrap from 2.3.2 to 5.1.1

### PR DESCRIPTION
**Pull request by linrock**
Makes the site feel more modern since bootstrap 2.3.2 is 8+ years old (Jul 2013) and 5.1.1 was released a few weeks ago. Most of the site should still look similar.

Bootstrap 5.1 docs:
https://getbootstrap.com/docs/5.1

There will likely be issues since I didn't exhaustively check every page and don't have much test data to do so.

issues found by ppigazzini:
- [x] switch from light to dark theme is broken: clicking on the moon icon seems to switch only the icon (moon->sun->moon...)
- [x] gauge test box in light theme: lacks color (red, yellow) in homepage and in test page
- [x] test page (both themes): missing button for "Show/Hide" diff code snippet
- [x] NN stat page (both themes): missing button for "Show/Hide non default net"
- [x] test raw stats page: still to bootstrap 2.3.2
- [x] Chess SPRT Calculator page): still to bootstrap 3.4.2

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated.

- [ ] light/dark theme switch seems broken: icon moon does nothing and disappears

**Comment by vondele** [comment]
Might be time for an upgrade indeed. 

I'll post a screenshot, colors are gone on the front page for me (firefox):

image

**Comment by vdbergh** [comment]
I'm a bit confused. The commit message also mentions bootstrap 4.5.3. Why sometimes 4.5.3 and sometimes 5.1.1? Just curious.

Another thing: It's not really important but the raw stats page still uses 2.3.2. I tried to upgrade it once but it looked awful. But perhaps you know what needs to be done?

**Comment by vondele** [comment]
The button 'hide non default nets' doesn't look like a button:

image

**Comment by vdbergh** [comment]
@ppigazzini It is out of the scope of this PR but IMHO dark/light mode would need an overhaul. IIUC dark mode is implemented by looking for certain strings and replacing these (the replacement marked with !important to override even inline styling). This means that each time there is a small change in light mode, dark mode breaks. Dark/light modes would need proper css implementations.

**Comment by ppigazzini** [comment]
DEV updated, updated also the [bugs list](https://github.com/glinscott/fishtest/pull/1044#issuecomment-924605640) with the fixes :)

**Comment by ppigazzini** [comment]
DEV updated.

Could you fix the vertical alignment at right border when using time odds? (e.g. reducing the "Thread" and "Priority" boxes)
time_odds

**Comment by ppigazzini** [comment]
DEV updated. All bugs fixed but the color for the test gauges in homepage/testpage with light theme, see https://github.com/glinscott/fishtest/pull/1044#issuecomment-924611957

**Comment by ppigazzini** [comment]
DEV updated, colors in elo boxes OK :)

**Comment by linrock** [comment]
> I'm a bit confused. The commit message also mentions bootstrap 4.5.3. Why sometimes 4.5.3 and sometimes 5.1.1? Just curious.

I'd started upgrading to bootstrap 4.5.3 last year when it was the latest version, didn't finish the upgrade, and only picked up the upgrade again recently. By now, the latest version is 5.1.1 !

> Another thing: It's not really important but the raw stats page still uses 2.3.2. I tried to upgrade it once but it looked awful. But perhaps you know what needs to be done?

I upgraded the raw stats page to use 5.1.1 and it should look ok now, but could use some spacing adjustments. The main thing that needed changing were the class names for the new [bootstrap grid system](https://getbootstrap.com/docs/5.1/layout/grid/) (i.e. need to rename `span8` to `col-8`)

> Could you fix the vertical alignment at right border when using time odds? (e.g. reducing the "Thread" and "Priority" boxes or scaling all the boxes)

sure, could we open an issue for this and revisit in a separate PR? i see this is also an issue in current master (bootstrap 2.3.2). would have to look more closely to figure out a fix

**Comment by linrock** [comment]
> DEV updated, colors in elo boxes OK :)

nice, lmk if you guys find more issues, big or small. happy to fix more things in this PR, or squash to prep for merge when you feel it's ready enough

**Comment by ppigazzini** [comment]
> > Could you fix the vertical alignment at right border when using time odds? (e.g. reducing the "Thread" and "Priority" boxes or scaling all the boxes)
> 
> sure, could we open an issue for this and revisit in a separate PR? i see this is also an issue in current master (bootstrap 2.3.2). would have to look more closely to figure out a fix

Sure :)

**Comment by vdbergh** [comment]
> > Another thing: It's not really important but the raw stats page still uses 2.3.2. I tried to upgrade it once but it looked awful. But perhaps you know what needs to be done?
> 
> I upgraded the raw stats page to use 5.1.1 and it should look ok now, but could use some spacing adjustments. The main thing that needed changing were the class names for the new [bootstrap grid system](https://getbootstrap.com/docs/5.1/layout/grid/) (i.e. need to rename `span8` to `col-8`)
> 

Thanks! It looks much better now! Don't worry about fine cosmetics. This page is not normally visited by users.

**Comment by vondele** [comment]
another minor nit on https://dfts-0.pigazzini.it/upload some space would look better between the browse and agree buttons:

image

**Review by ppigazzini — APPROVED** [review]
DEV looks good to me, please squash :)

**Comment by ppigazzini** [comment]
PROD updated, thank you @linrock :)

**Comment by snicolet** [comment]
On my Mac after the merge, all links are underlined text (both Safari and Chrome):

image

**Comment by ppigazzini** [comment]
Try a page refresh.

**Comment by snicolet** [comment]
I did it in Safari, and of course it reloaded the css file.

But I wonder if for such big changes to the css, it wouldn't be a good idea to *rename* the css in the page to force a fresh load of the new version by default.

**Comment by vdbergh** [comment]
Maybe add a cache buster? E.g. https://css-tricks.com/strategies-for-cache-busting-css/ .

**Comment by vdbergh** [comment]
I do not know how to do a hard page refresh on my iPad. However IIRC static content is only cached for 1 hour . So it is not a big deal.

**Comment by QuackQuackBlah** [comment]
I really like this change! Makes it feel a lot newer! One small issue that I've found, on a Mac with Chrome I can no longer select the "view individual parameter" option for the SPSA graphs. Unclear if that's a browser issue or a fishtest issue. (should I be making a separate issue for this, or is this a fine place to say it?)

**Comment by ppigazzini** [comment]
"View Individual Parameters" for SPSA graphs doesn't work also on Windows :(

https://tests.stockfishchess.org/tests/view/615193040d0a3569cbc641bd

**Comment by ppigazzini** [comment]
The drop down menu works on DEV after reverting this commit.

**Comment by ppigazzini** [comment]
@QuackQuackBlah fixed, refresh a couple of times the browser.

**Comment by AndrewTCEC** [comment]
I think this upgrade also ruined dark theme:
Screenshot_2021-09-27-21-37-52-578_com android chrome

**Comment by dav1312** [comment]
@AndrewTCEC 
Follow the instructions here: https://github.com/glinscott/fishtest/pull/1044#issuecomment-927376972

**Comment by AndrewTCEC** [comment]
This is Chrome Mobile @dav1312

**Comment by dav1312** [comment]
> This is Chrome Mobile @dav1312 What to do in this case?

The underlying issue is the same one, a cache one. Check if it persists in incognito mode.

**Comment by AndrewTCEC** [comment]
Already fixed it by clearing cache in my browser. Thanks for help @dav1312

**Pull request merged**
