### PR TITLE
Cache pending for 1s instead of 60s

### PR DESCRIPTION
**Pull request by tomtor**
Fix (makes rare) #578 

Edit: Alternatives are:
* completely remove caching of pending user query
* disable separate main page pserve instance

### CODE REVIEW

**Comment by ppigazzini** [comment]
PROD updated, thank you @tomtor :)
ps: Happy Easter to you and your family!

**Comment by tomtor** [comment]
@ppigazzini Happy wishes to you and your family too!

**Comment by ppigazzini** [comment]
@vondele @linrock @vdbergh @snicolet @xoto10 @glinscott @noobpwnftw
Happy Easter to you :)

**Comment by vondele** [comment]
@ppigazzini and all, same to you

**Pull request merged**
