### PR TITLE
Update to a new default book

### PR DESCRIPTION
**Pull request by vondele**
Switches to a new book by Stefan Pohl: UHO_XXL_+0.90_+1.19.epd

See
https://github.com/official-stockfish/books/commit/63b0f2095923d98d4dcb6d7b0ee79404f83c4270

See discussion and tests in
https://github.com/official-stockfish/Stockfish/issues/3323

### CODE REVIEW

**Comment by vondele** [comment]
There are a few more references to noob_3moves.epd in the comments, they appear to relate to the SPSA, and I don't think they need simultaneous updating (refers to the auto SPSA parameters, IIUC).

**Comment by ppigazzini** [comment]
DEV updated; created SPRT, NumGames, SPSA tests with the new book; joined Linux, WSL2, msys2 workers. I'm starting to review the references in the comment.

**Comment by ppigazzini** [comment]
> There are a few more references to noob_3moves.epd in the comments, they appear to relate to the SPSA, and I don't think they need simultaneous updating (refers to the auto SPSA parameters, IIUC).

That is the info box for the auto SPSA parameters, so the reference must stay. There is also a reference to `contempt = 24`, so I'm wondering if that code makes still sense with the NNUE Stockfish.

By the way the SPSA seems to tune very well the NNUE parameters.

**Comment by vondele** [comment]
yeah, I agree that reference must stay, and probably one could refit that code for the new book / new engine. However, as you say, SPSA is pretty successful these days, so it wouldn't be urgent to change.

**Comment by ppigazzini** [comment]
DEV and workers look good to me, let me know when I can merge and update the server.

**Comment by vondele** [comment]
please go ahead.

**Comment by ppigazzini** [comment]
PROD updated, thank you @vondele :)

**Pull request merged**
