### PR TITLE
One time upgrade script.

### PR DESCRIPTION
**Pull request by vdbergh**
The script works on my mini local db. But it will probably still lose information on very old tests. That's the reason for  #1216 . Then I can inspect some of those old tests.

### CODE REVIEW

**Comment by vdbergh** [comment]
Currently the script changes the run collection in place with the idea that if it fails, or does something wrong, one can just reload the db to undo the changes. 

But I can also work on a copy of the run collection and patch fishtest in the PR to use the copy - if that is more convenient.

**Comment by vdbergh** [comment]
I am now first copying the `run` collection. This seems cleaner.

**Comment by ppigazzini** [comment]
I will help testing the script on DEV as soon as merged the queued PRs.

**Comment by vdbergh** [comment]
I checked and I think the script does not lose any information with old tests (there just isn't much there).

The db conversion can be done while the server is running since it makes a copy of the `runs` collection to `runs_new`. 
After the conversion is done and the server is restarted it will use the `runs_new` collection (there is a debug print when the server starts, of course this is temporary).

Of course I have no idea how fast this will be, and what the required resources are.

**Comment by ppigazzini** [comment]
DEV on this PR and loaded with a fresh db copy.
I'm late for my commute, I will start the script as soon at the keyboard.

**Comment by vdbergh** [comment]
@ppigazzini Please take your time. There is no hurry!

**Comment by ppigazzini** [comment]
```
$ time ${VENV}/bin/python3 upgrade.py
...
2021-12-30T20:31:46.449+0000    20624 document(s) restored successfully. 0 document(s) failed to restore.
Starting conversion...
Traceback (most recent call last):
  File "upgrade.py", line 239, in <module>
    convert_run(r)
  File "upgrade.py", line 190, in convert_run
    assert chunks[0] == "LLR:"
AssertionError

real    6m53.092s
user    3m54.306s
sys     0m44.240s
```

**Comment by vdbergh** [comment]
I will need to print the run/task id to see what happened. I will do it tomorrow. Sorry for the hiccup.

However I am confused with the number of documents restored. Only 20624. While there are more than 100000 tests…

**Comment by ppigazzini** [comment]
Copied additional lines in previous post.

**Comment by vdbergh** [comment]
We would need to understand first my mongorestore restores so few documents.

This is the command
```
    cmd = (
        "mongodump --archive --db=fishtest_new --collection=runs"
        "|"
        "mongorestore --archive  --nsFrom=fishtest_new.runs --nsTo=fishtest_new.runs_new"
    )
```

**Comment by vdbergh** [comment]
https://stackoverflow.com/questions/59862612/mongorestore-returning-less-documents-with-no-erro

It seems other people have the same problem.

**Comment by vdbergh** [comment]
https://www.mongodb.com/community/forums/t/document-count-mismatch-in-a-collection/11052

Another one.

**Comment by ppigazzini** [comment]
Reloaded the same AWS backup, my restore script shows the same 20624 count:
```
2021-12-30T21:50:58.914+0000    [######################..]  fishtest_new.runs  1.24GB/1.33GB  (93.3%)
2021-12-30T21:51:01.914+0000    [######################..]  fishtest_new.runs  1.25GB/1.33GB  (94.3%)
2021-12-30T21:51:04.914+0000    [#######################.]  fishtest_new.runs  1.28GB/1.33GB  (96.2%)
2021-12-30T21:51:07.914+0000    [#######################.]  fishtest_new.runs  1.30GB/1.33GB  (97.7%)
2021-12-30T21:51:10.914+0000    [#######################.]  fishtest_new.runs  1.32GB/1.33GB  (99.6%)
2021-12-30T21:51:12.302+0000    [########################]  fishtest_new.runs  1.33GB/1.33GB  (100.0%)
2021-12-30T21:51:12.302+0000    restoring indexes for collection fishtest_new.runs from metadata
2021-12-30T21:51:38.523+0000    finished restoring fishtest_new.runs (20624 documents, 0 failures)
2021-12-30T21:51:38.523+0000    454022 document(s) restored successfully. 0 document(s) failed to restore.
```

The documents count in runs collection with mongo shell is 115225:
```
> use fishtest_new
switched to db fishtest_new
> db.runs.countDocuments({})
115225
```

**Comment by ppigazzini** [comment]
```
$ mongodump --archive --db=fishtest_new --collection=runs | mongorestore --archive  --nsFrom=fishtest_new.runs --nsTo=fishtest_new.runs_new
...
2021-12-30T22:17:54.314+0000    [#######################.]  fishtest_new.runs  114078/115225  (99.0%)
2021-12-30T22:17:57.264+0000    fishtest_new.runs_new  11.0GB
2021-12-30T22:17:57.314+0000    [#######################.]  fishtest_new.runs  114655/115225  (99.5%)
2021-12-30T22:18:00.264+0000    fishtest_new.runs_new  11.1GB
2021-12-30T22:18:00.314+0000    [#######################.]  fishtest_new.runs  115056/115225  (99.9%)
2021-12-30T22:18:00.731+0000    [########################]  fishtest_new.runs  115225/115225  (100.0%)
2021-12-30T22:18:00.762+0000    done dumping fishtest_new.runs (115225 documents)
2021-12-30T22:18:01.205+0000    fishtest_new.runs_new  11.2GB
2021-12-30T22:18:01.206+0000    restoring indexes for collection fishtest_new.runs_new from metadata
2021-12-30T22:18:22.418+0000    finished restoring fishtest_new.runs_new (20624 documents, 0 failures)
2021-12-30T22:18:22.418+0000    20624 document(s) restored successfully. 0 document(s) failed to restore.
```

```
> use fishtest_new
switched to db fishtest_new
> db.runs_new.countDocuments({})
115225
```

**Comment by vdbergh** [comment]
So it seems the faulty document count is a bug in `mongorestore`...

Also it seems that `run["results_info"]` is sometimes corrupt (the assertion error) ... 

Instead of trying to parse it I am now just recomputing it.

**Comment by ppigazzini** [comment]
Finished on DEV with the latest AWS db backup, no workers running:
```
$ time ${VENV}/bin/python3 fishtest/server/utils/upgrade.py
Copying "runs" to "runs_new"...
2021-12-31T13:43:01.212+0000    writing fishtest_new.runs to archive on stdout
2021-12-31T13:43:01.249+0000    preparing collections to restore from
2021-12-31T13:43:01.381+0000    reading metadata for fishtest_new.runs_new from archive on stdin
2021-12-31T13:43:01.387+0000    restoring fishtest_new.runs_new from archive on stdin
2021-12-31T13:43:04.145+0000    fishtest_new.runs_new  146MB
2021-12-31T13:43:04.192+0000    [........................]  fishtest_new.runs  2093/115264  (1.8%)

...

2021-12-31T13:46:46.192+0000    [#######################.]  fishtest_new.runs  114078/115264  (99.0%)
2021-12-31T13:46:49.145+0000    fishtest_new.runs_new  11.1GB
2021-12-31T13:46:49.192+0000    [#######################.]  fishtest_new.runs  115056/115264  (99.8%)
2021-12-31T13:46:51.248+0000    [########################]  fishtest_new.runs  115264/115264  (100.0%)
2021-12-31T13:46:51.265+0000    done dumping fishtest_new.runs (115264 documents)
2021-12-31T13:46:51.887+0000    fishtest_new.runs_new  11.2GB
2021-12-31T13:46:51.887+0000    restoring indexes for collection fishtest_new.runs_new from metadata
2021-12-31T13:47:12.790+0000    finished restoring fishtest_new.runs_new (20602 documents, 0 failures)
2021-12-31T13:47:12.791+0000    20602 document(s) restored successfully. 0 document(s) failed to restore.
Starting conversion...
Runs converted: 115264.
Conversion finished in 3420.70 seconds. Time per run: 29.68ms.

real    61m14.464s
user    49m36.531s
sys     2m23.990s
```

**Comment by vdbergh** [comment]
Did you restart the server after the conversion? Currently everything seems to be the same.

**Comment by ppigazzini** [comment]
No, done just now:
```
sudo systemctl stop fishtest@{6543..6544}
sudo systemctl restart mongod
sudo systemctl start fishtest@{6543..6544}
```

**Comment by vdbergh** [comment]
Well it seems to have worked. If you see things that need tweaking...

**Comment by ppigazzini** [comment]
I will run tests and workers, the crontab scripts and keep monitoring the logs.

**Comment by vdbergh** [comment]
It seems some workers reported a crazy amount of memory. E.g. 16724644MiB for task 5 in https://dfts-0.pigazzini.it/tests/view/5d713e070ebc5902bbd8bc19 .

Of course they can report whatever they want with the `--memory` argument.

**Comment by ppigazzini** [comment]
There are few "failed task ... is past end time" on DEV after the switch to the new collection.

**Comment by vdbergh** [comment]
In noticed that too. But I really can't see how this could possibly be related to the new collection.

I am now running a test locally. If it is ok, then I will connect a worker to DEV.

**Comment by ppigazzini** [comment]
I think to have find an explanation. I loaded an AWS db backup, converted it with the script, then I started some new tests with high priority, when completed them the workers switched to the original tests and some of these tests triggered the warning.

**Comment by vdbergh** [comment]
It's still not clear to me. Being past end time is something that is decided by the worker.

IMHO it can only happen if the worker is stopped for some time. E.g. by putting the computer in sleep mode, or doing Ctrl-Z (on Linux).

**Comment by ppigazzini** [comment]
Ops, I forgot that now a worker doesn't get an unfinished task.

**Comment by ppigazzini** [comment]
It can be that only 7 workers with some dozen of scheduled tests are using too much time in building the engines?

**Comment by ppigazzini** [comment]
I lowered the worker concurrency.

**Comment by vdbergh** [comment]
Hmmm. If a worker over estimates its own nps during the bench, then it will incorrectly compute how much time a task will take. This could cause the error. 

On a system with highly variable system load this is a plausible scenario.

**Comment by ppigazzini** [comment]
Nevers saw the issue with my tests @ 1+0.01, a couple of stopped tasks @ STC, all the others @ LTC. It seems that the formula doesn't scale correctly with the TC.

The 5 workers @ 5 cores ahev been running from the same server so they could have some bench noise. 

The worker @ 32 cores has been run for several months on PROD without problems:
https://tests.stockfishchess.org/actions?action=failed_task&user=ctoks&before=1641134114.062&count=100

**Comment by ppigazzini** [comment]
Raised the workers concurrency.

**Comment by vdbergh** [comment]
There is also this

https://dfts-0.pigazzini.it/actions?count=1&before=1641067457.127

I never saw this happening on DEV.

**Comment by vdbergh** [comment]
I am not a 100% sure this cannot be caused by doing Ctrl-C at an inopportune time.

**Comment by ppigazzini** [comment]
> I am not a 100% sure this cannot be caused by doing Ctrl-C at an inopportune time.

No CTRL-C on that worker (working in background).

BTW a new "past end time" @ LTC. I even rebooted the server before starting the 32 cores worker. 
https://dfts-0.pigazzini.it/actions?count=1&before=1641135821.554

**Comment by vdbergh** [comment]
> > I am not a 100% sure this cannot be caused by doing Ctrl-C at an inopportune time.
> 
> No CTRL-C on that worker (working in background).
> 
> BTW a new "past end time" @ LTC. I even rebooted the server before starting the 32 cores worker. https://dfts-0.pigazzini.it/actions?count=1&before=1641135821.554

Still... this is decided by the worker. Is there something funny in the api.log (api calls that take very long to complete perhaps)? 

We could make the worker send a bit more info to the event log.
> 
> EDIT_000: In this pgn there is a "unterminated" game after 311 plies: https://dfts-0.pigazzini.it/api/pgn/61cb9efce68b2a714b6eaa0d-2818.pgn

I think this normal. If the worker runs out of time it will send a SIGINT to cutechess-cli. Then cutechess-cli writes a final pgn. The games that are happening at that time become "unterminated".

**Comment by ppigazzini** [comment]
> EDIT. I hadn't noticed the point about the 311 moves. Yes if you have very short tasks then perhaps one very long game may cause the worker to go over time.

Yes, this should fit the "past end time" mostly for LTC (more drawish) and never for USTC.

**Comment by ppigazzini** [comment]
Another 309 plies unterminated game and another "past end time"
https://dfts-0.pigazzini.it/actions?count=1&before=1641137374.219
https://dfts-0.pigazzini.it/api/pgn/61cb9efce68b2a714b6eaa0d-2820.pgn

The worker has 32 cores, the task was completed 24/32, so it perhaps others 8 games was running very long.

Same numbers for the previous "past end time" task.

**Comment by vdbergh** [comment]
Not only that. Your tasks are 3 minutes. I have not analyzed the computation of tc_limit but I guess it is some small multiple of the estimated task duration. Say 6 minutes (a guess). In that case a games that takes 6 minutes to finish will make the worker go over time. The longer the tc, the more likely it is of course to have a 6 minute game.

**Comment by ppigazzini** [comment]
Let me know if I can merge and run the script on PROD.
Plan is to run in `tmux` a script like this, stopping the server for 1 hour:
```bash
sudo systemctl stop fishtest@{6543..6544}
sleep 10
sudo systemctl restart mongod
sleep 10
${VENV}/bin/python3 ${HOME}/fishtest/server/utils/update.py
sleep 10
sudo systemctl restart mongod
sleep 10
sudo systemctl start fishtest@{6543..6544}
```

**Comment by vdbergh** [comment]
The script seems to be fine. So I am ok with it.

**Comment by ppigazzini** [comment]
Conversion started!

**Comment by ppigazzini** [comment]
Conversion finished :)

```
2022-01-02T19:25:49.111+0000    [########################]  fishtest_new.runs  115357/115357  (100.0%)
2022-01-02T19:25:49.133+0000    done dumping fishtest_new.runs (115357 documents)
2022-01-02T19:25:49.652+0000    fishtest_new.runs_new  11.2GB
2022-01-02T19:25:49.652+0000    restoring indexes for collection fishtest_new.runs_new from metadata
2022-01-02T19:26:10.796+0000    finished restoring fishtest_new.runs_new (20631 documents, 0 failures)
2022-01-02T19:26:10.796+0000    20631 document(s) restored successfully. 0 document(s) failed to restore.
Starting conversion...
Runs converted: 115357.
Conversion finished in 2944.74 seconds. Time per run: 25.53ms.
```

**Comment by vdbergh** [comment]
The upgrade script can now be removed. As well as the old `runs` collection. We could rename `runs_new` to `runs` but that would require another dump/restore cycle (you'd think that renaming a collection would be a trivial operation...).

We can now start to remove glue code (such as checking for the existence of `worker_info`) I'll get to that in the near future but the next couple of weeks I will be a bit busy.

**Comment by ppigazzini** [comment]
> We could rename `runs_new` to `runs` but that would require another dump/restore cycle (you'd think that renaming a collection would be a trivial operation...).

Rename a collection in a bash script it's easy, just done:
https://docs.mongodb.com/v4.2/reference/method/db.collection.renameCollection/

```bash
mongo << 'EOF'
use fishtest_new
db.runs.renameCollection("runs_old")
exit
EOF
```
```
> use fishtest_new
switched to db fishtest_new
> show collections
actions
clop
deltas
flag_cache
nns
old_user_cache
pgns
regression_data
runs_new
runs_old
top_month
user_cache
users
> db.runs_old.countDocuments({})
115357
```

**Comment by vdbergh** [comment]
I see. I guess it is copying a collection that requires dump/restore.

So I guess it would be nice to rename `runs_new` to `runs`.

**Comment by ppigazzini** [comment]
Done on PROD.

```bash
#!/bin/bash
# time sudo bash rename_runs_collections.sh | tee rename_runs_collections.sh.log
user_name='fishtest'

echo "stop cron and fishtest ..."
systemctl stop cron
systemctl stop fishtest@{6543..6544}
sleep 5

echo "rename runs collections ..."

sudo -i -u ${user_name} << 'EOF000'
mongo << 'EOF'
use fishtest_new
db.runs.renameCollection("runs_old")
db.runs_new.renameCollection("runs")
exit
EOF
EOF000

echo "start fishtest and cron ..."
systemctl start fishtest@{6543..6544}
systemctl start cron
```

**Pull request merged**
