### PR TITLE
Fix race on task['pending']

### PR DESCRIPTION
**Pull request by tomtor**
between update_task and request_task.

This prevents SPSA tasks with 251/250 played,
because SPSA workers will always play 2*concurrency games
and request_task overwites the

    return {'task_alive': task['active']}

from update_task, causing one more game to be played.

### CODE REVIEW

**Comment by ppigazzini** [comment]
dev-server and workers are running w/ a SPSA test.

**Comment by tomtor** [comment]
@ppigazzini for some reason my tvijlbrief account is changed/locked on the dev server. When i use user00 I get a technical error when I click Pending(0)?

**Comment by ppigazzini** [comment]
@tomtor I loaded a fresh copy of the production DB.

**Comment by tomtor** [comment]
@ppigazzini Thanks, things look normal again...

**Comment by ppigazzini** [comment]
@tomtor if this is ready I'm for merging.

After 3 hours of SPSA test, the PR seems fine, this is the nohup.out:
```
Starting server in PID 5026.
Serving on http://0.0.0.0:6543
```
Travis passed with some hand restarts.

**Comment by tomtor** [comment]
Yes, please merge. Thanks

**Comment by ppigazzini** [comment]
Production server updated.
Thank you @tomtor

**Pull request merged**
