### PR TITLE
Fix timestamp for python2 (raise version to 74)

### PR DESCRIPTION
**Pull request by ppigazzini**
Also raise worker version to 74 worker side

### CODE REVIEW

**Comment by ppigazzini** [comment]
@noobpwnftw I raised the version to view if the old python2 workers will run with the fixed code.
Very low priority task: please update you workers to v74 :)

**Comment by ppigazzini** [comment]
@d3vv please update by hand your python2 workers to version 74. Next time the auto update will work fine (Murphy who? :)

**Comment by noobpwnftw** [comment]
@ppigazzini Started rolling update of v74 on regular workers. Fleet images have not changed, until next SPSA patch is done.

**Comment by ppigazzini** [comment]
@noobpwnftw thank you. The batching PRs are finishing the testing phase :)

**Pull request merged**
