### PR TITLE
Maintenance page

### PR DESCRIPTION
**Pull request by maximmasiutin**
The image is licensed - I purchased rights on Shutterstock

image-licenses

### CODE REVIEW

**Comment by Sopel97** [comment]
Legal aspects aside, this is just unneeded 190kB

**Comment by Sopel97** [comment]
is this page even used anywhere?

**Comment by maximmasiutin** [comment]
> this is just unneeded 190kB

Some people told it is compressed too much and wanted even a higher-sized image. Maybe we could put it to githubusercontent instead?

**Comment by maximmasiutin** [comment]
> is this page even used anywhere?

This page is used only when the admins put the server to maintenance mode - it is displayed to the users instead of the regular list of tests.

**Comment by vdbergh** [comment]
I think the taste of the server admin should prevail here... It is he who is doing the work.

**Comment by maximmasiutin** [comment]
Current page (master)
111-days

**Comment by maximmasiutin** [comment]
Proposed page (patch):

**Comment by maximmasiutin** [comment]
If you don't like the image, I can find another one upon your guidance, or you can take just the text without an image at all.

**Comment by ppigazzini** [comment]
I set the countdown for a long maintenance task to inform the users (I forgot to do it this morning).
During a new setup of the website I don't change the stop date, the script run for less than a dozen of seconds.

I'm fine with a revision of the text that better communicates information to the user, any improvement to the countdown is welcome. The puzzle engages users, reducing complaints about long downtime in the discord channel.

**Pull request closed without merging**
