### PR TITLE
Style changes and W3

### PR DESCRIPTION
**Pull request by dav1312**
Using more Bootstrap classes
Changed pending users icon and text
Changed grid system in test view
Increased contrast ratio of green links in light theme

Added lang (en) attribute
td inside of tr

This also reverts #1271

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated

**Comment by ppigazzini** [comment]
DEV updated, start commuting now.

**Comment by ppigazzini** [comment]
DEV updated

**Comment by dav1312** [comment]
Okay this should be all for this PR

**Comment by ppigazzini** [comment]
PROD - DEV
Is it the intended behavior?

image

**Comment by dav1312** [comment]
Yes, it is. Now the info cell has text wrapping instead of having a scrollbar for all the page and breaking the sidebar.

---

I have been testing some possible implementations to avoid the height problem.
I'll make a draft(?) pr for it soon after. It should be something like this when the screen size is very small:
image

**Comment by ppigazzini** [comment]
Fell free to add any tests on DEV.
You can use your credentials or "user01/user01" "user00/user00" as username/password for normal user and approver.
I view that this solved the weird vertical scrollbar in Contributors for small windows (never noted the problem before).

**Comment by dav1312** [comment]
Thinking about this... why not add a limit for the length of info? It it really necessary to have more than... 400-500 characters?

**Comment by ppigazzini** [comment]
By default the Info is the the commit message, this test with the last SF commit has 5766 chars
https://dfts-0.pigazzini.it/tests/view/6206cab47ec248cffe7a8a60

I'm fine to limit the Info length, @vondele ?

**Comment by vondele** [comment]
yes, reasonable to limit that.

**Comment by ppigazzini** [comment]
@dav1312 please squash the commits when ready to be merged

**Comment by ppigazzini** [comment]
The squash is a message to the maintainer the the wip is finished :)
I never tried the "Squash and merge" button, but in that case the commit message will be the cat of the single messages.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @dav1312 :)

**Pull request merged**
