### PR TITLE
Show worker RAM in home and test pages

### LINKED ISSUE #1131: show memory limit for machines.
Maybe the machine overview could show the memory limit ? 

Right now we know noob's workers can't run LTC tests because of that, but it would be nice to see the actual amount of mem available.

### PR DESCRIPTION
**Pull request by ppigazzini**
closes #1131

### CODE REVIEW

**Comment by ppigazzini** [comment]
@vondele DEV updated, let me know your preferred message format.

**Comment by vondele** [comment]
to me that looks good. 

The alternative is to show it in the test machine list where the architecture flags are shown. I don't have a strong preference.

**Comment by ppigazzini** [comment]
Added in both pages, PROD updated.

**Comment by vondele** [comment]
Thanks! You're on a super active sprint :-)

**Pull request merged**
