### PR TITLE
Progression tests presets v3

### PR DESCRIPTION
**Pull request by dav1312**
Set info (https://github.com/glinscott/fishtest/pull/1416#issuecomment-1239326536)

Notes:
- Only makes the API call when the PT or PT SMP buttons are pressed
- The message is the first line of the commit message

image

image

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated, LGTM, waiting @vondele for approval/suggestion.

**Comment by vondele** [comment]
excellent. I'll leave it up to David to consider/decide using 'Progression test' instead of 'PT' in the Info box, might be useful in the future searching for it.

**Comment by dav1312** [comment]
Whatever you prefer. Most use "Progression test" but some use "PT" and most other tests use the short version (e.g "LTC" or "VLTC")

**Comment by vondele** [comment]
let's use 'Progression test' in this case. The other abbreviations are more common.

**Comment by dav1312** [comment]
Do you also want me to replace the " with ' for the message?

**Comment by vondele** [comment]
whatever is the proper quoting to use in text like that :-), both are fine with me.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @dav1312 :)

**Pull request merged**
