### PR TITLE
Better handling of scroll to task.

### PR DESCRIPTION
**Pull request by vdbergh**
The case of the asynchronously appearing SPSA graph should now also be fixed, although I did not test this.

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated, here is a worker with a failed SPSA task, let me know if it's working as intended:

https://dfts-0.pigazzini.it/actions?max_actions=1&action=failed_task&user=mgrabiak&text=mgrabiak-3cores-0a8fbe43&before=1670038940.979
https://dfts-0.pigazzini.it/tests/view/638a9b91d2b9c924c4c636d8?show_task=35

**Comment by vdbergh** [comment]
It works even better than I expected :) Without this PR the purple row would scroll away once the the graph became visible.

**Comment by vdbergh** [comment]
I did some more testing and it really works well. No more need to hide the diff.

**Review by ppigazzini — APPROVED** [review]
LGTMVDB!

**Comment by ppigazzini** [comment]
Ops, one error with the W3C validator
https://validator.w3.org/nu/?doc=https%3A%2F%2Fdfts-0.pigazzini.it%2Ftests%2Fview%2F638a9b91d2b9c924c4c636d8%3Fshow_task%3D35
```html
Error: Attribute value missing.
At line 616, column 18
  <thead class=>↩      <tr>↩  
```

**Review by ppigazzini — APPROVED** [review]
The validation problem is already in master:
https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Ftests.stockfishchess.org%2Ftests%2Fview%2F638a9b91d2b9c924c4c636d8%3Fshow_task%3D35#cl608c18

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
