### PR TITLE
Some possibilities for LTC highlighting

### PR DESCRIPTION
**Pull request by dubslow**
Each commit is to be considered separately, independently:

1) Adjust color to match link color (still too dark/bright/attention-grabbing for my preference), reduce width for high-contrast color

2) Include `sprt @` in highlight box

3) don't highlight LLR box

@peregrineshahin thoughts?

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated

**Comment by peregrineshahin** [comment]
My suggestion is to do the opposite; Remove the outline around the sprt @ 60+06s
and keep the outline around the LLR box with:
outline: 2px solid #685210 !important; for dark mode
and
outline: 2px solid #d1b25d; for white mode.

I believe this is the best way we can take advantage of the border/outline idea without applying a complex design idea on table rows as a whole.

**Comment by ppigazzini** [comment]
The PR highlight works for time odds tests as well. A rare type of test, though.

image

**Comment by dav1312** [comment]
RFC
image

**Comment by peregrineshahin** [comment]
Probably works also.

**Comment by dubslow** [comment]
Pushed a version akin to dav's image, albeit still highlighting the `@`, altho that can of course be easily changed either way.

**Comment by ppigazzini** [comment]
DEV updated, LGTM

image

**Comment by dubslow** [comment]
My view in lightmode has much more contrast than your image: 
image

**Comment by ppigazzini** [comment]
In effect lower contrast in Chrome and higher in Edge. I use only the dark theme, by the way.

**Comment by dubslow** [comment]
My higher lighttheme contrast is in Chromium

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @dubslow :)

**Pull request merged**
