### PR TITLE
Implement PGN upload/download and database clone

### PR DESCRIPTION
**Pull request by tomtor**
See #140 

PGN-files are stored gzip compressed in a new MongoDb collection ('pgns') with as only additional attribute the creating run_id-task_id.

Currently only a minimal API to retrieve the PGNs and a link in the task list.

About 200 kbyte compressed storage for a 250 game task (compression to 25% original size).

Also add a simple clone script which uses the REST APIs to make a copy of the run and PGN data in a fishtest database.

### CODE REVIEW

**Comment by Stefano80** [comment]
Hi @tomtor , thanks for this idea, it would be really cool if we could start the SF pgn database!

Before, we merge it, though, I would ask to consider the following story from my side.

I have being playing with this idea for some time, too. While thinking, I had this insight: the .pgn format is a really old-fashioned stuff and, if you look at it, it is just another tree-like format like json or xml.

Actually, it would be very cool if json would become the standard for storing chess games and retrieving chess games. If you would have this, it could also be possible to use standard database tooling instead of .pgn custom ones. You should stipulate some conventions to be as close as possible to the pgn conventions, but it should be doable.

I then noticed that there is already a conversion tool pgn2json, which I immediately forked https://github.com/Stefano80/pgn-to-json

Unfortunately, it seems to be not really active, and immediately failed when I tried to jsonize a TCEC game.

Would you be willing to spend some thinking about this idea? I think we could make a great contribution to the chess world if we could do this. Imagine using standard cloud based tooling to search billions of games stored as jsons. It would be just so cool.

**Comment by vondele** [comment]
just wondering if the fishtest server has the capacity to store and serve this data. If we take about 1Kb per game, and we take current games/minute peak (4492 games / minute), we talk about 2 Tb storage per year. That's not soo much, but isn't nothing either, need to check what is available on the server. One way to limit things would be to do this only for LTC games.

Also, with this change results.pgn becomes a non-write-only-file, so two workers in the same dir will corrupt that file. So, I guess this needs at least two more elements... 
- some worker side parsing of the pgn file, only uploading if the file parses as a valid pgn.
- some better naming scheme for the pgn file (e.g. maybe a server generated name, containing runId, workerId, batchID, ....)

Further questions could be:
- will the server be able to deal with the synchronous upload of 100s of batches when a test finishes and all workers send their pgn.
- how to deal with unfinished batches
- how to deal with batches computed by two different workers
- what kind of meta-data do we attach to a pgn (date, testID, workerID, ....)

**Comment by tomtor** [comment]
@vondele Regarding metadata, we store a reference to the run which has all metadata.
Unique naming (worker-uuid) for the pgn file is also easy.
Batches completed by different workers is no problem, multiple uploads are possible, but the api will only return one (probably the most recent).

Storage IS an issue, but we could delete data from the database if it gets too big and eg keep only all the LTC and most recent uploads.

The upload will not be completely synchroneous because each game/worker has a variable time till it ends. We could use the random delay before request-task to randomize the upload event, if it is a problem.

**Comment by vondele** [comment]
Two more suggestions (again, feel free to ignore).

- over at lczero, there is some pgn viewer integrated in the site:
http://lczero.org/match_game/201042
if something browser side would be available to show the pgn, that would make fishtest attractive, and thus maybe lead to more contributors.
- If I read the code correctly, there will be a link for each batch under the test view. I assume what would be useful is to have a link that provides the aggregated results for a test (e.g. get all 40k games for a typical regression run).

**Comment by tomtor** [comment]
@vondele A pgn viewer would be nice, but for a later PR when we have actually some PGNs to view.
Idem dito for the bulk download...

**Comment by tomtor** [comment]
@Stefano80 Sounds like an interesting project! Note that storing the games in JSON would require a lot more storage. If we would like to implement search we would have to store a hash for each position too. Just translating the pgn to JSON on output is certainly possible. Perhaps that could be combined with a viewer PR as suggested by @vondele .

**Comment by snicolet** [comment]
Thanks you so much, everybody, for starting working on this! :-)

**Comment by tomtor** [comment]
@ppigazzini Hoe much free disk space for MongoDb has the server?

**Comment by tomtor** [comment]
@ppigazzini I added a PGN purge script which can be used to remove PGN uploads from the database when free storage space gets low. It defaults to 60 days and keeps all LTC uploads.

It also displays some statistics on number of PGNs found and deleted.

It is currently a bit slow because it counts each task and each run. It could be made to run a lot faster by eg ignoring runs older then purge-time+60days, but  it would be interesting to see how fast the current script runs on the dev server with an empty pgndb collection.

**Comment by ppigazzini** [comment]
dev-server and workers updated, test running.

**Comment by tomtor** [comment]
@ppigazzini Thanks! You should raise the worker version number by hand to 65 if you want to see the PGN download links in the task list...

**Comment by ppigazzini** [comment]
@tomtor Thank you!
In the last 20 minutes I played with systemd on the dev server.
In systemd units I start now `/usr/bin/pserve` and not the scripts `start.sh` and `start_db.sh`.
In this way systemd keeps the log with the log rotation, simply use `sudo journalctl -u fishtest.service` 

View the server setup script for the change to the systemd units:
https://github.com/glinscott/fishtest/wiki/Fishtest-server-setup

**Comment by vondele** [comment]
@tomtor.. yes, I think the pgn downloaded should contain the info needed to (in principle) retrieve the pgn again. Site could be the url of the view for the individual test, the event could be the task ID, or something. White and black should be not stockfish and base, but the engine_new and engine_base names (so we have the sha).

**Comment by vondele** [comment]
as a minor nit, should the link 
http://94.198.98.239/api/pgn/5af1a3cce44b0613a21aa21a-165.pgn
instead of
http://94.198.98.239/api/pgn/5af1a3cce44b0613a21aa21a-165

**Comment by Stefano80** [comment]
Hi, I am bit under pressure at work at the moment, I will have time again next week.

Please go ahead, I will catch up later...

**Comment by tomtor** [comment]
Changed to:

[Event "Batch 522: master vs master"]
[Site "http://tests.stockfishchess.org/tests/view/5af1a3cce44b0613a21aa21a"]
[Date "2018.05.09"]
[Round "1"]
[White "New-6634f41"]
[Black "Base-6634f41"]
[Result "1/2-1/2"]
[FEN "rnbqkbnr/pppppp2/6pp/8/P7/4P3/1PPP1PPP/RNBQKBNR w KQkq -"]
[PlyCount "116"]
[SetUp "1"]
[Termination "adjudication"]
[TimeControl "2.26+0.02"]

**Comment by tomtor** [comment]
@vondele 
> as a minor nit, should the link
http://94.198.98.239/api/pgn/5af1a3cce44b0613a21aa21a-165.pgn
instead of
http://94.198.98.239/api/pgn/5af1a3cce44b0613a21aa21a-165

I also change the mimetype to pgn. If you just want to view HTML/text you can remove the '.pgn' suffix by hand before downloading. I don't think we should add separate download links?

**Comment by ppigazzini** [comment]
dev-server and workers updated.

**Comment by vondele** [comment]
@tomtor one download link is certain enough. The pgn one works well for me, and I like the additional info in the file.

**Comment by ppigazzini** [comment]
dev-server and workers updated after the squash (better to be safe ...).

**Comment by candirufish** [comment]
Can you change the FEN to move sequence from start position such that every game is connected to one tree so it'll be easy to work/search with? And maybe just put the FEN notation in a comment style before the main game notation.

Another suggestion of mine is to save everything, both stc and ltc. Pgn size should be a temporary problem, maybe after a month or so, we can collect everything in a compressed file and host them on a torrent site so contributors with free space and bandwidth could seed and delete it from the server.

**Comment by candirufish** [comment]
Where's the source of 2moves_v1 anyway? Maybe we can convert it so it is the same as 8moves_v3 with move sequence instead of FEN?

**Comment by vondele** [comment]
No idea of the source for 2moves_v1. There is plenty of discussion in the forum. An easy solution would be to truncate 8moves_v3 to 2moves_v2 ;-)

**Comment by Stefano80** [comment]
Hi @tomtor , this is a cool project! Now I am again on board, can you maybe give me some update on how I can help you?

**Comment by tomtor** [comment]
@Stefano80 I think the code is complete as it is. and has received quit a lot of testing already, by me and @ppigazzini. Changing the PGN (like requested by @candirufish) would require changing cutechess-cli which is outside the scope of this PR. Other changes (Viewer, JSON output?) should have a separate PR.

We could merge this with a 65 worker version number now and leave the required server version still at 63, because older workers would work just fine, except that they will not upload a PGN.

Not sure when we want to force a worker update, because there are still a lot of workers at version 63, and we don't now how they will react to some manual update actions. Slowly these workers will be updated by new installs, so we could wait a few months?

**Comment by ppigazzini** [comment]
@Stefano80 dev-server and workers updated so you can experiment the PR.
@tomtor the production server has 34 GB free hard disk space
@candirufish @vondele check the @ianfab [bookgen repo](https://github.com/ianfab/bookgen). The [bookgen wiki](https://github.com/ianfab/bookgen/wiki/Examples) has also the reference to the forum post regarding 2moves_v1 book that inspired bookgen.

**Comment by vondele** [comment]
hmm ~30Gb will be filled in ~1 week at peak games production. Even just LTC games will fill that in a couple of weeks.

**Comment by tomtor** [comment]
Yes, 30Gb makes little sense... Would have to purge every week.

**Comment by noobpwnftw** [comment]
My suggestions:
Storing too detailed game data is not very useful, because it is evaluated too fast per move even at LTC, and too many duplicated positions will appear, instead, you can try to store [position+move]->[win_count,draw_count,lose_count,score] information, then you can get at least some overall information about also maybe create a good book(eventually I ditched all counts and re-calculate score).
With proper implementation of storage, you may hold a couple billion unique positions' information in this manner with 30GB. That's more useful than having individual games, which nobody would ever go through them all.

**Comment by tomtor** [comment]
I could modify the purge script to move the PGN to the fishtest S3 bucket, but perhaps that is better for a later PR. It is not clear who pays for that bucket, @glinscott ?
I would prefer to simply leave them in MongoDb and have a bit more storage space.
For now it's probably best to gain some experience with uploaded PGNs first and purge after 10 days. 
@ppigazzini Have you tried creating the index? The existing script in util/ should pick it up.

**Comment by vondele** [comment]
I also think we should keep it simple for now, and if needed purge quickly... I'd guess the first 24h after a test has been run would be most relevant. But being so close to out-of-space, I think this needs some regular monitoring as well.

**Comment by tomtor** [comment]
Probably it is best to have fishtest just store PGNs for a short time and registered users download the URLs of stored games with a REST api. This api would accept an optional batch offset and return batches of 100 URLs. One could repeat calling this api until URLs are returned which are already stored by the caller in its local database. This would allow replicating the PGN database with a simple script which runs eg every hour.

**Comment by ppigazzini** [comment]
dev server and workers updated.

@tomtor I think that the S3 space is paid by @glinscott.
Increasing the DB size should have these side effects:
  1. slowdown of the hourly backup process (`mongodump && tar && s3put`)
  2. raise in S3 space used for backup

Output of `index_pending.py` with the index creation commented out: 

```
Current Indexes:
{u'_id_': {u'key': [(u'_id', 1)], u'ns': u'fishtest_new.runs', u'v': 2},
 u'args.username_1': {u'background': True,
                      u'expireAfterSeconds': 86400,
                      u'key': [(u'args.username', 1)],
                      u'ns': u'fishtest_new.runs',
                      u'v': 2},
 u'deleted_1': {u'background': True,
                u'expireAfterSeconds': 86400,
                u'key': [(u'deleted', 1)],
                u'ns': u'fishtest_new.runs',
                u'v': 2},
 u'deleted_1_finished_1': {u'background': True,
                           u'expireAfterSeconds': 86400,
                           u'key': [(u'deleted', 1), (u'finished', 1)],
                           u'ns': u'fishtest_new.runs',
                           u'v': 2},
 u'finished_1_last_updated_-1': {u'key': [(u'finished', 1),
                                          (u'last_updated', -1)],
                                 u'ns': u'fishtest_new.runs',
                                 u'v': 2},
 u'finished_1_last_updated_-1_start_time_-1': {u'background': True,
                                               u'expireAfterSeconds': 86400,
                                               u'key': [(u'finished', 1),
                                                        (u'last_updated',
                                                         -1),
                                                        (u'start_time', -1)],
                                               u'ns': u'fishtest_new.runs',
                                               u'v': 2},
 u'last_updated_-1_start_time_-1': {u'background': True,
                                    u'expireAfterSeconds': 86400,
                                    u'key': [(u'last_updated', -1),
                                             (u'start_time', -1)],
                                    u'ns': u'fishtest_new.runs',
                                    u'v': 2},
 u'tasks.pending_1': {u'key': [(u'tasks.pending', 1)],
                      u'ns': u'fishtest_new.runs',
                      u'v': 2}}
```

**Comment by tomtor** [comment]
@ppigazzini Which PR is/are running on the dev server now?

http://94.198.98.239/api/pgn_100/0

Gives a not found on the new API. Also no-sorting on the table-headers.

**Comment by ppigazzini** [comment]
@tomtor 
```
# add here the PR to be tested
git pull --no-edit origin pull/282/head
git pull --no-edit origin pull/294/head
git pull --no-edit origin pull/295/head
```
I will try a fresh DB reload, give me some minutes.

**Comment by tomtor** [comment]
@ppigazzini It is ok now. Thsnks!!!

**Comment by ppigazzini** [comment]
@tomtor dev-server, DB (and CentOS version) updated.

**Comment by tomtor** [comment]
@ppigazzini I see that when you restore the database the pgndb is untouched (has still all old data). That might be confusing because those run-ids do no longer exist.

**Comment by ppigazzini** [comment]
@tomtor `mongorestore --drop` perhaps drops only duplicated DBs. I dropped the DBs by hand, reloaded the production DB, applied the index, reloaded fishtest.

**Comment by tomtor** [comment]
Hi @ppigazzini. Something goes wrong with the PR merge process when combining PRs on the dev server. It not DB related,  the DB is fine. The change 3b84e9b is not running now on the dev server. It's a one line change, could you please check the rundb.py file to see if the file has this change? If it has the change then it is related to not running "python setup.py install --user" after the merge. Anyway, the same happened yesterday with the sort-table headers not being visible until a complete reinstall.

**Comment by ppigazzini** [comment]
@tomtor the change https://github.com/glinscott/fishtest/commit/3b84e9beccfb5c193dd0ebc8d7b5c96deaf6ced5 is applied, here is the  `rundb.py`
```
  def get_pgn_100(self, skip):
    return [p['run_id'] for p in self.pgndb.find(skip=skip, limit=100, sort=[('_id',DESCENDING)])]
```

**Comment by tomtor** [comment]
@ppigazzini Ok, thanks for checking, but it is really not running. Are you sure you executed:

    python setup.py develop --user

before restarting, as described in your own guide:

    https://github.com/glinscott/fishtest/wiki/Fishtest-server-setup

Without rerunning setup.py the new files are ignored, because pserve will use the previously installed files.

**Comment by tomtor** [comment]
@ppigazzini Dev server returns oldest first (lowest batch first) on http://94.198.98.239/api/pgn_100/0

["5afae1b5e44b06107f7c9064-1", "5afae1cae44b06107f7c9066-0", "5afae1b5e44b06107f7c9064-0", "5afae1cae44b06107f7c9066-1", "5afae1cae44b06107f7c9066-2", "5afae1b5e44b06107f7c9064-2", "5afae1b5e44b06107f7c9064-3", "5afae1cae44b06107f7c9066-3", "5afae1b5e44b06107f7c9064-4", "5afae1b5e44b06107f7c9064-5", "5afae1cae44b06107f7c9066-4", "5afae1cae44b06107f7c9066-5", "5afae1cae44b06107f7c9066-6", "5afae1b5e44b06107f7c9064-6", "5afae1b5e44b06107f7c9064-7", "5afae1b5e44b06107f7c9064-8", "5afae1cae44b06107f7c9066-7", 

My test server http://fishtest.v7f.eu/api/pgn_100/0 returns newest first:

["5aedd0befb52a22ff26fafe1-64", "5aedd0befb52a22ff26fafe1-63", "5aedd0befb52a22ff26fafe1-61", "5aedd0befb52a22ff26fafe1-60", "5aedd0befb52a22ff26fafe1-60", "5aedd0befb52a22ff26fafe1-59", "5aedd0befb52a22ff26fafe1-58", "5aedd0befb52a22ff26fafe1-58", "5aedd0befb52a22ff26fafe1-57", "5aedd0befb52a22ff26fafe1-56", "5aedd0befb52a22ff26fafe1-55", "5aedd0befb52a22ff26fafe1-54", "5aedd0befb52a22ff26fafe1-53", "5aedd0befb52a22ff26fafe1-52", "5aedd0befb52a22ff26fafe1-51", "5aedd0befb52a22ff26fafe1-50"]

What happens when you change the text in eg:

https://github.com/glinscott/fishtest/blob/fab0fe8996d0d731bad2a3da484cf497823cb041/fishtest/fishtest/templates/base.mak#L34

from Tests to TESTS?

**Comment by ppigazzini** [comment]
@tomtor done.

**Comment by ppigazzini** [comment]
@tomtor dev server specifications
```
CentOS Linux release 7.5.1804 (Core)
MongoDB server version: 3.6.4
Python 2.7.5 (default, Apr 11 2018, 07:36:10)

$ pip list
backports.ssl-match-hostname (3.5.0.1)
boto (2.48.0)
certifi (2018.1.18)
chardet (3.0.4)
configobj (4.7.2)
decorator (3.4.0)
fishtest-server (0.1, /home/fishtest/fishtest/fishtest)
hupper (1.0)
idna (2.6)
iniparse (0.4)
ipaddress (1.0.16)
Mako (1.0.7)
MarkupSafe (1.0)
nose (1.3.7)
numpy (1.7.1)
PasteDeploy (1.5.2)
perf (0.1)
pip (8.1.2)
plaster (1.0)
plaster-pastedeploy (0.4.2)
psutil (5.4.3)
pycurl (7.19.0)
Pygments (2.2.0)
pygobject (3.22.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pymongo (3.6.1)
pyramid (1.9.1)
pyramid-debugtoolbar (4.4)
pyramid-mako (1.0.2)
python-linux-procfs (0.4.9)
pyudev (0.15)
pyxattr (0.5.1)
pyzmq (14.3.1)
repoze.lru (0.7)
requests (2.18.4)
schedutils (0.4)
scipy (0.12.1)
setuptools (38.6.0)
six (1.9.0)
slip (0.4.0)
slip.dbus (0.4.0)
translationstring (1.3)
urlgrabber (3.10)
urllib3 (1.22)
venusian (1.1.0)
waitress (1.1.0)
WebOb (1.8.0rc1)
wheel (0.30.0)
yum-metadata-parser (1.1.4)
zope.deprecation (4.3.0)
zope.interface (4.4.3)
```

**Comment by tomtor** [comment]
@ppigazzini http://94.198.98.239/tests still shows TESTS (upper left) instead of MYTESTS?

**Comment by tomtor** [comment]
@ppigazzini And now its OK and http://94.198.98.239/api/pgn_100/0 also works!

**Comment by ppigazzini** [comment]
@tomtor my fault, I wrote start instead of restart.

**Comment by tomtor** [comment]
@ppigazzini Ok, problem/riddle solved! Thanks

**Comment by tomtor** [comment]
I just synced the dev-server database and update it twice:

    tom@swan:~/src/fishserver/fishtest$ python3 utils/clone_fish.py
    5afae1cae44b06107f7c9066-801
    5afae1cae44b06107f7c9066-798
    Already copied: 5afae1cae44b06107f7c9066-798
    Copied:       1 PGN files (~      250 games)
    Database:   828 PGN files (~   207000 games)
    Database:     2 runs

So that works nicely. This means that anyone can build a clone of the fishtest PGN database collection (including all run data except the task-list) by running the script eg every 15 minutes. Copy speed is about 100 tasks/minute, which translates to a few average fishtest runs each minute.

I'd say this is ready to be merged. I will run a copy script which only copies the LTC games and make them public on a Google drive.

**Comment by tomtor** [comment]
> You may create the PGN storage as capped collection, so it won't eat all free disk space.

That's a good suggestion! Limiting it to 50000 would result in about 10 gigabyte storage max.

**Comment by Stefano80** [comment]
Hi, I am trying to understand how I can experiment with the PR. At the moment, if I get it right, this is running on the dev server. Where are the changes? We are only creating an API for the DB at the moment right?

**Comment by ppigazzini** [comment]
@Stefano80 dev-server, workers and DB updated to run the PRs #282 #298

**Comment by tomtor** [comment]
@Stefano80 You have a PGN download link at the left for each completed task

http://94.198.98.239/tests/view/5b00731ce44b060509c7f0e0

**Comment by Stefano80** [comment]
Ahhh, I see, it is not possible to download them all at once?

**Comment by tomtor** [comment]
@Stefano80 https://github.com/glinscott/fishtest/pull/282/files#diff-aad3c9655043cf184559a80252415775

will download all and store them in a local mongodb

**Comment by ppigazzini** [comment]
@tomtor no. To try to solve the problem yesterday night I loaded a fresh copy of the DB, cloned git and the PR, rebooted the VM. Also the production server is a bit slow.

**Comment by ppigazzini** [comment]
@tomtor I will load only the #298 to view if this solve the slowness.

**Comment by tomtor** [comment]
@Stefano80 Regarding access to all PGNs. I will also save and publish all played LTC PGNs on a Google drive for easy access and as archive, as soon as this PR is live.

**Comment by ppigazzini** [comment]
@tomtor mmm, dev-server always slow and no tests running.

I reloaded a fresh copy of the DB with:
```
mongo fishtest         --eval 'db.dropDatabase()'
mongo fishtest_new     --eval 'db.dropDatabase()'
mongo fishtest_testing --eval 'db.dropDatabase()'
mongorestore --drop
```

and cloned the repo with the #298: 
```
git clone https://github.com/glinscott/fishtest.git

cd fishtest
git config --global user.email "you@example.com"
git config --global user.name "Your Name"

# add here the PR to be tested
#git pull --no-edit origin pull/282/head
git pull --no-edit origin pull/298/head
```

I will try to revert #295

**Comment by snicolet** [comment]
I haven't looked at the new client code for the PGN stuff, but do we transfer the PGN file after each game or at the end of the 250 games batch? 

I think transferring at the end of the 250 games batch would be by far good enough.

**Comment by ppigazzini** [comment]
@tomtor I reverted to c80a904, to me the server answers always slow but I could be biased now
```
git log --oneline
d334d9c Merge commit 'refs/pull/43/head' of https://github.com/glinscott/fishtes
c80a904 Fix race on task['pending']
10e6f22 Drop /bin/zsh and use /bin/sh
f7b08f2 Fix error for stop/delete when not logged in
282a136 Flush pserve buffered output
```

**Comment by tomtor** [comment]
@ppigazzini The dev-server became slow yesterday evening, without any change. It looks normal now, but I am pretty sure it is not related to any PR in particular. Perhaps a lot of traffic due to a bot visiting? We should have a way to monitor HTTP-requests, but it's not clear to me how to do that with pserv. A simple apache or nginx frontend would help here. Perhaps a good idea to implement that at the dev-server?

**Comment by ppigazzini** [comment]
@tomtor dev-server and workers updated with PRs #282 #298. DB fresh clone, executed ` python index_pending.py`

About nginx I found [this tutorial](https://medium.com/@cgroom/the-startup-ctos-guide-to-ops-3-of-3-a-minimal-production-and-deployment-setup-a10dccc04f51). The problem is that setting a proxy on the dev-server (with CentOS 7.5) is not so useful for the production server ( CentOS 6.9). So today I will prefer to try to setup a working fishtest dev-server on CentOS 6.9.

**Comment by ppigazzini** [comment]
@tomtor I lost my ssh connections with the dev-server, my ISP provider is unreachable...

**Comment by ppigazzini** [comment]
@tomtor connection reestablished, the dev-server seems running fine. I think that my ISP Seflow had some problems in the last hours.

**Comment by Stefano80** [comment]
OK, thank you! This is surely enough for me!

**Comment by tomtor** [comment]
@ppigazzini I created a DNS entry for the dev-server: http://fishdev.v7f.eu/tests

This will allow using a certificate for HTTPS

**Comment by ppigazzini** [comment]
@Stefano80 @tomtor I propose a worker update this night: candidates PRs #275 #282 #298 #300

**Comment by tomtor** [comment]
> I propose a worker update this night: candidates PRs #275 #282 #298 #300

That's OK with me. I think we should still leave the server version at 63, because the number of workers still at the broken updater version 63 is quite large (and we will loose these workers when we force an update) and these changes should be backward compatible. Only downside now is that we will miss the uploads of PGN-games from all the workers that have not updated. I and probably @noobpwnftw will update the workers by hand. I mailed the most important version 63 users myself about a week ago, but there was no response from them. So either they don't read the mail address they signed up with or they don't care. 

So I propose that we merge now (worker: 65, server: 63) and that we bump the server version to 65 a few days after an announcement on the forum.

I mailed this to the version 63 workers:

>**fishtest Worker version 63 update**

>I see that many of your (the same applies to many other users) workers are still running version 63.
Version 63 has a bug that prevents updating to higher versions, when requested to do so by the server.
To fix that you have various options. The most easy one is to simply add

>`import requests`

>to the top of the file `updater.py` or download this file from: https://raw.githubusercontent.com/glinscott/fishtest/master/worker/updater.py

>With that change the update will happen at a later time when the server raises the minimal required version number.

>If you downloaded from github.com you can also download (or git pull) the most recent version, so that you start running version 64 today.

**Comment by ppigazzini** [comment]
@tomtor I merged the PRs #275 #298 #300 #308. The last one raised the worker version to 65 to have the code base in a working state and to pinpoint the workers updated with git. Feel free to raise the worker version to 66 with this PR.

**Comment by tomtor** [comment]
@ppigazzini Thanks for all the merging! I updated my 2 workers to the latest master (worker 65) and this PR to 66.

**Comment by ppigazzini** [comment]
@tomtor dev-server and workers updated for a fast test.

**Comment by Stefano80** [comment]
Hi, I am just back. I tried to download some pgn from the test server, but I got a 404. The test I was using is http://94.198.98.239/tests/view/5b07d1a2e44b06041f3999cd

Is it supposed to be so because we do not actually store the pgn from the test server or it is something else?

**Comment by tomtor** [comment]
@Stefano80 had it allready played 250 games?

**Comment by ppigazzini** [comment]
I'm commuting now, at 22.00 CEST I will be able to load a clean db on the dev-server.

**Comment by Stefano80** [comment]
I tried another one with 250 games and it does not work too.

**Comment by tomtor** [comment]
What is the download URL? Which task?

**Comment by tomtor** [comment]
Ah, I know what is wrong, I showed the download link for worker > 64, but now the PGN worker has version 66. See last commit.

**Comment by ppigazzini** [comment]
@tomtor dev-serv and workers updated.

**Comment by ppigazzini** [comment]
Production server updated, finger crossed :)
Thank you @tomtor

**Comment by noobpwnftw** [comment]
Workers updated, looks fine.

**Comment by ppigazzini** [comment]
@noobpwnftw Perfect! You can ran the worker also with python3.

**Comment by tomtor** [comment]
@ppigazzini It looks to be running smoothly so I made a small wiki entry: 

https://github.com/glinscott/fishtest/wiki/PGN-files-of-games-played-on-fishtest

I assume you have added `fishtest/utils/purge_pgn.py` to the server crontab to run eg once a day?
Did you use it as is (default 8 days STC, 160 days LTC)? I am also curious how fast the purge script runs...

**Comment by ppigazzini** [comment]
@tomtor scheduled to run at 4:36 (CET) every day, here are the running times of the scheduled scripts:
```
$ time  ~/fishtest/fishtest/utils/purge_pgn.py
PGN runs/tasks saved:   1227/  11226
PGN runs/tasks purged: 21011/      0

real    4m45.726s
user    2m33.225s
sys     0m28.069s
```

```
$ time ~/fishtest/fishtest/utils/backup.sh

real    4m31.322s
user    2m33.169s
sys     0m47.124s
```

```
$ time ~/fishtest/fishtest/utils/scavenge.py

real    0m1.306s
user    0m0.360s
sys     0m0.054s
```

```
$ time  ~/fishtest/fishtest/utils/update_users.py
Successfully updated 1186 users

real    1m44.527s
user    0m56.710s
sys     0m0.872s
```

**Comment by tomtor** [comment]
@ppigazzini Thanks! The purge script runs under 5 minutes. That is not bad. About as fast as backup.sh which makes sense because it reads all runs.

**Pull request merged**
