### PR TITLE
Remove tasks from run data in actions

### LINKED ISSUE #710: Optimize action storage
I wondered why MongoDb actions database is so big. The reason is that it stores a copy of the complete run with all empty task slots included. 

We should remove all the task slots to safe space.

Needs a change of the fishtest code and a script to adapt the current database. This will significantly shrink the database.

### PR DESCRIPTION
**Pull request by tomtor**
to save a LOT of space

Should fix #710

### CODE REVIEW

**Comment by tomtor** [comment]
@ppigazzini Could you please run `utils/compact_actions.py` at a convenient time on TEST and measure the reduction in the storage size?

**Comment by ppigazzini** [comment]
@tomtor DEV updated with the PR and a fresh DB copy.

* before running `utils/compact_actions.py`
```
$ df
Filesystem        1K-blocks     Used Available Use% Mounted on
/dev/ploop18047p1 257896900 34592556 212697776  14% /

db.actions.stats()
{
        "ns" : "fishtest_new.actions",
        "size" : 15572247778,
        "count" : 237236,
        "avgObjSize" : 65640,
        "storageSize" : 2109833216,
        "capped" : false,
```

* after running `utils/compact_actions.py`
```
df
Filesystem        1K-blocks     Used Available Use% Mounted on
/dev/ploop18047p1 257896900 34674776 212615556  15% /

db.actions.stats()
{
        "ns" : "fishtest_new.actions",
        "size" : 1122534243,
        "count" : 237238,
        "avgObjSize" : 4731,
        "storageSize" : 2192269312,
        "capped" : false,
```

* after running `db.runCommand({compact:'actions'})`
```
df
Filesystem        1K-blocks     Used Available Use% Mounted on
/dev/ploop18047p1 257896900 33216596 214073736  14% /

db.actions.stats()
{
        "ns" : "fishtest_new.actions",
        "size" : 1122534243,
        "count" : 237238,
        "avgObjSize" : 4731,
        "storageSize" : 699035648,
        "capped" : false,
```

**Comment by tomtor** [comment]
@ppigazzini Thanks for running this!

So size is from 15 GB to 1.1 GB, but storageSize just from 2.1 GB to 0.7 GB

It could be that storage is allocated in chunks and avgObjSize is just over 4k (4096)

Any way, it is a nice improvement.

I could reduce it more, by just storing the name and id for all actions except "modify run", but that requires more code changes.
Perhaps at a later time.

**Comment by ppigazzini** [comment]
@tomtor `utils/compact_actions.py` took 20 minutes to run on DEV. Should we put off line fishtest on PROD?

**Comment by tomtor** [comment]
Only `db.runCommand({compact:'actions'})` need to be run offline?

The `compact_actions.py` may be run online, that should do no harm, except for a slow down while running.

Is DEV currently running this PR? Must I test some (all) actions to see if they (all) still work or have you done that?

**Comment by tomtor** [comment]
The correct order is to merge the PR first (so new entries are compact)  and run `compact_actions.py` later (to compact old entries)

**Comment by ppigazzini** [comment]
@tomtor I reset DEV with this PR and a fresh copy of the PROD DB. Now I will run the scripts keeping the execution times.

**Comment by ppigazzini** [comment]
@tomtor I tested successfully on DEV several actions, please double check at your convenience.

**Comment by tomtor** [comment]
Did some more testing, looks good to me! Please merge and run scripts at PROD at a convenient time.

**Comment by ppigazzini** [comment]
PROD updated and scripts ran, thank you @tomtor :)

```
db.actions.stats()
{
        "ns" : "fishtest_new.actions",
        "size" : 1123578071,
        "count" : 238025,
        "avgObjSize" : 4720,
        "storageSize" : 643469312,
        "capped" : false,
```

**Pull request merged**
