### PR TITLE
Make notifications clickable.

### PR DESCRIPTION
**Pull request by vdbergh**
Not tested with native notifications.

### CODE REVIEW

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated thank you @vdbergh :)

**Comment by vdbergh** [comment]
This PR is not quite right. We still need the focus call at onclick before loading the test page. And I guess it is best to load the test page in a new tab (`taget=_blank`), rather than overwriting a random page.

**Comment by dav1312** [comment]
> @dav1312 Would that also give focus to the browser?

I tested it pasting this in the devtools inside Fishtest and it did so I guess it works
```js
function notify(title = "title", body = "body", link = "/tests/view/63bc1f35cd3db0c8d39a3016") {
  if (Notification.permission === "granted") {
    const notification = new Notification(title, {
      body: body,
      requireInteraction: true,
      icon: "https://tests.stockfishchess.org/img/stockfish.png",
    });
    notification.onclick = () => {
      window.open(link, "_blank");
    };
  }
}

setTimeout(notify, 5000);
```

**Comment by vdbergh** [comment]
> > @dav1312 Would that also give focus to the browser?
> 
> I tested it pasting this in the devtools inside Fishtest and it did so I guess it works
> 
> ```js
> function notify(title = "title", body = "body", link = "/tests/view/63bc1f35cd3db0c8d39a3016") {
>   if (Notification.permission === "granted") {
>     const notification = new Notification(title, {
>       body: body,
>       requireInteraction: true,
>       icon: "https://tests.stockfishchess.org/img/stockfish.png",
>     });
>     notification.onclick = () => {
>       window.open(link, "_blank");
>     };
>   }
> }
> 
> setTimeout(notify, 5000);
> ```

That sounds like next level hacking to me :smile: But thanks for checking!

**Pull request merged**
