### PR TITLE
Speed up request_task logic

### PR DESCRIPTION
**Pull request by tomtor**
by replacing the get_machines() MongoDb query with some Python code.

This is not critical but will reduce the request_task API time from about 700ms to probably < 200ms.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor I will run the PR on the [dev server](http://94.198.98.239/tests) for a couple of hours to check for problems.

**Comment by tomtor** [comment]
@ppigazzini Thanks, that would allow us to test the speedup. Please let me know when it is in place.

**Comment by ppigazzini** [comment]
@tomtor the test on the dev server is already running from 30 minutes
```
top - 12:51:29 up 19:47,  2 users,  load average: 0.00, 0.01, 0.05
Tasks: 141 total,   1 running, 140 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.2 sy,  0.5 ni, 98.7 id,  0.4 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  4044204 total,  1113936 free,  1437600 used,  1492668 buff/cache
KiB Swap:  8388604 total,  8388560 free,       44 used.  2358532 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 3358 fishtest  25   5 1955352 257796   9728 S   2.3  6.4   0:49.75 pserve
  991 mongod    20   0 2051860 1.027g   8300 S   0.7 26.6   3:27.56 mongod
 1350 root       0 -20       0      0      0 S   0.3  0.0   0:00.36 kworker/3:+
    1 root      20   0   43228   3344   2160 S   0.0  0.1   0:04.12 systemd
```

**Comment by tomtor** [comment]
@ppigazzini Ok, response is from about 700ms to 160ms when it is not the first request in the last minute. Speed up strongly depends on number of running tasks, so on the dev server we mainly can spot errors.

What is changed is the computation of nr of active workers and resuming on interrupted task, I tested this locally.

**Comment by ppigazzini** [comment]
@tomtor official server updated and restarted

**Comment by ppigazzini** [comment]
@tomtor [tune_imbalance3 @ 1+0.05](http://tests.stockfishchess.org/tests/view/5ab4f8790ebc590295d8841d) (limited to 10 workers). The workers seems keep the connection, low CPU load.
There is also your 3 cores worker. 

```
top - 14:25:53 up 59 min,  1 user,  load average: 0.70, 0.92, 0.70
Tasks:  21 total,   2 running,  19 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.0%us,  1.1%sy, 13.1%ni, 85.8%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   3145728k total,  2848648k used,   297080k free,        0k buffers
Swap:        0k total,        0k used,        0k free,  1395824k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
  661 fishtest  25   5 2465m 1.2g 3604 R 38.6 41.3  13:32.48 python
  633 fishtest  25   5 12.7g 307m 209m S  4.7 10.0  11:54.30 mongod
 1447 fishtest  20   0 14892 1088  856 R  0.3  0.0   0:00.99 top
    1 root      20   0 19232 1080  840 S  0.0  0.0   0:00.00 init
```

**Pull request merged**
