### PR TITLE
Catch error in case of no browser support

### PR DESCRIPTION
**Pull request by dav1312**
Use a try catch because some old safari versions might not support this

Closes https://github.com/glinscott/fishtest/issues/1412

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated with #1434, #1433, #1425

**Comment by ppigazzini** [comment]
DEV updated (I don't know if there was a change with the last push).
Let me know when this is ready to be merged.

**Comment by ppigazzini** [comment]
PROD updated, thank you @dav1312 :)

**Comment by dav1312** [comment]
> DEV updated (I don't know if there was a change with the last push). Let me know when this is ready to be merged.

Didn't read this on time but no, I just changed the commit message

**Comment by ppigazzini** [comment]
I checked the previous version on DEV :)

**Comment by snicolet** [comment]
thanks everybody :-)

**Pull request merged**
