### PR TITLE
Save diffs in sessionStorage

### PR DESCRIPTION
**Pull request by dav1312**
Draft in case someone wants to make suggestions and because it has debug code

### CODE REVIEW

**Comment by peregrineshahin** [comment]
I don't think saving the diff in local storage is going to be a good practice, as some may find saving a whole block of code inside their browser storage does feel a bit malicious

**Comment by dav1312** [comment]
> saving a whole block of code inside their browser storage does feel a bit malicious

I think that if the user is knowledgeable enough to even check its localStorage it shouldn't have a hard time understanding what the contents are or just checking the source code

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by peregrineshahin** [comment]
If you insist on the idea, I suggest that you minimize the save to only the session storage and not the local storage, because in real situation, refreshes are made during the same session, and deleting those when user exist browser would make more sense

**Comment by ppigazzini** [comment]
Some thoughts:
- it's more dangerous running the code on the worker than saving a code diff in the browser cache. The browser load already that code diff
- a caching of the diff should not done on the server: the diff could be big (16 MB max size for a MongoDB document), delay downloading the data from PROD, PROD could hit the GH API rate etc

**Comment by peregrineshahin** [comment]
Thoughts:

I picked a random diff size calculating the difference by this script one before saving any diff and another time after saving one:
using this script:
```
 let limit = 1024 * 1024 * 5; // 5 MB
 let remSpace = limit - unescape(encodeURIComponent(JSON.stringify(sessionStorage))).length;
 remSpace ``` in chrome 
 
 The Session size limit per domain in chrome is 5 MB = 5242880
 one random diff size = 5242880 - 5241359 = 1521 B
 How many diffs should be stored before the browser stops saving and hits and error (no overwriting) =
           5242880 / 1521 ≈ 3447 diffs
  
 therefore this amount of diffs is practically impossible to fetch by a sane user, so I think it is a safe solution minding that the code saved is publicly available and is not sensitive and open source,
 performance wise it's surprisingly blazingly fast, LGTM

**Comment by dav1312** [comment]
> 5242880 / 1521 ≈ 3447 diffs

Actually, if the user is _really_ stubborn is not hard to ran out of sessionStorage space
Regression tests have pretty big diffs (200-300kB), it would fill with less than 20 tests

**Comment by ppigazzini** [comment]
```
ls -lah big_diff_00*
-rw-r--r-- 1 usr00 usr00 1.4M Aug  5 13:15 big_diff_000.txt
-rw-r--r-- 1 usr00 usr00 4.1M Aug  5 13:14 big_diff_001.txt
-rw-r--r-- 1 usr00 usr00 7.5M Aug  5 13:20 big_diff_002.txt
```
https://dfts-0.pigazzini.it/tests/view/62ecf2b5921046e23f7fc1ac
https://dfts-0.pigazzini.it/tests/view/62ecf9f7921046e23f7fc1ae
https://dfts-0.pigazzini.it/tests/view/62ecfc44921046e23f7fc1b0

Master has no problem loading the diff for any tests, the PR only if there is space left in SessionStorage, otherwise we get this error:
```
62ecfc44921046e23f7fc1b0:631 Fetching diff
62ecfc44921046e23f7fc1b0:661 Uncaught (in promise) DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of '62ecfc44921046e23f7fc1b0' exceeded the quota.
    at showDiff (https://dfts-0.pigazzini.it/tests/view/62ecfc44921046e23f7fc1b0:661:22)
    at https://dfts-0.pigazzini.it/tests/view/62ecfc44921046e23f7fc1b0:649:11
showDiff @ 62ecfc44921046e23f7fc1b0:661
(anonymous) @ 62ecfc44921046e23f7fc1b0:649
Promise.then (async)
fetchDiff @ 62ecfc44921046e23f7fc1b0:647
(anonymous) @ 62ecfc44921046e23f7fc1b0:632
```

I'm wondering if we can deal with this exception (I don't know JS).

BTW there is a library to compress text in storage with a nice demo page to test size and time for LZ-String and LZMA-JS (but the original text size seems to be doubled...):
https://pieroxy.net/blog/pages/lz-string/index.html
https://pieroxy.net/blog/pages/lz-string/demo.html

- big_diff_000.txt:

image

- big_diff_001.txt:

image

- big_diff_002.txt:

image

**Comment by ppigazzini** [comment]
DEV updated, LGTM :)

**Comment by ppigazzini** [comment]
DEV updated, I will review after a fast lunch.

**Review by ppigazzini — APPROVED** [review]
Looks good to me, tested on Firefox, Chrome, Edge, Opera, Chrome mobile, Edge mobile.

Checked github api rate usage with https://api.github.com/rate_limit

**Comment by ppigazzini** [comment]
PROD updated, thank you @dav1312 :)

**Comment by ppigazzini** [comment]
BTW with previous master any F5 consumed 2 github api calls, so this PR should be a life changer for some users.

**Comment by peregrineshahin** [comment]
So I tried using the library @ppigazzini referenced above and it does a great job compressing the diff text, but I don't know about how malicious the text looks in session storage though

should do we it?
Capture

**Comment by ppigazzini** [comment]
I do like to post in the PR/Issue some links than can be useful right now or for future improvements.
IMO at the moment the sessionStorage is fine as in master, that library could be useful if we start saving other info in sessionStorage.

**Pull request merged**
