### PR TITLE
Record server shutdown and restart as system events in the event log.

### PR DESCRIPTION
**Pull request by vdbergh**
Also: retire the update_stats event and replace it with the more generic system_event.

### CODE REVIEW

**Comment by vdbergh** [comment]
CI fails. This is because the bench test does a github api call and it likely hits the ratelimit.

**Comment by ppigazzini** [comment]
> CI fails. This is because the bench test does a github api call and it likely hits the ratelimit.

Testing the github token
https://github.com/glinscott/fishtest/commit/1cfb4317b37dc22411e368b9d6177e5a0f89ec9b

**Comment by vdbergh** [comment]
The documentation says that the GITHUB_TOKEN is only valid for the workflow repo.

**Comment by vdbergh** [comment]
Unless I misunderstand and you were using a token of your own somehow (I don't really understand how secrets work).

**Comment by ppigazzini** [comment]
I simply forgot that that "should" work (with the macos runner didn't worked) only for the workflow repo.

**Comment by ppigazzini** [comment]
DEV updated, LGTM.
Tested with:
```
sudo reboot
sudo systemctl restart fishtest@{6543..6544}
sudo systemctl restart fishtest@6543
sudo systemctl restart fishtest@6544
sudo systemctl stop fishtest@{6543..6544}
sudo systemctl start fishtest@{6543..6544}
sudo systemctl stop fishtest@6543
sudo systemctl start fishtest@6543
${VENV}/bin/python3 fishtest/server/utils/delta_update_users.py
```

**Comment by vdbergh** [comment]
Looking at the messages, it seems it would be useful to include the port number in the message.

**Comment by vdbergh** [comment]
Hmm this seems to be not so obvious. The pyramid application does not seem to know the port it is listening on. The only way I see is to parse the command line via `sys.argv`.

**Comment by vdbergh** [comment]
Ok I did it via parsing of the command line (until a better method is found to get the port number).

**Comment by ppigazzini** [comment]
DEV updated, LGTM, I'm away from the keyboard right now, not able to search for a better way for the port. I wonder why 6542 as default.

**Comment by vdbergh** [comment]
6542 is what is contained in development.ini. I think a more robust way is to parse the config file using the command line arguments (assuming the config file is a regular ini file).

**Comment by vdbergh** [comment]
Ok I am now parsing the config file. This should be robust.

**Comment by vdbergh** [comment]
Still a small bug. If we instantiate `Rundb` directly (e.g. in `delta_update_users()` or in CI ) there should be no event log messages.

**Comment by vdbergh** [comment]
Fixed.

**Comment by ppigazzini** [comment]
DEV updated. It look very good to me.
Nit-picking. What about using the same command name from `systemctl` (ie `stop` and `start`)?

**Comment by vdbergh** [comment]
> DEV updated. It look very good to me. Nit-picking. What about using the same command name from `systemctl` (ie `stop` and `start`)?

Fine for me! I will change it. I think the order of the arguments is also the opposite (i.e. start fishtest:6542).

**Comment by ppigazzini** [comment]
Yes `<sytemd_unit_file>@<parameter>`
```
sudo systemctl start fishtest@6543
sudo systemctl start fishtest@{6543..6544}
# this is the development/debug systemd unit file
sudo systemctl start fishtest_dbg
```

**Comment by vdbergh** [comment]
Done. Now the systemd syntax is followed.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
