### PR TITLE
Automatic default theme

### PR DESCRIPTION
**Pull request by dav1312**
Set the default theme automatically based on the prefered color scheme

### CODE REVIEW

**Comment by ppigazzini** [comment]
Impressive the switch on the fly with Opera :)

image

**Comment by ppigazzini** [comment]
LGTM on the 4 major browsers, feel free to squash the commits.

**Comment by ppigazzini** [comment]
PROD updated, thank you @dav1312 :)

**Comment by ppigazzini** [comment]
@dav1312 If I'm not wrong the feature is working a bit randomly, I never saw a wrong theme loaded during the tests. Perhaps an interaction with #1406

**Comment by dav1312** [comment]
> @dav1312 If I'm not wrong the feature is working a bit randomly, I never saw a wrong theme loaded during the tests. Perhaps an interaction with #1406

I don't know... can you tell me step by step how to reproduce a "random" behaviour?
But if the PR was working fine up until that change then it's not really my fault Kappa

**Pull request merged**
