### PR TITLE
Use old mongodb method to drop users

### PR DESCRIPTION
**Pull request by tomtor**
This fixes scavenge.py for the current MongoDb software in production.

Followup for #246

### CODE REVIEW

**Comment by tomtor** [comment]
@ppigazzini I tested this, it still works on the newer MongoDb software, so you can test it on the dev server as well.

**Comment by ppigazzini** [comment]
It works fine on the dev-server, but it fails on the official server...

```
OscarAmono
edwardpeng91
juergen
bingodoc
Traceback (most recent call last):
  File "fishtest/fishtest/utils/scavenge.py", line 47, in <module>
    main()
  File "fishtest/fishtest/utils/scavenge.py", line 44, in main
    scavenge_users(scavenge=True)
  File "fishtest/fishtest/utils/scavenge.py", line 38, in scavenge_users
    print(u['username'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 8: ordinal not in range(128)

```

**Comment by tomtor** [comment]
@ppigazzini Some are already dropped, you can just comment (or remove) the print:

    #print(u['username'])

**Comment by ppigazzini** [comment]
@tomtor no error, please check if the users are dropped

**Comment by tomtor** [comment]
Yes, they are gone :grinning:

**Comment by ppigazzini** [comment]
@tomtor please open a new PR dropping the print

**Pull request merged**
