### PR TITLE
Minor NN Updates and fix test buttons

### LINKED ISSUE #704: Lost options when changing TC in the test creation page
Steps to reproduce:

1) open the following passed STC test, which correctly includes "Contempt=0" in the options for base and tested patch: https://tests.stockfishchess.org/tests/view/5ee7f27daae8aec816ab75db

2) click on "reschedule" : the options correctly include "Contempt=0" in the test creation page

3) click on "Long (LTC)": the page changes correctly the hash table settings, but clear all the other options. If the user doesn't notice and launch the test, then it is a surpise that the STC and the LTC tests do not use the same settings... https://tests.stockfishchess.org/tests/view/5ee84d41563bc7aa755ffb6d

Expected behavior: changing the time control should change the hash table size for the test, but leave all other options the same.

### PR DESCRIPTION
**Pull request by tomtor**
Minor updates to NN code:

- Align NN downloads right
- Monospace font for NN
- Smarter new test buttons

Should close #704 and #741

### CODE REVIEW

**Comment by vondele** [comment]
if easy... can we use a fixed font (monospaced) for the name of the net (or even table) ? I.e. so that all names are equally long.

**Comment by vondele** [comment]
BTW, after the merge, I plan to replace 'contempt=24' by 'Use NNUE=true'. If it is easier to remove 'contempt=24' now, this can be done as well.

**Comment by ppigazzini** [comment]
@tomtor DEV updated, IMO there is a bug:
 - `Use NNUE=true` is always added, also for normal test :(
Anyway:
 - `Hash` field is changed according the TC
 - other custom option are maintained

**Comment by vondele** [comment]
@ppigazzini this patch (including the options) would only be OK after a NNUE merge, where I would assume the normal testing would become 'Use NNUE=true' and only eval tests would use 'Use NNUE=false' (while regression tests would be mixed options).

**Comment by ppigazzini** [comment]
Ok, I added the "wip" label.

**Comment by ppigazzini** [comment]
@vondele I scheduled a test with:
- test `Hash=16 Use NNUE=true Contempt=666`
- base `Hash=16 Use NNUE=false Contempt=999`

Rescheduling and changing the TC I got:
 - `Hash=16 Use NNUE=true Use NNUE=false Contempt=999`

**Comment by vondele** [comment]
that would be wrong... options should be separate for base and test.

**Comment by tomtor** [comment]
> options should be separate for base and test.

They are...

I remove the default options which leaves the user options and prepend the new defaults options.

Only when the user entered "Use NNUE=false" then "Use NNUE" is twice in the resulting options, the user specified is last (valid).

I can remove "Use NNUE=[^ ]+" but this will always reset Use NNUE to true.

**Comment by vondele** [comment]
OK, thanks, there was a small edit to the comment that clarified they are separate. 

I don't know exactly how cutechess would deal with duplicated options, but normally it sends the options in alphabetical order, not the user specified order (see also https://github.com/cutechess/cutechess/issues/557). It is likely it would send `Use NNUE=true` last.

**Comment by tomtor** [comment]
I could also leave "Use NNUE=*" in the original and remove it from the prepended defaults, so only Hash is replaced.

**Comment by vondele** [comment]
Yes, only replacing Hash is right, I think.

**Comment by ppigazzini** [comment]
DEV updated, I confirm that change only the "Hash" value.
With old test is not added "Use NNUE="

I wait the squash to merge.

**Comment by vondele** [comment]
Also, merging only after NNUE gets merged in master please.

**Comment by ppigazzini** [comment]
I'm wondering if `Hash=16 Use NNUE=true` as default for a new SPSA test is the right option.

**Comment by vondele** [comment]
This will depend if the SPSA is tuning search or eval. So, I think it is fine like that.

**Comment by vondele** [comment]
@ppigazzini this can be merged when you think it is ready.

**Comment by ppigazzini** [comment]
PROD updated, thank you @tomtor :)

**Pull request merged**
