### PR TITLE
Unique_key from task + 2 fixes

### PR DESCRIPTION
**Pull request by tomtor**
A small optimization for #261 

In addition add a lock to get_worker_key() because it has a race condition.

Fix print issue introduced in #162

8a2da7b

### CODE REVIEW

**Comment by tomtor** [comment]
@ppigazzini Hmm, i just fixed the server unit test, but now the worker test fails. Looks like a temporary error to me....

**Comment by Stefano80** [comment]
Hi Tom, you can always check the tests locally using the shell script on root. Do they pass locally?

**Comment by ppigazzini** [comment]
Travis worked at the second restart by hand, sometimes it happens.
dev-serv and workers updated.

**Comment by ppigazzini** [comment]
dev-serv and workers updated after https://github.com/glinscott/fishtest/pull/269/commits/323e51f22f9a990c35d7305fbd6db74f4928daca

**Comment by tomtor** [comment]
@ppigazzini Thanks, I added another minor change and travis runs fine now.
Could you please refresh the dev-server again? Sorry for the overhead.

**Comment by tomtor** [comment]
@Stefano80 Yes, I always test locally worker/server combo to see if the fix looks good, but I sometimes forget to run/change the unit tests after a change :-/

**Comment by ppigazzini** [comment]
@tomtor dev-server and workers updated (the workers start with a git clone and pull #269 and #267). All three workers are outputting the same error message
```
make[1]: Leaving directory '/tmp/tmpTOhDeQ/IIvec-Stockfish-95beeb1/src'
strip stockfish
Downloading 2moves_v1.pgn ...
Downloading cutechess-cli-linux-64bit.zip ...
Verifying signature of stockfish_95beeb1c17d92604d1ed994d3dbd6ef2184b3a5a ...
Verifying signature of stockfish_95beeb1c17d92604d1ed994d3dbd6ef2184b3a5a ...
CPU factor : 1.027491 - tc adjusted to 2.05+0.02
Running tune_imbalance vs tune_imbalance

Exception running games:
Traceback (most recent call last):
  File "worker.py", line 100, in worker
    run_games(worker_info, password, remote, run, task_id)
  File "/root/_git/fishtest/worker/games.py", line 480, in run_games
    task_status = launch_cutechess(cmd, remote, result, spsa_tuning, games_to_play, tc_limit * games_to_play / min(games_to_play, games_concurrency))
  File "/root/_git/fishtest/worker/games.py", line 307, in launch_cutechess
    req = requests.post(remote + '/api/request_spsa', data=json.dumps(result), headers={'Content-type': 'application/json'}, timeout=HTTP_TIMEOUT).json()
  File "/root/_git/fishtest/worker/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Task exited
```

**Comment by tomtor** [comment]
@ppigazzini My workers run OK?

**Comment by ppigazzini** [comment]
@tomtor your workers are OK.

**Comment by tomtor** [comment]
I will look into it later this evening...

**Comment by tomtor** [comment]
@ppigazzini Fixed print issue from #162. 

I cannot reproduce your other error locally with server and worker from this PR.
When a new worker from this PR talks to your dev server now I get the error.
It looks as if a new worker from this PR is talking to an older server (without this PR)... That will fail. Perhaps I will have to reintroduce the worker key to ease the transition.

**Comment by ppigazzini** [comment]
@tomtor dev-server and workers updated: now they runs fine.

**Comment by tomtor** [comment]
@ppigazzini Thanks for testing. Let me think about it a bit longer because I am not sure why the last change was needed.

**Comment by ppigazzini** [comment]
@tomtor OK.

**Comment by tomtor** [comment]
@ppigazzini Tested again locally, should be OK (Travis failure is temporary)

**Comment by ppigazzini** [comment]
@tomtor dev-server and workers updated

**Pull request merged**
