### PR TITLE
Small cleanups

### PR DESCRIPTION
**Pull request by tomtor**
remove test for obsolete worker version

remove redundant line for tests_stop()

leading 0's for Played (better sorting)

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor dev server updated.
https://github.com/glinscott/fishtest/pull/409/commits/80870b72b046681b1e11da0f78ac7c519b9e70dd verified, I don't know how to check the other two changes.

**Comment by tomtor** [comment]
@ppigazzini not related to this patch but I see that a worker is not  stopped immediately?

**Comment by tomtor** [comment]
@ppigazzini I assume the test server has the nginx multi process setup with separate process for /tests? This means that seeing the stop in the main view is a bit delayed (about 1 or 2 seconds) after pressing STOP. So you must reload /tests, that is the disadvantage of the multiple processes.

I pushed a change so that this effect should be reduced, can you please reload the server?

**Comment by tomtor** [comment]
> sentenced to 50 PRs!

@ppigazzini I think I am already close to that or did you mean NEW PRs? ;-)

**Comment by ppigazzini** [comment]
@tomtor server updated
ps: NEW PRs upon MY requirements. First one: "Stop button" floating position > 50 pixel from the mouse if the user is Dutch.

**Comment by ppigazzini** [comment]
@tomtor dev server setup with the latest version of the [wiki script](https://github.com/glinscott/fishtest/wiki/Fishtest-server-setup)

**Comment by tomtor** [comment]
@ppigazzini Ok, I have tested and stopping works fine now.

The other change was for showing the download link and that is working too. So merging is OK for me.

**Comment by ppigazzini** [comment]
Prod server updated.

**Comment by tomtor** [comment]
Thanks!

**Pull request merged**
