### PR TITLE
Minor sidebar cosmetic update

### PR DESCRIPTION
**Pull request by linrock**
- All sidebar links now show up on one line
- Hide register and login links when already logged-in
- Add Github section for fishtest and stockfish repos

---
Before and after:

### CODE REVIEW

**Comment by ppigazzini** [comment]
@linrock I found this strange behavior:
- register a new user
- pending (1) in red 
- login as approver
- click on pending (1)
- unblock new user
- always pending (1) in red
- click on pending (1): no waiting user
- pending in black
Until here it works like the master (there is this little glitch that pending requires a second visit to change from red to black) but with the PR:
- login as other user
- pending (1) in red (???)

**Comment by ppigazzini** [comment]
@linrock errata corrige: also master has the same strange behavior

**Comment by ppigazzini** [comment]
PROD updated, thank you @linrock

**Comment by linrock** [comment]
@ppigazzini cool no prob, maybe worth filing an issue for the `pending (1)` bug

**Comment by vondele** [comment]
I've filled an issue for the pending bug. I had seen this before, it is there since quite a long time.

**Comment by tomtor** [comment]
It is caused (introduced) by serving the main page from a different pserv instance.

**Pull request merged**
