### PR TITLE
fix restart name conflict

### PR DESCRIPTION
**Pull request by tomtor**
Should fix https://github.com/glinscott/fishtest/issues/368

### CODE REVIEW

**Comment by tomtor** [comment]
@vdbergh I fixed the travis build by forcing scipy 1.1.0 (until the fixed 1.2.1 https://github.com/scipy/scipy/issues/9606) but I am not familiar with scipy. Do you think using 1.1.0 is safe?

**Comment by tomtor** [comment]
Hi @ppigazzini I am not sure I understand the second problem.

You think that there is a restart problem when the user did start:

    python worker/worker.py

instead of:

    cd worker; python worker.py

**Comment by ppigazzini** [comment]
@tomtor yes, that is the problem. We cannot enforce as a user launch the worker. What about forcing an os.chdir() in the worker.py folder at the start of worker.py?

PS: I will be at home in the afternoon.

**Comment by tomtor** [comment]
> @tomtor yes, that is the problem. We cannot enforce as a user launch the worker. What about forcing an os.chdir() in the worker.py folder at the start of worker.py?
> 

Forcing a different working directory would prevent using different configuration files. I think just restoring the original working directory is the best approach for the cleanest `do_restart()`

I did this in the last commit.

**Comment by tomtor** [comment]
@ppigazzini It should be OK now. I think the last Travis failure is a transient error...

**Comment by tomtor** [comment]
@ppigazzini It's not ready yet, I'll have a look at it later...

**Comment by tomtor** [comment]
@ppigazzini It should be ready for testing now. 

I tested it myself by forcing an update by changing line 100 in `worker.py` from:

    if req['version'] > WORKER_VERSION:      

to

    if True:

and starting:

         python3 worker/worker.py

It did do a succesfull update, i.e. restore my working copy to master.

**Comment by ppigazzini** [comment]
@tomtor the production server (CentOS 6) and the dev-server (CentOS 7) are using numpy and scipy from distutils installed with yum.
On the dev/sever I successfully uninstalled numpy and scipy with yum and installed the latest versions with pip, but I'm not confident to try this on the fly on the production server because I have very little time in these days to debug a server problem (in the past some package updates with pip broke the production server). 

Please open a new PR for scipy and numpy and keep this PR only for the updater problem.

**Comment by tomtor** [comment]
@ppigazzini Sure, I understand.

I removed the scipy commit from this PR.

There is no need for a new PR because in time scipy 1.2.1 will fix this Travis build issue.

**Comment by ppigazzini** [comment]
@tomtor the update of running workers (Linux, Windows, Windows Subsystem for Linux) went fine on the dev server. I will test other combinations before merging this PR. Great work Tom.

**Comment by ppigazzini** [comment]
@tomtor all my tests went fine, ready to be merged.
@noobpwnftw tomorrow at 02:15 PM CET I would like to force a worker update. Please let me know if there is a problem with the scheduling.

**Comment by noobpwnftw** [comment]
@ppigazzini It's fine with me.

**Comment by tomtor** [comment]
@ppigazzini thanks for your test work and diagnosis of the working directory issue!

Note that the workers would need a last manual restart. After that newer updates should properly restart. Not sure that is clear for everybody. Will the update of tomorrow carry the new @vdbergh pentamonial worker updates?

**Comment by noobpwnftw** [comment]
Just a quick question:
Is it true that the workers will *not* automatically update and restart? Or there is a chance.

If the former, can you bump the version number when ready so I can manually update them earlier?

**Comment by ppigazzini** [comment]
@noobpwnftw no problem, I can raise the worker version tonight at 11 pm CET.
@tomtor I wrote a post in fishcooking group to make clear that will be required a restart by hand.
I think that the pentanomial is still a WIP, the @vdbergh 's dev laptop should return in action tomorrow after a serious injury :)

**Comment by noobpwnftw** [comment]
@ppigazzini My workers have updated with a clean install to latest master.

**Pull request merged**
