### PR TITLE
Speed up main page by sorting in Python

### PR DESCRIPTION
**Pull request by tomtor**
and not with MongoDb which reads the whole database.

@ppigazzini Please test on dev server at a convenient time.

See also https://github.com/glinscott/fishtest/issues/408#issuecomment-555445376

Someone knows what happened to Travis builds?

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor dev-server updated w/ the PR.
Are welcome suggestions about how to benchmark this PR and the https://github.com/glinscott/fishtest/issues/408#issuecomment-555445376

**Comment by ppigazzini** [comment]
@tomtor no idea about travis

**Comment by tomtor** [comment]
@ppigazzini I do not see a significant speedup (I wonder why), so I guess moving all but the most recent 1000 tests to `old_runs` is the only option? Do you agree or do you find the main page delay acceptable? One issue now is that approved/created tests take a long time to appear.

Should I write something like https://stackoverflow.com/questions/27039083/mongodb-move-documents-from-one-collection-to-another-collection/41483981#41483981

**Comment by tomtor** [comment]
https://travis-ci.org/glinscott/fishtest/pull_requests shows the up to date Travis build status  including this PR but https://github.com/glinscott/fishtest/pulls does not.

@vondele Do you have a suggestion?

**Comment by vondele** [comment]
@tomtor this seems similar to
https://github.com/official-stockfish/Stockfish/issues/2314#issuecomment-533812660

**Comment by ppigazzini** [comment]
I have access to https://travis-ci.org/glinscott/fishtest/settings but not to https://github.com/glinscott/fishtest/settings/

I wrote a mail to @glinscott

**Comment by tomtor** [comment]
I am closing this because of https://github.com/glinscott/fishtest/pull/434

**Comment by glinscott** [comment]
From what I see, travis should still be active:

image

It looks like the previous integration we used is now deprecated though.

**Pull request closed without merging**
