### PR TITLE
Set new book default

### PR DESCRIPTION
**Pull request by ppigazzini**
To be tested after the merging of these PRs official-stockfish/books#1 official-stockfish/books#2.

It's working fine with my up to date books repo.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor works fine on DEV.
The [old setup repo](https://github.com/mcostalba/FishCooking/tree/setup) hasn't the 2moves_v2.pgn, so this must be merged only after enforcing the update of the worker to v71 (w/ https://github.com/glinscott/fishtest/pull/351 https://github.com/glinscott/fishtest/pull/471)

**Comment by ppigazzini** [comment]
OK, waiting for feedback from @snicolet and other people before changing the default book.

**Comment by vondele** [comment]
I'm also fine with using noob_3moves.epd seems like a pretty reasonable and broad set of positions.

Do I understand that it will be easy to test these books after the worker update? If so, one could maybe do a test with these books and see what the difference is (i.e. measure sensitivity).

**Comment by ppigazzini** [comment]
@vondele yes, simply write the name of the book (w/o the .zip extension) in the new test page.
Check a preview on DEV https://dfts-2.pigazzini.it/tests

I will update this PR to set the default to "noob_3moves.epd"

**Comment by tomtor** [comment]
@vondele Parked http://tests.stockfishchess.org/tests/view/5dfc6aa0e70446e17e451035 at -1 because it hangs for some reason (cannot load book?)

**Comment by vondele** [comment]
@tomtor thanks... would be very interesting data however. I wonder what is causing it. Maybe just trying again at a later point helps.

**Comment by ppigazzini** [comment]
@vondele @tomtor the "noob_4moves.epd" works fine on DEV
https://dfts-2.pigazzini.it/tests/view/5dfc9991397337f81076843e

**Comment by ppigazzini** [comment]
@vondele @tomtor the old cutechess-cli on linux hangs loading .epd books

**Comment by ppigazzini** [comment]
@vondele @tomtor also the old windows cutechess-cli hangs loading *.epd books.

**Comment by ppigazzini** [comment]
@tomtor @vondele I temporary raised the priority to 0 for debug http://tests.stockfishchess.org/tests/view/5dfc6aa0e70446e17e451035
I viewed hanging:
 - 3 active workers with 24 cores
 - 4 active workers with 32 cores
 - 5 active workers with 40 cores
Unfortunately my worker have not taken tasks from that test.

@noobpwnftw it seems that some of your workers are using a cutechess-cli version not able to load noob_4moves.epd

**Comment by noobpwnftw** [comment]
I may have to manually deploy the book since large downloads from GitHub are timing out on the workers.

**Comment by vondele** [comment]
Summarizing the book testing, in the following table:

book                    |   Size       | Realism |      Elo      |        Link
---                     |     ---     | ---     |      ---      |        ---
noob_5moves             |  455287      |   +     |  47.02 +-2.2  |   [test](http://tests.stockfishchess.org/tests/view/5e01c04cc13ac2425c4a9aa6)
noob_4moves             | 1837365      |   +     |  48.31 +-2.2  |   [test](http://tests.stockfishchess.org/tests/view/5dfc6aa0e70446e17e451035)
noob_3moves             |  150932      |   +     |  44.90 +-2.2  |   [test](http://tests.stockfishchess.org/tests/view/5dfc6a8de70446e17e451033)
noob_2moves             |    7314      |   ++    |  40.75 +-2.2  |   [test](http://tests.stockfishchess.org/tests/view/5dfc6a7ae70446e17e451031)
2moves_v1               |   40457      |   -     |  44.50 +-2.3  |   [test](http://tests.stockfishchess.org/tests/view/5dfc68e9e70446e17e451015)
2moves_v2               |   12092      |   +     |  40.75 +-2.2  |   [test](http://tests.stockfishchess.org/tests/view/5dfc69c2e70446e17e45102b)
8moves_v3               |   34700      |   ++    |  38.74 +-2.1  |   [test](http://tests.stockfishchess.org/tests/view/5dfc6a2ce70446e17e45102d)
Drawkiller_balanced_big |   15962      |   --    |  63.63 +-2.6  |   [test](http://tests.stockfishchess.org/tests/view/5dfc6a56e70446e17e45102f)
hybrid_book_beta        |   28054      |   --    |  57.20 +-2.4  |   [test](http://tests.stockfishchess.org/tests/view/5dfc7ba9e70446e17e45104d)
endgames                |   33977      |   ++    |  19.86 +-1.5  |   [test](http://tests.stockfishchess.org/tests/view/5e01c083c13ac2425c4a9aaa)

'Realism' is my subjective take on how likely the positions are in 'real' chess games.

Based on this test, I would like to switch now to the noob_3moves book. I see the following advantages:
* Good Elo gain, similar to 2moves_v1
* Significantly larger than other books, in particular sufficient to have unique game-pairs for almost all tests in fishtest (i.e. for runs up to ~300k games, once the cutechess randomization issues are fixed). 
* Realistic positions, i.e. reachable from startpos in few moves, non-extreme evals
* Not too many moves away from startpos (i.e. able to train opening).

I think the only other candidate which comes close is noob_4moves, but the size (100Mb unzipped) is slightly problematic, and some fishtesters have asked for books with few moves. So I think noob_3moves strikes the right balance. 

@ppigazzini could you change the default accordingly?

**Comment by ppigazzini** [comment]
@vondele to avoid misunderstanding, this PR already set the default to noob_3moves.epd, view https://github.com/glinscott/fishtest/pull/472/commits/7f487385ed14d5ff046c299ca31ca18dd4e2bfcc

Are you asking to merge the PR?

**Comment by vondele** [comment]
Ah right. Yes, in that case I think it is ready to merge.

**Comment by ppigazzini** [comment]
PROD updated, thank you @vondele

**Comment by vondele** [comment]
thanks, announced on fishcooking https://groups.google.com/d/msg/fishcooking/hcGWL4mXFGw/auXlxKmeBwAJ

**Pull request merged**
