### PR TITLE
Adjustments of dark mode

### PR DESCRIPTION
**Pull request by SFisGOD**
Some contrast adjustments of dark mode.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@SFisGOD [DEV](https://dfts-0.pigazzini.it) updated.
Bug: when in light theme pushing the moon button doesn't work anymore (and sometimes the moon button disappear). Please double check.
Improvement: if possible darken a bit the white box tests.

**Comment by SFisGOD** [comment]
I need to update js/application.js

**Comment by ppigazzini** [comment]
DEV updated.
The moon button doesn't trigger the switch to the dark theme for the original page, I need to select a new page to get the change.
The sun button works fine, though.

**Comment by SFisGOD** [comment]
@ppigazzini Could you please update the dev once again with my latest change

**Comment by SFisGOD** [comment]
The moon button doesn't trigger because I did not change the sha256 integrity. With my latest commit, it should be fine now.

**Comment by ppigazzini** [comment]
DEV updated, the moon button bug seems still there.

**Comment by SFisGOD** [comment]
@ppigazzini It seems my changes are not reflected in dev?

**Comment by ppigazzini** [comment]
@SFisGOD I close and reopen the browser in incognito, or reload with CRTL+F5, all changes visible but the moon bug still here with Chrome and Edge.

**Comment by ppigazzini** [comment]
I do this to switch:
 - push the moon button (the moon button disappears)
 - refresh with F5, the theme switches

**Comment by SFisGOD** [comment]
@ppigazzini It should be fine now with latest sha?

**Comment by SFisGOD** [comment]
I still need to lower the contrast of the white boxes.

**Comment by ppigazzini** [comment]
DEV updated, moon bug fixed :)

**Comment by SFisGOD** [comment]
@ppigazzini I have one more change and the moon bug will appear again but I just need to update sha after you update the DEV.

**Comment by SFisGOD** [comment]
@ppigazzini I'm done now with the changes or if you have suggestions please tell me.

**Comment by ppigazzini** [comment]
@SFisGOD please squash the commits :)

**Comment by ppigazzini** [comment]
DEV updated, great job :)

**Comment by SFisGOD** [comment]
@ppigazzini Done.

**Comment by ppigazzini** [comment]
@SFisGOD there are still 6 different commits and I don't view the necessity to have more than 1 commit for this PR:
- `git checkout master && git fetch -p upstream && git reset --hard upstream/master && git checkout adjust_contrast`
- `git rebase -i master`
- replace "pick" with "squash" for all the commits but the first one
- write the final commit message (eg copying deleting the commits messages)
- `git push -f origin adjust_contrast`

**Comment by ppigazzini** [comment]
By the way I already added "Jonathan Buladas Dumale (SFisGOD)" in AUTHORS file, copied from Stockfish project :)

**Comment by SFisGOD** [comment]
> @SFisGOD there are still 6 different commits and I don't view the necessity to have more than 1 commit for this PR:
> 
> * `git checkout master && git fetch -p upstream && git reset --hard upstream/master && git checkout adjust_contrast`
> * `git rebase -i master`
> * replace "pick" with "squash" for all the commits but the first one
> * write the final commit message (eg copying deleting the commits messages)
> * `git push -f origin adjust_contrast`

Thanks for this.

**Comment by SFisGOD** [comment]
@ppigazzini Thanks for the help and suggestions!

**Comment by ppigazzini** [comment]
PROD updated, thank you @SFisGOD :)

I will post a note on the forum/discord to collect opinions/suggestions from developers/approvers.

**Comment by SFisGOD** [comment]
@ppigazzini Yes please, thanks! Suggestions are very welcome :)

**Comment by ppigazzini** [comment]
@SFisGOD sorry, only enthusiastic comments on discord/forum :(

**Comment by SFisGOD** [comment]
@ppigazzini I posted some sample images of possible refinements. I'll submit another PR soon.

**Pull request merged**
