### PR TITLE
Add explanations to the SPRT calculator.

### PR DESCRIPTION
**Pull request by vdbergh**
The new version of the SPRT calculator is here. 

http://hardy.uhasselt.be/Toga/SPRTcalculator.html

Feel free to comment.

### CODE REVIEW

**Comment by vdbergh** [comment]
PS. This PR implements some requests by @snicolet .

**Comment by ppigazzini** [comment]
DEV updated

**Comment by snicolet** [comment]
You should add a `<br><hr>` before the start of the explanations, otherwise on some browsers the first paragraph is cut, see http://cassio.free.fr/divers/screenshot.png

Also concerning the first paragraph: 

- it is strange to start a sentence with a variable name, it could read for instance "The parameters Elo0 and Elo1 represent the bounds [...]"

- I would rename the variables everywhere in the document
```
   Elo 0      --->      Elo0
   Elo 1      --->      Elo1
```

More feedback later, I have to run for now. Thanks for the page :-)

**Comment by vdbergh** [comment]
@snicolet I posted a new version. I put in <br><hr> . Can you check if it fixes the rendering error?

**Comment by snicolet** [comment]
> I put in <br><hr> . Can you check if it fixes the rendering error?

No it does not, it seems that the `<br>` and `<hr>` has been styled in CSS.
However this is only a cosmetic problem.

I propose that we commit the current state of the PR and we can improve/simplify the text and the graphical layout later in other PR, if necessary.

**Comment by vdbergh** [comment]
@snicolet Ok. I must say I am a bit puzzled by this issue. The html is trivial and the page renders as intended in Firefox and Chrome.

As you say it is probably the CSS styling applied by bootstrap. But right now I don't have much time to investigate.

**Comment by vdbergh** [comment]
Actually now it seems that it may not actually be a bug.  It has to do with the floating behavior of the graphs. I looked on my cell phone and there the behavior is sensible. The text floats to the right of the graphs, depending on the availability of screen real estate. However the non-breakability of the URLs in the second bullet, forces most of the text to be below the graphs anyway.

Later I will try to make the graphs non-floating.

**Comment by vdbergh** [comment]
I think making only the first graph float left has fixed the issue. The second graph will be either to the right of below the second graph, but the text (contained in an UL environment) will always be below the second graph. So it is should always be ok.

http://hardy.uhasselt.be/Toga/SPRTcalculator.html

**Comment by ppigazzini** [comment]
I wait the test by @snicolet to merge this.

**Comment by snicolet** [comment]
It now works fine in Safari!

**Comment by ppigazzini** [comment]
PROD updated. Thanks to @vdbergh for the patch and to @vondele @snicolet for the test/review :)

**Comment by vdbergh** [comment]
I guess we should now add Henri Wiechers to the list of authors also.

**Comment by ppigazzini** [comment]
@vdbergh correct. The list must be update with all the contributors:
```
$ git shortlog -sn
   728  Gary Linscott
   301  Marco Costalba
   134  Tom Vijlbrief
    53  ppigazzini
    24  Kamyar Kaviani
    15  Joost VandeVondele
    15  xoto10
    11  ianfab
     9  Michel Van den Bergh
     9  Werner Fenchel
     8  Stefano Cardanobile
     8  lucasart
     6  Jean-Francois Romang
     4  Vince Negri
     3  David Zar
     2  Chess13234
     2  Joona Kiiski
     2  Lucas Braesch
     2  Stéphane Nicolet
     2  mcostalba
     2  noobpwnftw
     1  FieryDragonLord
     1  Henri Wiechers
     1  Michael An
     1  Michał Robaczyk
     1  Noé Costa
     1  Stefano80
     1  Your Name
     1  fishtest
     1  hxim
     1  joergoster
     1  theo77186
```

**Comment by ppigazzini** [comment]
@vdbergh opened the #500, Henri Wiechers was already an authors (but not credited).

**Comment by vdbergh** [comment]
The SPRT calculator uses the d3 framework which is a javascript layer above svg (in other words the graphs are essentially created by hand).

As an experiment I made a version using Google Charts. 

http://hardy.uhasselt.be/Toga/SPRTcalculator.html

It is functionally more or less equivalent and the javascript code is much shorter and also much easier to understand.

**Comment by ppigazzini** [comment]
Feel free to open a new PR :)

**Comment by ppigazzini** [comment]
@vdbergh minor glitch of the Google Charts version: after inserting an invalid value the charts disappear.

**Comment by snicolet** [comment]
a) The master version seems a little bit smoother, maybe because it works even when the mouse is not touching the curves -- in fact I always use it by moving the mouse horizontally anywhere in the grey areas, never by following the curves.

b) since you are at it, can you make the Elo steps 0.05 or 0.02 instead of 0.1 ? this way it would feel even smoother

**Comment by snicolet** [comment]
Btw, the link in the left menu (in the MISC section) could read "Simulator", as it would be fit on one line.

**Comment by vdbergh** [comment]
@ppigazzini This was intentional, but not a good idea in retrospect. I was trying to think what to do if the user supplies illegal parameters via the URL (then there are no previous parameters to fall back on). But I guess the solution is easy. Just draw the graph with the default parameters. 

@snicolet Google Charts do not generate mouseover events outside the data points. So this behaviour of master cannot be duplicated. I guess it would be a choice between more easily maintainable code and more flexibility.

**Comment by vdbergh** [comment]
@snicolet I experimented with setting the Elo increment to 0.01. While then the behavior is a  bit smoother (to my surprise), it also becomes harder to position the cursor accurately. So I left it as is, but made the increment easy to change in the source.

**Comment by vdbergh** [comment]
It appears master's behaviour can be duplicated in a not too hacky way by attaching eventlisterners directly to the enclosing div.

**Comment by ppigazzini** [comment]
> Btw, the link in the left menu (in the MISC section) could read "Simulator", as it would be fit on one line

"SPRT simul" ?

**Comment by vdbergh** [comment]
But it is not a simulator... Perhaps SPRT calc?

**Comment by ppigazzini** [comment]
I agree for "SPRT calc"

**Comment by vdbergh** [comment]
Here is a new version that more or less emulates the behavior of master 

http://hardy.uhasselt.be/Toga/SPRTcalculator.html

Occasionally there is a small dead zone next to the curve which has to do with GC eating events.

**Pull request merged**
