### PR TITLE
Call the engine binaries by absolute path.

### PR DESCRIPTION
**Pull request by vdbergh**
This should fix the docker image built by @Dantist. See #1360 .

The instructions for rebuilding the image are in Dockerfile. Since this PR has not been committed yet I could not test the rebuilding. However I applied the PR manually (after starting the container) and it worked!

### CODE REVIEW

**Comment by vdbergh** [comment]
One complication with the docker image is, that it apparently has no permanent storage to preserve the config file. So each time it is run it will have a different `uuid_prefix`.

**Comment by vdbergh** [comment]
It seems to be not very difficult to have the worker directory outside the container and map it to a directory inside the container

https://docs.docker.com/storage/bind-mounts/

**Comment by vdbergh** [comment]
It's not so straightforward though since you cannot mount something while building an image.

**Comment by noobpwnftw** [comment]
Can declare a docker volume.

**Comment by vdbergh** [comment]
As I understand it you can mount something while creating the container, but not while building the image.

**Comment by vdbergh** [comment]
@noobpwnftw Actually now I understand what you are saying. Mounting an empty volume over a directory in the container causes the files in the directory to be copied to the volume. This then becomes permanent storage. Thanks!

**Comment by vdbergh** [comment]
This is the command I use to run the image by @Dantist with permanent storage
```
sudo docker run -it -v worker-dir:/opt/fishtest/worker -e concurrency=MAX fishtest
```
The volume `worker-dir` has been created by
```
sudo docker volume create worker-dir
```
Pretty convenient actually. Given that this will work on all OS'es that docker supports.

**Comment by vdbergh** [comment]
Interestingly the same volume can be mounted by two docker containers, so that effectively two workers share the same directory. The current lockfile implementation is defeated as the two workers have the same PID (in different containers). This can be solved by including the hostname in the lockfile (besides the PID).

**Comment by vdbergh** [comment]
There is no a cutechess-cli binary that works in the docker image and that does not need the PR. See #1362 . This is a better solution. So I am closing this PR.

**Comment by noobpwnftw** [comment]
Containerized worker is always nice to have. PID isolation can be disabled by running the container with `--pid=host`, although it is hardly necessary to run multiple containers in the first place.

**Comment by vdbergh** [comment]
@noobpwnftw Thanks! The —pid option would indeed prevent two workers from running in the same directory.

**Pull request closed without merging**
