### PR TITLE
Elo confidence intervals were inverted.

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by ppigazzini** [comment]
@vdbergh DEV updated with this PR and https://github.com/glinscott/fishtest/pull/476, let me know if I can merge both.

**Comment by vdbergh** [comment]
I ran a few tests on DEV and the PRs behave as they should.

**Comment by ppigazzini** [comment]
PROD updated with both PRs. Thank you @vdbergh

**Comment by vdbergh** [comment]
Thanks!

**Pull request merged**
