### PR TITLE
Fix password parsing with configparser

### LINKED ISSUE #79: Worker doesn't handle passwords with % characters in them
Running the worker using `python2 worker.py --concurrency 3 Username "Password%"` results in an incorrect formatting error. If the % is doubled, the formatting error does not occur, but the password is then invalid.

```
Traceback (most recent call last):
  File "worker.py", line 173, in <module>
    main()
  File "worker.py", line 136, in main
    config.set('login', 'password', args[1])
  File "/usr/lib/python2.7/ConfigParser.py", line 752, in set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in 'Password%' at position 8
```

### PR DESCRIPTION
**Pull request by zungur**
Passwords with % can now be handled on terminal. Fixes #79

### CODE REVIEW

**Review by ppigazzini — APPROVED** [review]
Tested working with some workers (Linux Ubuntu, WSL2 Ubuntu, msys2 cli msys2-python, cmd cli msys2-python, cmd cli windows-python)

**Comment by ppigazzini** [comment]
@zungur I wait a while for other worker PRs (at least my python2 drop) before triggering a worker update.

**Comment by zungur** [comment]
No worries and thank you for letting me know! When to merge is at your discretion. I was already relieved to see the changes approved and figured that there are other changes happening in parallel :)

**Comment by ppigazzini** [comment]
Merged, thank you @zungur :)

**Pull request merged**
