### PR TITLE
Speed up finished runs MongoDb query

### PR DESCRIPTION
**Pull request by tomtor**
edit: Filtering 'deleted' in python speeds up to 0.2s

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor dev-server test before your last commit (two runs) https://github.com/glinscott/fishtest/pull/443/commits/cac2c52ed4cecc63706d4d212be38746815a3049

* master:
```
${VENV}/bin/python fishtest/fishtest/utils/test_queries.p                      y

Fetching unfinished runs ...
0.000162839889526s
Fetching machines ...
0.0795078277588s
Fetching finished runs ...
2.60631203651s
Requesting pgn ...
0.000993013381958s

${VENV}/bin/python fishtest/fishtest/utils/test_queries.p                      y

Fetching unfinished runs ...
0.000190019607544s
Fetching machines ...
0.073038816452s
Fetching finished runs ...
2.89345192909s
Requesting pgn ...
0.000911951065063s
```
* pr:
```
${VENV}/bin/python fishtest/fishtest/utils/test_queries.p                      y

Fetching unfinished runs ...
0.000173091888428s
Fetching machines ...
0.0736258029938s
Fetching finished runs ...
2.87277507782s
Requesting pgn ...
0.000942945480347s

$ ${VENV}/bin/python fishtest/fishtest/utils/test_queries.p                      y

Fetching unfinished runs ...
0.000170946121216s
Fetching machines ...
0.072921037674s
Fetching finished runs ...
2.79401803017s
Requesting pgn ...
0.000946998596191s
```

**Comment by tomtor** [comment]
@ppigazzini See ~/x/rebuild_queries on prod which I used for my timing...

**Comment by ppigazzini** [comment]
@tomtor dev-serve test **after** https://github.com/glinscott/fishtest/pull/443/commits/cac2c52ed4cecc63706d4d212be38746815a3049
```
$ ${VENV}/bin/python ${UPATH}/test_queries.py

Fetching unfinished runs ...
0.000162839889526s
Fetching machines ...
0.0793800354004s
Fetching finished runs ...
1.83845090866s
Requesting pgn ...
0.000683069229126s

$ ${VENV}/bin/python ${UPATH}/test_queries.py

Fetching unfinished runs ...
0.000181913375854s
Fetching machines ...
0.075838804245s
Fetching finished runs ...
1.90634894371s
Requesting pgn ...
0.000868082046509s
```

**Comment by ppigazzini** [comment]
@tomtor I viewed only now your post
> @ppigazzini See ~/x/rebuild_queries on prod which I used for my timing...

**Comment by ppigazzini** [comment]
@tomtor sorry for the confusion, after viewing your https://github.com/glinscott/fishtest/pull/443#issuecomment-558587099 I wanted to don't post my https://github.com/glinscott/fishtest/pull/443#issuecomment-558598854 and in automatic way I pushed the rightmost button. Unfortunately the button is "Close and comment" and not "Cancel" :(

**Comment by tomtor** [comment]
@ppigazzini I see you used `rebuild_indices.py`

So on prod the speedup is very large.

**Comment by ppigazzini** [comment]
@tomtor I'm not able to reproduce the speedup on the dev with `~/x/rebuild_indeces` (`~/x/rebuild_queries` not found).

*master:
```
$ ${VENV}/bin/python rebuild_indeces.py
reindex
t0=1574774084.04
t1=1574774084.18
t1-t0=0.138878107071
done...

$ ${VENV}/bin/python rebuild_indeces.py
reindex
t0 = 1574774122.86
t1 = 1574774123.02
t1-t0 = 0.157711029053
done...

$ ${VENV}/bin/python rebuild_indeces.py
reindex
t0 = 1574774191.32
t1 = 1574774191.46
t1-t0 = 0.139991044998
done...
```

*pr:
```
$ ${VENV}/bin/python rebuild_indeces.py
reindex
t0 = 1574774548.6
t1 = 1574774548.74
t1-t0 = 0.144069910049
done...
$ ${VENV}/bin/python rebuild_indeces.py
reindex
t0 = 1574774550.5
t1 = 1574774550.65
t1-t0 = 0.148473978043
done...
$ ${VENV}/bin/python rebuild_indeces.py
reindex
t0 = 1574774552.04
t1 = 1574774552.19
t1-t0 = 0.142319917679
done...
```

**Comment by xoto10** [comment]
Nice work!

I have made a new branch with some changes to test_queries.py that may give some useful info on this: [testqueries2](https://github.com/glinscott/fishtest/compare/master...xoto10:testqueries2)

It displays the explain() output for the old and new versions of the finished() query and tries using a hint().

**Comment by ppigazzini** [comment]
@tomtor this is on prod, I double checked that it's in sync w/ master (`git branch`, `git status` and inspected `rundb.py`) and that mongo has the usual indexes. I restarted mongod and fishtest.
I'm obviously missing something...

* master:
```
$ ${VENV}/bin/python rebuild_indices.py
reindex
t0 = 1574778108.66
t1 = 1574778108.82
t1-t0 = 0.156199932098
done...
$ ${VENV}/bin/python rebuild_indices.py
reindex
t0 = 1574778110.97
t1 = 1574778111.14
t1-t0 = 0.168743133545
done...
```

* pr (files copied by hand):
```
${VENV}/bin/python rebuild_indices.py
reindex
t0 = 1574778777.21
t1 = 1574778777.39
t1-t0 = 0.185088157654
done...
$ ${VENV}/bin/python rebuild_indices.py
reindex
t0 = 1574778779.22
t1 = 1574778779.43
t1-t0 = 0.21334695816
done...
```

**Comment by tomtor** [comment]
@ppigazzini rebuild_indices only does the new query from this PR (in 0.2s instead of eg 2.0s) and is not depending on the PR. If you re-add skip=0 and the test for `deleted` it will slow down again.

**Comment by tomtor** [comment]
t1-t0 = 0.167485952377         (PR)                                                                                                                     
    t1-t0 = 0.709129095078         (master)

**Comment by tomtor** [comment]
@ppigazzini For some reason the `skip=0` no longer makes a major difference, but 0.16s for the main page is very fast...

**Comment by tomtor** [comment]
I removed the `skip=0` rewrite and only left the removal of `deleted` from the query....

**Comment by ppigazzini** [comment]
@tomtor it's a bit paranoid but on dev, when testing for speedup, I comment out crontab, I run the scripts a couple of times to avoid cache effects, and I reinstall fishtest with `update_fishtest.py` to be sure to don't use leftovers (*.pyc)

**Comment by ppigazzini** [comment]
@tomtor I wrote this `test_pr443.py`, check if it's correct:
```python
from __future__ import print_function

import os
import sys
import time
import numpy
from pymongo import MongoClient, ASCENDING, DESCENDING

db_name='fishtest_new'
# MongoDB server is assumed to be on the same machine, if not user should use
# ssh with port forwarding to access the remote host.
conn = MongoClient(os.getenv('FISHTEST_HOST') or 'localhost')
db = conn[db_name]

def test_query(q):
  n=20
  t=[]
  t.append(time.time())
  for i in range(n):
    c = db['runs'].find(q, skip=0, limit=100, sort=[('last_updated', DESCENDING)])
    result = [list(c), c.count()]
    t.append(time.time())

  delta=numpy.array([j-i for i,j in zip(t[:-1], t[1:])])

  print("query =%s" % q)
  print("mean = %s" % numpy.mean(delta))
  print("stdev = %s" % numpy.std(delta))

ma = {'finished': True, 'deleted': {'$exists': False}}
pr ={'finished': True}
test_query(ma)
test_query(pr)

print("done...")
```

Result:
```
$ ${VENV}/bin/python test_pr443.py
query ={'deleted': {'$exists': False}, 'finished': True}
mean = 0.23638049364089966
std = 0.037089635227488704
query ={'finished': True}
mean = 0.19297879934310913
std = 0.029167710507801748
done...
```

Result w/ comment out `result = [list(c), c.count()]`:
```
$ ${VENV}/bin/python test_pr443.py
query ={'deleted': {'$exists': False}, 'finished': True}
mean = 5.32984733581543e-05
std = 4.1316809902932895e-05
query ={'finished': True}
mean = 3.159046173095703e-05
std = 5.517471610339806e-06
done...
```

**Comment by tomtor** [comment]
@ppigazzini Why don't you compare the PR to:

    ${VENV}/bin/python fishtest/fishtest/utils/test_queries.py

which took 2.6s in master? (first tests in this PR)

**Comment by ppigazzini** [comment]
@tomtor I compared the two queries from `rebuild_indices.py`, if I'm not wrong those are the queries swapped with this PR.
By the way swapping the queries order in `rebuild_indices.py` I got reversed results (and results very noisy), so I wrote that new python script. I don't know if the mongodb cache system voids the results.

**Comment by tomtor** [comment]
@ppigazzini I agree it is noisy and for some reason on PROD the results are better.
I changed `~/x/rebuild_indices` to loop 10 times and still get imo significant speedup on prod. Because the code change is small I suggest to merge it:

master t1-t0 = 0.821694850922                                                                                                                       pr     t1-t0 = 0.3378469944                                                                                                                         master t1-t0 = 0.749480009079                                                                                                                       pr     t1-t0 = 0.31048989296                                                                                                                        master t1-t0 = 0.66680598259                                                                                                                        pr     t1-t0 = 0.275230169296                                                                                                                       master t1-t0 = 0.637083053589                                                                                                                       pr     t1-t0 = 0.193940162659                                                                                                                       master t1-t0 = 0.635390043259                                                                                                                       pr     t1-t0 = 0.28871512413                                                                                                                        master t1-t0 = 0.695110082626                                                                                                                       pr     t1-t0 = 0.289213180542                                                                                                                       master t1-t0 = 0.93700504303                                                                                                                        pr     t1-t0 = 0.284004926682                                                                                                                       master t1-t0 = 0.671402931213                                                                                                                       pr     t1-t0 = 0.213750123978                                                                                                                       master t1-t0 = 0.466464042664                                                                                                                       pr     t1-t0 = 0.270710945129                                                                                                                       master t1-t0 = 0.605162858963                                                                                                                       pr     t1-t0 = 0.297113180161

**Comment by ppigazzini** [comment]
@tomtor I don't have doubt about this PR (is a speedup and a simplification) but about the MongoDB speedup test process, that it-s very noisy.
Check the new version of `test_pr434.py` on PROD:
```
$ ${VENV}/bin/python test_pr443.py
query = {'deleted': {'$exists': False}, 'finished': True}
delta = [0.60400009 0.27735806 0.24879813 0.16153693 0.22231817 0.1577642
 0.21798706 0.16012716 0.23373795 0.17926478 0.17849898 0.17742085
 0.15449095 0.17154098 0.157305   0.17739916 0.15700507 0.18264794
 0.1611979  0.19547606]
mean = 0.20879377126693727
std = 0.09673169808141673

query = {'finished': True}
delta = [0.18024898 0.15704489 0.15905786 0.16830993 0.1443069  0.16591001
 0.15809894 0.19154978 0.1630311  0.15251493 0.15572095 0.14711618
 0.15738487 0.152982   0.16729498 0.13909006 0.17114711 0.1412828
 0.17332602 0.15667295]
mean = 0.16010456085205077
std = 0.012704282036201713
```

**Comment by xoto10** [comment]
@ppigazzini @tomtor 
Perhaps the slower queries are more noisy? It's possible they are affected more by what else is running at the time.
If I understand that data correctly, the std there is roughly 50% of runtime for the old query, but <10% for the new query - that sounds like progress :-)

**Comment by xoto10** [comment]
@ppigazzini  @tomtor 
Hmmm, looks like deleted runs may still be displayed on main test page? Or is there some caching effect that will pass in a minute or two?

**Comment by ppigazzini** [comment]
@xoto10 @tomtor the queries have different results:
```
query = {'finished': True}
count = 7251
query = {'deleted': {'$exists': False}, 'finished': True}
count = 6673
```

**Comment by tomtor** [comment]
@ppigazzini Yes, I made an error in skipping deleted. PR created.

**Comment by xoto10** [comment]
@tomtor @ppigazzini 
Ah, I can see an issue; the _unfinished_runs_ query has been changed to remove the test for "not deleted", but the python code to filter out the deleted tests:
```
    if 'deleted' in run:
        continue
```
has been added into the loop that fetches _finished_ runs!

**Comment by ppigazzini** [comment]
@xoto10 yes the old query is more noisy, here is a new test run:
```
$ ${VENV}/bin/python test_pr443.py
query = {'deleted': {'$exists': False}, 'finished': True}
delta = [0.84660912 0.85216403 0.84407902 0.83137178 0.641927   0.417768
 0.27091599 0.18505406 0.22831798 0.17131901 0.2459271  0.18428612
 0.253582   0.19984698 0.22356796 0.26520801 0.24722004 0.18503594
 0.44312    0.61151814]
mean = 0.4074419140815735
std = 0.25365219856629306

query = {'finished': True}
delta = [0.23993707 0.19446921 0.17676401 0.24122906 0.21078396 0.16472411
 0.13755393 0.16784096 0.1401031  0.19447708 0.15433788 0.19321203
 0.15973496 0.22445416 0.20886707 0.18313098 0.14262891 0.26454401
 0.19564199 0.26501799]
mean = 0.1929726243019104
std = 0.03821481357211526
```

Here is the script:
```python
from __future__ import print_function

import os
import time
import numpy
from pymongo import MongoClient, ASCENDING, DESCENDING

db_name='fishtest_new'

# MongoDB server is assumed to be on the same machine, if not user should use
# ssh with port forwarding to access the remote host.
conn = MongoClient(os.getenv('FISHTEST_HOST') or 'localhost')
db = conn[db_name]

def bench_query(q, d):
  t=time.time()
  c = db['runs'].find(q, skip=0, limit=100, sort=[('last_updated', DESCENDING)])
  result = [list(c), c.count()]
  d.append(time.time()-t)

def bench_queries(q0, q1):
  n=20
  d0=[]
  d1=[]
  for i in range(n):
    if i%2:
      bench_query(q0, d0)
      bench_query(q1, d1)
    else:
      bench_query(q1, d1)
      bench_query(q0, d0)

  d0=numpy.array(d0)
  d1=numpy.array(d1)

  print("query = %s" % q0)
  print("delta = %s" % d0)
  print("mean = %s" % numpy.mean(d0))
  print("std = %s" % numpy.std(d0))
  print("")
  print("query = %s" % q1)
  print("delta = %s" % d1)
  print("mean = %s" % numpy.mean(d1))
  print("std = %s" % numpy.std(d1))

ma = {'finished': True, 'deleted': {'$exists': False}}
pr ={'finished': True}

bench_queries(ma, pr)
```

**Pull request merged**
