### PR TITLE
[wip] Send the chosen ARCH (e.g. x86-64-bmi2) to server.

### PR DESCRIPTION
**Pull request by vdbergh**
I think this is useful to see what's going on, especially with the new Apple/clang support.

### CODE REVIEW

**Comment by ppigazzini** [comment]
PROD updated, joined some workers on g++/clang++

I'm confused, "features" should have the same information.

**Comment by vdbergh** [comment]
> PROD updated, joined some workers on g++/clang++
> 
> I'm confused, "features" should have the same information.

Ok I think I misunderstood "features" (worker_info["ARCH"]). I thought it represented cpu features. Now I see that it actually represents compiler options.

So maybe a better layout would be 

`arch:  x86-64-modern (64bit SSE41 SSSE3 SSE2 POPCNT)`

**Comment by vdbergh** [comment]
I am going to close this for now.

**Comment by ppigazzini** [comment]
The `ARCH` is extracted every task from the binary, `ARCH_selected` only when building the binary.
After a worker restart with binaries cached `ARCH_selected` is missing, making the info a bit confusing.

Idx | Worker | Info | Last Updated | Played | Pentanomial [0‑2] | Crashes | Time | Residual
-- | -- | -- | -- | -- | -- | -- | -- | --
81 | user00-5cores-5ad31f22 | os: Linux 5.4.0-96-generic; ram: 7500MiB; compiler: clang++ 12.0.1; python: 3.10.2; worker: 153; features: 64bit BMI2 AVX2 SSE41 SSSE3 SSE2 POPCNT; arch: x86-64-bmi2 | 2022-01-22 14:51:47 | 140 / 292 | [4, 23, 28, 14, 1] | 0 | 0 | 0.954
82 | user01-2cores-1f4a0140 | os: Linux 5.4.144+; ram: 6495MiB; compiler: g++ 7.5.0; python: 3.7.12; worker: 153; features: 64bit BMI2 AVX2 SSE41 SSSE3 SSE2 POPCNT; arch: x86-64-bmi2 | 2022-01-22 14:54:16 | 080 / 116 | [3, 9, 20, 6, 2] | 0 | 0 | 0.000
83 | user00-2cores-9a128d4e | os: Linux 5.10.60.1-microsoft-standard-WSL2; ram: 12703MiB; compiler: clang++ 12.0.1; python: 3.10.2; worker: 153; features: 64bit SSE41 SSSE3 SSE2 POPCNT; arch: ? | 2022-01-22 14:53:53 | 116 / 116 | [1, 18, 26, 11, 2] | 0 | 0 | 0.510
84 | ctoks-3cores-017ac510 | os: Windows 10; ram: 16224MiB; compiler: clang++ 13.0.0; python: 3.9.7; worker: 153; features: 64bit SSE41 SSSE3 SSE2 POPCNT; arch: ? | 2022-01-22 14:54:25 | 120 / 174 | [4, 9, 27, 17, 3] | 0 | 0 | 0.305
85 | user00-5cores-a65a4325 | os: Linux 5.4.0-96-generic; ram: 7500MiB; compiler: clang++ 12.0.1; python: 3.10.2; worker: 153; features: 64bit BMI2 AVX2 SSE41 SSSE3 SSE2 POPCNT; arch: ? | 2022-01-22 14:54:17 | 180 / 292 | [6, 13, 45, 24, 2] | 0 | 0 | 0.187
86 | user00-2cores-9a128d4e | os: Linux 5.10.60.1-microsoft-standard-WSL2; ram: 12703MiB; compiler: clang++ 12.0.1; python: 3.10.2; worker: 153; features: 64bit SSE41 SSSE3 SSE2 POPCNT; arch: ? | 2022-01-22 14:54:21 | 008 / 116 | [1, 2, 1, 0, 0] | 0 | 0 | 0.510

**Comment by ppigazzini** [comment]
I tested the cpu features with this code (`msys2` and `cygwin` have `/proc/cpuinfo` too):
```python
def cpu_props():
    p = subprocess.Popen(
        ["cat", "/proc/cpuinfo"],
        stdout=subprocess.PIPE,
        universal_newlines=True,
        bufsize=1,
        close_fds=not IS_WINDOWS,
    )

    for line in iter(p.stdout.readline, ""):
        if "flags" in line:
                return {"flags": line.split()[2:]}
```

Here is the ouput:
```
cpu_props:
 {'flags': ['fpu', 'vme', 'de', 'pse', 'tsc', 'msr', 'pae', 'mce', 'cx8', 'apic', 'sep', 'mtrr', 'pge', 'mca', 'cmov', 'pat', 'pse36', 'clflush', 'mmx', 'fxsr', 'sse', 'sse2', 'ss', 'ht', 'syscall', 'nx', 'rdtscp', 'lm', 'constant_tsc', 'rep_good', 'nopl', 'xtopology', 'cpuid', 'pni', 'pclmulqdq', 'ssse3', 'cx16', 'pcid', 'sse4_1', 'sse4_2', 'popcnt', 'aes', 'xsave', 'avx', 'f16c', 'rdrand', 'hypervisor', 'lahf_lm', 'pti', 'ssbd', 'ibrs', 'ibpb', 'stibp', 'fsgsbase', 'smep', 'erms', 'xsaveopt', 'flush_l1d', 'arch_capabilities']}
gcc_props:
 {'flags': ['128bit-long-double', '64', '80387', 'aes', 'align-stringops', 'avx', 'avx256-split-unaligned-load', 'avx256-split-unaligned-store', 'cx16', 'f16c', 'fancy-math-387', 'fp-ret-in-387', 'fsgsbase', 'fxsr', 'glibc', 'hard-float', 'ieee-fp', 'long-double-80', 'mmx', 'pclmul', 'popcnt', 'push-args', 'rdrnd', 'red-zone', 'sahf', 'sse', 'sse2', 'sse3', 'sse4', 'sse4.1', 'sse4.2', 'ssse3', 'stv', 'tls-direct-seg-refs', 'vzeroupper', 'xsave', 'xsaveopt'], 'arch': 'ivybridge'}
clang_props:
 {'flags': ['sse2', 'cx16', 'sahf', 'fsgsbase', 'popcnt', 'aes', 'mmx', 'xsave', '64bit', 'avx', 'cx8', 'rdrnd', 'sse4.1', 'sse4.2', 'fxsr', 'sse', 'pclmul', 'f16c', 'ssse3', 'cmov', 'xsaveopt', 'sse3'], 'arch': 'ivybridge'}
```

**Pull request closed without merging**
