### PR TITLE
Create an index _id/actions on the actions collection

### PR DESCRIPTION
**Pull request by vdbergh**
This should help with paging (though I am not sure).
    
At first I thought we could redefine the actions/_id index but we need this one for other queries.

### CODE REVIEW

**Comment by ppigazzini** [comment]
I can timeit a function/code on DEV before/after, let me know if this point is correct.

https://github.com/glinscott/fishtest/blob/d015b3b5a602712646d97a1860ff5d6befbe2c26/server/fishtest/views.py#L366

**Comment by vdbergh** [comment]
The question is if mongodb will pick up the index. In my local testing it did not, but of course I only have very small db.

**Comment by ppigazzini** [comment]
Ok, before the PR  8 seconds to get the last event page, now I'm rebuilding the index.

**Comment by ppigazzini** [comment]
It seems faster, 4 seconds, I restarted mongod to clear the cache.

**Comment by vdbergh** [comment]
No it is too slow. I think it is not picking up the index. Can you maybe to
```js
 db.actions.find({"action":{"$nin":["system_event","update_stats","dead_task"]}}).hint("_id_-1_action_1").skip(500000).limit(25).explain()
```
in mongosh?

**Comment by vdbergh** [comment]
Sorry I meant
```js
 db.actions.find({"action":{"$nin":["system_event","update_stats","dead_task"]}}).skip(500000).limit(25).explain()
```

**Comment by ppigazzini** [comment]
I restored master and rebuilt the index, now it's loading the last pages at 4 seconds...

**Comment by ppigazzini** [comment]
This is with master, I need to run mongosh with PR as well?

```yaml
db.actions.find({"action":{"$nin":["system_event","update_stats","dead_task"]}}).skip(500000).limit(25).explain()
{
  explainVersion: '1',
  queryPlanner: {
    namespace: 'test.actions',
    indexFilterSet: false,
    parsedQuery: {
      action: {
        '$not': { '$in': [ 'dead_task', 'system_event', 'update_stats' ] }
      }
    },
    maxIndexedOrSolutionsReached: false,
    maxIndexedAndSolutionsReached: false,
    maxScansToExplodeReached: false,
    winningPlan: { stage: 'EOF' },
    rejectedPlans: []
  },
  command: {
    find: 'actions',
    filter: {
      action: { '$nin': [ 'system_event', 'update_stats', 'dead_task' ] }
    },
    skip: 500000,
    limit: 25,
    '$db': 'test'
  },
  serverInfo: {
    host: 'dfts-0',
    port: 27017,
    version: '6.0.5',
    gitVersion: 'c9a99c120371d4d4c52cbb15dac34a36ce8d3b1d'
  },
  serverParameters: {
    internalQueryFacetBufferSizeBytes: 104857600,
    internalQueryFacetMaxOutputDocSizeBytes: 104857600,
    internalLookupStageIntermediateDocumentMaxSizeBytes: 104857600,
    internalDocumentSourceGroupMaxMemoryBytes: 104857600,
    internalQueryMaxBlockingSortMemoryUsageBytes: 104857600,
    internalQueryProhibitBlockingMergeOnMongoS: 0,
    internalQueryMaxAddToSetBytes: 104857600,
    internalDocumentSourceSetWindowFieldsMaxMemoryBytes: 104857600
  },
  ok: 1
}

```

**Comment by ppigazzini** [comment]
On DEV with PR:
```yaml
Current Mongosh Log ID: 6447e7214ba074cb54f1b354
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.8.0
Using MongoDB:          6.0.5
Using Mongosh:          1.8.0

For mongosh info see: ESC[1mhttps://docs.mongodb.com/mongodb-shell/ESC[0m

------
   The server generated these startup warnings when booting
   2023-04-25T16:39:59.897+02:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
   2023-04-25T16:40:01.133+02:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
   2023-04-25T16:40:01.133+02:00: vm.max_map_count is too low
------

------
   Free Monitoring URL:
   https://cloud.mongodb.com/freemonitoring/cluster/EXXEZBGNTROAEKIKXD5YMOE64KP267S4
------

test> switched to db fishtest_new
fishtest_new> {
  explainVersion: '1',
  queryPlanner: {
    namespace: 'fishtest_new.actions',
    indexFilterSet: false,
    parsedQuery: {
      action: {
        '$eq': { '': [ 'system_event', 'update_stats', 'dead_task' ] }
      }
    },
    queryHash: '28EACEB4',
    planCacheKey: '0F9D5258',
    maxIndexedOrSolutionsReached: false,
    maxIndexedAndSolutionsReached: false,
    maxScansToExplodeReached: false,
    winningPlan: {
      stage: 'LIMIT',
      limitAmount: 25,
      inputStage: {
        stage: 'FETCH',
        inputStage: {
          stage: 'SKIP',
          skipAmount: 500000,
          inputStage: {
            stage: 'IXSCAN',
            keyPattern: { action: 1, _id: -1 },
            indexName: 'action_1__id_-1',
            isMultiKey: false,
            multiKeyPaths: { action: [], _id: [] },
            isUnique: false,
            isSparse: false,
            isPartial: false,
            indexVersion: 2,
            direction: 'forward',
            indexBounds: {
              action: [
                '[{ : [ "system_event", "update_stats", "dead_task" ] }, { : [ "system_event", "update_stats", "dead_task" ] }]'
              ],
              _id: [ '[MaxKey, MinKey]' ]
            }
          }
        }
      }
    },
    rejectedPlans: []
  },
  command: {
    find: 'actions',
    filter: { action: { '': [ 'system_event', 'update_stats', 'dead_task' ] } },
    skip: 500000,
    limit: 25,
    '$db': 'fishtest_new'
  },
  serverInfo: {
    host: 'dfts-0',
    port: 27017,
    version: '6.0.5',
    gitVersion: 'c9a99c120371d4d4c52cbb15dac34a36ce8d3b1d'
  },
  serverParameters: {
    internalQueryFacetBufferSizeBytes: 104857600,
    internalQueryFacetMaxOutputDocSizeBytes: 104857600,
    internalLookupStageIntermediateDocumentMaxSizeBytes: 104857600,
    internalDocumentSourceGroupMaxMemoryBytes: 104857600,
    internalQueryMaxBlockingSortMemoryUsageBytes: 104857600,
    internalQueryProhibitBlockingMergeOnMongoS: 0,
    internalQueryMaxAddToSetBytes: 104857600,
    internalDocumentSourceSetWindowFieldsMaxMemoryBytes: 104857600
  },
  ok: 1
}
fishtest_new>
```

**Comment by vdbergh** [comment]
As I expected it using the wrong index `{ action: 1, _id: -1 }`. Can you maybe delete that index to force mongodb to use the new one?

**Comment by ppigazzini** [comment]
Suggest the command :)

**Comment by vdbergh** [comment]
This will make all other queries slower of course. It is just for testing.

**Comment by ppigazzini** [comment]
Done. Current indexes on actions:
```yaml
{ '_id_': {'key': [('_id', 1)], 'v': 2},
  '_id_-1_action_1': {'key': [('_id', -1), ('action', 1)], 'v': 2},
  'action_text_username_text_worker_text_message_text_run_text_user_text_nn_text__id_-1': { 'default_language': 'none',
                                                                                            'key': [ ( '_fts',
                                                                                                       'text'),
                                                                                                     ( '_ftsx',
                                                                                                       1),
                                                                                                     ( '_id',
                                                                                                       -1)],
                                                                                            'language_override': 'language',
                                                                                            'textIndexVersion': 3,
                                                                                            'v': 2,
                                                                                            'weights': SON([('action', 1), ('message', 1), ('nn', 1), ('run', 1), ('user', 1), ('username', 1), ('worker', 1)])},
  'run_id_1__id_-1': {'key': [('run_id', 1), ('_id', -1)], 'v': 2},
  'username_1__id_-1': {'key': [('username', 1), ('_id', -1)], 'v': 2}}
```

**Comment by vdbergh** [comment]
Hmm it seems to make little difference. Can you do the explain again?

**Comment by ppigazzini** [comment]
```yaml
Current Mongosh Log ID: 6447e9e5f1b5940679632abc
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.8.0
Using MongoDB:          6.0.5
Using Mongosh:          1.8.0

For mongosh info see: ESC[1mhttps://docs.mongodb.com/mongodb-shell/ESC[0m

------
   The server generated these startup warnings when booting
   2023-04-25T16:39:59.897+02:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
   2023-04-25T16:40:01.133+02:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
   2023-04-25T16:40:01.133+02:00: vm.max_map_count is too low
------

------
   Free Monitoring URL:
   https://cloud.mongodb.com/freemonitoring/cluster/EXXEZBGNTROAEKIKXD5YMOE64KP267S4
------

test> switched to db fishtest_new
fishtest_new> {
  explainVersion: '1',
  queryPlanner: {
    namespace: 'fishtest_new.actions',
    indexFilterSet: false,
    parsedQuery: {
      action: {
        '$eq': { '': [ 'system_event', 'update_stats', 'dead_task' ] }
      }
    },
    queryHash: '28EACEB4',
    planCacheKey: '9EDCC4DC',
    maxIndexedOrSolutionsReached: false,
    maxIndexedAndSolutionsReached: false,
    maxScansToExplodeReached: false,
    winningPlan: {
      stage: 'LIMIT',
      limitAmount: 25,
      inputStage: {
        stage: 'SKIP',
        skipAmount: 500000,
        inputStage: {
          stage: 'COLLSCAN',
          filter: {
            action: {
              '$eq': { '': [ 'system_event', 'update_stats', 'dead_task' ] }
            }
          },
          direction: 'forward'
        }
      }
    },
    rejectedPlans: []
  },
  command: {
    find: 'actions',
    filter: { action: { '': [ 'system_event', 'update_stats', 'dead_task' ] } },
    skip: 500000,
    limit: 25,
    '$db': 'fishtest_new'
  },
  serverInfo: {
    host: 'dfts-0',
    port: 27017,
    version: '6.0.5',
    gitVersion: 'c9a99c120371d4d4c52cbb15dac34a36ce8d3b1d'
  },
  serverParameters: {
    internalQueryFacetBufferSizeBytes: 104857600,
    internalQueryFacetMaxOutputDocSizeBytes: 104857600,
    internalLookupStageIntermediateDocumentMaxSizeBytes: 104857600,
    internalDocumentSourceGroupMaxMemoryBytes: 104857600,
    internalQueryMaxBlockingSortMemoryUsageBytes: 104857600,
    internalQueryProhibitBlockingMergeOnMongoS: 0,
    internalQueryMaxAddToSetBytes: 104857600,
    internalDocumentSourceSetWindowFieldsMaxMemoryBytes: 104857600
  },
  ok: 1
}
fishtest_new>
```

**Comment by ppigazzini** [comment]
I'm leaving for a hour.

**Comment by vdbergh** [comment]
I did some more experiments on my local system. It seems mongodb absolutely positively refuses to the right thing.  I do not understand enough of mongodb to debug this so closing.

**Comment by vdbergh** [comment]
Actually getting to the last page on DEV seems to be considerably faster than on PROD. So perhaps it is doing something after all...

**Comment by ppigazzini** [comment]
DEV has been on master (with old indexes) for 5 minutes.

**Comment by ppigazzini** [comment]
Testing this on PROD and on DEV with `time bash time_actions.sh`:
```
#!/bin/bash
for i in {0..20000..1000}: do
    curl https://dfts-0.pigazzini.it/actions?page=${i} > /dev/null
done

```

**Comment by ppigazzini** [comment]
Yes, PROD takes 1.5x
Now I'm testing DEV with the PR, I will update the previous post.

**Comment by vdbergh** [comment]
```
DEV on master

real    0m41.659s
user    0m0.425s
sys     0m0.265s

PROD on master

real    1m13.267s
user    0m0.361s
sys     0m0.153s
```
So PROD is slower than DEV....

**Comment by ppigazzini** [comment]
Usually PROD is faster than DEV courtesy of a faster hard disk (but with cloud instances things can change).

**Comment by ppigazzini** [comment]
The first run is slow, the successive runs are faster also changing the starting page.
I redone the timing using the second runs changing the starting page.

DEV on PR:
```
real    0m43.817s
user    0m0.704s
sys     0m0.571s
```

PROD on master:
```
real    0m55.548s
user    0m0.352s
sys     0m0.157s
```

**Comment by ppigazzini** [comment]
DEV on master seems still 2x faster than PROD and DEV on PR.

**Comment by xoto10** [comment]
@vdbergh 
Looking at e.g. https://github.com/glinscott/fishtest/blob/d55f68f839c1736332b7d67c51430631cc55d24b/server/fishtest/actiondb.py#L114

can this be re-written using `$in` ?

I suspect this is the last query in https://github.com/glinscott/fishtest/issues/1629#issuecomment-1522792372 and it should work well if the required actions are listed instead of using `$nin`

**Comment by xoto10** [comment]
And do we have a way to list the current indexes on a collection in Prod without running create_indexes?

I'm wondering what the current indexes on actions are? Do you know what that compound index on 8 fields is used for?

**Comment by ppigazzini** [comment]
```yaml
${VENV}/bin/python3 create_indexes.py
Current indexes on user_cache:
{'_id_': {'key': [('_id', 1)], 'v': 2}, 'username_1': {'key': [('username', 1)], 'unique': True, 'v': 2}}

Current indexes on top_month:
{'_id_': {'key': [('_id', 1)], 'v': 2}}

Current indexes on pgns:
{'_id_': {'key': [('_id', 1)], 'v': 2}, 'run_id_-1': {'key': [('run_id', -1)], 'v': 2}}

Current indexes on users:
{'_id_': {'key': [('_id', 1)], 'v': 2}, 'username_1': {'key': [('username', 1)], 'unique': True, 'v': 2}}

Current indexes on actions:
{ '_id_': {'key': [('_id', 1)], 'v': 2},
  'action_1__id_-1': {'key': [('action', 1), ('_id', -1)], 'v': 2},
  'action_text_username_text_worker_text_message_text_run_text_user_text_nn_text__id_-1': { 'default_language': 'none',
                                                                                            'key': [ ( '_fts',
                                                                                                       'text'),
                                                                                                     ( '_ftsx',
                                                                                                       1),
                                                                                                     ( '_id',
                                                                                                       -1)],
                                                                                            'language_override': 'language',
                                                                                            'textIndexVersion': 3,
                                                                                            'v': 2,
                                                                                            'weights': SON([('action', 1), ('message', 1), ('nn', 1), ('run', 1), ('user', 1), ('username', 1), ('worker', 1)])},
  'run_id_1__id_-1': {'key': [('run_id', 1), ('_id', -1)], 'v': 2},
  'username_1__id_-1': {'key': [('username', 1), ('_id', -1)], 'v': 2}}

Current indexes on runs:
{ '_id_': {'key': [('_id', 1)], 'v': 2},
  'finished_green_runs': { 'key': [('finished', 1), ('is_green', -1), ('last_updated', -1)],
                           'partialFilterExpression': SON([('finished', True), ('is_green', True)]),
                           'v': 2},
  'finished_ltc_runs': { 'key': [('finished', 1), ('last_updated', -1), ('tc_base', -1)],
                         'partialFilterExpression': SON([('finished', True), ('tc_base', SON([('$gte', 40)]))]),
                         'v': 2},
  'finished_runs': { 'key': [('finished', 1), ('last_updated', -1)],
                     'partialFilterExpression': SON([('finished', True)]),
                     'v': 2},
  'finished_user_runs': { 'key': [('args.username', -1), ('finished', 1), ('last_updated', -1)],
                          'partialFilterExpression': SON([('finished', True)]),
                          'v': 2},
  'finished_yellow_runs': { 'key': [('finished', 1), ('is_yellow', -1), ('last_updated', -1)],
                            'partialFilterExpression': SON([('finished', True), ('is_yellow', True)]),
                            'v': 2},
  'unfinished_runs': { 'key': [('finished', 1)],
                       'partialFilterExpression': SON([('finished', False)]),
                       'v': 2},
  'user_runs': {'key': [('args.username', -1), ('last_updated', -1)], 'v': 2}}

Current indexes on deltas:
{'_id_': {'key': [('_id', 1)], 'v': 2}}

Current indexes on nns:
{'_id_': {'key': [('_id', 1)], 'v': 2}, 'name_-1': {'key': [('name', -1)], 'v': 2}}

Collections in fishtest_new: ['user_cache', 'top_month', 'pgns', 'users', 'actions', 'runs', 'deltas', 'nns']
Give a list of collection names as arguments to re-create indexes. For example:

  python3 create_indexes.py users runs - drops and creates indexes for runs and users
```

**Comment by xoto10** [comment]
Ah, I understand now. Reading the code more closely, it doesn't create the indexes unless you tell it to, it just lists them. I didn't know that earlier.

**Pull request closed without merging**
