### PR TITLE
Rewrite the SPRT Calculator using Google Charts.

### PR DESCRIPTION
**Pull request by vdbergh**
Google Charts are already used at other places in Fishtest and people are familiar with it.

The latest version can be found here.

http://hardy.uhasselt.be/Toga/SPRTcalculator.html

### CODE REVIEW

**Comment by vdbergh** [comment]
I discovered the cause of the dead zone and the flicker in the neighborhood of the curve. Will update.

**Comment by vdbergh** [comment]
Ok updated.

http://hardy.uhasselt.be/Toga/SPRTcalculator.html

**Comment by ppigazzini** [comment]
@vdbergh https://dfts-0.pigazzini.it updated with this PR, it's looks good to me.
I will merge it as soon as you will shorten this:
https://github.com/glinscott/fishtest/blob/591a401dc6a144d7c4dd4324adf3e6909a9030fd/fishtest/fishtest/templates/base.mak#L65

**Comment by vdbergh** [comment]
Done :)

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
