### PR TITLE
Immediately stop runs

### PR DESCRIPTION
**Pull request by tomtor**
instead of relying on some auto_purge actions

See #395

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor dev server updated but no time to make tests now. I will be online in a couple of hours.

**Comment by ppigazzini** [comment]
@tomtor evil runs signed failed at first wrong bench. Let me know if you want some other tests or I can merge on the fly.

**Comment by tomtor** [comment]
This should be low risk so merging is ok for me.

**Comment by ppigazzini** [comment]
Prod server updated, thank you @tomtor

**Pull request merged**
