### PR TITLE
Use a short pagination

### PR DESCRIPTION
**Pull request by ppigazzini**

### CODE REVIEW

**Comment by vondele** [comment]
still a tiny bit too wide on my phone (assuming fishtest is updated right now)

**Comment by dav1312** [comment]
What about something like this? Having Prev, first, last and Next always and then 5 "cells" beween them

image

image

image

image

**Comment by ppigazzini** [comment]
> What about something like this? Having Prev, first, last and Next always and then 5 "cells" beween them

Approved! I will update the code in a couple of hours.

**Comment by ppigazzini** [comment]
PROD updated.

**Comment by vondele** [comment]
that's nice.

**Pull request merged**
