### PR TITLE
Add button to copy command for fetching diff and git-apply'ing it

### PR DESCRIPTION
**Pull request by linrock**
Adds a button to the diff section of tests_view pages to copy a command for fetching the diff and then git-applying the diff in a Stockfish repo. Fixes https://github.com/glinscott/fishtest/issues/590

Example of a copied command:
`curl -s https://github.com/pb00068/Stockfish/compare/5c58f67...5431821.diff | git apply`

---
image

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated, the script works but `/img/clipboard.png` is missing in action :)

**Comment by linrock** [comment]
oops, `/img/clipboard.png` is there now

**Comment by ppigazzini** [comment]
PROD updated, thank you @linrock :)

**Comment by vondele** [comment]
@ppigazzini I updated the issue with an error I'm currently seeing on PROD.

**Comment by ppigazzini** [comment]
@vondele I fixed by hand, please try now with firefox (chrome and edge worked fine for me)

**Comment by vondele** [comment]
yep works... thanks!

**Comment by ppigazzini** [comment]
Fine, I'm opening a PR :)

**Pull request merged**
