### PR TITLE
Use 10 digits of the sha

### PR DESCRIPTION
**Pull request by vondele**
avoids rare cases where 7 is not enough.

Fixes https://github.com/glinscott/fishtest/issues/688

### CODE REVIEW

**Comment by ppigazzini** [comment]
@vondele DEV now shows the diff
https://dfts-0.pigazzini.it/tests/view/5ecc351980f2c838b965580b

Please raise also the worker version.
https://github.com/glinscott/fishtest/blob/fea6729d1b52bbb04824ba7d4401a0eb171dfeab/worker/worker.py#L31

**Comment by vondele** [comment]
done.

**Comment by vondele** [comment]
BTW, just ran into this  
https://stackoverflow.com/questions/18134627/how-much-of-a-git-sha-is-generally-considered-necessary-to-uniquely-identify-a 
linux kernel uses 12 digits, but 10 should be enough for most projects seemingly.

**Comment by ppigazzini** [comment]
Test on DEV are all OK.
Let me know if you want merge now with 10 digits or wait tomorrow :)

**Comment by vondele** [comment]
either is fine. 10 digits will be OK till we have 100k commits :-)

**Comment by ppigazzini** [comment]
PROD updated, thank you @vondele :)

@noobpwnftw please update your workers fleet at your convenience :)
After that I will force the update for other workers.

**Pull request merged**
