### PR TITLE
Add hyperlink to hardy.uhasselt.be/Toga/live_elo

### PR DESCRIPTION
**Pull request by tomtor**
and a proper stop() to rundb.

Also some minor tweaks to the Travis test.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor updated dev-server and workers, test started.

**Comment by tomtor** [comment]
@ppigazzini Thanks!

**Comment by tomtor** [comment]
@Stefano80 It deletes (x) the run. The point is that it should be the last test run. test_delete_run was run as second test. It is executed in alphabetic order. An alternative is prepending 00, 01, 02 to the test name?

**Comment by tomtor** [comment]
@Stefano80 Added 10, 20, 30 as prefix, as is done in other scripts where order is important...

**Comment by Stefano80** [comment]
Ah ok. It is specified in unit test that the order is important? I would actually solve this by writing helper methods and call them in the desired order in the test methods.

You can also make use of the setup methods in the class.

**Comment by tomtor** [comment]
@Stefano80 Not sure how to rewrite it, please post the setup class code you prefer

**Comment by Stefano80** [comment]
For me it's ok like it is now, if in python unit test it is specified that the order is alphabetical. In the next days I will see whether I can improve on this.

**Comment by Stefano80** [comment]
Commited, restarted service. Thank you @tomtor , this is a simple yet effective improvement for UX.

**Comment by tomtor** [comment]
It was a feature request by @snicolet a while ago

**Comment by snicolet** [comment]
Supercool :-)

**Pull request merged**
