### PR TITLE
Increase active timeout settings

### PR DESCRIPTION
**Pull request by tomtor**
Increase timeout settings because we now batch SPSA results.

In addition workers with 7 or more cores will never show as active because they post only results after 200 played games.
This is caused by a batch size of 32*concurrency.

@vondele I remember you suggested to increase this setting? What would you suggest?

We could adjust with concurrency of workers and NPS.

EDIT: See also https://github.com/glinscott/fishtest/issues/809

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor `scavenge.py` tested working on DEV loading a DB backup (several workers passed the timeout). 

While here please fix this warning:
```
scavenge.py:31: DeprecationWarning: save is deprecated. Use insert_one or replace_one instead
  rundb.runs.save(run)
```

**Comment by vondele** [comment]
@tomtor, not sure what to suggest. 

Probably it needs to be actually something depending on batch size, concurrency and TC? We can expect games to run for 
sf * estimate_game_duration(tc) * batch_size * threads / concurrency
where sf is some kind of scale factor probably ~ 4.

**Comment by ppigazzini** [comment]
We compute/use a tc_limit in `games.py`

https://github.com/glinscott/fishtest/blob/b5cf10759ab5f6b7329e6cfadbd25600d8e87178/worker/games.py#L451

https://github.com/glinscott/fishtest/blob/b5cf10759ab5f6b7329e6cfadbd25600d8e87178/worker/games.py#L1003-L1004

https://github.com/glinscott/fishtest/blob/b5cf10759ab5f6b7329e6cfadbd25600d8e87178/worker/games.py#L1102

https://github.com/glinscott/fishtest/blob/b5cf10759ab5f6b7329e6cfadbd25600d8e87178/worker/games.py#L586-L590

**Comment by tomtor** [comment]
> While here please fix this warning:

Done

**Comment by tomtor** [comment]
@vondele @ppigazzini I don't want to complicate the code too much, because the timeout is just a safety net for crashed workers. Normally on CTRL-C a worker will send a sign-off message.

So the timeout should just be not too small, but indeed ideally it takes TC/threads/etc into account.

I can live with just using `concurrency` to adjust a large timeout.

**Comment by vondele** [comment]
OK, let's keep it simple, I don't know the code will enough to suggest otherwise :)

**Comment by tomtor** [comment]
@ppigazzini I will change the PR tomorrow to skip scaling for SPSA tests...

**Comment by tomtor** [comment]
@ppigazzini I think this can be commited.

First step is to update the workers, after that we can update the hand-patched code on the prod server with this PR.

It is not critical, we can also update/restart the server earlier, timeout values are better than the old master and the issue is mostly cosmetic.

**Comment by ppigazzini** [comment]
@tomtor great, I can do that this afternoon.

**Comment by ppigazzini** [comment]
@tomtor updated DEV and some workers.

**Comment by ppigazzini** [comment]
Thank you @tomtor :)
PROD updated (I want to merge some night mode PRs). Some git objects had wrong ownership (?!?) and the usual pull failed, I reinstalled fishtest with `x/update_fishtest.h`, now git works fine.

@noobpwnftw please update the fleet at your convenience :)

**Comment by noobpwnftw** [comment]
@ppigazzini Updated.

**Pull request merged**
