### PR TITLE
Make it so that the sprt object is only updated in a single location.

### PR DESCRIPTION
**Pull request by vdbergh**
This will hopefully fix the occasional loss of overshoot data.

### CODE REVIEW

**Comment by ppigazzini** [comment]
Tests started on DEV.

**Comment by vdbergh** [comment]
Thanks! It seems the code causes an exception when looking at older tests. This is not the case on my installation. Are such exceptions logged?

**Comment by vdbergh** [comment]
I made an extra commit with recomputes the upper/lower bound fields in the sprt object to deal with earlier tests.

**Comment by ppigazzini** [comment]
DEV updated, hoping in a @tomtor review, my server side knowledge is too low to help.

**Comment by vdbergh** [comment]
@tomtor I am continuing the discussion here. It seems that the sprt object seen by `update_task` is at least sometimes the same as the one seen by `format_results`. I printed out the id's.

```
format_results 140694687141640
update_task 140694687141640
update_task 140694687141640
format_results 140694677086728
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
format_results 140694687141640
update_task 140694687141640
update_task 140694687141640
update_task 140694687141640
```

With the current PR `format_results` will no longer call `SPRT` (renamed as `update_SPRT`). It will just faithfully display what is already in the `sprt` object that it is given.

**Comment by tomtor** [comment]
@vdbergh This PR is ok, but you should be aware that the main view shows outdated info from run-objects retrieved from MongoDb. These objects have the same id as those used in update_task, but they contain older data. So number of played games shown on the main page can be lower than shown on the individual test page.

**Comment by vdbergh** [comment]
@ppigazzini  With the additional commit there are no longer exceptions when looking at older tests, it seems.

**Comment by ppigazzini** [comment]
@vdbergh I will test a bit tonight before merging.

**Comment by tomtor** [comment]
> Updating the sprt object while building the main page should not lead to a race condition as the object that would be updated is discarded afterwards (I assume).

Yes, that is correct

**Comment by ppigazzini** [comment]
@vdbergh please squash :)

**Comment by vdbergh** [comment]
Squashed.

Overshoots of random walks is really fascinating stuff. There is some deep math involved. There is for example an important connection with the zeta function.

https://projecteuclid.org/download/pdf_1/euclid.aop/1024404419

(Theorem 1.1).

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh!

ps: learned a bit about random walk and martingale

**Pull request merged**
