### PR TITLE
Dark mode refinements

### PR DESCRIPTION
**Pull request by SFisGOD**
Closes https://github.com/glinscott/fishtest/pull/1008

### CODE REVIEW

**Comment by SFisGOD** [comment]
@ppigazzini Please update DEV :)

**Comment by ppigazzini** [comment]
[DEV](https://dfts-0.pigazzini.it) update, problem still there.

**Comment by SFisGOD** [comment]
Okay let me check

**Comment by SFisGOD** [comment]
@ppigazzini Why was this altered?
https://github.com/glinscott/fishtest/blob/67518594c0867626aef3aec062c5b9fac5ab7a9a/server/fishtest/templates/elo_results.mak

**Comment by ppigazzini** [comment]
To add a pink border to the widget of "time odds" test.
DEV updated, something is improved.

**Comment by SFisGOD** [comment]
Ahh to indicate that it's a time odds test.

**Comment by SFisGOD** [comment]
I will push, but need to update integrity again, wait ....

**Comment by SFisGOD** [comment]
@ppigazzini Please update DEV

**Comment by ppigazzini** [comment]
DEV updated, looks good to me. Please double check, if it's all ok squash.

**Comment by SFisGOD** [comment]
Maybe I should darken the pink border in dark mode

**Comment by ppigazzini** [comment]
Feel free to experiment :)

**Comment by SFisGOD** [comment]
Is this fine?
image

**Comment by ppigazzini** [comment]
Yes.

On DEV I set `border-radius:5px;'` here, seems fine:
https://github.com/glinscott/fishtest/blob/9ef5981bdcbcd7e0d7aa5390aa2d2752d38ca02f/server/fishtest/templates/elo_results.mak#L12

**Comment by ppigazzini** [comment]
More simple, delete `border-radius`:
```python
ret+='border-style:solid;border-color:Pink;border-width:medium;' 
```

@vdbergh do you squared the widget on purpose?

**Comment by ppigazzini** [comment]
DEV updated, IMO better to delete `border-radius:` and keep the default.

**Comment by SFisGOD** [comment]
image
`border-radius:10px` adds a rounded corner effect to better distinguish the time odds tests

**Comment by SFisGOD** [comment]
> DEV updated, IMO better to delete `border-radius:` from both light/dark themes and keep the default corner rounding.

Okay wait

**Comment by vdbergh** [comment]
@ppigazzini No not really. I actually had not noticed that the normal widgets are also rounded.  I am fine with rounding the border.

I also did not think of dark mode since I never use it. If different versions of the border will be used then perhaps it would be better to use a proper css class for it, instead of inline styling. 

I must confess I have not looked how dark mode works exactly.

**Comment by SFisGOD** [comment]
@ppigazzini Is it fine now?

**Comment by ppigazzini** [comment]
Yes.

**Comment by SFisGOD** [comment]
@ppigazzini Squashed and force pushed :)

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @SFisGOD :)

**Pull request merged**
