### PR TITLE
Handle some 2013 runs without 'worker_info'

### PR DESCRIPTION
**Pull request by tomtor**
Eg: http://tests.stockfishchess.org/tests/view/511c69688f0c3e39b391362e

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor dev-server updated, that test is now fine.
Anyway I found an error for this test:
https://dfts-2.pigazzini.it/tests/view/51251e398f0c3e5b3742696f

**Comment by tomtor** [comment]
> @tomtor dev-server updated, that test is now fine.
> Anyway I found an error for this test:
> https://dfts-2.pigazzini.it/tests/view/51251e398f0c3e5b3742696f

Could you send me the error log from dev-server? Prod crashes on the code line from this PR on your test URL so I cannot see the new error on prod. Note that it only crashes when logged in as approver.

**Comment by ppigazzini** [comment]
@tomtor you are right, error only when logged as approver:
```
Nov 25 13:51:05 vps1572612706 systemd[1]: Stopping Fishtest Server port 6543...
Nov 25 13:51:05 vps1572612706 systemd[1]: Stopped Fishtest Server port 6543.
Nov 25 13:51:36 vps1572612706 systemd[1]: Started Fishtest Server port 6543.
Nov 25 13:51:44 vps1572612706 pserve[5730]: /home/usr00/fishtest/fishtest/fishtest/views.py:749: RuntimeWarning: invalid value encountered in divide
Nov 25 13:51:44 vps1572612706 pserve[5730]:   residual = diff / numpy.sqrt(expected * adj)
Nov 25 13:51:44 vps1572612706 pserve[5730]: /home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
Nov 25 13:51:44 vps1572612706 pserve[5730]:   return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
Nov 25 13:52:34 vps1572612706 pserve[5730]: 2019-11-25 13:52:34,439 ERROR [waitress][waitress] Exception while serving /tests/view/51251e398f0c3e5b3742696f
Nov 25 13:52:34 vps1572612706 pserve[5730]: Traceback (most recent call last):
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/waitress/channel.py", line 356, in service
Nov 25 13:52:34 vps1572612706 pserve[5730]:     task.service()
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/waitress/task.py", line 172, in service
Nov 25 13:52:34 vps1572612706 pserve[5730]:     self.execute()
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/waitress/task.py", line 440, in execute
Nov 25 13:52:34 vps1572612706 pserve[5730]:     app_iter = self.channel.server.application(environ, start_response)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/waitress/proxy_headers.py", line 62, in translate_proxy_headers
Nov 25 13:52:34 vps1572612706 pserve[5730]:     return app(environ, start_response)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/router.py", line 270, in __call__
Nov 25 13:52:34 vps1572612706 pserve[5730]:     response = self.execution_policy(environ, self)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/router.py", line 279, in default_execution_policy
Nov 25 13:52:34 vps1572612706 pserve[5730]:     return request.invoke_exception_view(reraise=True)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/view.py", line 778, in invoke_exception_view
Nov 25 13:52:34 vps1572612706 pserve[5730]:     reraise_(*exc_info)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/router.py", line 277, in default_execution_policy
Nov 25 13:52:34 vps1572612706 pserve[5730]:     return router.invoke_request(request)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
Nov 25 13:52:34 vps1572612706 pserve[5730]:     response = handle_request(request)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 43, in excview_tween
Nov 25 13:52:34 vps1572612706 pserve[5730]:     response = _error_handler(request, exc)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 17, in _error_handler
Nov 25 13:52:34 vps1572612706 pserve[5730]:     reraise(*exc_info)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
Nov 25 13:52:34 vps1572612706 pserve[5730]:     response = handler(request)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/router.py", line 148, in handle_request
Nov 25 13:52:34 vps1572612706 pserve[5730]:     registry, request, context, context_iface, view_name
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/view.py", line 667, in _call_view
Nov 25 13:52:34 vps1572612706 pserve[5730]:     response = view_callable(context, request)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 460, in rendered_view
Nov 25 13:52:34 vps1572612706 pserve[5730]:     request, result, view_inst, context
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/renderers.py", line 451, in render_view
Nov 25 13:52:34 vps1572612706 pserve[5730]:     return self.render_to_response(response, system, request=request)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/renderers.py", line 474, in render_to_response
Nov 25 13:52:34 vps1572612706 pserve[5730]:     result = self.render(value, system_values, request=request)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid/renderers.py", line 470, in render
Nov 25 13:52:34 vps1572612706 pserve[5730]:     result = renderer(value, system_values)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 156, in __call__
Nov 25 13:52:34 vps1572612706 pserve[5730]:     reraise(MakoRenderingException(errtext), None, exc_info[2])
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
Nov 25 13:52:34 vps1572612706 pserve[5730]:     result = template.render_unicode(**system)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/mako/template.py", line 482, in render_unicode
Nov 25 13:52:34 vps1572612706 pserve[5730]:     self, self.callable_, args, data, as_unicode=True
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/mako/runtime.py", line 883, in _render
Nov 25 13:52:34 vps1572612706 pserve[5730]:     **_kwargs_for_callable(callable_, data)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/mako/runtime.py", line 920, in _render_context
Nov 25 13:52:34 vps1572612706 pserve[5730]:     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/mako/runtime.py", line 947, in _exec_template
Nov 25 13:52:34 vps1572612706 pserve[5730]:     callable_(context, *args, **kwargs)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "base_mak", line 37, in render_body
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "tests_view_mak", line 166, in render_body
Nov 25 13:52:34 vps1572612706 pserve[5730]: MakoRenderingException:
Nov 25 13:52:34 vps1572612706 pserve[5730]: Traceback (most recent call last):
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
Nov 25 13:52:34 vps1572612706 pserve[5730]:     result = template.render_unicode(**system)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/mako/template.py", line 482, in render_unicode
Nov 25 13:52:34 vps1572612706 pserve[5730]:     self, self.callable_, args, data, as_unicode=True
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/mako/runtime.py", line 883, in _render
Nov 25 13:52:34 vps1572612706 pserve[5730]:     **_kwargs_for_callable(callable_, data)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/mako/runtime.py", line 920, in _render_context
Nov 25 13:52:34 vps1572612706 pserve[5730]:     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/env/local/lib/python2.7/site-packages/mako/runtime.py", line 947, in _exec_template
Nov 25 13:52:34 vps1572612706 pserve[5730]:     callable_(context, *args, **kwargs)
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/fishtest/templates/base.mak", line 83, in render_body
Nov 25 13:52:34 vps1572612706 pserve[5730]:     ${self.body()}
Nov 25 13:52:34 vps1572612706 pserve[5730]:   File "/home/usr00/fishtest/fishtest/fishtest/templates/tests_view.mak", line 177, in render_body
Nov 25 13:52:34 vps1572612706 pserve[5730]:     <td><a href="/user/${task['worker_info']['username']}">${task['worker_key']}</a></td>
Nov 25 13:52:34 vps1572612706 pserve[5730]: KeyError: 'username'
```

**Comment by ppigazzini** [comment]
@tomtor I'm wondering if could be more simple to check if a data in the collection has all the variables expected and, in case, add a default/void for the missing variables. I'm talking about an one time DB update.

**Comment by tomtor** [comment]
> I'm wondering if could be more simple to check if a data in the collection has all the variables expected and, in case, add a default/void for the missing variables

@ppigazzini I hope we do not find other cases than the current one...

Could you please retest with last commit?

**Comment by ppigazzini** [comment]
@tomtor:

https://dfts-2.pigazzini.it/tests/view/511c69688f0c3e39b391362e
* no login: OK
* login normal user: OK
* login approver: OK

https://dfts-2.pigazzini.it/tests/view/51251e398f0c3e5b3742696f
* no login: OK
* login normal user: OK
* login approver: OK

Tonight I will check randomly other old tests, hopefully I will be able to push the "Rebase and merge" button :)

**Comment by ppigazzini** [comment]
Prod-server update, great work @tomtor !

The first sprt test:
https://dfts-2.pigazzini.it/tests/view/515c71c78f0c3e0d3d02c7bc

There is a 2013 test still pending :)
https://tests.stockfishchess.org/tests/view/5163bea28f0c3e4841a1cfc7

**Pull request merged**
