### PR TITLE
Experiment: clean up indexes.

### PR DESCRIPTION
**Pull request by vdbergh**
Rationalize indexes according to #1242

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated:

```
~$ ${VENV}/bin/python3 ${HOME}/fishtest/server/utils/create_indexes.py actions flag_cache pgns runs users
Re-creating indexes...

Dropping indexes on actions
Current indexes: ['_id_', 'username_1__id_-1', 'action_1__id_-1']
Dropping actions index username_1__id_-1 ...
Dropping actions index action_1__id_-1 ...

Dropping indexes on flag_cache
Current indexes: ['_id_', 'ip_1', 'geoip_checked_at_1']
Dropping flag_cache index ip_1 ...
Dropping flag_cache index geoip_checked_at_1 ...

Dropping indexes on pgns
Current indexes: ['_id_']
Creating indexes on pgns collection

Dropping indexes on runs
Current indexes: ['_id_', 'finished_runs', 'finished_green_runs', 'finished_yellow_runs', 'finished_ltc_runs', 'user_runs', 'unfinished_runs']
Dropping runs index finished_runs ...
Dropping runs index finished_green_runs ...
Dropping runs index finished_yellow_runs ...
Dropping runs index finished_ltc_runs ...
Dropping runs index user_runs ...
Dropping runs index unfinished_runs ...
Creating indexes on runs collection

Dropping indexes on users
Current indexes: ['_id_', 'username_1']
Dropping users index username_1 ...
Finished creating indexes!

Current indexes on runs:
{ '_id_': {'key': [('_id', 1)], 'v': 2},
  'finished_green_runs': { 'key': [('finished', 1), ('is_green', -1), ('last_updated', -1)],
                           'partialFilterExpression': SON([('finished', True), ('is_green', True)]),
                           'v': 2},
  'finished_ltc_runs': { 'key': [('finished', 1), ('last_updated', -1), ('tc_base', -1)],
                         'partialFilterExpression': { 'finished': True,
                                                      'tc_base': SON([('$gte', 40)])},
                         'v': 2},
  'finished_runs': { 'key': [('finished', 1), ('last_updated', -1)],
                     'partialFilterExpression': SON([('finished', True)]),
                     'v': 2},
  'finished_yellow_runs': { 'key': [('finished', 1), ('is_yellow', -1), ('last_updated', -1)],
                            'partialFilterExpression': SON([('finished', True), ('is_yellow', True)]),
                            'v': 2},
  'unfinished_runs': { 'key': [('finished', 1), ('last_updated', 1)],
                       'partialFilterExpression': SON([('finished', False)]),
                       'v': 2},
  'user_runs': {'key': [('args.username', -1), ('last_updated', -1)], 'v': 2}}

Current indexes on old_user_cache:
{'_id_': {'key': [('_id', 1)], 'v': 2}}

Current indexes on regression_data:
{'_id_': {'key': [('_id', 1)], 'v': 2}}

Current indexes on actions:
{ '_id_': {'key': [('_id', 1)], 'v': 2},
  'action_1__id_-1': {'key': [('action', 1), ('_id', -1)], 'v': 2},
  'username_1__id_-1': {'key': [('username', 1), ('_id', -1)], 'v': 2}}

Current indexes on deltas:
{'_id_': {'key': [('_id', 1)], 'v': 2}}

Current indexes on pgns:
{'_id_': {'key': [('_id', 1)], 'v': 2}, 'run_id_-1': {'key': [('run_id', -1)], 'v': 2}}

Current indexes on user_cache:
{'_id_': {'key': [('_id', 1)], 'v': 2}, 'username_1': {'key': [('username', 1)], 'unique': True, 'v': 2}}

Current indexes on clop:
{'_id_': {'key': [('_id', 1)], 'v': 2}}

Current indexes on flag_cache:
{ '_id_': {'key': [('_id', 1)], 'v': 2},
  'geoip_checked_at_1': {'expireAfterSeconds': 604800, 'key': [('geoip_checked_at', 1)], 'v': 2},
  'ip_1': {'key': [('ip', 1)], 'v': 2}}

Current indexes on users:
{'_id_': {'key': [('_id', 1)], 'v': 2}, 'username_1': {'key': [('username', 1)], 'unique': True, 'v': 2}}

Current indexes on nns:
{'_id_': {'key': [('_id', 1)], 'v': 2}, 'name_-1': {'key': [('name', -1)], 'v': 2}}

Current indexes on top_month:
{'_id_': {'key': [('_id', 1)], 'v': 2}}
```

**Comment by vdbergh** [comment]
Try clicking on old pages...(in the pager for finished runs).

**Comment by ppigazzini** [comment]
The users page is loading in two steps, first a dozen of users then all (same on PROD), never was before.

image

**Comment by vdbergh** [comment]
If it is the same on PROD then it is not related to this PR...

I think this is just the result of the user page being very long. I looked on firefox and there were no artifacts AFAICS.

**Comment by ppigazzini** [comment]
Time to run the script on DEV:
real    1m12.795s
user    0m0.238s
sys     0m0.049s

Let me know when I can merge :)

**Comment by vdbergh** [comment]
What seems to be happening on Chrome is on the fly reformatting. Chrome starts rendering the table and then notices that the rightmost column is not wide enough. Then it redraws the table. 

This could probably be fixed by setting the width of the rightmost column beforehand.

**Comment by vdbergh** [comment]
> Time to run the script on DEV: real 1m12.795s user 0m0.238s sys 0m0.049s
> 
> Let me know when I can merge :)

I think it can be merged.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
Thank you @vdbergh :)

PROD updated:
```
$ time sudo bash create_indexes.sh | tee create_indexes.sh.log
Re-creating indexes...

Dropping indexes on runs
Current indexes: ['_id_', 'unfinished_runs', 'finished_runs', 'finished_green_runs', 'finished_yellow_runs', 'finished_ltc_runs', 'user_runs']
Dropping runs index unfinished_runs ...
Dropping runs index finished_runs ...
Dropping runs index finished_green_runs ...
Dropping runs index finished_yellow_runs ...
Dropping runs index finished_ltc_runs ...
Dropping runs index user_runs ...
Creating indexes on runs collection
Finished creating indexes!

Current indexes on user_cache:
{'_id_': {'key': [('_id', 1)], 'v': 2}, 'username_1': {'key': [('username', 1)], 'unique': True, 'v': 2}}

Current indexes on top_month:
{'_id_': {'key': [('_id', 1)], 'v': 2}}

Current indexes on clop:
{'_id_': {'key': [('_id', 1)], 'v': 2}}

Current indexes on old_user_cache:
{'_id_': {'key': [('_id', 1)], 'v': 2}}

Current indexes on pgns:
{'_id_': {'key': [('_id', 1)], 'v': 2}, 'run_id_-1': {'key': [('run_id', -1)], 'v': 2}}

Current indexes on users:
{'_id_': {'key': [('_id', 1)], 'v': 2}, 'username_1': {'key': [('username', 1)], 'unique': True, 'v': 2}}

Current indexes on regression_data:
{'_id_': {'key': [('_id', 1)], 'v': 2}}

Current indexes on actions:
{ '_id_': {'key': [('_id', 1)], 'v': 2},
  'action_1__id_-1': {'key': [('action', 1), ('_id', -1)], 'v': 2},
  'username_1__id_-1': {'key': [('username', 1), ('_id', -1)], 'v': 2}}

Current indexes on runs:
{ '_id_': {'key': [('_id', 1)], 'v': 2},
  'finished_green_runs': { 'key': [('finished', 1), ('is_green', -1), ('last_updated', -1)],
                           'partialFilterExpression': SON([('finished', True), ('is_green', True)]),
                           'v': 2},
  'finished_ltc_runs': { 'key': [('finished', 1), ('last_updated', -1), ('tc_base', -1)],
                         'partialFilterExpression': { 'finished': True,
                                                      'tc_base': SON([('$gte', 40)])},
                         'v': 2},
  'finished_runs': { 'key': [('finished', 1), ('last_updated', -1)],
                     'partialFilterExpression': SON([('finished', True)]),
                     'v': 2},
  'finished_yellow_runs': { 'key': [('finished', 1), ('is_yellow', -1), ('last_updated', -1)],
                            'partialFilterExpression': SON([('finished', True), ('is_yellow', True)]),
                            'v': 2},
  'unfinished_runs': { 'key': [('finished', 1), ('last_updated', 1)],
                       'partialFilterExpression': SON([('finished', False)]),
                       'v': 2},
  'user_runs': {'key': [('args.username', -1), ('last_updated', -1)], 'v': 2}}

Current indexes on deltas:
{'_id_': {'key': [('_id', 1)], 'v': 2}}

Current indexes on nns:
{'_id_': {'key': [('_id', 1)], 'v': 2}, 'name_-1': {'key': [('name', -1)], 'v': 2}}

Current indexes on flag_cache:
{ '_id_': {'key': [('_id', 1)], 'v': 2},
  'geoip_checked_at_1': {'expireAfterSeconds': 604800, 'key': [('geoip_checked_at', 1)], 'v': 2},
  'ip_1': {'key': [('ip', 1)], 'v': 2}}


real    1m16.188s
user    0m0.202s
sys     0m0.078s

```

**Comment by vdbergh** [comment]
Maybe we can once again try to remove the hack for counting finished runs.
Before this PR, without index hint
```javascript
rs0 [direct: primary] fishtest_new> db.runs.explain().count({finished: true}).queryPlanner.winningPlan
{
  stage: 'COUNT',
  inputStage: {
    stage: 'COLLSCAN',
    filter: { finished: { '$eq': true } },
    direction: 'forward'
  }
}
```
Yek! An evil COLLSCAN.

Before this PR with an index hint
```
rs0 [direct: primary] fishtest_new> db.runs.explain().count({finished: true}, {hint:"finished_runs"}).queryPlanner.winningPlan
{
  stage: 'COUNT',
  inputStage: {
    stage: 'FETCH',
    filter: { finished: { '$eq': true } },
    inputStage: {
      stage: 'IXSCAN',
      keyPattern: { last_updated: -1 },
      indexName: 'finished_runs',
      isMultiKey: false,
      multiKeyPaths: { last_updated: [] },
      isUnique: false,
      isSparse: false,
      isPartial: true,
      indexVersion: 2,
      direction: 'forward',
      indexBounds: { last_updated: [ '[MaxKey, MinKey]' ] }
    }
  }
}
```
Not much better. All documents still need to be fetched with a filter.

With this PR
```javascript
rs0 [direct: primary] fishtest_new> db.runs.explain().count({finished: true}).queryPlanner.winningPlan
{
  stage: 'COUNT',
  inputStage: {
    stage: 'COUNT_SCAN',
    keyPattern: { finished: 1, last_updated: -1 },
    indexName: 'finished_runs',
    isMultiKey: false,
    multiKeyPaths: { finished: [], last_updated: [] },
    isUnique: false,
    isSparse: false,
    isPartial: true,
    indexVersion: 2,
    indexBounds: {
      startKey: { finished: true, last_updated: MaxKey() },
      startKeyInclusive: true,
      endKey: { finished: true, last_updated: MinKey() },
      endKeyInclusive: true
    }
  }
}
```
So now mongodb can figure out for itself that there is an index, and moreover it does not have to fetch any documents!!

**Comment by vondele** [comment]
since this change the 'query targeting' increased (see jump between 6 and 9PM in the screenshot.

image

but with no real effect on e.g. CPU usage, so possibly no action needed.

**Comment by ppigazzini** [comment]
An explanation could be that now the indexes are used.

image

**Comment by vdbergh** [comment]
This is no doubt due to the count of finished documents. This currently requires counting the elements of the index `finished_runs`. In mongodb lingo this is called a `COUNT_SCAN`. I tried to find how it is implemented but did not succeed.

Anyway, there is a myriad of ways in which this could be optimized in our special situation, all of which introducing some ugliness.  

The question is if it is worth it. I suspect that the counting of `finished runs` is only a minor part of the time needed to generate the main page. 

@ppigazzini 

Could you do the following benchmark
```javascript
use fishtest_new
db.runs.explain("executionStats").count({finished:true})["executionStats"]
```
(maybe do it twice and report the second run, to make sure the index is in memory).

Could you do the same for
```javascript
use fishtest_new
db.runs.explain("executionStats").count({})["executionStats"]
```
and
```javascript
use fishtest_new
db.runs.explain("executionStats").count({finished:false})["executionStats"]
```
(this is how it was optimized before, from the returned count one needs to subtract the number of unfinished runs).

**Comment by ppigazzini** [comment]
"db.runs.explain("executionStats").count({finished:true})["executionStats"]"

- first run:
```
{
  executionSuccess: true,
  nReturned: 0,
  executionTimeMillis: 118,
  totalKeysExamined: 115655,
  totalDocsExamined: 0,
  executionStages: {
    stage: 'COUNT',
    nReturned: 0,
    executionTimeMillisEstimate: 12,
    works: 115655,
    advanced: 0,
    needTime: 115654,
    needYield: 0,
    saveState: 115,
    restoreState: 115,
    isEOF: 1,
    nCounted: 115654,
    nSkipped: 0,
    inputStage: {
      stage: 'COUNT_SCAN',
      nReturned: 115654,
      executionTimeMillisEstimate: 12,
      works: 115655,
      advanced: 115654,
      needTime: 0,
      needYield: 0,
      saveState: 115,
      restoreState: 115,
      isEOF: 1,
      keysExamined: 115655,
      keyPattern: { finished: 1, last_updated: -1 },
      indexName: 'finished_runs',
      isMultiKey: false,
      multiKeyPaths: { finished: [], last_updated: [] },
      isUnique: false,
      isSparse: false,
      isPartial: true,
      indexVersion: 2,
      indexBounds: {
        startKey: { finished: true, last_updated: MaxKey() },
        startKeyInclusive: true,
        endKey: { finished: true, last_updated: MinKey() },
        endKeyInclusive: true
      }
    }
  }
}
```
- second run:
```
{
  executionSuccess: true,
  nReturned: 0,
  executionTimeMillis: 81,
  totalKeysExamined: 115655,
  totalDocsExamined: 0,
  executionStages: {
    stage: 'COUNT',
    nReturned: 0,
    executionTimeMillisEstimate: 7,
    works: 115655,
    advanced: 0,
    needTime: 115654,
    needYield: 0,
    saveState: 115,
    restoreState: 115,
    isEOF: 1,
    nCounted: 115654,
    nSkipped: 0,
    inputStage: {
      stage: 'COUNT_SCAN',
      nReturned: 115654,
      executionTimeMillisEstimate: 6,
      works: 115655,
      advanced: 115654,
      needTime: 0,
      needYield: 0,
      saveState: 115,
      restoreState: 115,
      isEOF: 1,
      keysExamined: 115655,
      keyPattern: { finished: 1, last_updated: -1 },
      indexName: 'finished_runs',
      isMultiKey: false,
      multiKeyPaths: { finished: [], last_updated: [] },
      isUnique: false,
      isSparse: false,
      isPartial: true,
      indexVersion: 2,
      indexBounds: {
        startKey: { finished: true, last_updated: MaxKey() },
        startKeyInclusive: true,
        endKey: { finished: true, last_updated: MinKey() },
        endKeyInclusive: true
      }
    }
  }
}
```

**Comment by ppigazzini** [comment]
`db.runs.explain("executionStats").count({})["executionStats"]`

- first run:
```
{
  executionSuccess: true,
  nReturned: 0,
  executionTimeMillis: 0,
  totalKeysExamined: 0,
  totalDocsExamined: 0,
  executionStages: {
    stage: 'RECORD_STORE_FAST_COUNT',
    nReturned: 0,
    executionTimeMillisEstimate: 0,
    works: 1,
    advanced: 0,
    needTime: 0,
    needYield: 0,
    saveState: 0,
    restoreState: 0,
    isEOF: 1,
    nCounted: 115657,
    nSkipped: 0
  }
}
```
- second run:
```
{
  executionSuccess: true,
  nReturned: 0,
  executionTimeMillis: 0,
  totalKeysExamined: 0,
  totalDocsExamined: 0,
  executionStages: {
    stage: 'RECORD_STORE_FAST_COUNT',
    nReturned: 0,
    executionTimeMillisEstimate: 0,
    works: 1,
    advanced: 0,
    needTime: 0,
    needYield: 0,
    saveState: 0,
    restoreState: 0,
    isEOF: 1,
    nCounted: 115657,
    nSkipped: 0
  }
}
```

**Comment by ppigazzini** [comment]
`db.runs.explain("executionStats").count({})["executionStats"]`

- first run:
```
{
  executionSuccess: true,
  nReturned: 0,
  executionTimeMillis: 0,
  totalKeysExamined: 0,
  totalDocsExamined: 0,
  executionStages: {
    stage: 'RECORD_STORE_FAST_COUNT',
    nReturned: 0,
    executionTimeMillisEstimate: 0,
    works: 1,
    advanced: 0,
    needTime: 0,
    needYield: 0,
    saveState: 0,
    restoreState: 0,
    isEOF: 1,
    nCounted: 115657,
    nSkipped: 0
  }
}
```

- second run:
```
{
  executionSuccess: true,
  nReturned: 0,
  executionTimeMillis: 0,
  totalKeysExamined: 0,
  totalDocsExamined: 0,
  executionStages: {
    stage: 'RECORD_STORE_FAST_COUNT',
    nReturned: 0,
    executionTimeMillisEstimate: 0,
    works: 1,
    advanced: 0,
    needTime: 0,
    needYield: 0,
    saveState: 0,
    restoreState: 0,
    isEOF: 1,
    nCounted: 115657,
    nSkipped: 0
  }
}
```

**Comment by vdbergh** [comment]
Thanks. So `COUNT_SCAN` is about `100ms`, whereas `RECORD_STORE_FAST_COUNT` is `0ms` :) (but we still have to add the time for counting the unfinished runs, which is probably also `0ms`).

`100ms` isn't much but it would have to be compared with the time it takes to build the main page (which is cached I think).

**Pull request merged**
