### PR TITLE
Usernames from 2 to 3 characters

### PR DESCRIPTION
**Pull request by tomtor**
and add username mouse-over popup

See #304

### CODE REVIEW

**Comment by ppigazzini** [comment]
dev-server and workers updated w/ PRs #305 and #306

**Comment by tomtor** [comment]
@ppigazzini Stil just 2 characters shown, so the PR is not active?

**Comment by ppigazzini** [comment]
@tomtor here the `fishtest/fishtest/templates/run_table.mak` on the dev-server

```
    <td style="width:6%">${run['start_time'].strftime("%y-%m-%d")}</td>
    <td style="width:2%"><a href="/tests/user/${run['args'].get('username','')}" title="${run['args'].get('username','')}">${run['args'].get('username','')[:3]}</td>
    <td style="width:16%"><a href="/tests/view/${run['_id']}">${run['args']['new_tag'][:23]}</a></td>
 ```

**Comment by tomtor** [comment]
@ppigazzini Yes, it's OK now...

**Comment by ppigazzini** [comment]
@tomtor tried with a reboot of the VM. Have you any idea because this can have worked?

**Comment by tomtor** [comment]
@ppigazzini Running "setup.py install" and restarting the Python process should be sufficient. You did the first step, so for some reason your restart procedure does not kill the running Python. I suggest just checking the PID of Python before and after the restart attempt to see if it changed. If not just kill it with "kill PID". The same happened to the test of #302 and probably #300

**Comment by ppigazzini** [comment]
@tomtor I don't understand why the fishtest stopping was commented out in the script, it makes absolutely no sense ...
The problem should be solved now.

```
#!/bin/bash
# to update a fishtest server simply run:
# sudo -H bash update-fishtest.sh 2>&1 | tee update-fishtest.sh.log
#
# to use fishtest open a browser and connect to:
# http://<ip-address>

STAMP=$(date +%Y%m%d%H%M%S --utc -d '1 hour')

#systemctl stop fishtest
```

**Comment by ppigazzini** [comment]
Production server updated.
Thank you @tomtor

**Pull request merged**
