### PR TITLE
fix strip_run()

### PR DESCRIPTION
**Pull request by tomtor**
Should fix https://github.com/glinscott/fishtest/issues/721#issuecomment-659642277

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor DEV updated, error calling https://dfts-0.pigazzini.it/api/get_run/5f10d3465608d708dc5f62f9
`Jul 16 22:35:01 vps1572612706 pserve[20796]: AttributeError: 'dict' object has no attribute 'deepcopy'`

The error was already reported by Travis.

**Comment by vdbergh** [comment]
> @tomtor DEV updated, error calling https://dfts-0.pigazzini.it/api/get_run/5f10d3465608d708dc5f62f9
> `Jul 16 22:35:01 vps1572612706 pserve[20796]: AttributeError: 'dict' object has no attribute 'deepcopy'`
> 
> The error was already reported by Travis.

Yes it should be `copy.deepcopy(...)`.

**Comment by ppigazzini** [comment]
DEV updated. I need more time to understand how to break the SPSA history with master, so at the moment I don't know if this PR solves the problem. The server runs fine with the PR, though.

**Comment by tomtor** [comment]
> DEV updated. I need more time to understand how to break the SPSA history with master, so at the moment I don't know if this PR solves the problem. The server runs fine with the PR, though.

Thanks for verifying that it does not break things. Calling the API on a running tune, used to clear the graph.

I tested https://dfts-0.pigazzini.it/tests/view/5f0463281f032aa2239452f1

by calling https://dfts-0.pigazzini.it/api/get_run/5f0463281f032aa2239452f1

and the graph is still OK, it's OK for me to merge and restart prod.

**Comment by ppigazzini** [comment]
With some free time I was able to break the SPSA history on DEV with master.

PROD updated, thank you @tomtor @vdbergh :)

**Pull request merged**
