### PR TITLE
Delay scavenge on boot

### PR DESCRIPTION
**Pull request by tomtor**
See https://github.com/glinscott/fishtest/pull/832#issuecomment-715900620

### CODE REVIEW

**Comment by ppigazzini** [comment]
PR applied by hand to PROD.
I raised the scavenge timeout to 37 minutes, took PROD offline for 7 minutes to apply  #834, several workers were still lost in space after 18 minutes since the server restart.

image

Now I lowered the scavenge timeout to 3 minutes and there are only 54 workers.

**Comment by JojoM-sf** [comment]
Error message looked like this:

`Exception from calling update_task:
Expecting value: line 1 column 1 (char 0)
Exception from calling heartbeat:
Expecting value: line 1 column 1 (char 0)`

I had to ctrl-C and manually log back on.

**Comment by ppigazzini** [comment]
Scavenge timeout raised to 15 minutes, only 57 workers.

**Review by ppigazzini — APPROVED** [review]

**Comment by JojoM-sf** [comment]
Noob's workers are gone, it would seem :(

**Comment by ppigazzini** [comment]
Raising scavenge timeout to 15 minutes not helped.

@noobpwnftw please report the message error from your workers.

**Comment by ppigazzini** [comment]
@tomtor Merged, reinstalled the server with `x/update_fishtest.sh`, raised the scavenge timeout to 15 minutes by hand.

**Comment by ppigazzini** [comment]
@tomtor scavenge timeout lowered to default 3 minutes, we have 178 workers now.

**Comment by vondele** [comment]
BTW, there was some comment by @noobpwnftw  in discord yesterday: 
image
not quite sure if that made it to one of the issues here.

**Comment by tomtor** [comment]
@vondele @ppigazzini @noobpwnftw Ah, `sys.exit()` must be preceeded by `ALIVE = False`.

Will make a PR for that

**Comment by tomtor** [comment]
@ppigazzini There are 0 "dead tasks" removed by the currently running pserv with 3 minutes timeout, which is good.

Workers which are shown with longer timeouts are probably just waiting for a task, the heartbeat code on the server ignores these beats by design.

**Comment by tomtor** [comment]
> Workers which are shown with longer timeouts are probably just waiting for a task

Hmm, after inspecting the code I do not think this is the cause. Anyway, currently no machines >1 minute idle, so that's ok.

**Comment by tomtor** [comment]
@ppigazzini Currently an issue with idle times but a Python MongoDb error in the log...

**Comment by tomtor** [comment]
@ppigazzini after a restart of mongo and pserv correct times.

**Comment by tomtor** [comment]
> Currently an issue with idle times but a Python MongoDb error in the log...

@ppigazzini Should be fixed with #844

**Pull request merged**
