### PR TITLE
Use raw.githubusercontent.com to download long living stuff from github

### PR DESCRIPTION
**Pull request by vdbergh**
See the discussion  for the PR #1443 .

### CODE REVIEW

**Review by ppigazzini — APPROVED** [review]
It worked in my tests on my repo with the macos workflow.

**Comment by ppigazzini** [comment]
Thank you @vdbergh :)

A couple of notes.
I can either add a separate workflow for macOS or change the matrix of the linux workflow: do you have a preference?
On my repo the linux workflow fails because `ubuntu-latest` (alias for v 20.04 right now) starts unexpectedly v 22.04 that has dropped the python 3.6 support, see
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
noob's fleet uses python 3.6, so perhaps better to force `ubuntu-20.04` in the workflow.

**Comment by vondele** [comment]
This leads to problems with noob's workers. Maybe a proxy issue or some thing?

**Comment by vondele** [comment]
blocked in China:
https://github.com/openvinotoolkit/openvino/issues/8492

**Comment by vdbergh** [comment]
Bah. I guess it is best to revert for now. The solution is to first use the api and if that fails, as a fallback raw.gitusercontent.com. Or perhaps the other way round.

**Comment by vdbergh** [comment]
Hmm sri.txt is also downloaded from raw.gituserconttent.com. So it seems it is not always blocked. Otherwise the worker would not start.

**Comment by vdbergh** [comment]
Maybe we should wait a bit. It is not the first time that the noob workers have transient problems with github.

**Comment by vdbergh** [comment]
The noob workers appear to be working normally again.

**Comment by vdbergh** [comment]
E.g. this worker https://tests.stockfishchess.org/actions?max_actions=1&before=1668548747.379 now appears to be producing games.

**Comment by vondele** [comment]
probably because it doesn't need the different book, i.e. that book is just available ?

**Comment by vdbergh** [comment]
Well it was trying to download the book, which failed at first, but now apparently it has succeeded.

**Comment by vondele** [comment]
some more discussion in discord on this https://discord.com/channels/435943710472011776/900771437177094156/1042243969867849839

**Pull request closed without merging**
