### PR TITLE
Add search to actions

### PR DESCRIPTION
**Pull request by tomtor**
This is an alternative for https://github.com/glinscott/fishtest/issues/237

Allow searching on action type and/or username.

Also clean up some named parameter white space issues.

### CODE REVIEW

**Comment by ppigazzini** [comment]
dev server updated: the "Actions" page is a little slow.

**Comment by vondele** [comment]
The interface is very nice and useful. It is indeed rather slow.

**Comment by ppigazzini** [comment]
dev server updated setting actions limit to 100.

**Comment by vondele** [comment]
LGTM

**Comment by tomtor** [comment]
@ppigazzini Adding a mongodb index to action['username'] (should/could be done outside this PR) should speed user searches up (but those are rare), so I think this is OK with the old 100 limit.

**Comment by ppigazzini** [comment]
official server updated
@tomtor thank you! If a search should be slow we can try with the mongodb index.

**Pull request merged**
