### PR TITLE
Speedup computation of info pages

### PR DESCRIPTION
**Pull request by tomtor**
Currently active machines and pending tests info is
computed for every info page even if it is not displayed.

Also remove computation of total_games which is never displayed.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor DEV updated, huge speedup but page 1 need a fix:

https://dfts-2.pigazzini.it/tests?page=1

Benches running `$ time bash curl_tests.sh`

* master
```
real    2m3.240s
user    0m4.297s
sys     0m9.578s
```
* master loading mongo also with `curl_loop.sh`
```
real    2m47.738s
user    0m4.563s
sys     0m9.125s
```

* PR
```
real    0m56.825s
user    0m4.484s
sys     0m9.313s
```
* PR loading mongo also with `curl_loop.sh`
```
real    1m24.185s
user    0m4.547s
sys     0m9.219s
```

**Comment by tomtor** [comment]
> DEV updated, huge speedup but page 1 needs a fix:

@ppigazzini What do you see on page 1 that needs fixing? Is it the second entry in 'finished' that shows pending? 

It is strange, because the behaviour for pages > 1 is changed by the new code, page = 1 should be not effected, but it is... I just added an if branch and indented the code.

**Comment by ppigazzini** [comment]
@tomtor on DEV page 1 shows always 'pending 0 tests' 'active 0 machines', home page shows correctly the numbers of pending tests and active machines. page > 1 correctly don't show the fields 'pending tests' and 'active machines'. On PROD page 1 shows the same info of the home page.

https://dfts-2.pigazzini.it/tests
https://dfts-2.pigazzini.it/tests?page=1
https://dfts-2.pigazzini.it/tests?page=2

https://tests.stockfishchess.org/tests
https://tests.stockfishchess.org/tests?page=1
https://tests.stockfishchess.org/tests?page=2

**Comment by tomtor** [comment]
@ppigazzini Ah thanks, I see now the issue (not the fix yet)

**Comment by tomtor** [comment]
@ppigazzini I discovered recently that specifying "page=1" skips the cache code. Pushed a fix, please redeploy.

**Comment by tomtor** [comment]
@ppigazzini Now the home page is broken :D, will fix....

**Comment by ppigazzini** [comment]
@tomtor done, now the home shows the wrong 0 info :(

**Comment by tomtor** [comment]
> done, now the home shows the wrong 0 info :(

Yes, fix pushed again... Sorry for this

**Comment by ppigazzini** [comment]
DEV now is boring fast :D   
Great work @tomtor !

**Comment by ppigazzini** [comment]
@tomtor I'm thinking if we should add a "robots.txt" to stop robots activity

https://www.google.com/search?hl=it&ei=7IfiXdqkLpC8kwWYtY2IDQ&q=site%3Ahttps%3A%2F%2Ftests.stockfishchess.org&oq=site%3Ahttps%3A%2F%2Ftests.stockfishchess.org&gs_l=psy-ab.3...2379.16565..16745...0.0..0.73.1821.37......0....1..gws-wiz.......0i67j0i131j0j0i10j0i10i67.wx_DUNjydbc&ved=0ahUKEwjayrG0nZLmAhUQ3qQKHZhaA9EQ4dUDCAs&uact=5

**Comment by tomtor** [comment]
@ppigazzini Yes, we could do that.

See also https://pyramid-cookbook-stevepiercy.readthedocs.io/en/latest/static_assets/files.html

**Comment by tomtor** [comment]
@ppigazzini I will create a PR. Also includes favicon, we need to choose/get an image

**Comment by ppigazzini** [comment]
@tomtor DEV is slower to load older tests pages. I think two possibile explanations:
 - it's a feature: tests pages divided in two sets (fast and slow search process)
 - still computing info for the old tests pages

```
# pages 0-100
$ time bash curl_tests.sh
real    0m23.596s
user    0m1.891s
sys     0m4.453s

# pages 500-600
$ time bash curl_tests.sh
real    0m55.460s
user    0m1.859s
sys     0m4.359s

# pages 1000-1100
$ time bash curl_tests.sh
real    0m58.621s
user    0m1.656s
sys     0m4.313s
```

**Pull request merged**
