### PR TITLE
Make the task target links in the event log point to tasks.

### PR DESCRIPTION
**Pull request by vdbergh**
Also: include the bytes 2-4 of the run_id in the run name (there may be many tests with the same branch, currently these are indistinguishable).

One cannot yet search for the extra data. This will require again a database conversion.

### CODE REVIEW

**Comment by vdbergh** [comment]
There is currently a bug in fishtest that after purging `task_id`'s change (a task does not know its own id) so links to specific tasks in the event log may become incorrect  and more seriously, theoretically workers can become confused as well when suddenly the `task_id` they are using points to a different task. 

I will fix this in another PR but it cannot be done retroactively (the required information is gone).

**Comment by ppigazzini** [comment]
DEV updated, LGTM.

https://dfts-0.pigazzini.it/tests/view/639011178536e3e199afe346?show_task=299

**Comment by vdbergh** [comment]
Do you have the RGB values for your suggestion?

There is a slight issue with the diff which sometimes pushes the selected task down. I'll have a look at this.

**Comment by ppigazzini** [comment]
> Do you have the RGB values for your suggestion?
> 
> There is a slight issue with the diff which sometimes pushes the selected task down. I'll have a look at this.

I'm experimenting, I noted that we have already this color for the purged tasks, searching for the RGB

image

**Comment by ppigazzini** [comment]
What about the light purple `#ffbbff`?

image

image

**Comment by ppigazzini** [comment]
@dav1312 suggestion for the colors?

**Review by ppigazzini — APPROVED** [review]
I will fix the color for the light theme during the merge,

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Comment by vdbergh** [comment]
I am still struggling with the diff issue (this part of the page is entirely done in javascript). On my local installation the diff seems to be always hidden so I cannot replicate the issue. Perhaps someone who understands the javascript code can help?

**Comment by ppigazzini** [comment]
@peregrineshahin could help with javascript code

**Comment by vdbergh** [comment]
Ok whether a diff is shown or hidden appears to depend on the diff itself (perhaps its size?).

**Comment by vdbergh** [comment]
Ok found it in the javascript code (hide large diffs by default).

**Pull request merged**
