### PR TITLE
Query for unfinished_runs with only the id attribute

### PR DESCRIPTION
**Pull request by tomtor**
Speedup by dropping tasks from unfinished_runs query

See #677

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor I will test on DEV if this PR breaks something, please suggest how to test if the PR solves the problem.

**Comment by tomtor** [comment]
@ppigazzini I adapted the `~/x/view_unfinished.py` script on prod to test the speedup, and it gives a hugh speedup:

```elapsed time: 0.031681```

So if the PR does not break fishtest (sorting or new test detection broken) it should fix the issue

**Comment by ppigazzini** [comment]
@tomtor DEV updated, I'm start checking if fishtest is broken :)

**Comment by tomtor** [comment]
@ppigazzini  Thanks. Last push should be non functional so no need to restart your test...

**Comment by ppigazzini** [comment]
@tomtor DEV updated. I will start the test in a couple of hours after my commute.

**Comment by ppigazzini** [comment]
@tomtor I run several tests on DEV with a looping mongodump, the workers switched always to the right tests after lowering/raising the priorities.
I wait the squash to merge.

**Comment by ppigazzini** [comment]
PROD updated, thank you @tomtor :)

**Comment by tomtor** [comment]
Thanks @ppigazzini for testing this!

**Pull request merged**
