### PR TITLE
Drop task list from request_task

### PR DESCRIPTION
**Pull request by tomtor**
This will reduce the message size and speedup request_task API.

### CODE REVIEW

**Comment by tomtor** [comment]
@ppigazzini @Stefano80 Should be combined with other worker PRs

**Comment by ppigazzini** [comment]
dev-server, workers and DB updated, I got this error:
```
Exception running games:
Traceback (most recent call last):
  File "worker.py", line 102, in worker
    pgn_file = run_games(worker_info, password, remote, run, task_id)
  File "/home/ppadmin/_git/fishtest/worker/games.py", line 323, in run_games
    task = run['my_task']
KeyError: 'my_task'
Task exited
```

**Comment by tomtor** [comment]
@ppigazzini Runs OK now!

**Comment by ppigazzini** [comment]
@tomtor all my workers (linux, windows, wsl) got the same error
```
Exception running games:
Traceback (most recent call last):
  File "worker.py", line 101, in worker
    run_games(worker_info, password, remote, run, task_id)
  File "/root/_git/fishtest/worker/games.py", line 344, in run_games
    task = run['my_task']
KeyError: 'my_task'
Task exited
```

**Comment by tomtor** [comment]
@ppigazzini This PR does not raise the version in worker.py. Either edit it by hand to 65 or merge an PR that does.

**Comment by ppigazzini** [comment]
@tomtor linux and wsl workers are running fine, the windows worker outputs this error message:
```
Exception running games:
Traceback (most recent call last):
  File "D:\__test_worker\ori\worker01\\worker.py", line 101, in worker
    run_games(worker_info, password, remote, run, task_id)
  File "D:\__test_worker\ori\worker01\games.py", line 344, in run_games
    task = run['tasks'][task_id]
IndexError: list index out of range
Task exited
```

**Comment by ppigazzini** [comment]
@tomtor bug found very easily (I simply looked in a mirror), now also the windows worker runs fine.

**Comment by ppigazzini** [comment]
@tomtor I'm wondering if committing this on the production server will stop the workers ver < 65

**Comment by tomtor** [comment]
@ppigazzini No, old workers should be fine. It is backwards compatible. You can test this yourself by checking out an old worker (version 63). An old worker should be able to talk to the latest server.

**Comment by ppigazzini** [comment]
@tomtor I trust your word way more than my tests ;)

**Comment by tomtor** [comment]
@ppigazzini You should not. If the devserver has this merged then an old worker (version <= 64) should be able to talk to it. This is easy to test. If it does not work then something is wrong.

**Comment by ppigazzini** [comment]
@tomtor Tested OK on the dev-server with workers ver 63.
Production server updated, all workers are running fine.

**Pull request merged**
