### PR TITLE
Detect a common clang misconfiguration (missing llvm-profdata).

### PR DESCRIPTION
**Pull request by vdbergh**
This is an alternative for #1459 . We catch the error at worker start up.

### CODE REVIEW

**Comment by vdbergh** [comment]
Now CI fails for the MacOS :)

**Comment by ppigazzini** [comment]
It works:
```diff
diff --git a/worker/sri.txt b/worker/sri.txt
index 554d914..94d696f 100644
--- a/worker/sri.txt
+++ b/worker/sri.txt
@@ -1 +1 @@
-{"__version": 188, "updater.py": "iN1p2Qba0tK78vGLA5iEAkX/IMSYkcaS5StImgla6QDPo0lTv1wxuN3pvxl84aOe", "worker.py": "hdXWEUDUBiokvDt01OP7GNDnb6NMfQmkymOaq/yizJ/fz8Ta5cdrLXB+QI5ix+l1", "games.py": "5h/Vo+50Xh07L4wVVg/wZ0Nkz1eglnnTsCiv+JbpsN3pQupKpI8xh2Pu6jjToJrY"}
+{"__version": 188, "updater.py": "iN1p2Qba0tK78vGLA5iEAkX/IMSYkcaS5StImgla6QDPo0lTv1wxuN3pvxl84aOe", "worker.py": "SWogfLZEopCzJcn+v/Erz/RxWB/IW21t4/PtHMCCPztJk21DFLFEy3PgI9MsUOwh", "games.py": "5h/Vo+50Xh07L4wVVg/wZ0Nkz1eglnnTsCiv+JbpsN3pQupKpI8xh2Pu6jjToJrY"}
diff --git a/worker/worker.py b/worker/worker.py
index 62d16ac..27ec16c 100644
--- a/worker/worker.py
+++ b/worker/worker.py
@@ -41,6 +41,7 @@ import packages.expression as expression
 import requests
 from games import (
     EXE_SUFFIX,
+    IS_MACOS,
     FatalException,
     RunException,
     WorkerException,
@@ -1055,7 +1056,7 @@ def clang_version():
     # Check for a common toolchain issue
     try:
         with subprocess.Popen(
-            ["llvm-profdata", "--help"],
+            ["xcrun" if IS_MACOS else "", "llvm-profdata", "--help"],
             stdin=subprocess.DEVNULL,
             stdout=subprocess.DEVNULL,
             stderr=subprocess.DEVNULL,
```

**Comment by ppigazzini** [comment]
Now msys2 fails :(
https://github.com/ppigazzini/fishtest/actions/runs/3525366292/jobs/5911997828

**Comment by vdbergh** [comment]
But not with this PR...

**Comment by ppigazzini** [comment]
This package `mingw-w64-clang-x86_64-llvm` installs `llvm-profdata`, I'm trying to write the yaml in the right way.

**Comment by vdbergh** [comment]
> It works, see https://github.com/ppigazzini/fishtest/actions/runs/3525366285 :
> 
> ```diff
> diff --git a/worker/sri.txt b/worker/sri.txt
> index 554d914..94d696f 100644
> --- a/worker/sri.txt
> +++ b/worker/sri.txt
> @@ -1 +1 @@
> -{"__version": 188, "updater.py": "iN1p2Qba0tK78vGLA5iEAkX/IMSYkcaS5StImgla6QDPo0lTv1wxuN3pvxl84aOe", "worker.py": "hdXWEUDUBiokvDt01OP7GNDnb6NMfQmkymOaq/yizJ/fz8Ta5cdrLXB+QI5ix+l1", "games.py": "5h/Vo+50Xh07L4wVVg/wZ0Nkz1eglnnTsCiv+JbpsN3pQupKpI8xh2Pu6jjToJrY"}
> +{"__version": 188, "updater.py": "iN1p2Qba0tK78vGLA5iEAkX/IMSYkcaS5StImgla6QDPo0lTv1wxuN3pvxl84aOe", "worker.py": "SWogfLZEopCzJcn+v/Erz/RxWB/IW21t4/PtHMCCPztJk21DFLFEy3PgI9MsUOwh", "games.py": "5h/Vo+50Xh07L4wVVg/wZ0Nkz1eglnnTsCiv+JbpsN3pQupKpI8xh2Pu6jjToJrY"}
> diff --git a/worker/worker.py b/worker/worker.py
> index 62d16ac..27ec16c 100644
> --- a/worker/worker.py
> +++ b/worker/worker.py
> @@ -41,6 +41,7 @@ import packages.expression as expression
>  import requests
>  from games import (
>      EXE_SUFFIX,
> +    IS_MACOS,
>      FatalException,
>      RunException,
>      WorkerException,
> @@ -1055,7 +1056,7 @@ def clang_version():
>      # Check for a common toolchain issue
>      try:
>          with subprocess.Popen(
> -            ["llvm-profdata", "--help"],
> +            ["xcrun" if IS_MACOS else "", "llvm-profdata", "--help"],
>              stdin=subprocess.DEVNULL,
>              stdout=subprocess.DEVNULL,
>              stderr=subprocess.DEVNULL,
> ```

Thanks!

**Review by ppigazzini — APPROVED** [review]

**Comment by vdbergh** [comment]
I am still confused about what causes the conflict. Assume a PR is properly rebased with master (it should be automatically so if there were no commits to master after work on the PR started).

Raising the worker version, regenerating the sri and changing the latest commit in the PR with `commit -a --amend` should not create a conflict with master IMHO.

**Comment by ppigazzini** [comment]
I was surprised too. I added a new commit with the new version and new "sri.txt", then rebased vs master, then pushed. I was expecting the PR to autoclose because I merged your commit without a change.
Next time I will add the "close #..." in the comment.

**Pull request closed without merging**
