### PR TITLE
Fix delete run

### PR DESCRIPTION
**Pull request by tomtor**

### CODE REVIEW

**Comment by tomtor** [comment]
@ppigazzini Merged, restarted and they are gone...

**Comment by tomtor** [comment]
@ppigazzini Have to fix old_runs too....

**Comment by ppigazzini** [comment]
@tomtor I'm commuting now, can you revert?

**Comment by tomtor** [comment]
@ppigazzini Sure, I will combine it with this PR

**Comment by ppigazzini** [comment]
@tomtor in effect also the DEV crashes, but unfortunately I thought than that code was triggered by the workers and I didn't know how to test it. My bad.

**Pull request merged**
