### PR TITLE
Strip non utf-8 characters from PGN files

### PR DESCRIPTION
**Pull request by tomtor**
Should fix EDIT:  https://github.com/glinscott/fishtest/issues/685

Also reduce some line lengths to less than 80 chars

@ppigazzini I tested this with python 2 and 3 workers, but not with a PGN containing non-utf8 characters. Perhaps you can create one with a particular Windows setting? If not then it's OK for me to commit and let @kotenok2000 test?

### CODE REVIEW

**Comment by kotenok2000** [comment]
I substituted  file work
er.py  with file from tomtor:non-utf8. Now my pgns upload.
[5edc25adf29b40b0fc95ab65-18.pgn.txt](https://github.com/glinscott/fishtest/files/4741277/5edc25adf29b40b0fc95ab65-18.pgn.txt)

**Comment by tomtor** [comment]
@kotenok2000 Thanks for testing!

@ppigazzini I raised worker version to 80

**Comment by ppigazzini** [comment]
@noobpwnftw please update your fleet at your convenience :)

**Comment by noobpwnftw** [comment]
@ppigazzini Updated.

**Pull request merged**
