### PR TITLE
Update and cleanup for Ubuntu 18.04

### PR DESCRIPTION
**Pull request by ppigazzini**
General updates and cleanup after the switch to Ubuntu 18.04:
- delete old startup scripts and SETUP
- update README
- update .gitignore
- use python3 print()
- update the scripts shebang as a reminder to use the virtual environment python, either with:
  - `${VENV}/bin/python script.py` (suggested by Pyramid documentation)
  - `source ${VENV}/bin/activate` and `python script.py`
- set the scripts mode to not executable to limit execution with the wrong python

### CODE REVIEW

**Comment by ppigazzini** [comment]
Low priority house keeping PR.
@tomtor review and suggestions are welcome.

With virtual environment a python scripts must be started either:
 - with `source ${VENV}/bin/activate` and `python script.py`
 - with `source ${VENV}/bin/activate` and `./script.py` (w/ mode executable; the update shebang takes the correct python)
 - with `${VENV}/bin/python script.py`

Pyramid documentation suggests the last as best practice.

**Comment by tomtor** [comment]
https://github.com/glinscott/fishtest/blob/52cdedc7adf0156778716865e4d16b0d2a71d38f/fishtest/utils/current.py#L29

and

https://github.com/glinscott/fishtest/blob/52cdedc7adf0156778716865e4d16b0d2a71d38f/fishtest/utils/index_pending.py#L29

and

https://github.com/glinscott/fishtest/blob/52cdedc7adf0156778716865e4d16b0d2a71d38f/fishtest/utils/scavenge.py#L18

are not python3 safe.

Perhaps you could change those lines to `print(...)` and merge the python3 PR in the near future?

**Comment by ppigazzini** [comment]
@ppigazzini the plan is to switch to python3 before 2020. Tonight I will update this PR.

**Comment by tomtor** [comment]
@ppigazzini 

Oops, for python 2 compatibility you need to add:

    from __future__ import print_function

**Comment by ppigazzini** [comment]
@tomtor done. This restored Travis too!

Just kidding :)

**Pull request merged**
