### PR TITLE
Limit concurrent flag queries

### PR DESCRIPTION
**Pull request by tomtor**
Guard against slow or unavailable flag server

See https://github.com/glinscott/fishtest/issues/553#issuecomment-619777152

### CODE REVIEW

**Comment by noobpwnftw** [comment]
I think one more thing can be done regarding to flags: IPv4 address blocks has to be no less than /24, so you can assume they have the same origin, thus reducing the number of duplicated queries/caches.

**Comment by tomtor** [comment]
> I think one more thing can be done regarding to flags: IPv4 address blocks has to be no less than /24 in order to advertise on the Internet, so you can assume any IP under the same class C network is from the same origin, thus reducing the number of duplicated queries/caches.

Yes, that's true. It would however add considerable code for a limited gain?

**Comment by ppigazzini** [comment]
@tomtor on DEV with the first PR version the server dropped the flags, with latest version the flags are still there (reloaded a DB backup), the log is clean, the geoip service is still down.
Can I merge?

**Comment by tomtor** [comment]
@ppigazzini yes ok to merge. Thanks.

**Comment by ppigazzini** [comment]
PROD updated, thank you @tomtor :)

**Comment by ppigazzini** [comment]
GeoIP service restarted working
https://freegeoip.app/json/

**Pull request merged**
