### PR TITLE
Use .. instead of ... for github compare.

### PR DESCRIPTION
**Pull request by Sopel97**
...: https://github.com/MichaelB7/Stockfish/compare/0470bcef0e...be08a5bf65
..: https://github.com/MichaelB7/Stockfish/compare/0470bcef0e..be08a5bf65

untested, not sure if it will work in all cases

### CODE REVIEW

**Comment by G-Lorenz** [comment]
Is this similar to #924 ?

**Comment by G-Lorenz** [comment]
I tested this PR in my local DEV: inline diff is broken. This is due to GitHub API, see https://github.com/glinscott/fishtest/pull/924#issuecomment-841476534 or directly Lolligerhans' code.

I suggest you to read also the comments since vondele's review: he poses an issue that I think it should be solved. There are some proposals but the discussion doesn't come to an end.

**Comment by ppigazzini** [comment]
[DEV](https://dfts-0.pigazzini.it/) updated with the PR. It breaks the git diff like #924, see

https://dfts-0.pigazzini.it/tests/view/609d84615085663412d08e2f
https://tests.stockfishchess.org/tests/view/609d84615085663412d08e2f

**Comment by Sopel97** [comment]
> 
> 
> [DEV](https://dfts-0.pigazzini.it/) updated with the PR. It breaks the git diff like #924, see
> 
> https://dfts-0.pigazzini.it/tests/view/609d84615085663412d08e2f
> https://tests.stockfishchess.org/tests/view/609d84615085663412d08e2f

what exactly is broken here?
obraz
obraz

**Comment by ppigazzini** [comment]
The git diff disappears

Untitled

**Comment by Sopel97** [comment]
> 
> 
> The git diff windows disappears:
> 
> Untitled

this is the first time I see this feature, and I'm unable to find it on https://tests.stockfishchess.org/tests/view/609d84615085663412d08e2f

**Comment by Sopel97** [comment]
so if it's not possible to get the inline diff correct it should be dropped entirely?

**Comment by ppigazzini** [comment]
> So if it's not possible to get the inline diff correct it should maybe be dropped entirely? It is useless if it's not correct.

I agree with you that a feature with wrong output should be or fixed or dropped.
I'm not a Stockfish developer, never used that feature, so like in #924 I ask to the Stockfish maintainer (cc @vondele) what to do.

**Comment by vondele** [comment]
I use the inline diff all the time... but of course it would be good if it were correct.

**Pull request closed without merging**
