### PR TITLE
Fix https://github.com/glinscott/fishtest/issues/324

### LINKED ISSUE #324: SPSA reports always the same 'c' across all iterations
The problem is explained here
https://groups.google.com/d/msg/fishcooking/X6yCuH55AHY/G5nEcZW2BwAJ

A fix would be to change the way that view.py "prints" the report
https://groups.google.com/d/msg/fishcooking/X6yCuH55AHY/a4Suhsi8BwAJ

This way, fishtest will report the results similarly as the spsa.pl of Joona

### PR DESCRIPTION
**Pull request by tomtor**
Should fix #324 

Needs some testing, @Rocky640 could you test this on https://dfts-0.pigazzini.it/tests when @ppigazzini confirms it can be tested?

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor I got "Internal Server Error" rescheduling a SPSA w/ this PR.
w/o this PR the SPSA can be rescheduled and runs fine.

**Comment by ppigazzini** [comment]
@tomtor 
```bash
sudo journalctl -u fishtest@6543


Sep 04 15:12:56 dfts-0 pserve[11482]:   File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 821, in tests_view
Sep 04 15:12:56 dfts-0 pserve[11482]:     p['a'] / (value['A'] + value['iter']) ** value['alpha']) for p in value['params']]
Sep 04 15:12:56 dfts-0 pserve[11482]: ZeroDivisionError: float division by zero
```

**Comment by ppigazzini** [comment]
@tomtor @Rocky640 dev server up and running w/ this PR

**Comment by tomtor** [comment]
@ppigazzini @Rocky640 @vdbergh Not sure what to show in this / 0.0 condition. I just resort to the old code in that exception situation but that is not very elegant.

**Comment by Rocky640** [comment]
@tomtor 
I just went on https://dfts-0.pigazzini.it/tests

a) When I click LTC, the SPRT bounds does not change here 
    do i need to update my worker as well and how ?

b) I don't know why suddenly you would have some division by 0 errors
    If you click LTC and SPSA is selected, no need to change the SPRT bounds at all,
    they don,t apply for SPSA

**Comment by ppigazzini** [comment]
@Rocky640 you need to update the worker only to run the test w/ the https server, I start this script:

```bash
#!/bin/bash
rm -rf __fishtest
mkdir __fishtest
cd __fishtest
git clone -b master --single-branch https://github.com/glinscott/fishtest.git
cd fishtest
git config user.email "you@example.com"
git config user.name "Your Name"

# add here the personal upstream branch to be tested
#git remote add new-upstream https://github.com/<username>/fishtest
#git pull --no-edit new-upstream <branchname>
# add here the official PRs to be tested
git pull --no-edit origin pull/383/head
git pull --no-edit origin pull/387/head

cd worker
echo "make profile-build ARCH=x86-64-modern COMP=gcc -j" > custom_make.tx
python worker.py --host dfts-0.pigazzini.it --concurrency 3 user00 user00 2>&1 | tee worker.log
#python3 worker.py --host dfts-0.pigazzini.it --concurrency 3 user01 user01 2>&1 | tee worker.log
```

**Comment by tomtor** [comment]
@Rocky640 When I look at https://dfts-0.pigazzini.it/tests/view/5d6fc1319f44c5a725c69afd I see the 'c' value changing on every iteration...

**Comment by ppigazzini** [comment]
> a) When I click LTC, the SPRT bounds does not change here

@Rocky640 I'm viewing the same behavior pushing the buttons on official-server and dev-server pages. I don't understand the point a)

**Comment by Rocky640** [comment]
OK, my wrong, I thought it was a fix for another issue. 
I will take a look tomorrow.

**Comment by Rocky640** [comment]
About the divisions by zero, it can happen only if value['iter'] is 0
So you might want to skip reporting if this is the case.

Or a trick similar to line 582 of rundb.py where we add 1 
`iter_local = spsa['iter'] + 1 #assume at least one completed, and avoid division by zero`

**Comment by tomtor** [comment]
> iter_local = spsa['iter'] + 1 #assume at least one completed, and avoid division by zero

Thanks @Rocky640 , I think that is the best suggestion.

@ppigazzini I squashed and made that change, so if you could please reapply this PR for testing?

**Comment by ppigazzini** [comment]
@tomtor PR applied.

**Comment by ppigazzini** [comment]
@tomtor new problem in the log

```bash
sudo journalctl -u fishtest@6543

Sep 04 15:36:34 dfts-0 systemd[1]: Started Fishtest Server port 6543.
Sep 04 15:48:21 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
Sep 04 15:48:21 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
Sep 04 15:49:11 dfts-0 systemd[1]: Started Fishtest Server port 6543.
Sep 04 15:59:06 dfts-0 pserve[1923]: /home/fishtest/fishtest/fishtest/fishtest/views.py:729: RuntimeWarning: invalid value encountered in divide
Sep 04 15:59:06 dfts-0 pserve[1923]:   residual = diff / numpy.sqrt(expected * adj)
Sep 04 21:23:36 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
Sep 04 21:23:36 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
Sep 04 21:24:16 dfts-0 systemd[1]: Started Fishtest Server port 6543.
Sep 04 21:27:47 dfts-0 pserve[18900]: /home/fishtest/fishtest/fishtest/fishtest/views.py:729: RuntimeWarning: invalid value encountered in divide
Sep 04 21:27:47 dfts-0 pserve[18900]:   residual = diff / numpy.sqrt(expected * adj)
```

**Comment by tomtor** [comment]
@ppigazzini I don't think that error is related to this change, I remember seeing that before but I am not 100% sure. To be sure you will have to verify with master to see if that generates the same warning....

**Comment by ppigazzini** [comment]
@tomtor no Warning w/o this PR

```bash
sudo journalctl -u fishtest@6543

Sep 04 15:36:04 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
Sep 04 15:36:04 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
-- Reboot --
Sep 04 15:36:34 dfts-0 systemd[1]: Started Fishtest Server port 6543.
Sep 04 15:48:21 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
Sep 04 15:48:21 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
Sep 04 15:49:11 dfts-0 systemd[1]: Started Fishtest Server port 6543.
Sep 04 15:59:06 dfts-0 pserve[1923]: /home/fishtest/fishtest/fishtest/fishtest/views.py:729: RuntimeWarning: invalid value encountered in divide
Sep 04 15:59:06 dfts-0 pserve[1923]:   residual = diff / numpy.sqrt(expected * adj)
Sep 04 21:23:36 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
Sep 04 21:23:36 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
Sep 04 21:24:16 dfts-0 systemd[1]: Started Fishtest Server port 6543.
Sep 04 21:27:47 dfts-0 pserve[18900]: /home/fishtest/fishtest/fishtest/fishtest/views.py:729: RuntimeWarning: invalid value encountered in divide
Sep 04 21:27:47 dfts-0 pserve[18900]:   residual = diff / numpy.sqrt(expected * adj)
Sep 04 21:43:31 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
Sep 04 21:43:31 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
Sep 04 21:44:12 dfts-0 systemd[1]: Started Fishtest Server port 6543.

```

**Comment by ppigazzini** [comment]
@tomtor errata corrige, Warning also w/o this PR :)

```bash
sudo journalctl -u fishtest@6543

Sep 04 15:36:04 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
Sep 04 15:36:04 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
-- Reboot --
Sep 04 15:36:34 dfts-0 systemd[1]: Started Fishtest Server port 6543.
Sep 04 15:48:21 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
Sep 04 15:48:21 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
Sep 04 15:49:11 dfts-0 systemd[1]: Started Fishtest Server port 6543.
Sep 04 15:59:06 dfts-0 pserve[1923]: /home/fishtest/fishtest/fishtest/fishtest/views.py:729: RuntimeWarning: invalid value encountered in divide
Sep 04 15:59:06 dfts-0 pserve[1923]:   residual = diff / numpy.sqrt(expected * adj)
Sep 04 21:23:36 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
Sep 04 21:23:36 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
Sep 04 21:24:16 dfts-0 systemd[1]: Started Fishtest Server port 6543.
Sep 04 21:27:47 dfts-0 pserve[18900]: /home/fishtest/fishtest/fishtest/fishtest/views.py:729: RuntimeWarning: invalid value encountered in divide
Sep 04 21:27:47 dfts-0 pserve[18900]:   residual = diff / numpy.sqrt(expected * adj)
Sep 04 21:43:31 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
Sep 04 21:43:31 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
Sep 04 21:44:12 dfts-0 systemd[1]: Started Fishtest Server port 6543.
Sep 04 21:47:10 dfts-0 pserve[23279]: /home/fishtest/fishtest/fishtest/fishtest/views.py:729: RuntimeWarning: invalid value encountered in divide
Sep 04 21:47:10 dfts-0 pserve[23279]:   residual = diff / numpy.sqrt(expected * adj)

```

**Comment by tomtor** [comment]
@ppigazzini Thanks for testing, so I think this PR is OK now.

**Comment by ppigazzini** [comment]
Production server updated.
Thank you @tomtor @Rocky640

**Pull request merged**
