### PR TITLE
Open test window and give focus when clicking a native notification.

### PR DESCRIPTION
**Pull request by vdbergh**
Suggested by dav1312.

### CODE REVIEW

**Comment by vdbergh** [comment]
I managed to get fishtest working over ssl. So I could actually test this myself...

**Comment by ppigazzini** [comment]
A click on system notification opens the test in a new tab of the correct browser.
A click on a bootstrap notification opens the test in the tab where we clicked.

**Comment by vdbergh** [comment]
I tried to open the link in a bootstrap notification in a different tab but that did not work very well as this tab now also started showing notifications.

It might work if we could close individual notifications (and they would then close in all tabs). But we aren't there yet....

**Comment by ppigazzini** [comment]
PROD updated with both PRs, thank you @vdbergh :)

**Pull request merged**
