### PR TITLE
Limit request_task concurrency

### PR DESCRIPTION
**Pull request by tomtor**
A request_task call takes about 150ms (7 per second).

The worker randomizes calls in a 1 to 30s interval.

With 200 workers or more the request queue might consume
all threads, so limit concurrency to 4 requests.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor the dev-server and the workers are running fine since 4 hours. I'm waiting the @Stefano80 review before merging this PR.

**Comment by tomtor** [comment]
@Stefano80 renamed

**Comment by Stefano80** [comment]
Thanks. For me it's ok.

**Comment by Stefano80** [comment]
Restarted.

**Pull request merged**
