### PR TITLE
Automatically follow tests created on the browser

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by vdbergh** [comment]
This should be the last "infrastructure" PR.

**Comment by ppigazzini** [comment]
I got the notifications on the browser without any user logged, no notification in the browsers with "user01" (owner of the tests) logged.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Comment by vdbergh** [comment]
@ppigazzini Thank you for testing all these PRs! It must be a huge amount of work.

**Pull request merged**
