### PR TITLE
Template literals, avoid innerHTML and user link

### PR DESCRIPTION
**Pull request by dav1312**
Use template literals
Avoid innerHTML as much as possible, using textContent instead
Add a link to the user tests
Reorder based on table order

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated, LGTM. If I'm not wrong this PR makes #1436 obsolete.

**Comment by dav1312** [comment]
Yes, this PR also adds a link to the user tests

**Comment by ppigazzini** [comment]
PROD updated, thank you @dav1312 (and @snicolet) :)

**Comment by snicolet** [comment]
Slight surprise with the username link : it should not open in a new tab. We should remove the « target = blank »

**Comment by dav1312** [comment]
> it should not open in a new tab

Why not

**Comment by snicolet** [comment]
because if we do a sequence of 
LiveElo -> username -> LiveElo -> username -> LiveElo -> username, 
we end up with an infinite number of tabs.

All other links pointing to https://tests.stockfishchess.org remain in the same page, giving the global impression that https://tests.stockfishchess.org is a single app (there must be a technical term for that). I think it's a good feature.

**Pull request merged**
