### PR TITLE
Fix overflow on both mobile and desktop

### PR DESCRIPTION
**Pull request by peregrineshahin**
mobile version looks unreadable now, do an auto fix.

### CODE REVIEW

**Comment by ppigazzini** [comment]
LG on DEV

image

**Comment by dav1312** [comment]
Note that `.table-responsive` already adds `overflow-x: auto;`
image

**Comment by ppigazzini** [comment]
LG on DEV the desktop version too.

image

**Comment by peregrineshahin** [comment]
> Note that `.table-responsive` already adds `overflow-x: auto;` image

Yeah makes sense. pushed

**Comment by ppigazzini** [comment]
DEV updated, LGTM

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin :)

**Pull request merged**
