### PR TITLE
Some enhancements

### PR DESCRIPTION
**Pull request by vdbergh**
The PR has two independent commits

- Display the bootstrap notifications in all fishtest browser windows (currently a bootstrap notification is displayed only once, like a system notifications).

- Display the number of received (and non closed) notifications in the title of the tab.

### CODE REVIEW

**Comment by vdbergh** [comment]
It seems to work. I noticed as small bug in the string handling which has not consequence for the titles used in Fishtest. I will fix it in a separate PR.

**Comment by ppigazzini** [comment]
I think to have found a strange behavior.
If the home page is not reloaded after the tests are finished, it seems that you can trigger a new notification for the already finished test clicking on the icon.

**Comment by vdbergh** [comment]
> I think to have found a strange behavior. If the home page is not reloaded after the tests are finished, it seems that you can trigger a new notification for the already finished test clicking on the icon.

Yes that is correct. Good catch! Since it is an unrelated problem I will fix it in a separate PR.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
