### PR TITLE
Adaptation to W3C html validator, cleanups, formats, consistent uses,…

### PR DESCRIPTION
**Pull request by peregrineshahin**
… and retire innerHTML.
Please let me know if any validator error was missed.
a note: perhaps it needs a round or two of testing the whole thing (I didn't build it) maybe reviews also... Thanks.

### CODE REVIEW

**Comment by ppigazzini** [comment]
I was cleaning all the void elements, here for reference:
https://github.com/glinscott/fishtest/compare/master...ppigazzini:fishtest:fix_html_tests?expand=1

**Comment by ppigazzini** [comment]
DEV updated, started testing.

**Comment by ppigazzini** [comment]
DEV updated

**Comment by ppigazzini** [comment]
DEV updated

**Comment by ppigazzini** [comment]
`actions.mak` has still some problems, it's easier showing the source too:
https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fdfts-0.pigazzini.it%2Factions

**Comment by ppigazzini** [comment]
DEV updated.
Validated:
https://dfts-0.pigazzini.it/actions
https://dfts-0.pigazzini.it/nns
https://dfts-0.pigazzini.it/users

**Comment by ppigazzini** [comment]
DEV updated.
tests.mak has a problem with the button:
- Error: Attribute href not allowed on element [button](https://html.spec.whatwg.org/multipage/#the-button-element) at this point.
- Warning: The button role is unnecessary for element button.

https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fdfts-0.pigazzini.it%2Ftests

**Comment by ppigazzini** [comment]
DEV updated, the show/hide button for the workers stopped working.

**Comment by ppigazzini** [comment]
DEV updated

**Comment by peregrineshahin** [comment]
https://getbootstrap.com/docs/5.0/components/buttons/#:~:text=When%20using%20button,as%20screen%20readers.
bootstrap advice to change the button to anchor tag in this case

so let's see

**Comment by peregrineshahin** [comment]
```
<a class="btn btn-primary" href="#" role="button">Link</a>
<button class="btn btn-primary" type="submit">Button</button>
```
indeed the example code is self-explanatory I expect it to work.

**Comment by ppigazzini** [comment]
DEV updated, buttons working and `tests` page validated :)

**Comment by ppigazzini** [comment]
`nn_upload.mak` shows
> Error: Bad value for attribute action on element [form](https://html.spec.whatwg.org/multipage/#the-form-element): Must be non-empty.

for:
```html
<form action="" method="POST">
```

**Comment by ppigazzini** [comment]
https://dfts-0.pigazzini.it/tests/run

Has these problems:

image

**Comment by ppigazzini** [comment]
The SPSA parameters selector stopped working:
https://dfts-0.pigazzini.it/tests/view/63948b8d88432ad6ae39e6b0

**Comment by ppigazzini** [comment]
DEV updated

**Comment by ppigazzini** [comment]
DEV updated, SPSA fixed!

**Comment by ppigazzini** [comment]
DEV updated.
- SPSA works
- https://dfts-0.pigazzini.it/tests/run validated

The SPSA page has some problems:
https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fdfts-0.pigazzini.it%2Ftests%2Fview%2F63948b8d88432ad6ae39e6b0

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
Login and Register are working.

**Comment by ppigazzini** [comment]
DEV updated

**Comment by ppigazzini** [comment]
Now there is only this error for the SPSA page

**Comment by ppigazzini** [comment]
@FishChess I'm curious to know the technical reason of your downvotes (eg the button code commits)

**Comment by ppigazzini** [comment]
DEV updated, error changed

image

image

**Comment by ppigazzini** [comment]
DEV updated, SPSA page working and validated!

**Comment by FishChess** [comment]
> @FishChess I'm curious to know the technical reason of your downvotes (eg the button code commits)

_The `getElementsByClassName() `and `getElementsByTagName()` methods return a live **HTMLCollection**._

_The `querySelector` method returns a static **NodeList**._

_converting querySelector to getElements perhaps is not good idea_

**Comment by ppigazzini** [comment]
Found 1 problem in https://dfts-0.pigazzini.it/upload
(the URI doesn't work for page requiring authentication, I pasted the html code in the validator)

image

image

**Comment by peregrineshahin** [comment]
@FishChess
While The `getElementsByClassName()` and `getElementsByTagName()` methods return a live HTMLCollection. that is not the case for `getElementById()`

**Comment by ppigazzini** [comment]
Live Elo page 2 little problems
https://dfts-0.pigazzini.it/tests/live_elo/638ff4018536e3e199afde36
https://validator.w3.org/nu/?doc=https%3A%2F%2Fdfts-0.pigazzini.it%2Ftests%2Flive_elo%2F638ff4018536e3e199afde36

image

**Comment by FishChess** [comment]
> that is not the case for

In any case, only the names of the functions will change. What is the benefit?

**Comment by ppigazzini** [comment]
Raw statistic page 2 little problems
https://dfts-0.pigazzini.it/tests/stats/638ff4018536e3e199afde36

image

**Comment by ppigazzini** [comment]
Chess SPRT Calculator has 1 problem. I think to have tested all the pages.

https://validator.w3.org/nu/?doc=https%3A%2F%2Fdfts-0.pigazzini.it%2Fsprt_calc%3Felo-model%3DNormalized%26elo-0%3D0.0%26elo-1%3D2.0%26draw-ratio%3D0.49%26rms-bias%3D191

image

**Comment by vdbergh** [comment]
It seems to be the same issue as with the raw statistics page. `<style>` is not allowed inside a `<div>` . Maybe we should just move it to top level?

**Comment by peregrineshahin** [comment]
> It seems to be the same issue as with the raw statistics page. `<style>` is not allowed inside a `<div>` . Maybe we should just move it to top level?
> 
> EDIT: Info: [stackoverflow.com/questions/1385384/style-tag-inside-any-elements-will-still-work](https://stackoverflow.com/questions/1385384/style-tag-inside-any-elements-will-still-work)

Correct.

**Comment by ppigazzini** [comment]
DEV updated, upload page FIXED

**Comment by ppigazzini** [comment]
DEV updated, Live Elo page, href fixed

**Comment by ppigazzini** [comment]
DEV updated, checking the pages...

**Comment by ppigazzini** [comment]
DEV updated, Raw Statistic validate!
@peregrineshahin please squash the commits :)

**Comment by ppigazzini** [comment]
Applied by hand to PROD to test in the wide, finger crossed

**Comment by peregrineshahin** [comment]
There is one issue still I notice, I'll figure out now
the path to the preload img seems wrong when put in the css file
because the relative path change.

**Comment by peregrineshahin** [comment]
Sorry about the false positive, the link looks all right!

**Review by ppigazzini — APPROVED** [review]
No problems reported by users.

**Comment by ppigazzini** [comment]
PROD updated with master, thank you @peregrineshahin , great clean up :)

<a href="http://www.w3.org/html/logo/">
HTML5 Powered with CSS3 / Styling, and Semantics
</a>

**Comment by FishChess** [comment]
@peregrineshahin, great clean up, good luck :)

**Pull request merged**
