### PR TITLE
Various stats tweaks.

### PR DESCRIPTION
**Pull request by vdbergh**
Cleanups of SPRT handling in stat_util.py.

Remove a bit of code duplication.

Use """ """ style doc strings.

Document the LLR approximations we use in the raw_stats page.

### CODE REVIEW

**Comment by vdbergh** [comment]
I did some benchmarking. On Python3 on my laptop the LLR approximation we use is 20 times faster than the exact one. On the other hand, one call to compute the exact LLR takes about 80 microseconds (it requires numerically solving a secular equation). I wonder how many SPRT updates there are per second on fishtest... 

```
import time
from LLRcalc import LLR, LLR_alt, L_,results_to_pdf

elo0=-1
elo1=3
results=[726, 5007, 10065, 5021, 734]

s0,s1=[L_(elo) for elo in (elo0,elo1)]
N,pdf=results_to_pdf(results)

E=100000
t0=time.time()
for i in range(0,E):
    X=N*LLR(pdf,s0,s1)
t1=time.time()
A=(t1-t0)/E
t2=time.time()
for i in range(0,E):
    X=N*LLR_alt(pdf,s0,s1)
t3=time.time()
B=(t3-t2)/E
print(A,B,A/B)

```

**Comment by vdbergh** [comment]
Using scipy's brentq is a bit faster but not much. 60 microseconds.

**Comment by vdbergh** [comment]
Note that there is no clear theoretical reason why the "exact" LLR would be the best (the only thing that is known is that it behaves correctly asymptotically). With my testing resolution I could not establish any difference in behavior between the approximations. I would have to write a much faster simulator (C++ multi-threaded) to be able to detect any difference I guess.

**Comment by ppigazzini** [comment]
@vdbergh I my work prefer to use standard library and simplify the code base. IMO a new implementation makes sense only if the standard library is very slow or lacks precision.

**Comment by vdbergh** [comment]
@ppigazzini We can discuss this, but this is not what I was addressing in my comment. I was just wondering if it would be feasible to replace the LLR approximation I use with the exact value (which is about 15 times slower to compute, even if using the scipy brentq).

**Comment by vdbergh** [comment]
To clarify: **the LLR computation itself is not part of scipy.** But it needs a numerical solver and brentq is the best.

**Comment by ppigazzini** [comment]
I was talking about using scipy brentq and dropping the implementation used now.
About the impact of the slower LLR exact implementation, after some tests on DEV I can update by hand the files on PROD and test for sensible slowdown. The bottleneck on fishtest is MongoDB not the python code.

**Comment by vdbergh** [comment]
I will update the PR so that the exact LLR is always used.

But let's postpone changing brentq (and using the normal cdf from scipy) to a different PR. The scipy brentq has a slightly different interface so the assertions need to be adapted. I would prefer to test this first.

**Comment by vdbergh** [comment]
I updated to PR to always use the exact LLR (in a separate commit so that it is easier to revert).

**Comment by ppigazzini** [comment]
[DEV](https://dfts-0.pigazzini.it) updated after https://github.com/glinscott/fishtest/pull/519/commits/30705eab773cee607bc506db5e1bd74f37f4f4eb

**Comment by vdbergh** [comment]
I guess it should not be a problem. ```1868 games/minute```. 

```1868/60*80e-6=0.0025=0.25%```

A negligible increase in load.

**Comment by ppigazzini** [comment]
@vdbergh PROD update by hand copying the 3 files, CPU load unchanged (and very very low).

If I'm not wrong "secular equation" should be the "characteristic equation", in this case I suggest to use the latter term. At the moment the references doc "computeLLR.pdf" is unreachable and I'm not able to check by myself.

**Comment by vdbergh** [comment]
"Secular equation" has two meanings: a general one and a specific one. I am using it it in the specific sense of 
https://en.wikipedia.org/wiki/Divide-and-conquer_eigenvalue_algorithm (see the section conquer).

However I agree it is better that I change the wording as it is confusing.

**Comment by vdbergh** [comment]
Updated and squashed PR to a single commit.

**Comment by vdbergh** [comment]
Oops. Note rebased on current master.

**Comment by vdbergh** [comment]
Ok now.

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh 

ps: interesting algorithm :)

**Pull request merged**
