### PR TITLE
Cards for cores, nps...

### PR DESCRIPTION
**Pull request by dav1312**
The idea was popular in the Discord server so I created it
Cards can be removed, modified or reordered if necessary

### CODE REVIEW

**Comment by vondele** [comment]
I would drop `Avg. nodes / sec / core' can be computed easily enough.

**Comment by ppigazzini** [comment]
DEV updated https://github.com/glinscott/fishtest/pull/1376

**Comment by vondele** [comment]
on desktop, it feels like the info is a bit too dominant. Possibly because the numbers/data is bold and a large font. Maybe also because the cards span the whole width?

**Comment by dav1312** [comment]
> on desktop, it feels like the info is a bit too dominant. Possibly because the numbers/data is bold and a large font.

It uses the same font size as before, `h4`

> Maybe also because the cards span the whole width?

I can try to limit the width

**Comment by vondele** [comment]
yes, the font is the same, but since it is in the cards it becomes more prominent. I think it could probably be the same font size as what is in the LLR boxes.

**Comment by dav1312** [comment]
> yes, the font is the same, but since it is in the cards it becomes more prominent. I think it could probably be the same font size as what is in the LLR boxes.

That looks a little bit ridiculous...

image

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
Update to PROD by hand to collect a clear feedback.

**Comment by ppigazzini** [comment]
PROD updated, thank you @dav1312 :)

**Pull request merged**
