### PR TITLE
Fix info not showing in smaller screens

### PR DESCRIPTION
**Pull request by peregrineshahin**
My first Pull Request ever :)

### CODE REVIEW

**Comment by ppigazzini** [comment]
[DEV](https://dfts-0.pigazzini.it) updated with this PR, LGTM :)

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin :)
Please let me know your real name if you want that too in the AUTHORS file.

**Comment by vdbergh** [comment]
Hmm..  for me the info widget does not wrap (as it should IMHO). This PR creates horizontal scrolling instead in the Active tab (Linux Chrome on laptop) on a small screen.

The Finished tab behaves correctly though. Why are the Active tab and the Finished tab behaving differently...? They have the same source code (as one can see with view source).

**Comment by vdbergh** [comment]
In Firefox the Active tab also behaves correctly (the info widget wraps and no horizontal scrolling).

**Comment by vdbergh** [comment]
Perhaps this is the reason:

https://validator.w3.org/nu/?doc=https%3A%2F%2Ftests.stockfishchess.org%2Ftests

If there are errors in the html then one may expect unpredictable things to happen.

**Comment by vdbergh** [comment]
Ok I think I found the real cause. Chrome does not break links. Some of the current info widgets contain links, preventing the info widgets from wrapping.

**Comment by vdbergh** [comment]
See #1273

**Pull request merged**
