### PR TITLE
New worker version

### PR DESCRIPTION
**Pull request by Stefano80**
Update worker version to 63.

To be merged after all worker PR have been merged, before restarting.

### CODE REVIEW

**Comment by Stefano80** [comment]
If I am correct, merging this after all other worker PR have been merged will solve all problems, right?

**Comment by ppigazzini** [comment]
@Stefano80 I agree that this is the correct workflow to update the worker.

**Comment by Stefano80** [comment]
Before merging, we should:
- test on the dev server after merging locally this one
- then merge also xoto10 patch and test again on the dev server
- then merge this one on the repository, retest on the dev server
- go to production

**Comment by ppigazzini** [comment]
@snicolet the update process seems a little fragile, e.g. on windows w/ msys2 never worked (the worker continue to cycle w/ an error).

**Pull request closed without merging**
