### PR TITLE
Fix "tc_limit" for SPSA

### PR DESCRIPTION
**Pull request by ppigazzini**
For SPSA raise "tc_limit" only once and not at any iteration.
~~Raise also the "scaled_tc" decimal places to 5 for ultra low time control.~~

### CODE REVIEW

**Comment by vondele** [comment]
cutechess will only parse 3 digits of the tc, as far as I know. Similarly, in Stockfish time has millisecond resolution only.

**Comment by ppigazzini** [comment]
Thanks @vondele, added a comment about cutechess-cli and stockfish time control resolution.

**Comment by tomtor** [comment]
@ppigazzini Nice you found this bug.

I think this explains why I saw https://github.com/glinscott/fishtest/issues/731 only on SPSA tests. It did probably also happen on SPRT tests, but the timeout was much faster, so I did not notice it hanging.

**Comment by ppigazzini** [comment]
> @ppigazzini Nice you found this bug.
> 
> I think this explains why I saw #731 only on SPSA tests. It did probably also happen on SPRT tests, but the timeout was much faster, so I did not notice it hanging.

SPRT and NumGames return here skipping the timeout
https://github.com/glinscott/fishtest/blob/c16bc060f6c049fde2a1205f2ca8bfba44bfded2/worker/games.py#L373-L375

**Pull request merged**
