### PR TITLE
Simplify authentication in api.py.

### PR DESCRIPTION
**Pull request by vdbergh**
As a bonus we can now also return "blocked" messages.

### CODE REVIEW

**Comment by ppigazzini** [comment]
I can merge this and refactor #1173 

Unfortunately on DEV I'm getting this error installing fishtest (also master), perhaps a new pymongo version:

```
  File "<stdin>", line 4, in <module>
  File "/home/usr00/fishtest/server/fishtest/userdb.py", line 77, in add_user_group
    self.users.save(user)
  File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pymongo/collection.py", line 2584, in __call__
    raise TypeError("'Collection' object is not callable. If you meant to "
TypeError: 'Collection' object is not callable. If you meant to call the 'save' method on a 'Collection' object it is failing because no such method exists.
```

**Comment by vdbergh** [comment]
This is discussed here https://stackoverflow.com/questions/46866702/save-is-deprecated-for-what-in-pymongo

**Comment by vdbergh** [comment]
So maybe it should be 
```
self.users.replace_one({'_id': user['_id']}, user)
```

**Comment by ppigazzini** [comment]
I'm pushing a fix to use `pymongo 3.x,` better to debug the issue taking the proper time.

**Comment by ppigazzini** [comment]
DEV updated.

**Pull request merged**
