### PR TITLE
Remove Use NNUE which is no longer an option in master SF

### PR DESCRIPTION
**Pull request by vondele**

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by vondele** [comment]
hmm, looks wrong. Hash disappears.

**Comment by ppigazzini** [comment]
DEV updated

**Comment by vondele** [comment]
OK, that appears correct

**Review by ppigazzini — APPROVED** [review]
LG on DEV

**Comment by ppigazzini** [comment]
PROD updated, thank you @vondele :)

**Pull request merged**
