### PR TITLE
Enhance test_queries.py to include explains and to test hints

### PR DESCRIPTION
**Pull request by xoto10**
Enhance test_queries.py to include explains and to test hints.

### CODE REVIEW

**Comment by xoto10** [comment]
The explains show ` u'stage' : u'COLLSCAN' ` in my local fishtest since it has no data, but on prod they should show which index is being used.

**Comment by ppigazzini** [comment]
@xoto10 here the log from the dev-server:
[test_queries.zip](https://github.com/glinscott/fishtest/files/3893187/test_queries.zip)

**Comment by xoto10** [comment]
@ppigazzini @tomtor 
Interesting!

Looking at the explain plans, (see winningPlan for each one and above that executionTimeMillis) it looks like @tomtor 's change makes the finished query use the finished_1_last_updated_-1 index with a runtime of 2ms instead of the finished_1_last_updated_-1_start_time_-1 index which had a runtime of 13ms. (runtimes maybe not believable but the index change looks definite)
  
Looking at the hinted queries at the end, either there's a bug or they ran a lot faster than the originals at the top of the log file. :-)

These suggest to me that would we could consider one of:
- dropping the finished_1_last_updated_-1_start_time_-1 index since perhaps it isn't useful
- adding `.hint('finished_1_last_updated_-1')` to these queries in the code

There is a possibility that these results are influenced by caching, so you could try cutting and pasting the `# Tests: Hint some queries` section from the end to before the `# Time some important queries` so that the hinted versions have the disadvantage of going first, and run the test again.

**Comment by xoto10** [comment]
@ppigazzini 
Those runtimes for the hinted queries are buggy, I will update the PR ...

**Comment by xoto10** [comment]
@ppigazzini @tomtor 
No, perhaps the hints really are working! :-)
I've moved the hinted queries to the start of the script and added the #rows returned so we can check the results match between the original and hinted versions.

**Comment by xoto10** [comment]
Updated this to use the current definitions of the queries.

**Comment by tomtor** [comment]
Merged, we should write a rebuild indices script which deletes unneeded and creates needed indices in the future.

**Comment by xoto10** [comment]
> a rebuild indices script

Agreed. A standard technique is to code it to drop all the existing indexes (either with an exhaustive list or even better by querying the db to get the list) and then recreate the ones that are wanted. Ideally this makes it re-runnable in almost any circumstance and the end state is always the same.

**Comment by xoto10** [comment]
@ppigazzini @tomtor 
Can we run this latest test_queries.py to see how the queries are being executed now and to get some benchmark times now the system is running fairly smoothly?

**Comment by ppigazzini** [comment]
@xoto10 [test_queries.zip](https://github.com/glinscott/fishtest/files/3912755/test_queries.zip)

**Comment by xoto10** [comment]
@ppigazzini @tomtor 
Can we try dropping the index on finished, last_updated, start_time ?
I suspect the other index on finished and last_updated is as good / maybe better (it should be smaller), and there's no need to have both. 

If am wrong, it is possible the opposite could work, dropping the index on finished, last_updated, but I prefer to try dropping the larger index first.

We can run test_queries.py, and look at the load averages to see if the change helps or makes things worse.

**Comment by tomtor** [comment]
> Can we try dropping the index on finished, last_updated, start_time

This is the sort order, so I expect that dropping the other index would be better, but timing both options on dev is a good idea

**Comment by tomtor** [comment]
@ppigazzini @xoto10 I dropped by hand on prod:

    db['runs'].drop_index('finished_1_last_updated_-1') 

without bad effects... 

@xoto10 `test_queries.py` will now fail:

    pymongo.errors.OperationFailure: error processing query: ns=fishtest_new.runsTree: finished $eq false                                                                                        Sort: { last_updated: -1, start_time: -1 }                                                                                                                                                   
    Proj: {}                                                                                                                                                                                      
    planner returned error :: caused by :: hint provided does not correspond to an existing index

Can you file a PR to fix that?

**Pull request merged**
