### PR TITLE
Systematically benchmark api calls (worker side and server side).

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by vdbergh** [comment]
Now we also benchmark api calls server side. It seems that even on local host the network overhead is substantial.

**Comment by ppigazzini** [comment]
DEV and workers updated to run this and the companion #1200 
Scheduled some test @ 0.5+0.005, now we have `18 machines 81 cores 0.70 MNps (56.71 total MNps) 1684 games/minute 261.7 hours remaining`
This is the DEV load:
```
top - 17:09:08 up 83 days, 20:57,  1 user,  load average: 0.00, 0.06, 0.11
Tasks:  31 total,   1 running,  30 sleeping,   0 stopped,   0 zombie
%Cpu0  :   0.7/0.0     1[|                                                                                                   ]
%Cpu1  :   0.7/0.0     1[|                                                                                                   ]
%Cpu2  :   0.7/0.3     1[|                                                                                                   ]
%Cpu3  :   0.3/0.0     0[                                                                                                    ]
KiB Mem : 35.5/6291456  [|||||||||||||||||||||||||||||||||||                                                                 ]
KiB Swap:  0.6/3145728  [|                                                                                                   ]

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20      224904   4952   3320 S        0.1   0:59.65 init -z
    2 root      20                           S                       `- [kthreadd/13518]
    3 root      20                           S              0:00.12      `- [khelper]
   63 root      20      154392  31452  20780 S        0.5   5:13.01  `- /lib/systemd/systemd-journald
  189 root      20       42100    628    576 S        0.0   0:11.23  `- /lib/systemd/systemd-udevd
  191 systemd+  20       71712               S              0:13.36  `- /lib/systemd/systemd-networkd
  197 root      20       61976    432    260 S        0.0   0:14.56  `- /lib/systemd/systemd-logind
  203 message+  20       47880   1372    828 S        0.0   0:02.99  `- /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  315 root      20      184296    464    464 S        0.0   0:00.16  `- /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
  330 root      20       13016    288    288 S        0.0            `- /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux
  332 root      20      100980    492    488 S        0.0            `- /usr/sbin/saslauthd -a pam -c -m /var/run/saslauthd -n 2
  334 root      20      100980      4        S        0.0                `- /usr/sbin/saslauthd -a pam -c -m /var/run/saslauthd -n 2
  333 root      20       13016    308    308 S        0.0            `- /sbin/agetty -o -p -- \u --noclear tty2 linux
  344 root      20       72296    684    572 S        0.0   0:09.84  `- /usr/sbin/sshd -D
 5680 root      20       97188   3752   2812 S        0.1   0:00.04      `- sshd: usr00 [priv]
 5695 usr00     20       97188   3192   2252 S        0.1   0:04.47          `- sshd: usr00@pts/0
 5696 usr00     20       19668   4520   2876 S        0.1   0:00.46              `- -bash
30268 usr00     20       36620   3160   2636 R   0.3  0.1   0:03.85                  `- top
  376 root      20       24184    516    512 S        0.0            `- /usr/sbin/xinetd -pidfile /run/xinetd.pid -stayalive -inetd_compat -inetd_ipv6
  604 Debian-+  20       61532    676    616 S        0.0   0:02.52  `- /usr/sbin/exim4 -bd -q30m
24556 root      20       28352   2408   2208 S        0.0   0:10.50  `- /usr/sbin/cron -f
 7775 syslog    20      189024   1644   1524 S        0.0   0:07.29  `- /usr/sbin/rsyslogd -n
17080 root      20      142272    552        S        0.0            `- nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
17081 www-data  20      143804   6980   5152 S   1.0  0.1  13:21.15      `- nginx: worker process
17082 www-data  20      143336   5936   4856 S        0.1   0:02.41      `- nginx: worker process
17083 www-data  20      142764   3016   2140 S        0.0   0:00.05      `- nginx: worker process
17084 www-data  20      142896   3272   2048 S        0.1   0:00.06      `- nginx: worker process
14608 usr00     20       76912  11300   2816 S        0.2   5:41.76  `- /home/usr00/post-server/env/bin/python3 /home/usr00/post-server/server.py
29376 mongodb   20     2981452 1.430g  36760 S   0.3 23.8   0:36.69  `- /usr/bin/mongod --config /etc/mongod.conf
29532 usr00     20     1375248 569128  32864 S   2.0  9.0   1:24.38  `- /home/usr00/fishtest/server/env/bin/python3 /home/usr00/fishtest/server/env/bin/pserve production.ini http_port=6543
29533 usr00     20      983748 210808  30836 S   0.3  3.4   0:07.66  `- /home/usr00/fishtest/server/env/bin/python3 /home/usr00/fishtest/server/env/bin/pserve production.ini http_port=6544
```

**Comment by ppigazzini** [comment]
Tests @ 0.3+0.003 `18 machines 81 cores 0.81 MNps (65.55 total MNps) 3313 games/minute 262.4 hours remaining`
DEV loads:
```
top - 17:35:33 up 83 days, 21:23,  2 users,  load average: 0.11, 0.16, 0.14
Tasks:  35 total,   1 running,  34 sleeping,   0 stopped,   0 zombie
%Cpu0  :   0.7/0.0     1[|                                                                                                   ]
%Cpu1  :   1.7/0.3     2[||                                                                                                  ]
%Cpu2  :   1.0/0.7     2[||                                                                                                  ]
%Cpu3  :   1.7/0.7     2[|||                                                                                                 ]
KiB Mem : 36.5/6291456  [||||||||||||||||||||||||||||||||||||                                                                ]
KiB Swap:  0.6/3145728  [|                                                                                                   ]

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20      224904   4952   3320 S        0.1   0:59.66 init -z
    2 root      20                           S                       `- [kthreadd/13518]
    3 root      20                           S              0:00.12      `- [khelper]
   63 root      20      154392  32920  22244 S        0.5   5:13.12  `- /lib/systemd/systemd-journald
  189 root      20       42100    628    576 S        0.0   0:11.24  `- /lib/systemd/systemd-udevd
  191 systemd+  20       71712               S              0:13.36  `- /lib/systemd/systemd-networkd
  197 root      20       61976    432    260 S        0.0   0:14.56  `- /lib/systemd/systemd-logind
  203 message+  20       47880   1372    828 S        0.0   0:02.99  `- /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  315 root      20      184296    464    464 S        0.0   0:00.16  `- /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
  330 root      20       13016    288    288 S        0.0            `- /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux
  332 root      20      100980    492    488 S        0.0            `- /usr/sbin/saslauthd -a pam -c -m /var/run/saslauthd -n 2
  334 root      20      100980      4        S        0.0                `- /usr/sbin/saslauthd -a pam -c -m /var/run/saslauthd -n 2
  333 root      20       13016    308    308 S        0.0            `- /sbin/agetty -o -p -- \u --noclear tty2 linux
  344 root      20       72296    860    748 S        0.0   0:09.84  `- /usr/sbin/sshd -D
 5680 root      20       97188   3752   2812 S        0.1   0:00.04      `- sshd: usr00 [priv]
 5695 usr00     20       97188   3192   2252 S        0.1   0:04.72          `- sshd: usr00@pts/0
 5696 usr00     20       19668   4520   2876 S        0.1   0:00.46              `- -bash
30268 usr00     20       36620   3160   2636 S        0.1   0:06.55                  `- top
 1480 root      20       97188   6580   5640 S        0.1   0:00.04      `- sshd: usr00 [priv]
 1494 usr00     20       97188   3404   2464 S        0.1   0:00.01          `- sshd: usr00@pts/1
 1495 usr00     20       19536   4340   2932 S        0.1   0:00.06              `- -bash
 1516 usr00     20       36620   3108   2580 R   0.3  0.0   0:00.09                  `- top
  376 root      20       24184    516    512 S        0.0            `- /usr/sbin/xinetd -pidfile /run/xinetd.pid -stayalive -inetd_compat -inetd_ipv6
  604 Debian-+  20       61532    676    616 S        0.0   0:02.52  `- /usr/sbin/exim4 -bd -q30m
24556 root      20       28352   2408   2208 S        0.0   0:10.50  `- /usr/sbin/cron -f
 7775 syslog    20      189024   1644   1524 S        0.0   0:07.29  `- /usr/sbin/rsyslogd -n
17080 root      20      142272    552        S        0.0            `- nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
17081 www-data  20      143804   6980   5152 S   2.3  0.1  14:04.57      `- nginx: worker process
17082 www-data  20      143336   5936   4856 S        0.1   0:03.46      `- nginx: worker process
17083 www-data  20      142764   3016   2140 S        0.0   0:00.05      `- nginx: worker process
17084 www-data  20      142896   3272   2048 S        0.1   0:00.06      `- nginx: worker process
14608 usr00     20       76912  11300   2816 S        0.2   5:42.06  `- /home/usr00/post-server/env/bin/python3 /home/usr00/post-server/server.py
29376 mongodb   20     2982480 1.429g  36760 S   2.0 23.8   0:58.83  `- /usr/bin/mongod --config /etc/mongod.conf
29532 usr00     20     1432864 626536  32864 S   2.3 10.0   3:13.19  `- /home/usr00/fishtest/server/env/bin/python3 /home/usr00/fishtest/server/env/bin/pserve production.ini http_port=6543
29533 usr00     20      983748 210808  30836 S        3.4   0:09.13  `- /home/usr00/fishtest/server/env/bin/python3 /home/usr00/fishtest/server/env/bin/pserve production.ini http_port=6544

```

**Comment by ppigazzini** [comment]
Tests @ 0.1 + 0.001 `18 machines 81 cores 0.68 MNps (55.38 total MNps) 8397 games/minute 156.5 hours remaining`.
DEV loads:
```
top - 02:29:17 up 84 days,  6:17,  1 user,  load average: 0.43, 0.33, 0.33
Tasks:  31 total,   2 running,  29 sleeping,   0 stopped,   0 zombie
%Cpu0  :   6.6/1.3     8[||||||||                                                                                            ]
%Cpu1  :   4.7/0.7     5[||||||                                                                                              ]
%Cpu2  :   6.0/1.0     7[|||||||                                                                                             ]
%Cpu3  :   3.3/0.7     4[||||                                                                                                ]
KiB Mem : 24.8/6291456  [|||||||||||||||||||||||||                                                                           ]
KiB Swap:  0.5/3145728  [|                                                                                                   ]

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20      224904   4964   3332 S        0.1   0:59.94 init -z
    2 root      20                           S                       `- [kthreadd/13518]
    3 root      20                           S              0:00.12      `- [khelper]
   63 root      20      162584  47220  36520 S        0.8   5:14.88  `- /lib/systemd/systemd-journald
  189 root      20       42100    628    576 S        0.0   0:11.28  `- /lib/systemd/systemd-udevd
  191 systemd+  20       71712               S              0:13.42  `- /lib/systemd/systemd-networkd
  197 root      20       61976    432    260 S        0.0   0:14.63  `- /lib/systemd/systemd-logind
  203 message+  20       47880   1372    828 S        0.0   0:02.99  `- /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  315 root      20      184296    464    464 S        0.0   0:00.16  `- /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
  330 root      20       13016    288    288 S        0.0            `- /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux
  332 root      20      100980    492    488 S        0.0            `- /usr/sbin/saslauthd -a pam -c -m /var/run/saslauthd -n 2
  334 root      20      100980      4        S        0.0                `- /usr/sbin/saslauthd -a pam -c -m /var/run/saslauthd -n 2
  333 root      20       13016    308    308 S        0.0            `- /sbin/agetty -o -p -- \u --noclear tty2 linux
  344 root      20       72296    860    748 S        0.0   0:09.84  `- /usr/sbin/sshd -D
 1480 root      20       97188   6580   5640 S        0.1   0:00.07      `- sshd: usr00 [priv]
 1494 usr00     20       97188   4328   3376 S        0.1   0:05.88          `- sshd: usr00@pts/1
 1495 usr00     20       19668   4616   2996 S        0.1   0:00.08              `- -bash
13599 usr00     20       36628   3176   2636 R        0.1   0:38.90                  `- top
  376 root      20       24184    516    512 S        0.0            `- /usr/sbin/xinetd -pidfile /run/xinetd.pid -stayalive -inetd_compat -inetd_ipv6
  604 Debian-+  20       61532   1220   1120 S        0.0   0:02.54  `- /usr/sbin/exim4 -bd -q30m
24556 root      20       28352   2408   2208 S        0.0   0:10.59  `- /usr/sbin/cron -f
 7775 syslog    20      189024   1912   1556 S        0.0   0:07.38  `- /usr/sbin/rsyslogd -n
17080 root      20      142272    552        S        0.0            `- nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
17081 www-data  20      144020   7336   5584 R  12.3  0.1  44:16.81      `- nginx: worker process
17082 www-data  20      143532   6188   4980 S   1.3  0.1   2:58.71      `- nginx: worker process
17083 www-data  20      142860   5716   4756 S        0.1   0:02.83      `- nginx: worker process
17084 www-data  20      142896   3272   2048 S        0.1   0:00.06      `- nginx: worker process
14608 usr00     20       76912  11300   2816 S        0.2   5:48.13  `- /home/usr00/post-server/env/bin/python3 /home/usr00/post-server/server.py
13302 mongodb   20     2307044 828160  37268 S   1.0 13.2   4:54.75  `- /usr/bin/mongod --config /etc/mongod.conf
13446 usr00     20     1442632 667312  32972 S  11.0 10.6  32:55.25  `- /home/usr00/fishtest/server/env/bin/python3 /home/usr00/fishtest/server/env/bin/pserve production.ini http_port=6543
13447 usr00     20      972616 109780  31396 S        1.7   0:16.36  `- /home/usr00/fishtest/server/env/bin/python3 /home/usr00/fishtest/server/env/bin/pserve production.ini http_port=6544
```

**Comment by vdbergh** [comment]
I am currently only sending to timing to the worker (as `{'duration': ..., ...}`. 

I could also print it so that it appears in the server log but I do not know what would be the performance impact of a print statement in every api call. Probably none if we do not use `flush=True`. But that does not help if the server itself is invoked with python -u (as has been discussed). Of course even with `flush=True` the performance impact is probably negligible.

**Comment by vdbergh** [comment]
BTW with #1200 I typically get
```
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.124825s (server: 0.003433s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.112473s (server: 0.002888s)
```
So about `3ms`.

I do not know without #1200.

**Comment by ppigazzini** [comment]
In this moment, with several NumGames tests 800k @ 0.1+0.001, (17 machines 58 cores 0.69 MNps (39.77 total MNps) 6031 games/minute 8.8 hours remaining) I got this numbers:
- w/o #1200
```
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.127612s (server: 0.000375s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.138098s (server: 0.000351s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.111545s (server: 0.000431s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.124445s (server: 0.000416s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.134029s (server: 0.000337s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.143616s (server: 0.000341s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.123071s (server: 0.000358s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.130644s (server: 0.000467s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.149471s (server: 0.000254s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.159467s (server: 0.000654s)
```
- w #1200
```
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.117395s (server: 0.000327s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.116607s (server: 0.000406s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.133323s (server: 0.000658s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.119845s (server: 0.000327s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.138632s (server: 0.000509s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.155345s (server: 0.000421s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.181358s (server: 0.000458s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.143473s (server: 0.000525s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.139605s (server: 0.000445s)
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 0.137495s (server: 0.000524s)
```

**Comment by vondele** [comment]
what about trying to add a worker that simulates the failed github access and see what happens?

**Comment by vdbergh** [comment]
So the difference seems to be very small so far. I am surprised by this. On my laptop the difference was very significant (even for a run with 200 tasks).

During the flooding we had runs with 3500 tasks.

**Comment by vdbergh** [comment]
Ah wait. It is not `/api/update_task` that is the problem but `/api/failed_task` !!!

**Comment by ppigazzini** [comment]
> what about trying to add a worker that simulates the failed github access and see what happens?

Added a failing worker according to https://github.com/vondele/fishtest/commit/a235712b1131bcb69b3bd8728a249b8e5e4b549c

**Comment by ppigazzini** [comment]
> Ah wait. It is not `/api/update_task` that is the problem but `/api/failed_task` !!!
> 
> #1200 doesn't touch `/api/update_task`.

I logged the wrong api :(
Redoing the test.

**Comment by vdbergh** [comment]
> > Ah wait. It is not `/api/update_task` that is the problem but `/api/failed_task` !!!
> > #1200 doesn't touch `/api/update_task`.
> 
> I logged the wrong api :( Redoing the test.

I usually run the workers under `nohup` (with `python -u`). Then a simple grep is sufficient to extract whatever data one wants.

**Comment by ppigazzini** [comment]
> what about trying to add a worker that simulates the failed github access and see what happens?

failing worker with 30 cores, 111 events entries per minute:
```
sudo journalctl -u fishtest@6543 --since "1 hour ago" | grep 14:46 | wc -l
111
```

DEV CPU load is fine `top - 14:44:59 up 84 days, 18:33,  1 user,  load average: 0.09, 0.08, 0.20`

**Comment by vondele** [comment]
is that with the new patch or without ?

**Comment by ppigazzini** [comment]
With the new patch, but the `failed_task` API call seems to be very rare (still no seen in over 30 minutes).
@vdbergh DEV and workers look good, I'm fine with your speedup test. If you agree I will prefer to stop the test, approve #1200 and #1202 and start testing other PRs.

**Comment by vdbergh** [comment]
> With the new patch, but the `failed_task` API call seems to be very rare (still no seen in over 30 minutes). 

In normal circumstances it is indeed quite rare. But with a broken worker it can become very frequent  (as one can see in the event log). Then I think the implementation in master does not scale at all (which was mostly my fault).

> @vdbergh DEV and workers look good, I'm fine with your speedup test. If you agree I will prefer to stop the test, approve #1200 and #1202 and start testing other PRs.

Sure. The PRs are fine.

**Comment by ppigazzini** [comment]
So testing was easy with a failing worker...
- w/o #1200
```
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.188283s (server: 0.069129s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.236573s (server: 0.113572s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.181832s (server: 0.068418s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.198777s (server: 0.076142s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.21424s (server: 0.073388s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.221294s (server: 0.100456s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.234602s (server: 0.113458s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.25228s (server: 0.110979s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.212404s (server: 0.07196s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.230099s (server: 0.107163s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.244521s (server: 0.129894s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.250656s (server: 0.127137s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.233313s (server: 0.103834s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.318865s (server: 0.194635s)
```
- w/ #1200 
```
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.139353s (server: 0.007551s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.12473s (server: 0.002511s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.124337s (server: 0.004964s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.11725s (server: 0.002904s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.139246s (server: 0.002406s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.142941s (server: 0.002901s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.117775s (server: 0.004917s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.126929s (server: 0.002322s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.143664s (server: 0.003018s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.128821s (server: 0.003191s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.147381s (server: 0.003445s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.141684s (server: 0.002891s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.125202s (server: 0.003875s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.132277s (server: 0.002498s)
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 0.122109s (server: 0.002293s)
```

**Comment by ppigazzini** [comment]
master with one failing worker at 30 cores, 88 events entries per minute:
```
sudo journalctl -u fishtest@6543 --since "1 hour ago" | grep 16:00 | wc -l
88
```

CPU load seems to be higher than with the patch in place `top - 16:26:37 up 84 days, 20:14,  1 user,  load average: 0.30, 0.34, 0.30`

**Review by ppigazzini — APPROVED** [review]

**Pull request merged**
