### PR TITLE
Opt-in system for notifications.

### PR DESCRIPTION
**Pull request by vdbergh**
The live_elo page now has a button where one can subscribe to notifications.

Some information is saved in local storage. Since Fishtest may have been opened in several tabs, this may lead to race conditions. We try to mitigate this by avoiding slow operations in critical sections.

Note that the current version prints a few messages on the console for debugging.

As usual the notifications themselves are not tested.

Note: it is currently not possible subscribe to notifications for fixed length tests. To make this possible one should extend the live elo page to handle NumGames tests. Or put the subscription button somewhere else (e.g. on the main page).

### CODE REVIEW

**Comment by ppigazzini** [comment]
Problem on Edge:

image

**Comment by ppigazzini** [comment]
Opera:

image

**Comment by ppigazzini** [comment]
Firefox

image

**Comment by ppigazzini** [comment]
Chrome:

image

**Comment by vdbergh** [comment]
I saw a notification on chrome.

However while trying to disable notifications in the settings (to test the dialog for allowing notifications) I saw an error appear in the console. Not sure where it came from.

**Comment by vdbergh** [comment]
@dav1312 

> It doesn't make sense that u get different results on opera, edge and chrome since they are all basically the same

I am not sure I understand. What is the difference you are referring to?

**Comment by ppigazzini** [comment]
Notifications work on Chrome, Opera, Firefox, tested with live_elo opened and with home page opened.

**Comment by ppigazzini** [comment]
master shows those warning on Edge as well

image

**Comment by dav1312** [comment]
> @dav1312
> 
> > It doesn't make sense that u get different results on opera, edge and chrome since they are all basically the same
> 
> I am not sure I understand. What is the difference you are referring to?

Idk he seemed to get an error on edge but not in the others, maybe I just misread

**Comment by ppigazzini** [comment]
I started testing Edge on a VM, perhaps is ublocker that breaks the script.

**Comment by vdbergh** [comment]
> master shows those warning on Edge as well
> 
> image

Are you in a private browser window perhaps?

**Comment by vdbergh** [comment]
image

This is the error I sometimes get when disabling notifications on chrome.

**Comment by vdbergh** [comment]
Ok I see. The previous dialog no longer exists since one now has to push a button anyway to opt in.

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by vdbergh** [comment]
> master with Edge (not InPrivate) in a clean VM
> 
> image

It seems these errors are benign since the gauges are moving. It seems google charts tries to access some kind of storage on the browser and Edge is disallowing this (because of CORS maybe?).

**Comment by ppigazzini** [comment]
I started the 4 browser clearing the permission for the notification, then I clicked "Follow". Only Firefox asked for the permission to send the notification. Waiting the finish of the test.

**Comment by vdbergh** [comment]
In my case Chrome usually asks for permission to send notifications. But clicking allow does not always seem to have an immediate effect.

**Comment by ppigazzini** [comment]
> In my case Chrome usually asks for permission to send notifications. But clicking allow does not always seem to have an immediate effect.

After a change of the permission the browser ask for a refresh..

**Comment by ppigazzini** [comment]
!!!

image

**Comment by vdbergh** [comment]
This is the code executed as a response to an click event (borrowed from @dav1312 )
```js
      if (supportsNotifications() && Notification.permission === "default") {
        Notification.requestPermission();
      }
```
This is the code for `supportsNotifications()`: (also from dav123)
```js
function supportsNotifications() {
  if (
    // Notifications only work over a secure connection                                                                                                                                
    window.location.protocol == "https:" &&
    // Safari on iOS doesn't support them                                                                                                                                              
    "Notification" in window &&
    // Chrome and Opera on Android don't support them                                                                                                                                  
    !(
      navigator.userAgent.match(/Android/i) &&
      navigator.userAgent.match(/Chrome/i)
    )
  ) {
    return true;
  }
  return false;
}
```
It's not clear to me if there could be a problem.

**Comment by ppigazzini** [comment]
If I understood correctly if the browser has the system notification blocked it shows a browser notification.

**Comment by vdbergh** [comment]
@ppigazzini  Yes if you block notifications then the browser will not ask. If you still insist on following the test the PR will use a bootstrap alert to display notifications.

**Comment by ppigazzini** [comment]
Resetting to "Ask" all browser asked for the permission.

**Comment by ppigazzini** [comment]
Passed! The firefox notification seems disappear after few seconds.

image

**Comment by dav1312** [comment]
> Passed! The firefox notification seems disappear after few seconds.

Firefox doesn't support `requireInteraction`

**Comment by ppigazzini** [comment]
Tested working with Edge InPrivate with uBlock.

**Comment by vdbergh** [comment]
I fixed a bug (the LRU object losing its capacity field). This seems to have had no consequences, but it is not nice.

**Comment by ppigazzini** [comment]
DEV updated, new round of tests.

**Comment by vdbergh** [comment]
Things work on ipad. The notification is displayed in a bootstrap alert.

**Comment by ppigazzini** [comment]
It seems that I don't have the "Follow" button on Chrome...

**Comment by vdbergh** [comment]
@dav1312 Do you know what would be a good way to make sure that the bootstrap alert div does not scroll under the main (it should be floating).

**Comment by vdbergh** [comment]
> It seems that I don't have the "Follow" button on Chrome...

I see them. Does the button appear if you reload the page?

**Comment by vdbergh** [comment]
If there is a network error during fetching the finished runs, then the follow button will not show.

**Comment by ppigazzini** [comment]
> > It seems that I don't have the "Follow" button on Chrome...
> 
> I see them. Does the button appear if you reload the page?

Yes, in another browser the button appeared after a reload.

**Comment by ppigazzini** [comment]
> Things work on ipad. The notification is displayed in a bootstrap alert.

Bootstrap alert in Android/Chrome as weel.

**Comment by dav1312** [comment]
> @dav1312 Do you know what would be a good way to make sure that the bootstrap alert div does not scroll under the main header (it should be floating).

A [modal](https://getbootstrap.com/docs/5.2/components/modal/#live-demo)?

**Comment by vdbergh** [comment]
> > @dav1312 Do you know what would be a good way to make sure that the bootstrap alert div does not scroll under the main header (it should be floating).
> 
> A [modal](https://getbootstrap.com/docs/5.2/components/modal/#live-demo)?

Hmm I don't think notifications should be modal.... They should be as non-intrusive as possible. 

I think I will leave this to another PR.

**Review by ppigazzini — APPROVED** [review]
Let's merge!

**Comment by vdbergh** [comment]
> > Things work on ipad. The notification is displayed in a bootstrap alert.
> 
> Bootstrap alert in Android/Chrome as well. On Android/Edge the alert appeared after a reload of the home page.

It may have been hidden under the main header. Ideally the alert should stay in place like the main header stays in place when you scroll. But I do not know how to do this.

**Comment by vdbergh** [comment]
> Let's merge!

I will first remove the instrumentation.

**Comment by vdbergh** [comment]
Oops its already merged. I'll make a separate commit.

**Comment by ppigazzini** [comment]
PROD update, sorry @vdbergh :D

**Comment by vdbergh** [comment]
Done.

**Comment by dav1312** [comment]
> > > @dav1312 Do you know what would be a good way to make sure that the bootstrap alert div does not scroll under the main header (it should be floating).
> > 
> > 
> > A [modal](https://getbootstrap.com/docs/5.2/components/modal/#live-demo)?
> 
> Hmm I don't think notifications should be modal.... They should be as non-intrusive as possible.
> 
> I think I will leave this to another PR.

You can also use `position-absolute` but be careful because darkmode modals have slighly transparent backgrounds

**Comment by vdbergh** [comment]
> > > > @dav1312 Do you know what would be a good way to make sure that the bootstrap alert div does not scroll under the main header (it should be floating).
> > > 
> > > 
> > > A [modal](https://getbootstrap.com/docs/5.2/components/modal/#live-demo)?
> > 
> > 
> > Hmm I don't think notifications should be modal.... They should be as non-intrusive as possible.
> > I think I will leave this to another PR.
> 
> You can also use `position-absolute` but be careful because darkmode alerts have slighly transparent backgrounds

Thanks! I'll have a look.

**Comment by vdbergh** [comment]
Actually the instrumentation isn't so bad. It is useful for debugging.

**Pull request merged**
