### PR TITLE
Add new line to big screens and temporarily change colors ltc highlig…

### PR DESCRIPTION
**Pull request by peregrineshahin**
…ht colors to suggested ones.

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by peregrineshahin** [comment]
this will do the job, for the time being, will need feedback from users on colors and any suggested design enhancements

**Comment by ppigazzini** [comment]
DEV updated

**Comment by peregrineshahin** [comment]
the intended behavior is confirmed.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin for the fast fix :)

**Comment by dubslow** [comment]
I don't fully follow the div change, but sure.

I do however think the original color was better. It's supposed to be a subtle eye attractor, not a big massive "LOOK AT ME" sort of thing which is what it feels like now. It should rather be the ~same shade as the link color (as it was before).

**Comment by peregrineshahin** [comment]
The <div> change as opposed to a <br> fixes the responsiveness naturally because divs are displayed as a block adding a break line but in mobile the break line is not needed and handled otherwise via CSS and not HTML. 

Regarding the colors I agree that the color of the outline is too strong on the night-mode layout and is not in contrast with the other green which links have. But it was added temporarily based on 2 users feedback.
As of all, I'm in favor of the idea of making ltc easier to spot but I'm not sure about the design details before and after this commit.

**Pull request merged**
