### PR TITLE
Optimized, Beauty, Cleanups, ...

### PR DESCRIPTION
**Pull request by FishChess**
**old formatting A** 
```js
  if (
    // Safari on iOS doesn't support them
    "Notification" in window &&
    // Chrome and Opera on Android don't support them
    !(
      navigator.userAgent.match(/Android/i) &&
      navigator.userAgent.match(/Chrome/i)
    )
  )
    return true;
  return false;
```

**new formatting A**

```js
    if (// Safari on iOS doesn't support them
    "Notification"in window && // Chrome and Opera on Android don't support them
    !(navigator.userAgent.match(/Android/i) && navigator.userAgent.match(/Chrome/i)))
        return true;
    return false;
```

**old formatting B**
```js 
  s.num_games = -1;
  for (let i = 0; i < s.num_params; i++) {
    const ng = Math.round(s.lambda_ratio * lambda[i]);
    if (ng > s.num_games) {
      s.num_games = ng;
         }
  }
  ```
  
  **new formatting B**
  
  ```js 
  s.num_games = -1;
  ```
  
  **old formatting C** 
```js
const getCellValue = (tr, idx) =>
  tr.children[idx].dataset.diff ||
  tr.children[idx].innerText ||
  tr.children[idx].textContent;
const padDotVersion = (dn) =>
  dn
    .split(".")
    .map((n) => +n + 1000)
    .join("");
const padDotVersionStr = (dn) => dn.replace(/\d+/g, (n) => +n + 1000);
```

**new formatting C** 
```js
const getCellValue = (tr,idx)=>tr.children[idx].dataset.diff || tr.children[idx].innerText || tr.children[idx].textContent;
const padDotVersion = (dn)=>dn.split(".").map((n)=>+n + 1000).join("");
const padDotVersionStr = (dn)=>dn.replace(/\d+/g, (n)=>+n + 1000);
```
  
  **old formatting D**

```js
 let ret = "";
  for (let i = 0; i < ss.params.length; i++) {
    const p = ss.params;
    ret +=
      p[i].name +
      "," +
      p[i].start +
      "," +
      p[i].min +
      "," +
      p[i].max +
      "," +
      p[i].c.toFixed(2) +
      "," +
      p[i].r.toFixed(5) +
      "\n";
  }
  return ret;
```
**new formatting D**
```js
    let ret = "";
    for (let i = 0; i < ss.params.length; i++) {
        const p = ss.params;
        ret += p[i].name + "," + p[i].start + "," + p[i].min + "," + p[i].max + "," + p[i].c.toFixed(2) + "," + p[i].r.toFixed(5) + "\n";
    }
    return ret;
```

**old formatting E**
```js
  return tc_seconds !== null
    ? logistic(slope * Math.log(tc_seconds) + intercept)
    : null;
```
**new formatting E**

```js 
  return tc_seconds !== null ? logistic(slope * Math.log(tc_seconds) + intercept) : null;
```

**old formatting F**
```js
  try {
    window
      .matchMedia("(prefers-color-scheme: dark)")
      .addEventListener("change", () => setTheme(getPreferredTheme()));
  } catch (e) {
    console.error(e);
  }
```

**new formatting F**

```js
    try {
        window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", ()=>setTheme(getPreferredTheme()));
    } catch (e) {
        console.error(e);
    }
```

### CODE REVIEW

**Comment by ppigazzini** [comment]
Please mind that we use formatters for the all the code base, see https://github.com/glinscott/fishtest/issues/634
For js, html, css:
```
npx prettier --write "server/fishtest/static/{css/*.css,html/*.html,js/*[!highlight.diff.min].js}"
```

**Comment by FishChess** [comment]
> Please mind that we use formatters for the all the code base, see #634 For js, html, css:

**_yes, I see, no formatters changed, no functional changes_**

**Comment by mhouppin** [comment]
> > Please mind that we use formatters for the all the code base, see #634 For js, html, css:
> 
> _yes, I see, no formatting changed, no functional changed_
> 
> _Just Optimized & Beauty Code Useful for developers_
> 
> _Formatting Adaptation to W3C_

All your changes are basically formatting changes. As explained by @ppigazzini , fishtest already uses a tool to format source code, which makes your edits unuseful since they will be all reverted by the next PR.
Furthermore, these changes make the code harder to read and maintain.

Could you please explain the reasoning behind this PR ? There's little to no chance this will get merged, unless you provide clear insights as to why this reformatting is pertinent.

**Comment by FishChess** [comment]
> Furthermore, these changes make the code harder to read and maintain.

```
const padDotVersion = (dn) =>
  dn
    .split(".")
    .map((n) => +n + 1000)
    .join("");
```
is this formatting is pertinent? 

> which makes your edits unuseful since they will be all reverted by the next PR.

**formating2 (formating1 code) ≠ formating2 code** 

> fishtest already uses a tool to format source code

can I see e.g. `calc.js` source after formatting ?

**Comment by mhouppin** [comment]
> ```
> const padDotVersion = (dn) =>
>   dn
>     .split(".")
>     .map((n) => +n + 1000)
>     .join("");
> ```
> 
> is this formatting is pertinent?

Yes. It's a very common thing in functional languages to place chained calls like this on a separated line, as it makes it much easier to see how a variable is manipulated to go from one state to another. This is for example the standard with Rust default formatter when these constructs take too much place to fit on one line.

> **formating2 (formating1 code) ≠ formating2 code**

In the case of your PR, this is wrong. You didn't change anything besides code indentation and spacing, so the next PR using the formatting tool will revert all the changes.

> > fishtest already uses a tool to format source code
> 
> can I see e.g. `calc.js` source after formatting ?

The file was already formatted by the tool before your PR, so reusing the tool on it will cancel your edits.

> > Could you please explain the reasoning behind this PR ?
> 
> my code formatting is best format, show me a bug in code formatting that not optimized or beauty ?

There's no such thing as "best format" or "beauty", and coming on a repository to argue about the formatting on your first PR is not [how you should contribute to an open-source project.](https://tirania.org/blog/archive/2010/Dec-31.html)
"Optimizing" a code for LOC is definitely not a good argument here, since it makes the code indigest and complex for no pertinent reason.

I'll let maintainers take the final stance, but I think this PR can be closed, as it doesn't bring value to the project and doesn't match the Fishtest Coding Style Guide.

**Comment by FishChess** [comment]
> Yes. It's a very common thing in functional languages to place chained calls like this on a separated line, as it makes it much easier to see how a variable is manipulated to go from one state to another. This is for example the standard with Rust default formatter when these constructs take too much place to fit on one line.

**first format** 
```
const getCellValue = (tr, idx) =>
  tr.children[idx].dataset.diff ||
  tr.children[idx].innerText ||
  tr.children[idx].textContent;
const padDotVersion = (dn) =>
  dn
    .split(".")
    .map((n) => +n + 1000)
    .join("");
const padDotVersionStr = (dn) => dn.replace(/\d+/g, (n) => +n + 1000);
```

**secound format** 
```
const getCellValue = (tr,idx)=>tr.children[idx].dataset.diff || tr.children[idx].innerText || tr.children[idx].textContent;
const padDotVersion = (dn)=>dn.split(".").map((n)=>+n + 1000).join("");
const padDotVersionStr = (dn)=>dn.replace(/\d+/g, (n)=>+n + 1000);
```

### **This is quite clear that second format is beauty & optimized, do you really not see?** 

> In the case of your PR, this is wrong. You didn't change anything besides code indentation and spacing, so the next PR using the formatting tool will revert all the changes.

I completely disagree because if **formating2 (formating1 code) = formating2 code** then prettier is false formatter

**Comment by mhouppin** [comment]
> **first format**
> 
> ```
> const getCellValue = (tr, idx) =>
>   tr.children[idx].dataset.diff ||
>   tr.children[idx].innerText ||
>   tr.children[idx].textContent;
> const padDotVersion = (dn) =>
>   dn
>     .split(".")
>     .map((n) => +n + 1000)
>     .join("");
> const padDotVersionStr = (dn) => dn.replace(/\d+/g, (n) => +n + 1000);
> ```
> 
> **secound format**
> 
> ```
> const getCellValue = (tr,idx)=>tr.children[idx].dataset.diff || tr.children[idx].innerText || tr.children[idx].textContent;
> const padDotVersion = (dn)=>dn.split(".").map((n)=>+n + 1000).join("");
> const padDotVersionStr = (dn)=>dn.replace(/\d+/g, (n)=>+n + 1000);
> ```
> 
> This is quite clear that second format is beauty & optimized, do you really not see?

Nope. Making convoluted code doesn't make it more "beautiful" or "optimized", it's literally the same thing, but less readable. Once again, open-source projects care about maintainability, not "beauty".

> > In the case of your PR, this is wrong. You didn't change anything besides code indentation and spacing, so the next PR using the formatting tool will revert all the changes.
> 
> I completely disagree because if **formating2 (formating1 code) = formating2 code** then prettier is false formatter

Disagreeing with what I said doesn't make my argument wrong unfortunately. Changing where whitespaces are placed in the code will mean nothing once the formatter processes the JS file again, reverting everything back to its state, so your edits are essentially a no-op.

> if you right, all 3 values must be same as separated line

Your sentence doesn't make any sense. Once again, this PR doesn't match the Fishtest Coding Style Guide, and once again, arguing about formatting is not how you should contribute to an open-source project.

**Comment by mhouppin** [comment]
> not exits a true formatting, one value separate, one value Attached, who do this formatting?!!!!!!

Literally every open-source Rust project will have this formatting, and I would expect most major JavaScript projects to have a similar (albeit maybe slightly different) code format for the sake of readability.

**Comment by FishChess** [comment]
@mhouppin there is no formatting do , 3 value are different , you can formatting this code with any tool and you can see All three should be the same

**Comment by mhouppin** [comment]
> @mhouppin there is no formatting do , 3 value are different , you can formatting this code with any tool and you can see All three should be the same

`const getCellValue = (tr, idx) =>
  tr.children[idx].dataset.diff ||
  tr.children[idx].innerText ||
  tr.children[idx].textContent;
const padDotVersion = (dn) =>
  dn
    .split(".")
    .map((n) => +n + 1000)
    .join("");
const padDotVersionStr = (dn) => dn.replace(/\d+/g, (n) => +n + 1000);`

This code block is **already** formatted, and the three variables follow the **same rules** for their formatting. You still haven't acknowledged that a tool for auto-formatting was already on the repo (which is the exact reason these three variable assignations are formatted as-is), and that Fishtest already had a Coding Style Guide. In its state, this PR will not get merged.

**Comment by FishChess** [comment]
**befor formatting** 
```js
const getCellValue = (tr, idx) =>
  tr.children[idx].dataset.diff ||
  tr.children[idx].innerText ||
  tr.children[idx].textContent;
const padDotVersion = (dn) =>
  dn
    .split(".")
    .map((n) => +n + 1000)
    .join("");
const padDotVersionStr = (dn) => dn.replace(/\d+/g, (n) => +n + 1000);
```

**after formatting** 
```js
const getCellValue = (tr,idx)=>tr.children[idx].dataset.diff || tr.children[idx].innerText || tr.children[idx].textContent;
const padDotVersion = (dn)=>dn.split(".").map((n)=>+n + 1000).join("");
const padDotVersionStr = (dn)=>dn.replace(/\d+/g, (n)=>+n + 1000);
```

**Comment by mhouppin** [comment]
This is wrong, since the auto-formatting tool matches the Fishtest Coding Style Guide, and will keep the initial code block after formatting.

**Comment by FishChess** [comment]
> This is wrong, since the auto-formatting tool matches the Fishtest Coding Style Guide, and will keep the initial code block after formatting.

Ok ,if you right,  Fishtest Coding Style has problem because 3 value formats must be as same

**Comment by MinetaS** [comment]
There are no absolute must-follow standard about coding styles and conventions.
If you want to propose a new formatting style, please open an issue and provide reasonable grounds.

**Comment by mhouppin** [comment]
> Ok ,if you right, Fishtest Coding Style has problem because 3 value formats must be as same

You might consider it as an issue, but this isn't the correct place to argue about it. I would again suggest reading [this article](https://tirania.org/blog/archive/2010/Dec-31.html) that explains well why formatting changes are very often not well received by project maintainers, before you decide to create an issue about it.

**Comment by ddobbelaere** [comment]
Don't feed the troll, see https://en.m.wiktionary.org/wiki/don%27t_feed_the_troll

He's given ample proof of himself earning the troll status, not only in this joke PR (downvoted by himself btw), but also in other numerous irrelevant "issues", PR discussions, etc. What a complete waste of time and energy. Get a life, man. Seriously.

**Comment by FishChess** [comment]
**before formatting** 
```js
  if (
    // Safari on iOS doesn't support them
    "Notification" in window &&
    // Chrome and Opera on Android don't support them
    !(
      navigator.userAgent.match(/Android/i) &&
      navigator.userAgent.match(/Chrome/i)
    )
  )
    return true;
  return false;
```

**after formatting**

```js
    if (// Safari on iOS doesn't support them
    "Notification"in window && // Chrome and Opera on Android don't support them
    !(navigator.userAgent.match(/Android/i) && navigator.userAgent.match(/Chrome/i)))
        return true;
    return false;
```

which one is better ?

**Comment by FishChess** [comment]
@mhouppin  @ddobbelaere  compare

**before formatting**
```js
  return tc_seconds !== null
    ? logistic(slope * Math.log(tc_seconds) + intercept)
    : null;
```
**after formatting**

```js 
  return tc_seconds !== null ? logistic(slope * Math.log(tc_seconds) + intercept) : null;
```

which one is better?
which one is optimize?
which one is correct?

**Comment by FishChess** [comment]
```js
  s.num_games = -1;
  for (let i = 0; i < s.num_params; i++) {
    const ng = Math.round(s.lambda_ratio * lambda[i]);
    if (ng > s.num_games) {
      s.num_games = ng;
         }
  }
```

also, for example this code is cleaned up after formatting

**Comment by peregrineshahin** [comment]
Could you stop mentioning me and other people here, please?

**Comment by FishChess** [comment]
@peregrineshahin  , I'm curious to know the technical reason of your downvotes

**Comment by peregrineshahin** [comment]
I'm not sure I should feed the troll-ness of yours after the maintainer himself told you that for JavaScript we use Prettier which did the formatting for us, the reason why I did the formatting and a cleanup PR is the maintainer himself made the decision to adapt to the W3C validator in these two commits https://github.com/glinscott/fishtest/commit/eb9de7c686aa3aa447ecb4e5b28b081a5c1479d9
https://github.com/glinscott/fishtest/commit/845fa4ca14352849a413cf1f522050ea1e56838d
and after the suggestion by vdberg here
https://github.com/glinscott/fishtest/pull/1480#issuecomment-1353725753
"The bad news is that there are quite a few HTML errors at other places. These should be fixed (preferably by the people which are responsible for the current HTML code) but this is outside the scope of this PR."

Now the exception made here to not use prettier is because prettier first can't format the mako templates that have JavaScript, CSS, and HTML, but also another exception is that Prettier formatter forces a `/` on void HTML elements because it simply does not have the implementation to check if it's a void element or not.
I pointed to that to the maintainer with
- Prettier forces the / on void elements.
in which was his response to:
- Yes, I read, but we can fix the mako templates that are not formatted with prettier

[validator/validator/wiki/Markup-%C2%BB-Void-elements#configuring-tools-to-not-output-trailing-slashes-for-void-elements](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#configuring-tools-to-not-output-trailing-slashes-for-void-elements)


moreover, doing the adaptation to that validator we indeed found some html bad practices used.
And as I replaced jQuery to JavaScript in this commit https://github.com/peregrineshahin/fishtest/commit/911213f6b09ebe332d7e48b08819842bd3a2375a
I left out some inconsistencies that are fixed now.

Now looking at your PR it has bad formatting indeed. since all it does is instead of splitting lines for readability as suggested by our tool used Prettier, with yours it all dumbing code in a one-line based on the naïve understanding that this optimizes the code for whatever reason
Example:
```
const chart_colors = ["#3366cc", "#dc3912", "#ff9900", "#109618", "#990099", "#0099c6", "#dd4477", "#66aa00", "#b82e2e", "#316395", "#994499", "#22aa99", "#aaaa11", "#6633cc", "#e67300", "#8b0707", "#651067", "#329262", "#5574a6", "#3b3eac", "#b77322", "#16d620", "#b91383", "#f4359e", "#9c5935", "#a9c413", "#2a778d", "#668d1c", "#bea413", "#0c5922", "#743411", "#3366cc", "#dc3912", "#ff9900", "#109618", "#990099", "#0099c6", "#dd4477", "#66aa00", "#b82e2e", "#316395", "#994499", "#22aa99", "#aaaa11", "#6633cc", "#e67300", "#8b0707", "#651067", "#329262", "#5574a6", "#3b3eac", "#b77322", "#16d620", "#b91383", "#f4359e", "#9c5935", "#a9c413", "#2a778d", "#668d1c", "#bea413", "#0c5922", "#743411", ];```
your code has this one goes of the screen for whatever reason, do you really want me to scroll horizontally so see the end of the line in hopes that this optimizes some magical performance, no thanks

also, I'm not sure I understand the technical reason why the formatting has a semi-colon floating alone on a new line.
`sprt.js L57`
```
    this.characteristics = function(elo) {
        const score = L(elo);
        const h = (2 * score - (this.score0 + this.score1)) / (this.score1 - this.score0);
        const PT_ = PT(this.LA, this.LB, h);
        return [PT_[0], PT_[1] / this.w2];
    }
    ;
```

Now, assuming you are not a troll but a really naïve beginner in software engineering and open-source community here is a good article on how to not contribute to the open-source community [tirania.org/blog/archive/2010/Dec-31.html](https://tirania.org/blog/archive/2010/Dec-31.html)
Now assuming you don't like prettier as a formatter here is a better place to discuss it as someone already pointed to you where you can find what we use for formatting.

Now, as I'm pretty sure you are a troll, but sorry I will not further reply to you anywhere anymore.

**Comment by FishChess** [comment]
@Peregrineshahin this code written by a human person & Prettier not effect to improvement code

```js
const padDotVersion = (dn) =>
  dn
    .split(".")
    .map((n) => +n + 1000)
    .join("");
const padDotVersionStr = (dn) => dn.replace(/\d+/g, (n) => +n + 1000);
```

also need clean up for null loop

```js
  s.num_games = -1;
  for (let i = 0; i < s.num_params; i++) {
    const ng = Math.round(s.lambda_ratio * lambda[i]);
    if (ng > s.num_games) {
      s.num_games = ng;
         }
  }
```

**Comment by FishChess** [comment]
**old formatting**

```js
 let ret = "";
  for (let i = 0; i < ss.params.length; i++) {
    const p = ss.params;
    ret +=
      p[i].name +
      "," +
      p[i].start +
      "," +
      p[i].min +
      "," +
      p[i].max +
      "," +
      p[i].c.toFixed(2) +
      "," +
      p[i].r.toFixed(5) +
      "\n";
  }
  return ret;
```
**new formatting**
```js
    let ret = "";
    for (let i = 0; i < ss.params.length; i++) {
        const p = ss.params;
        ret += p[i].name + "," + p[i].start + "," + p[i].min + "," + p[i].max + "," + p[i].c.toFixed(2) + "," + p[i].r.toFixed(5) + "\n";
    }
    return ret;
```

**Comment by FishChess** [comment]
https://github.com/glinscott/fishtest/pull/1490#issue-1501851950 _@vdbergh I have completed the supplementary description for this PR, Type A-F,  is it possible to be merged?_

**Comment by ppigazzini** [comment]
Just a note. If `prettier` had been able to format mako template, I would have definitely preferred automatic formatting to perfect W3C validation.
Before the use of autoformatters the code base was more hard to be read.

**Comment by FishChess** [comment]
> Before the use of autoformatters the code base was more hard to be read.

`prettier` is good formatter but my formatter is much better than `prettier`

You can also pass my codes through `prettier` filter, there will be no changes in the codes

You can see the huge difference in the codes (A-F types) ,  `prettier` is loser vs my formatter

**Comment by vdbergh** [comment]
Stephane always points to this https://tirania.org/blog/archive/2010/Dec-31.html .

**Comment by FishChess** [comment]
@vdbergh , Do you think this coding style is correct?

```js
  try {
    window
      .matchMedia("(prefers-color-scheme: dark)")
      .addEventListener("change", () => setTheme(getPreferredTheme()));
  } catch (e) {
    console.error(e);
  }
```

**Comment by FishChess** [comment]
If you don't like the code style to change, it's not a problem, can I open new PR just for delete this null loop?

```js
  s.num_games = -1;
  for (let i = 0; i < s.num_params; i++) {
    const ng = Math.round(s.lambda_ratio * lambda[i]);
    if (ng > s.num_games) {
      s.num_games = ng;
         }
  }
```

**Pull request closed without merging**
