### PR TITLE
Move the data from controller to the database

### PR DESCRIPTION
**Pull request by kamyarkaviani**
and provide an interface to update the data

### CODE REVIEW

**Comment by glinscott** [comment]
Oh, nice, sorry I forgot to review this!  Will take a look at it soon.

**Comment by kamyarkaviani** [comment]
That's fine. This is a busy time for the project as it is in release cycle. Take your time. We want to make sure this backend code is bullet-proof so that it doesn't introduce weird bugs or vulnerabilities.

**Comment by glinscott** [comment]
Oh, what is your username on fishtest, so I can add you to the approvers for the stats updates?

**Comment by kamyarkaviani** [comment]
My username is 'kamyar'. Please put Jens Lehmann and the project maintainers in the 'modify_stats' group, so they can go ahead and update the data as necessary. I've asked Jens to create a username.

**Comment by glinscott** [comment]
Great!  I've added you, and will add Jens once he's created his username.

**Pull request merged**
