### PR TITLE
Use different titles for finished test pages

### PR DESCRIPTION
**Pull request by linrock**
So the title of the page tells you which page you're on:

image

---
- Use a separate view for finished test pages
- Simplify tests view function for better readability
- Show Greens and LTC (Slow) titles on finished test pages
- Handle table pagination in one place

### CODE REVIEW

**Comment by vondele** [comment]
LGTM

**Comment by vondele** [comment]
BTW, a request that comes up often, and is reasonable IMO, is to have a page where the yellow tests are collected. Maybe that can be integrated here? 

If we would have a good search function (see https://github.com/glinscott/fishtest/issues/339) that might be somewhat redundant

**Comment by linrock** [comment]
yea that sounds good. we can start with a "Yellows" section in the sidebar, then build up to a multi-faceted search

**Comment by tomtor** [comment]
Nice code cleanup!

**Comment by ppigazzini** [comment]
DEV updated.
@tomtor does it work fine adding this to nginx?
```
        location /tests/finished {
            proxy_pass http://backend_all;
        }
```

**Comment by vondele** [comment]
Minor nit. The sidebar says `Slow (LTC)` while the title says `LTC (Slow)`. I wouldn't mind having just `LTC`

**Comment by vondele** [comment]
Minor nit 2. On the main page we have `Finished - 77477` consistent would be `Finished - 77477 tests`

**Comment by ppigazzini** [comment]
Minor minor nit. There is a double pages bar when selecting a (wrong counted) high page number. This shouldn't be a problem when Green and LTC pages will be counted correctly after merging #574.

**Comment by ppigazzini** [comment]
**Pro memoria**: test this also with python3 before merging and updating PROD :)

**Comment by tomtor** [comment]
> does it work fine adding this to nginx?
> 
> ```
>         location /tests/finished {
>             proxy_pass http://backend_all;
>         }
> ```

@ppigazzini Looks OK

**Comment by ppigazzini** [comment]
DEV nginx updated, after some test I will updated PROD and setup scripts.
```
        location ~ ^/tests/(finished|user/) {
            proxy_pass http://backend_all;
        }
```

**Comment by linrock** [comment]
fixed so that:
- both the sidebar and the page title say `LTC`
- homepage also says `Finished - 77477 tests` for consistency

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
PROD updated.
Thank you @linrock :)

**Pull request merged**
