### PR TITLE
More stats auditing.

### PR DESCRIPTION
**Pull request by vdbergh**
Display the batch size on the raw statistics page.
Add the LLR jumps to the raw statistics page.

This is something I wanted to do for a long time already. Sometimes a test finishes with an LLR of >3 (without it having been purged). We can now check if this is reasonable.

It was only tested locally with an SPRT test.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@vdbergh [DEV](https://dfts-0.pigazzini.it/tests) updated, I added 3 tests (SPRT, NumGames, SPSA) at 1+0.01, feel free to add other fitting tests.

**Comment by vdbergh** [comment]
There is something strange with DEV. If I go to this page

https://dfts-0.pigazzini.it/tests?page=3701

and click on `jki	neg_see_5` which should be a NumGames test then I am presented with the results of an SPRT test. https://dfts-0.pigazzini.it/tests/view/516461b48f0c3e5062d6e8f4

I haven't done any debugging.

**Comment by ppigazzini** [comment]
@vdbergh if I'm not wrong PROD and DEV have the same behavior:
https://tests.stockfishchess.org/tests/stats/516461b48f0c3e5062d6e8f4
https://dfts-0.pigazzini.it/tests/stats/516461b48f0c3e5062d6e8f4

**Comment by vdbergh** [comment]
I cannot test PROD since the access to https://tests.stockfishchess.org/tests?page=3701 times out....

**Comment by vdbergh** [comment]
Now I managed to access https://tests.stockfishchess.org/tests?page=3701 but it looks different from the corresponding page of DEV (for me). I did not find any inconsistencies.

**Comment by ppigazzini** [comment]
@vdbergh I loaded the last DB backup on DEV, that test is (now) at page 3705. If I'm not wrong PROD and DEV have the same behavior wrt that test.

https://tests.stockfishchess.org/tests?page=3705
https://tests.stockfishchess.org/tests/view/516461b48f0c3e5062d6e8f4
https://tests.stockfishchess.org/tests/stats/516461b48f0c3e5062d6e8f4

https://dfts-0.pigazzini.it/tests?page=3705
https://dfts-0.pigazzini.it/tests/view/516461b48f0c3e5062d6e8f4
https://dfts-0.pigazzini.it/tests/stats/516461b48f0c3e5062d6e8f4

**Comment by vdbergh** [comment]
It seems to be purely a wrong result widget on the main page. IIRC the result widget is cached in the database (to speed up to generation of the main page). So once an incorrect result widget finds its way in the db, it stays there.

**Comment by vondele** [comment]
It is probably unrelated, but something is still wrong currently. For example a test like 
https://tests.stockfishchess.org/tests/view/5fd8b2880c5870924361ff94
is stuck with 200 games missing. With a worker that claims to be updating, but isn't doing a think for more than a day.

**Comment by ppigazzini** [comment]
Not related to this PR, server error on PROD for "raw statistics" link in very old tests:
https://tests.stockfishchess.org/tests/view/51204fca8f0c3e2f1c770a83

```
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]: Traceback (most recent call last):
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]:   File "/home/fishtest/fishtest/server/env/lib/python3.8/site-packages/pyramid_mako/__init__.py", line 148, in __call__
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]:     result = template.render_unicode(**system)
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]:   File "/home/fishtest/fishtest/server/env/lib/python3.8/site-packages/mako/template.py", line 481, in render_unicode
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]:     return runtime._render(
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]:   File "/home/fishtest/fishtest/server/env/lib/python3.8/site-packages/mako/runtime.py", line 878, in _render
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]:     _render_context(
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]:   File "/home/fishtest/fishtest/server/env/lib/python3.8/site-packages/mako/runtime.py", line 920, in _render_context
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]:     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]:   File "/home/fishtest/fishtest/server/env/lib/python3.8/site-packages/mako/runtime.py", line 947, in _exec_template
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]:     callable_(context, *args, **kwargs)
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]:   File "/home/fishtest/fishtest/server/fishtest/templates/tests_stats.mak", line 52, in render_body
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]:     <tr><td>Book</td><td>${run['args']['book']}</td></tr>
Dec 16 21:13:29 tests.stockfishchess.org pserve[17770]: KeyError: 'book'
```

**Comment by vdbergh** [comment]
@ppigazzini Strange. Anyway this exception should be fixed with the latest push.

**Comment by ppigazzini** [comment]
@vdbergh `KeyError: 'book'` solved, but it raised another one KeyError, view below.
It seems that the problem hits only the tests dated before 01.04.2013

```
Dec 17 09:38:16 vps1572612706 pserve[16332]: Traceback (most recent call last):
Dec 17 09:38:16 vps1572612706 pserve[16332]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/pyramid_mako/__init__.py", line 148, in __call__
Dec 17 09:38:16 vps1572612706 pserve[16332]:     result = template.render_unicode(**system)
Dec 17 09:38:16 vps1572612706 pserve[16332]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/mako/template.py", line 481, in render_unicode
Dec 17 09:38:16 vps1572612706 pserve[16332]:     return runtime._render(
Dec 17 09:38:16 vps1572612706 pserve[16332]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/mako/runtime.py", line 878, in _render
Dec 17 09:38:16 vps1572612706 pserve[16332]:     _render_context(
Dec 17 09:38:16 vps1572612706 pserve[16332]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/mako/runtime.py", line 920, in _render_context
Dec 17 09:38:16 vps1572612706 pserve[16332]:     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
Dec 17 09:38:16 vps1572612706 pserve[16332]:   File "/home/usr00/fishtest/server/env/lib/python3.8/site-packages/mako/runtime.py", line 947, in _exec_template
Dec 17 09:38:16 vps1572612706 pserve[16332]:     callable_(context, *args, **kwargs)
Dec 17 09:38:16 vps1572612706 pserve[16332]:   File "/home/usr00/fishtest/server/fishtest/templates/tests_stats.mak", line 57, in render_body
Dec 17 09:38:16 vps1572612706 pserve[16332]:     <tr><td>Threads</td><td>${run['args']['threads']}</td></tr>
Dec 17 09:38:16 vps1572612706 pserve[16332]: KeyError: 'threads'
```

**Comment by vdbergh** [comment]
:frowning_face: Ok in the latest push no key is assumed to exist...

**Comment by ppigazzini** [comment]
@vdbergh DEV updated, in my fast tests the "raw statistics" link is working fine also for very old tests.
Please do a double check and let me know when the PR is ready to be merged :)

**Comment by tomtor** [comment]
@vdbergh Nice fixes, thanks.

**Comment by vdbergh** [comment]
@ppigazzini I am fine with this version... 

Incidentally I checked some recent tests. With this test 

https://dfts-0.pigazzini.it/tests/stats/5fd899350c5870924361ff6e

we see that the LLR jumps (listed per possible outcome of a game pair) can be very big (this is because of the very high draw ratio). I computed that the above test could theoretically end with a LLR of 3.26... So 3 does not seem all that unreasonable. 

Note that the stats take overshooting into account so the pass/fail probabilities always remain equal to 0.05.

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

@tomtor I haven't any idea about how to fix the test stuck reported here https://github.com/glinscott/fishtest/pull/874#issuecomment-746933489 ?

**Pull request merged**
