### PR TITLE
Made some pages responsive

### PR DESCRIPTION
**Pull request by dav1312**
Also update and use more Bootstrap classes

This should make the live elo, SPRTcalculator and raw statistics pages be responsive (look good on mobile devices)

### CODE REVIEW

**Review by ppigazzini — APPROVED** [review]
Looks good to me (pc and mobile). I will merge to get feedbacks from the users.

**Comment by ppigazzini** [comment]
PROD updated, thank you @dav1312 :)

**Comment by vdbergh** [comment]
This PR seems to break the cursor positioning in the SPRT calculator (see screenshot). Strangely this is only on PROD and not on my local fishtest. I have no time to debug it now.

Screenshot from 2022-02-13 17-07-37

**Comment by vdbergh** [comment]
This is how it should be

Screenshot from 2022-02-13 17-14-03

**Pull request merged**
