### PR TITLE
Revert "Rough fix for empty book problem"

### PR DESCRIPTION
**Pull request by ppigazzini**
Reverts glinscott/fishtest#149

View the issue https://github.com/glinscott/fishtest/issues/204
```
Downloading 2moves_v1.pgn ...
Exception running games:
Traceback (most recent call last):
  File "fishtest-master/worker/worker.py", line 91, in worker
  File "/home/fishtest/fishtest-master/worker/games.py", line 407, in run_games
    if cleanup(book, testing_dir) and os.path.exists(os.path.join(testing_dir, book)):
  File "/home/fishtest/fishtest-master/worker/games.py", line 100, in cleanup
    if not os.path.exists(os.path.join(testing_dir, book)):
NameError: global name 'book' is not defined
Task exited
```

### CODE REVIEW

**Comment by ppigazzini** [comment]
@Stefano80 mmmmm, this revert also https://github.com/glinscott/fishtest/commit/793ad5d5cfe4758fe9b6fa6b8e1045354dd30007 .
Please, suggest the actions to revert only https://github.com/glinscott/fishtest/commit/ccfae576fa0ae40e0fa3ada6510e46e817fbf15d or take in charge the process: in latter case I will follow your steps in order to learn to be prepared for the next time.

**Comment by Stefano80** [comment]
Hi Pasquale, I can look into it in one hour.

**Comment by ppigazzini** [comment]
@Stefano80 I'm start commuting to home and I will be on line after the 2200 CEST, so feel free to close this PR. I have a basic knowledge of git/github as the [chain of reverts](https://github.com/glinscott/fishtest/commit/2b73ca009cdae1fb9b0dffeb960a661892fb0f46) clearly show :(

**Comment by ppigazzini** [comment]
Closed because there is the better one https://github.com/glinscott/fishtest/pull/207

**Pull request closed without merging**
