### PR TITLE
Speedup backup using mongodump options

### PR DESCRIPTION
**Pull request by ppigazzini**
Speedup the back process using collection skipping and compression options of new mongodump.
Respect to the previous version this saves:
 - 9/10 hard disk space
 - 1/2 time
 - 1/6 size backup file

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor I tested on DEV some combinations of tar, gzip and new mongodump options ("--archive" "--gzip" "--excludeCollection")
https://docs.mongodb.com/manual/reference/program/mongodump/

* PR
  * time 4m35.101s
  * file size 959 MB (956 MB using default gzip compression level)
* master
  * time 8m26.697s
  * file size 1.2 GB
* skipping second gzip (fastest but changing the extension inserts a discontinuity for the S3 download process)
  * time 4m22.275s
  * file size 1.2 GB
* using archive file (file readable only w/ mongorestore) and skipping second gzip (a bit slow, I suppose than OpenVZ likes more to deal w/ many files than w/ a bigger one)
  * time 5m18.137s
  * file size 1.2 GB

**Comment by tomtor** [comment]
I am surprised that the second 'gzip -1' (fast minimal compression) reduces the size of the already compressed MongoDb dump (normal compression). I would expect no gain at all. 

What is the size/time when you dump without the dump `--gzip`?

**Comment by ppigazzini** [comment]
@tomtor I used `gzip -1` only to get a tar.gz and no disrupt the S3 download process, no better compression expected. I updated the info with the `dump` folder size.
```
for db_name in "fishtest_new" "admin" "fishtest" "fishtest_testing"; do
  mongodump --db=${db_name} --excludeCollection="pgns"
done
tar -cv dump | gzip -1 > dump.tar.gz
```
```
* skipping `--gzip`
  * time 6m28.927s
  * dump size 14 GB
  * file size 1.4 GB
```

**Comment by tomtor** [comment]
> I used `gzip -1` only to get a tar.gz and no disrupt the S3 download process, no better compression expected

I understand, but you state that you get `file size 959 MB` with `gzip -1` (this PR)
and `file size 1.2 GB` with skipping second gzip? So `gzip -1` DOES make the output smaller?

**Comment by ppigazzini** [comment]
@tomtor yes, it makes final file smaller.

**Comment by ppigazzini** [comment]
@tomtor second compression test with latest dump on PROD:
* dump.tar.gz 1.3 G
* dump.tar.gz1.gz  1015 M (second compression with `gzip -1`)

**Comment by tomtor** [comment]
Ok, clear. @ppigazzini Looks good to me!

**Comment by ppigazzini** [comment]
@tomtor @xoto10 PROD updated just in time for the scheduled backup :)
Only 5 minutes w/ also the s3 transfer, file size 964 M.
DB successfully restored on DEV from s3 download.

**Pull request merged**
