### PR TITLE
Do not scavenge finished runs

### LINKED ISSUE #852: Fishtest logs shows dead tasks on completion of test
Fishtest server logs show regular (every few hours) errors with dead tasks for workers which are running just fine.

### PR DESCRIPTION
**Pull request by tomtor**
Should fix #852

### CODE REVIEW

**Comment by tomtor** [comment]
@ppigazzini Applied patch to prod by hand

**Comment by vondele** [comment]
could this also fix https://github.com/glinscott/fishtest/issues/851 ?

**Comment by tomtor** [comment]
> could this also fix #851 ?

No, I do not think that is related. This patch only applies to finished tests.

**Comment by tomtor** [comment]
@ppigazzini Hmm, at 15:07 in the log the same issue, but this time not at the end of test.

**Comment by tomtor** [comment]
Test for finished run was allready in code

**Pull request closed without merging**
