### PR TITLE
Fix race condition in get_pending()

### PR DESCRIPTION
**Pull request by tomtor**
Found while stress testing with pypy

### CODE REVIEW

**Comment by Stefano80** [comment]
Hi @tomtor , thank you for this, I will merge as soon as @ppigazzini gives its ok. Could you maybe post or commit the code you used for stress testing? By the way, would it make sense to add it Travis?

**Comment by tomtor** [comment]
@Stefano80 that's really simple, utils/stress-main.sh:

    for i in 1 2 3 4 5 6 7 8 9 10; do curl http://localhost:6543/tests?[1-1000] > /dev/null & done
    wait

Not sure if that should be added to the repo.
I could perhaps add something to travis later, those travis scripts do need some love.

**Comment by Stefano80** [comment]
Ok, then let me merge, at latest tomorrow (unless @ppigazzini precedes me).

**Comment by ppigazzini** [comment]
official server updated

**Pull request merged**
