### PR TITLE
Worker update

### PR DESCRIPTION
**Pull request by Stefano80**
Combination of several worker updates which have been informally approved by @glinscott but left open for quite some time in order to combine them into a single commit.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@Stefano80 OK to me for this PR. After the commit on GitHub, we must merge the patch also on the official server https://github.com/glinscott/fishtest/pull/128/commits/b1092a0b60df3bde1c1c9ad030cadd0bedef702e#diff-b7368b46572bf04e88e8fcd94d072a1dR17
I'm expecting than after the commit to GitHub some workers will require a manual restart, so better to write a post in the forum to warn the contributors.

**Comment by ppigazzini** [comment]
@Stefano80 we could merge also this PR https://github.com/glinscott/fishtest/pull/109 before the commit

**Comment by Stefano80** [comment]
I will use the following procedure:
- I post on the forum giving a warning
- In some hours I connect to the sever
- I squash all commits on to the github repository
- I update the server
cd fishtest
git fetch origin
git diff origin/master
git merge origin/master
sudo reboot

Can't we collect these commands in a .sh script, just for sake of documentation

**Comment by ppigazzini** [comment]
OK, you find in home a `sync_repo.sh` with:
```bash
#!/bin/zsh
# sync the local repo with the remote one
cd /home/fishtest/fishtest
git fetch origin
git diff origin/master
git merge origin/master
echo "repo sync finished, reboot the server with:"
echo "sudo reboot"
```

I inserted only a remainder for the reboot in order to view the git output.

To view and to log the output you can start a command using `tee` in this way:
`~/.sync_repo.sh | tee sync.log`

**Comment by ppigazzini** [comment]
My linux & windows workers up & running w/ version 60
Great work @Stefano80

**Comment by Stefano80** [comment]
Hi @ppigazzini , I did it manually, it did not work with the .sh script (and I forgot to copy the error message).

**Comment by ppigazzini** [comment]
@Stefano80 OK, I will try on a test VM

**Comment by ppigazzini** [comment]
@Stefano80 Forgot to update the test about the .sh script. It work to me, I use it on the official server.

**Pull request merged**
