### PR TITLE
Give some information about new runs in the event log.

### PR DESCRIPTION
**Pull request by vdbergh**
Examples
```
NumGames(40000)(PT) TC:30+0.3 Book:8moves_v3.pgn Threads:8(SMP)
SPRT<0.00,2.00> TC:10+0.1 Book:UHO_XXL_+0.90_+1.19.epd Threads:1
```
The format is terse, but the idea is that it should be easily searchable.

### CODE REVIEW

**Comment by vdbergh** [comment]
BTW. I feel that "If you need, you can always contact us Discord " is not grammatically correct and also a bit heavy. To me "If needed you may contact us on Discord" sounds better. Perhaps native English speakers can comment?

**Comment by vdbergh** [comment]
Needless to say that I like the new page. It's a great improvement over the lamentations by waitress.

**Comment by ppigazzini** [comment]
What about keeping simple with "You may contact us on Discord" ?

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by vdbergh** [comment]
> What about keeping it simple with "You may contact us on Discord" ?

That's also good. But then the "otherwise" that follows is a bit strange me.  What about 

We'll be back online soon but in the meantime you may contact us on Discord ...

**Comment by ppigazzini** [comment]
> We'll be back online soon but in the meantime you may contact us on Discord ...

Approved!

We could commit the page in fishtest repo. The trick is done by the nginx maintenance config (btw I never searched for a better solution).

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2 ipv6only=on;
    ssl_certificate /etc/letsencrypt/live/dfts-0.pigazzini.it/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dfts-0.pigazzini.it/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    server_name dfts-0.pigazzini.it;

    location ~ ^/(img|favicon.ico|robots.txt) {
        root /home/usr00/fishtest/server/fishtest/static;
        expires     1y;
        add_header  Cache-Control public;
        access_log  off;
    }

    location / {
        root /var/www/dfts-0.pigazzini.it/public_html;
        add_header  Cache-Control public;
        access_log  off;
        try_files /maintenance.html =404;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name dfts-0.pigazzini.it;

    location / {
        return 301 https://$host$request_uri;
    }
}
```

**Comment by vdbergh** [comment]
> 
> We could commit the page in fishtest repo. The trick is done by the nginx maintenance config (btw I never searched for a better solution).
>

Yes why not. I guess that page is served by nginx itself. I would expect a webserver to have custom error pages. But perhaps not...

**Comment by vdbergh** [comment]
Here is something about custom error pages in nginx:

https://www.tecmint.com/create-custom-nginx-error-page/

**Comment by vdbergh** [comment]
I think the count down is visually nice but a bit misleading. IMHO it should start counting from a realistic ETA value, and if there isn't any then the count should go up. I do not know if there is a way to template or otherwise parametrize the page.

**Comment by vdbergh** [comment]
BTW I tested the current PR, so if you want to experiment again with the error page, then please go ahead!

**Comment by ppigazzini** [comment]
I added too early the confetti but people thought that they were for the passed new net, so now they expect fireworks for tomorrow...

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
> `nginx` would have to react to `502 Bad Gateway` I would think.

IMO the maintenance page shouldn't be displayed for every `502 Bad Gateway`, otherwise if fishtest should die for whatever reason, people will not report the problem on Discord.

**Comment by dav1312** [comment]
Here are some custom error pages for nginx https://github.com/alexphelps/server-error-pages/tree/gh-pages/_site
* [403](https://alexphelps.github.io/server-error-pages/403.html)
* [404](https://alexphelps.github.io/server-error-pages/404.html)
* [500](https://alexphelps.github.io/server-error-pages/500.html)
* [502](https://alexphelps.github.io/server-error-pages/502.html)
* [504](https://alexphelps.github.io/server-error-pages/504.html)
* [Maintenance](https://alexphelps.github.io/server-error-pages/maintenance.html)

**Comment by ppigazzini** [comment]
https://serverfault.com/questions/310819/maintenance-page-on-nginx-best-practices

In effect the best practices for the maintenance require always an action (eg create a file/link for the maintenance page, reload a nginx config, etc).

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by vdbergh** [comment]
I am happy with the latest push https://dfts-0.pigazzini.it/actions?max_actions=4&action=&user=&text=&before=1672424226.7763801857 .

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
