### PR TITLE
Script to create indexes.

### PR DESCRIPTION
**Pull request by xoto10**
First go at a script to recreate the indexes in the fishtest db.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@xoto10 I'll test it on DEV when at home.

ps: python3 compatibility :)

**Comment by xoto10** [comment]
Should there be any indexes on actions / users / old_runs ?

**Comment by tomtor** [comment]
`users` has currently one:

    {u'_id_': {u'key': [(u'_id', 1)], u'ns': u'fishtest_new.users', u'v': 2},                                                                            
    u'username_1': {u'key': [(u'username', 1)],                                                                                                                         
    u'ns': u'fishtest_new.users',                                                                                                                       
    u'unique': True,                                                                                                                                    
    u'v': 2}}

**Comment by ppigazzini** [comment]
@xoto10 @tomtor tested on DEV w/ a db w/o indexes (mongorestore w/o *.json).

* runs:
```
> db.runs.stats()
...
        },
        "nindexes" : 5,
        "indexBuilds" : [ ],
        "totalIndexSize" : 544768,
        "indexSizes" : {
                "_id_" : 167936,
                "args.username_1" : 53248,
                "deleted_1" : 53248,
                "finished_1_last_updated_-1" : 98304,
                "finished_1_last_updated_-1_start_time_-1" : 172032
        },
        "scaleFactor" : 1,
        "ok" : 1
}
``` 
* pgns:
```
> db.pgns.stats()
...
        },
        "nindexes" : 2,
        "indexBuilds" : [ ],
        "totalIndexSize" : 552960,
        "indexSizes" : {
                "_id_" : 360448,
                "run_id_1" : 192512
        },
        "scaleFactor" : 1,
        "ok" : 1
}
```
* users:
```
> db.users.stats()
...
        },
        "nindexes" : 2,
        "indexBuilds" : [ ],
        "totalIndexSize" : 86016,
        "indexSizes" : {
                "_id_" : 45056,
                "username_1" : 40960
        },
        "scaleFactor" : 1,
        "ok" : 1
}
```

**Comment by tomtor** [comment]
On dev https://dfts-2.pigazzini.it/tests retrieving tests from `old_runs` takes a long time (timeout).

I had the impression ALL collections received an index on `_id` by default, but it seems that this is not so and `old_runs` should receive an index on `_id`...

**Comment by tomtor** [comment]
@ppigazzini I am pretty sure `regression_data` is no longer used and can be dropped?

**Comment by tomtor** [comment]
According to https://docs.mongodb.com/manual/indexes/#default-id-index ALL collections have an index on `_id`, so perhaps reading `old_runs` is just slow on dev?

**Comment by tomtor** [comment]
`old_user_cache`? It is created line 14 of userdb.py but never used...

**Comment by ppigazzini** [comment]
PROD updated, thank you @xoto10 !

**Comment by ppigazzini** [comment]
@tomtor we have to choices:
* to keep all data for historic value, dropping only empty databases/collections
* to drop all not useful databases/collections (e.g. clops and perhaps fishtest and fishtest_testing)

I would like to have the @glinscott opinion on this choice.

**Pull request merged**
