### PR TITLE
Add more API tests and simplify API code

### PR DESCRIPTION
**Pull request by linrock**
Added more comprehensive test coverage for API endpoints and actual use cases from workers. Simplified the API code a bit. Should be no functional change.

Add more API tests
- Use helper methods for more succinct tests
  - for building requests with invalid passwords
  - for building requests with correct passwords
- Add test cases for all API endpoints used by workers

Simplify API code
- Use a view class for API views
  - Set renderer type json for all views by default
  - Don't need manual json encoding with json renderer
- Use a separate method for authentication check
  - Use exception view for handling failed auth

### CODE REVIEW

**Comment by ppigazzini** [comment]
Travis log reports this, it's correct?
```
======================================================================
FAIL: test_login (test_users.Create50LoginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/glinscott/fishtest/fishtest/tests/test_users.py", line 64, in test_login
    self.assertTrue('Invalid password' in request.session.pop_flash())
AssertionError: False is not true
======================================================================
FAIL: test_stop_run (test_users.Create90APITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/glinscott/fishtest/fishtest/tests/test_users.py", line 114, in test_stop_run
    self.assertEqual(response, '{}')
AssertionError: '{"error": "Blocked"}' != '{}'
- {"error": "Blocked"}
+ {}
```

**Comment by vondele** [comment]
@ppigazzini how can one restart a travis check by hand? I can see some use for that as well :-)

**Comment by vondele** [comment]
Aha ... that button is missing for me on the official-stockfish repo,while I have it on my clone. @snicolet might have the right for this on official stockfish..

image

**Comment by ppigazzini** [comment]
@vondele I think that @snicolet should be able to setup that right for you. I and @tomtor are simple "Collaborator" for fishtest repo.

**Comment by snicolet** [comment]
Nope, I have "Owner" status for the official-stockfish repo, but simply "Collaborator" for fishtest.

**Comment by snicolet** [comment]
Oops, sorry, misread the thread... what do you want me to do on official-stockfish?

**Comment by ppigazzini** [comment]
> Oops, sorry, misread the thread... what do you want me to do on official-stockfish?

@snicolet you should enable on official-stockfish the right for you and @vondele to restart a Travis check (view my images above).

**Comment by ppigazzini** [comment]
@vondele perhaps we should have a look to Github "Actions"

**Comment by ppigazzini** [comment]
@linrock please rebase :)

**Comment by linrock** [comment]
@ppigazzini merge conflict fixed + rebased

regarding those two test cases you posted: i fixed them in this PR. they were broken in https://github.com/glinscott/fishtest/pull/608

i think github actions is certainly worth trying out

**Comment by ppigazzini** [comment]
PROD updated, thank you @linrock :)

**Pull request merged**
