### PR TITLE
Some code cleanup in the worker

### PR DESCRIPTION
**Pull request by vdbergh**
The worker code is serial and hence in principle
quite simple. Unfortunately it has grown organically
and currently it is not so easy too follow anymore.
This makes the idea of adding new types of tests
rather unattractive.

This is PR is the first timid attempt at cleaning
up some of the worker code.

This version of the worker should be functionally
equivalent to version 75. 

The most notable changes are

- The global variable old_stats is eliminated. The fact
that such a global variable exists needlessly complicates the
logic of the worker code.

- Trinomial and pentanomial frequencies are
now kept in sync for all types of tests. This simplifies
the code a lot.

- More asserts have been added.

### CODE REVIEW

**Comment by ppigazzini** [comment]
Workers updated on DEV.

**Comment by vondele** [comment]
This will fix https://github.com/glinscott/fishtest/issues/552

**Comment by ppigazzini** [comment]
@vdbergh workers have bee fine all day long.

**Comment by ppigazzini** [comment]
@noobpwnftw code clean up. Please update your fleet at your convenience.

**Comment by noobpwnftw** [comment]
@ppigazzini All workers updated to 76.

**Comment by ppigazzini** [comment]
@noobpwnftw thank you, I'm starting the auto update for all workers.

**Pull request merged**
