### PR TITLE
Switch to new books and binaries repo

### PR DESCRIPTION
**Pull request by ppigazzini**
Switch to new repo and download zipped books.

To be tested after the merging of these PRs https://github.com/official-stockfish/books/pull/1 https://github.com/official-stockfish/books/pull/2.

Anyway it's working fine with my up to date books repo.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor this works fine on DEV, tested with workers Windows, WSL, Linux.
If you agree I will proceed asap with:
1. merge this PR and the pentanomial PRs asking to @noobpwnftw @d3vv to update asap their workers fleets
2. write a post on the forum for the worker version raise (new repo for books&binaries, new default book, new cutechess-cli binaries, switch to pentanomial distribution)
3. after the @noobpwnftw @d3vv fleets update, enforcing the automatic update for all the workers: after this the pentanomial will start working
4. merge this PR to switch the default book

**Comment by tomtor** [comment]
@ppigazzini ok to merge!

**Comment by ppigazzini** [comment]
@noobpwnftw @d3vv worker version raised to 71 (only worker side, not automatic update enforced).
Update changelog:
* switch to the new books&binaries repo https://github.com/official-stockfish/books
* the new repo has Qt5 static build of `cutechess-cli`. To use the new version or delete/move the `worker/testing` folder (lazy solution) or delete/move these files in the `worker/testing` folder:
   * linux 64 bit : `cutechess-cli` `libcutechess.so.1`
   * linux 32 bit : `cutechess-cli` `libQtCore.so`
   * windows: `COPYING` `cutechess-cli.exe` `ENGINES` `msvcp100.dll` `msvcr100.dll` `QtCore4.dll` `README`
* support for pentanomial statistic. This will start working after the update of all workers in fishtest
* after the update of all workers we will switch to the new book `2moves_v2.pgn`
  
Please update your worker fleet asap and report here any problem.

**Comment by d3vv** [comment]
As I see, some of workers has no new versa yet
Do I need update by hand?
If answer is "yes" - I can do it  on the weekend

**Comment by tomtor** [comment]
@d3vv They should update after finishing the 250 game batch of VLTC games which can take a while...

**Comment by ppigazzini** [comment]
@d3vv be sure to upgrade to latest cutechess-cli binaries, the old one hang with the *.epd books.
The fast and dirty solution is to delete the "testing" folder.

**Comment by d3vv** [comment]
@ppigazzini I compiled cutechess-cli myself for most workers
due to I have no qt4-core into gentoo long time
Could you suggest from logs about any problems for dew-workers?

**Comment by ppigazzini** [comment]
@d3vv of course, we routinely check the server logs, however if a worker hang I fear that no info is available server side.

**Pull request merged**
