### PR TITLE
Live elo changes

### PR DESCRIPTION
**Pull request by dav1312**
Sorry for the inconvenience
If you want, test it on dev first to make sure it works as expected now

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated. I thought that the previous PR was a simple code refactor.

**Comment by dav1312** [comment]
Okay it should be fixed now \:)

**Comment by ppigazzini** [comment]
The striped table lgtm :)

**Comment by vdbergh** [comment]
I am the original author of this page. But feel free to delete `live_elo.css` if it gets in the way! I have no idea if it still relevant.

**Comment by ppigazzini** [comment]
DEV updated, lgtm, let me know if I can merge it :)

**Comment by vondele** [comment]
looks good to me. Eventually, would be nice to have also the pentanomial stats on that page, but that's independent from this PR.

**Comment by ppigazzini** [comment]
> looks good to me. Eventually, would be nice to have also the pentanomial stats on that page, but that's independent from this PR.

IMO in the new PR we should move in this page the info of the advanced statistic page (and drop that page). Normal user only want to copy the gauges on Discord :)

**Comment by vondele** [comment]
yes, I agree that would be a good to put the advanced stats. However, I think advanced stats are available for tests for which there is no SPRT gauges (like fixed number of games).

**Comment by ppigazzini** [comment]
Good point. We should add a ref also to the NumGames widget to land to the advanced statistics page. The SPRT advanced statistic page will have also the gauges at the top. SPSA hasn't advanced stats.

**Comment by ppigazzini** [comment]
DEV updated, I will be away from the keyboard for a couple of hours.

**Comment by dav1312** [comment]
> DEV updated, I will be away from the keyboard for a couple of hours.

It's fine, I just rebased onto master

**Comment by ppigazzini** [comment]
Ok, let me know when it's ready to be merged :)

**Comment by dav1312** [comment]
Lgtm!

**Comment by ppigazzini** [comment]
PROD updated, thank you @dav1312 :)

**Pull request merged**
