### PR TITLE
Break long words in table info

### PR DESCRIPTION
**Pull request by tomtor**
Fix layout on narrow devices

### CODE REVIEW

**Comment by ppigazzini** [comment]
dev-server updated.

**Comment by tomtor** [comment]
@ppigazzini Ok to merge. You should look in pending tests to the right most info column.  When there is a long link in the text (a reference to a commit) then not all text is shown (and no scrollbar is added) on a narrow display without this patch...

**Comment by tomtor** [comment]
@ppigazzini See fixStatsOverflow in production.

**Comment by ppigazzini** [comment]
Production server updated.
Thank you @tomtor

**Pull request merged**
