### PR TITLE
Send ARCH to server

### PR DESCRIPTION
**Pull request by tomtor**
Should implement #743

### CODE REVIEW

**Comment by tomtor** [comment]
@vondele @ppigazzini Not sure how to get the ARCH from a stockfish which has already been compiled...

**Comment by tomtor** [comment]
> Not sure how to get the ARCH from a stockfish which has already been compiled...

Never mind, I figured it out....

**Comment by tomtor** [comment]
@ppigazzini @vondele I have a problem.

The compile settings are written on 'stdout', the signature message on 'stderr'.

Reading both FDs does not work in the current PR, at least not on Linux, not sure why.

I expect merging both FDs might (also) give trouble on Windows systems.

**Comment by vondele** [comment]
@tomtor somewhat surprising, and maybe ppigazzini has another solution. However, you could write a small function like `required_net` but sending `compiler` instead of `uci` that does it independently from verify bench. It is maybe anyway a good idea to separate things.

**Comment by tomtor** [comment]
> somewhat surprising, and maybe ppigazzini has another solution. However, you could write a small function like `required_net(engine)` but sending `compiler` instead of `uci` that does it independently from verify bench. It is maybe anyway a good idea to separate things.

My code was broken in other ways, I am rewriting with separate processes now.

**Comment by vondele** [comment]
quick question, will the code work with older version that reply:
```
Stockfish 7 64 POPCNT by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
Unknown command: compiler 
``` 
Just returning `unknown` is fine.

**Comment by tomtor** [comment]
It works:

```
Linux 4.15.0-112-generic ARCH=64bit AVX2 SSE42 SSE41 SSSE3 SSE3 POPCNT
```

is shown as info in the test view for my 14 thread Ryzen 1700x

**Comment by vondele** [comment]
OK, nice!

**Comment by tomtor** [comment]
> quick question, will the code work with older version that reply:

That should return `None` now. I can replace it with `?`  (server default) or `Unknown`

**Comment by vondele** [comment]
`ARCH=?` would be nice

**Comment by ppigazzini** [comment]
@tomtor DEV and workers updated.

**Comment by vondele** [comment]
OK, my worker displays properly: `vdv-12cores-1 | Linux 5.4.0-42-generic      ARCH=64bit AVX2 SSE42 SSE41 SSSE3 SSE3 POPCNT`

**Comment by ppigazzini** [comment]
All my workers (installed from zero) are stuck with this message, no time now to debug on the fly:
```
Obtaining EvalFile of stockfish_857e045ced9e20f202e15d825e47b3ab8241dcef ...
Obtaining EvalFile of stockfish_857e045ced9e20f202e15d825e47b3ab8241dcef ...

Exception running games:
Traceback (most recent call last):
  File "worker.py", line 154, in worker
    pgn_file = run_games(worker_info, password, remote, run, task_id)
  File "/home/usr00/_git/__test_folder00/fishtest/worker/games.py", line 681, in run_games
    raise Exception('Failed to validate the network: %s ' % (net))
Exception: Failed to validate the network: nn-9931db908a9b.nnue
Task exited
```

**Comment by vondele** [comment]
I copied it over, because the network doesn't exist on the dev server (was my guess?)

**Comment by ppigazzini** [comment]
@vondele but I started also a `Use NNUE=false` test
https://dfts-0.pigazzini.it/tests/view/5f2d78a59ff42b2cd04b75fd

**Comment by vondele** [comment]
The network is downloaded irrespective of the options, if the binary has an EvalFile option. This will be needed in the future anyway to bench / PGO (even if the code for it has to change).

**Comment by ppigazzini** [comment]
@vondele ok, thanks. In the week end I will investigate how to keep DEV up to date.

**Comment by ppigazzini** [comment]
@vondele my workers are running fine after a sync with the PROD db.

**Comment by tomtor** [comment]
@vondele Not related to this PR but I get on aarch64:

```
tom@pine64:~/src/fishtest/worker$ uname -a
Linux pine64 4.19.63-sunxi64 #5.92 SMP Fri Aug 2 00:18:27 CEST 2019 aarch64 aarch64 aarch64 GNU/Linux
```

```
Exception running games:
Traceback (most recent call last):
  File "/tom/src/fishtest/worker/games.py", line 239, in setup_engine
    subprocess.check_call(MAKE_CMD + ARCH + ' -j %s' % (concurrency) + ' profile-build', shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'make COMP=gcc ARCH=x86-64 -j 3 profile-build' returned non-zero exit status 2.
```

Should I create a fishtest or stockfish issue? I thought aarch64 was supported?

**Comment by vondele** [comment]
it is supported for stockfish but not for fishtest, we don't have cutechess available (AFAIK), so the fishtest worker only needs to care about x86. I might be wrong however...

**Comment by ppigazzini** [comment]
PROD updated, thank you @tomtor :)

**Pull request merged**
