### PR TITLE
First go at CI

### PR DESCRIPTION
**Pull request by Stefano80**
Let me open this to check whether I understood how to set up travis.

### CODE REVIEW

**Comment by Stefano80** [comment]
For this @glinscott should activate this repo on travis CI. Would that be possible?

**Comment by Stefano80** [comment]
I think I have to close this and reopen in order for travis to notice.

**Comment by ppigazzini** [comment]
@Stefano80 I think that you are already read the [python guide from Travis](https://docs.travis-ci.com/user/languages/python/).
The last section links to some python projects as example of configurations.

**Comment by Stefano80** [comment]
So @ppigazzini , this is ready from my side.

The productive code is not changed. I just added the bare minimum to make travis CI functional, plus a small example test.

If you agree, and @tomtor , @xoto10 , @noobpwnftw , @glinscott and whoever is interested gives some feedback, I will merge.

**Comment by ppigazzini** [comment]
@Stefano80 OK

**Pull request merged**
