### PR TITLE
Dbconversion to remove the opaque date and run_id types in actiondb.

### PR DESCRIPTION
**Pull request by vdbergh**
The opaque types are a nuissance since they cannot be encoded as json. So it becomes difficult to do remote queries.

As usual the conversion program is

utils/convert_actions.py

### CODE REVIEW

**Comment by ppigazzini** [comment]
Converting "actions" on DEV...

**Comment by ppigazzini** [comment]
```
Jan 02 16:15:31 dfts-0 pserve[10927]: pyramid_mako.MakoRenderingException:
Jan 02 16:15:31 dfts-0 pserve[10927]: Traceback (most recent call last):
Jan 02 16:15:31 dfts-0 pserve[10927]:   File "/home/usr00/fishtest/server/env/lib/python3.10/site-packages/pyramid_mako/__init__.py", line 148, in __call__
Jan 02 16:15:31 dfts-0 pserve[10927]:     result = template.render_unicode(**system)
Jan 02 16:15:31 dfts-0 pserve[10927]:   File "/home/usr00/fishtest/server/env/lib/python3.10/site-packages/mako/template.py", line 444, in render_unicode
Jan 02 16:15:31 dfts-0 pserve[10927]:     return runtime._render(
Jan 02 16:15:31 dfts-0 pserve[10927]:   File "/home/usr00/fishtest/server/env/lib/python3.10/site-packages/mako/runtime.py", line 874, in _render
Jan 02 16:15:31 dfts-0 pserve[10927]:     _render_context(
Jan 02 16:15:31 dfts-0 pserve[10927]:   File "/home/usr00/fishtest/server/env/lib/python3.10/site-packages/mako/runtime.py", line 916, in _render_context
Jan 02 16:15:31 dfts-0 pserve[10927]:     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
Jan 02 16:15:31 dfts-0 pserve[10927]:   File "/home/usr00/fishtest/server/env/lib/python3.10/site-packages/mako/runtime.py", line 943, in _exec_template
Jan 02 16:15:31 dfts-0 pserve[10927]:     callable_(context, *args, **kwargs)
Jan 02 16:15:31 dfts-0 pserve[10927]:   File "/home/usr00/fishtest/server/fishtest/templates/base.mak", line 244, in render_body
Jan 02 16:15:31 dfts-0 pserve[10927]:     <div>${self.body()}</div>
Jan 02 16:15:31 dfts-0 pserve[10927]:   File "/home/usr00/fishtest/server/fishtest/templates/actions.mak", line 114, in render_body
Jan 02 16:15:31 dfts-0 pserve[10927]:     ${datetime.datetime.utcfromtimestamp(action['time']).strftime(r"%y&#8209;%m&#8209;%d %H:%M:%S")|n}</a></td>
Jan 02 16:15:31 dfts-0 pserve[10927]: TypeError: 'datetime.datetime' object cannot be interpreted as an integer
```

Reloading the db...

**Comment by vdbergh** [comment]
Yes the PR only works with the converted db.

**Comment by ppigazzini** [comment]
> Yes the PR only works with the converted db.

I started the script, but it did nothing from the console output. Reloading and retrying.

**Comment by vdbergh** [comment]
Hmm. I have
```sh
python convert_actions.py 
Starting conversion...
Actions converted: 961.
Conversion finished in 0.61 seconds. Time per run: 0.64ms.
```

**Comment by ppigazzini** [comment]
Well, I forgot to have commented out the conversion script to test the maintenance page...

**Comment by ppigazzini** [comment]
Done!
```
Starting conversion...
Actions converted: 712036.
Conversion finished in 1556.22 seconds. Time per run: 2.19ms.

real    26m40.227s
user    11m2.862s
sys     5m10.858s

```

**Comment by vdbergh** [comment]
I now created a javascript api to monitor events. It is illustrated in /html/events.html.

Unfortunately I had to copy most of the relevant api code in application.js to the header of the example script since it seems that application.js is not independent of fishtest anymore.

**Comment by vdbergh** [comment]
I decided that it is better in this PR not to modify application.js so that the PRs can remain independent.

**Comment by ppigazzini** [comment]
DEV updated.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, "actions" collection converted. Thank you @vdbergh :)

**Pull request merged**
