### PR TITLE
Move the diff above details.

### PR DESCRIPTION
**Pull request by peregrineshahin**

### CODE REVIEW

**Comment by ppigazzini** [comment]
@vondele DEV updated

**Comment by ppigazzini** [comment]
DEV updated

**Comment by ppigazzini** [comment]
DEV updated

**Comment by vondele** [comment]
I like it.

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by peregrineshahin** [comment]
right, now I think we should make hiding it with cookies possible (like other places) for users who keep refreshing to see LLR.

**Comment by vondele** [comment]
It already has some logic to hide it when the diff is large, so it would be kind of a 3 state thing?

**Comment by peregrineshahin** [comment]
> 

No, I will remove the large diff hide by default.

**Comment by ppigazzini** [comment]
> No, I will remove the large diff hide by default.

IMO the auto hide for large diff is a good solution.

**Comment by vondele** [comment]
Auto hide for large diffs is a good thing, I agree.

**Comment by peregrineshahin** [comment]
> > No, I will remove the large diff hide by default.
> 
> IMO the auto hide for large diff is a good solution.

it's a good solution but you can see in current DEV if the large diff is hidden we cannot predict the first text inside the button resulting in kind of flash if you refresh, try https://dfts-0.pigazzini.it/tests/view/6471a2ade549d9cf2fb213cd

**Comment by ppigazzini** [comment]
@peregrineshahin I view the change from " comments" to "0 comments".

**Comment by peregrineshahin** [comment]
> I view

Yeah just pushed that before you comment in 0s

so what do you think about being able to predict the first text?

**Comment by ppigazzini** [comment]
I think that we should collect the comments by the approvers using the diff feature.

**Comment by peregrineshahin** [comment]
We can of course transition the text change (make a delay) so that it has less flashing.

**Comment by peregrineshahin** [comment]
Okay the way people hack this in general is by having an icon instead of text, imagine an eye icon when show that gets crossed out when it's hidden.
I will claim this as LGTM maybe we can change the texts for Hide/Show to the whole website if some icon looks good.

**Comment by peregrineshahin** [comment]
Drafted I have an idea.

**Comment by ppigazzini** [comment]
A ghostly effect on auto hide :)

**Comment by peregrineshahin** [comment]
> A ghostly effect on auto hide :)

Yeah, it's just we can't predict the future due to the time nature of flowing linearly. I will revert the ghost until we invent a time-machine or we stop relying on the client to fetch stuff for us.

**Comment by ppigazzini** [comment]
Could auto-show behave better than auto-hide?

**Comment by peregrineshahin** [comment]
> Could auto-show behave better than auto-hide?

Great idea, let's see.

**Comment by ppigazzini** [comment]
LGTM :)

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by peregrineshahin** [comment]
Ready for shipping.

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
> Ready for shipping.

I must wait to have back some GitHub API rate to made the last tests, I'm getting 503 right now.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin :)

**Pull request merged**
