### PR TITLE
Add timeouts

### PR DESCRIPTION
**Pull request by vondele**
might be needed if there is a problem uploading to the server.

### CODE REVIEW

**Review by ppigazzini — APPROVED** [review]
DEV updated, lgtm:
- stopped `post-server` : "Network upload failed: 502"
- misconfigured port in `nginx` : "Network upload failed: 502"
- wrong URI : "Network upload failed: 404"

**Comment by ppigazzini** [comment]
PROD updated, thank you @vondele :)

BTW on DEV I got (faster) the same answers with master, hoping this will solve the issue.

**Comment by vondele** [comment]
I'm getting this on upload of a network: 
image

**Comment by vondele** [comment]
the upload worked after the 3rd time.

**Comment by vondele** [comment]
this is actually an exception that is thrown in that block. The exception should be printed in the server log?

**Comment by ppigazzini** [comment]
This is the `post-server` log on the nn server, now I will check PROD:
```
Nov 22 07:03:21 156-248-75-97 python3[931]: 127.0.0.1 - - [22/Nov/2021 06:32:58] "POST /0123456789/nn-7fb14027df19.nnue HTTP/1.0" 200 -
Nov 22 07:03:21 156-248-75-97 python3[931]: INFO:root:POST request,
Nov 22 07:03:21 156-248-75-97 python3[931]: Path: /0123456789/nn-fa2ce2d6da96.nnue
Nov 22 07:03:21 156-248-75-97 python3[931]: Headers:
Nov 22 07:03:21 156-248-75-97 python3[931]: X-Forwarded-Proto: \https
Nov 22 07:03:21 156-248-75-97 python3[931]: X-Forwarded-For: \185.83.217.134
Nov 22 07:03:21 156-248-75-97 python3[931]: X-Forwarded-Host: \fishnet-new.v7f.eu:\443
Nov 22 07:03:21 156-248-75-97 python3[931]: X-Forwarded-Port: \443
Nov 22 07:03:21 156-248-75-97 python3[931]: Host: upload_server
Nov 22 07:03:21 156-248-75-97 python3[931]: Connection: close
Nov 22 07:03:21 156-248-75-97 python3[931]: Content-Length: 47001243
Nov 22 07:03:21 156-248-75-97 python3[931]: User-Agent: python-requests/2.26.0
Nov 22 07:03:21 156-248-75-97 python3[931]: Accept-Encoding: gzip, deflate
Nov 22 07:03:21 156-248-75-97 python3[931]: Accept: */*
Nov 22 07:03:21 156-248-75-97 python3[931]: Body length:
Nov 22 07:03:21 156-248-75-97 python3[931]: 47001243
Nov 22 15:39:51 156-248-75-97 python3[931]: 127.0.0.1 - - [22/Nov/2021 07:03:21] "POST /0123456789/nn-fa2ce2d6da96.nnue HTTP/1.0" 200 -
Nov 22 15:39:51 156-248-75-97 python3[931]: INFO:root:POST request,
Nov 22 15:39:51 156-248-75-97 python3[931]: Path: /0123456789/nn-d4906134c39f.nnue
Nov 22 15:39:51 156-248-75-97 python3[931]: Headers:
Nov 22 15:39:51 156-248-75-97 python3[931]: X-Forwarded-Proto: \https
Nov 22 15:39:51 156-248-75-97 python3[931]: X-Forwarded-For: \185.83.217.134
Nov 22 15:39:51 156-248-75-97 python3[931]: X-Forwarded-Host: \fishnet-new.v7f.eu:\443
Nov 22 15:39:51 156-248-75-97 python3[931]: X-Forwarded-Port: \443
Nov 22 15:39:51 156-248-75-97 python3[931]: Host: upload_server
Nov 22 15:39:51 156-248-75-97 python3[931]: Connection: close
Nov 22 15:39:51 156-248-75-97 python3[931]: Content-Length: 47001243
Nov 22 15:39:51 156-248-75-97 python3[931]: User-Agent: python-requests/2.26.0
Nov 22 15:39:51 156-248-75-97 python3[931]: Accept-Encoding: gzip, deflate
Nov 22 15:39:51 156-248-75-97 python3[931]: Accept: */*
Nov 22 15:39:51 156-248-75-97 python3[931]: Body length:
Nov 22 15:39:51 156-248-75-97 python3[931]: 47001243
Nov 22 19:48:43 156-248-75-97 python3[931]: 127.0.0.1 - - [22/Nov/2021 15:39:51] "POST /0123456789/nn-d4906134c39f.nnue HTTP/1.0" 200 -
Nov 22 19:48:43 156-248-75-97 python3[931]: INFO:root:POST request,
Nov 22 19:48:43 156-248-75-97 python3[931]: Path: /0123456789/nn-4d9083486963.nnue
Nov 22 19:48:43 156-248-75-97 python3[931]: Headers:
Nov 22 19:48:43 156-248-75-97 python3[931]: X-Forwarded-Proto: \https
Nov 22 19:48:43 156-248-75-97 python3[931]: X-Forwarded-For: \185.83.217.134
Nov 22 19:48:43 156-248-75-97 python3[931]: X-Forwarded-Host: \fishnet-new.v7f.eu:\443
Nov 22 19:48:43 156-248-75-97 python3[931]: X-Forwarded-Port: \443
Nov 22 19:48:43 156-248-75-97 python3[931]: Host: upload_server
Nov 22 19:48:43 156-248-75-97 python3[931]: Connection: close
Nov 22 19:48:43 156-248-75-97 python3[931]: Content-Length: 47001243
Nov 22 19:48:43 156-248-75-97 python3[931]: User-Agent: python-requests/2.26.0
Nov 22 19:48:43 156-248-75-97 python3[931]: Accept-Encoding: gzip, deflate
Nov 22 19:48:43 156-248-75-97 python3[931]: Accept: */*
Nov 22 19:48:43 156-248-75-97 python3[931]: Body length:
Nov 22 19:48:43 156-248-75-97 python3[931]: 47001243
```

**Comment by ppigazzini** [comment]
PROD log of the last 2 days has only these 2 exception:
```
$ sudo journalctl -u fishtest@6543 --since "yesterday"
...
Nov 21 01:04:01 tests.stockfishchess.org pserve[25504]:   File "/home/fishtest/fishtest/server/fishtest/views.py", line 1264, in tests
Nov 21 01:04:01 tests.stockfishchess.org pserve[25504]:     if int(request.params.get("page", 1)) > 1:
Nov 21 01:04:01 tests.stockfishchess.org pserve[25504]: ValueError: invalid literal for int() with base 10: "5'A=0"
...
Nov 22 04:06:59 tests.stockfishchess.org pserve[9906]:   File "/home/fishtest/fishtest/server/fishtest/views.py", line 1264, in tests
Nov 22 04:06:59 tests.stockfishchess.org pserve[9906]:     if int(request.params.get("page", 1)) > 1:
Nov 22 04:06:59 tests.stockfishchess.org pserve[9906]: ValueError: invalid literal for int() with base 10: "5'A=0"
```

**Comment by vondele** [comment]
the server code that is executed on failure has this:
```python
   except Exception as e:
        print("Network upload fails or not configured: " + str(e))
        request.session.flash("Network upload fails or not configured", "error")
        return {}
```
where is this print statement going?

**Comment by ppigazzini** [comment]
The prints go in the journal, It seems that was needed a fishtest systemd unit restart to flush the log:
```
$ sudo journalctl -u fishtest@6544 --since "yesterday"
...
Nov 22 12:46:52 tests.stockfishchess.org pserve[10166]: Network upload fails or not configured: ('Connection aborted.', timeout('The write operation timed out'))
```

**Comment by ppigazzini** [comment]
I'm started a server code refactoring about `requests` usage, like this (the server setup script now configures also the post-server):
```python
    try:
        response = requests.post(upload_server, data=network, timeout=HTTP_TIMEOUT)
        response.raise_for_status()  # also catch return codes >= 400
    except Exception as e:
        print("Network upload failed: " + str(response.status_code))
        request.session.flash(
            "Network upload failed: " + str(response.status_code), "error"
        )
        return {}```

**Comment by vondele** [comment]
> The prints go in the journal, It seems that was needed a fishtest systemd unit restart to flush the log:

maybe we need to set something like `export PYTHONUNBUFFERED=1` where we execute the server, to make sure we have this kind of output unbuffered? I'm not sure if there could be any significant performance impact, I would expect not for our use.

**Comment by ppigazzini** [comment]
Thanks for the suggestions, I will test on DEV some journal writes with and without that variable.

**Comment by vondele** [comment]
an alternative would be to use print(...,flush=True) wherever we use that for error reporting..

**Comment by ppigazzini** [comment]
Before forcing the write I would like to understand why the print to stdout is buffered and why there is the delay with or systemd or waitress.

**Comment by vondele** [comment]
there is some documentation here: https://bugs.python.org/issue13597
how things are buffered depends on it being 'interactive' or not. So I assume that as part of systemd, things will be block buffered instead of non-buffered or line-buffered.

**Comment by vondele** [comment]
hmm just got this message: `400 Bad CSRF Token
Access is denied. This server can not verify that your cross-site request forgery token belongs to your login session. Either you supplied the wrong cross-site request forgery token or your session no longer exists. This may be due to session timeout or because browser is not supplying the credentials required, as can happen when the browser has cookies turned off.

check_csrf_token(): Invalid token `

**Comment by ppigazzini** [comment]
Logout and login usually solves that for me on DEV.

**Comment by vondele** [comment]
yeah, seems a singular event.

**Comment by ppigazzini** [comment]
With DEV workflow (db reload, PR merge, some browser tabs/windows etc.) sometime it happens.

**Comment by ppigazzini** [comment]
Some reading for the commute.
Pyramid logging https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/logging.html
Fishtest logging configuration:
https://github.com/glinscott/fishtest/blob/2e0b9838d3f7b615a70c5fc2857341038e7213af/server/production.ini#L35-L65

**Comment by vondele** [comment]
do we have an idea on how to debug this further? Somehow, I can upload nets by putting a loop around the upload script, and once every 10 times or so, the upload succeeds.... that's not ideal of course.

**Comment by ppigazzini** [comment]
nginx and post-server are ok.

I uploaded with sftp one of your nets:

| vps | s | MiB/s |
| - | - | - | 
| DEV | 12 |  3.6 | 
| nn server | 935 | 0.05 |

 Perhaps @noobpwnftw can help to debug this slow connection issue.

**Comment by vondele** [comment]
The strange thing is, sometimes the network upload works, and in that case it uploads in say <30s.

**Comment by vondele** [comment]
some additional info.... I'm trying to upload a net today, and it is essentially giving the error message >100 of times in a row. However, what I observe on the server is that the net is actually arriving. I.e. it is constantly being written to /home/v7f.eu/nn/ the written net is also complete and right sha (I'm uploading nn-d8fb88ad5b7d.nnue.gz right now).

I wonder if the 15s timeout is just really too small for the post of these nets, and we should increase the HTTP_TIMEOUT to something larger (e.g. 60s) or even significantly larger (we know it gets written, but sometimes very slowly, we could use for example 1800s).

**Comment by vondele** [comment]
could we do an experiment on prod with the timeout set to e.g. 300s ?

**Comment by ppigazzini** [comment]
PROD restarted with:
```python
response = requests.post(upload_server, data=network, timeout=HTTP_TIMEOUT * 20)
```

**Comment by ppigazzini** [comment]
I added the keepalive in nginx config, https://www.nginx.com/blog/tuning-nginx
```
        proxy_http_version 1.1;
        proxy_set_header Connection "";
```

**Comment by vondele** [comment]
yeah, looks like this works well. Let me do a second check..

**Comment by ppigazzini** [comment]
Noob suggested to add this too `proxy_request_buffering off;`. In the next days I will try to clean up the changes.

**Comment by vondele** [comment]
current configs works well. nets all uploaded properly on first try.

**Comment by ppigazzini** [comment]
Please try now, I reverted all the nginx changes.

**Comment by vondele** [comment]
still working.

**Comment by ppigazzini** [comment]
Thank you, so it should be only the timeout.

**Comment by ppigazzini** [comment]
@vondele The last test please, I reverted the Cloudflare caching for the upload.

**Comment by vondele** [comment]
now, I'm seeing failures.

**Comment by ppigazzini** [comment]
Ok, restored Cloudflare cache.

**Comment by vondele** [comment]
and immediate success..

**Comment by ppigazzini** [comment]
Thank you. I will update the PROD setup script.

**Comment by vondele** [comment]
The timeout needs a change to the code, I assume?

I wonder if we want to increase also the timeout in the worker, and see if this reduces the number of failing downloads from github / net. Maybe 15s is a bit tight for that as well in some cases.

**Pull request merged**
