### PR TITLE
Fix double listing of recently finished run

### PR DESCRIPTION
**Pull request by tomtor**
Needs testing on the Dev server

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor dev server ready with the PR code, some workers and a couple of runs (SPRT and Fixed).
user01 to add runs, user00 to approve runs.

**Comment by ppigazzini** [comment]
@tomtor the test on the dev server ran w/o problems, if you think that this PR is ready I will merge.

**Comment by tomtor** [comment]
@ppigazzini Just saw the double listing again so my fix apparantly does not work. I will have a look at the code again.

**Comment by tomtor** [comment]
Ok, I saw the double listing while #211 was in test. So #210 is most likely ok. It is cosmetic so committing is low risk and ok for me.

**Comment by ppigazzini** [comment]
@tomtor official server updated and restarted

**Pull request merged**
