### PR TITLE
Cache and buffer Run data

### PR DESCRIPTION
**Pull request by tomtor**
The idea is simple, there is no need to read Run data more than once from MongoDb, because we are the only one updating.

The only exceptions are

- request_task, which executes a MongoDb query that modifies the database, so
the Run data cache is invalidated.
- scavenge.py (new internal implementation for active Runs in this PR)
- update_users.py (does not write Run data)

This PR will also reduce the write frequency from update_task which is executed hundreds of times each second and overwrites the data it has just written a few milliseconds earlier. These writes are now buffered and a buffer is flushed every second.

In addition rewrite and speedup request_task by executing the selection logic in Python.

### CODE REVIEW

**Comment by tomtor** [comment]
@xoto10 @ppigazzini This could use some more testing, so if one of you is interested and has the time...

**Comment by xoto10** [comment]
@tomtor @ppigazzini I don't really agree with the idea, the db is essentially doing this for us already. Reads for a known run_id are probably taking 1% of our I/O (or elapsed time), probably a lot less than that - not worth writing code to get an unimportant gain.
I've been a bit slow in the last couple of days, I'll see if I can do some work on the updates this evening, I suspect that is where the gains are ...

**Comment by tomtor** [comment]
@xoto10 We do each seconds more than 100 reads for the same run and read back the data just written. Those reads are BIG, all tasks and all SPSA paramas and history. That's a lot of waisted IO better used for executing eg request_task. 49% of our IO are these waisted reads, 49% are waisted writes, the data wil be overwritten 0.01s later

I am currently doing the same for writes, just write the Run data at most once every second.
The database should store our persistent Run state for a fishtest reboot, nothing more nothing less.

**Comment by xoto10** [comment]
The db will cache frequently accessed runs in ram. For writes, be aware
that the app is killed every 6 hours. I hope it works!

**Comment by tomtor** [comment]
@xoto10 Yes, it is buffered in the IO cache and MonoDb but the transport over the local TCP/IP connection from MongoDb to Python fishtest is very slow compared to local data in Python. I write the data every second, so that should be safe en sufficient. Let's see how this works out, but it should improve throughput by a factor 100.

**Comment by ppigazzini** [comment]
@xoto10 pserve is never killed on the official server. The crontab had a reference to a non existent script, perhaps Gary changed is mind, forgetting to change the crontab. I commented out that line.

**Comment by xoto10** [comment]
@ppigazzini Ah ok, that's good. If we can batch the writes up a bit, that will certainly help. One of the best performance enhancements in my day job is to do "array" inserts/updates where you insert/update many rows of data with one statement. In our case I guess the equivalent is to only write the update of a single run to the db occasionally.

**Comment by tomtor** [comment]
@xoto10 @ppigazzini The code is done, and a short test shows no issues on my side. As said, this will reduce IO traffic enormously, I would really appreciate it if you can test it on your own servers to see if there are any functional flaws....

**Comment by ppigazzini** [comment]
@tomtor sure, I will test this night.

**Comment by xoto10** [comment]
Why separate read + write caches? If a run goes into the write cache, don't we want to read it back out of there? (Probably a dumb question but ...)

**Comment by ppigazzini** [comment]
@tomtor I'm testing on my [dev server](http://94.198.98.239/tests) with 93 cores workers.

**Comment by tomtor** [comment]
@ppigazzini Thanks, I will make some minor changes today. I will let you know when a newer version is ready.

**Comment by tomtor** [comment]
@xoto10 Regarding the good question about two caches, that should be no problem because both caches should have the same single Run object. So it just separates the read and delayed write logic. Note that there currently is a potential issue because I erase the read cache in request_task which will create new Run objects. I will fix that. I might also merge the two caches but I am not sure if that improves the readability of the code.

**Comment by xoto10** [comment]
@tomtor @ppigazzini Ok, the separate caches confused me. I've created a branch(https://github.com/xoto10/fishtest/tree/params2) with a change to the saves but my test workers are not building src for some reason (github problem??)
I'll have a look at your changes and test mine later on today ...

**Comment by tomtor** [comment]
@ppigazzini @tomtor Ok, I fixed some issues and it tested well locally, but it is tricky code. I expect a very significant performance boost from this change, but the question is, how to test this? Perhaps first keep it running some days on your server? Do we have a good way to compare the performance before and after this PR?

**Comment by ppigazzini** [comment]
@tomtor I'm open to suggestions to test properly the patch.

At the moment I'm testing it on the [dev server](http://94.198.98.239/tests) with:
* 3 workers
* 93 total threads
* 3 big SPSAs with very low time control

At the start the load is very low

```
top - 19:36:26 up 4 days, 19 min,  1 user,  load average: 0.10, 0.17, 0.14
Tasks: 139 total,   1 running, 138 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.1 sy,  0.2 ni, 99.2 id,  0.4 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  4044204 total,  1826176 free,   930980 used,  1287048 buff/cache
KiB Swap:  8388604 total,  8346184 free,    42420 used.  2744808 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
18567 mongod    20   0 1713884 768372   7908 S   1.0 19.0   0:07.28 mongod
18609 fishtest  25   5 1955356  81036   9536 S   0.7  2.0   0:03.24 pserve
   33 root      20   0       0      0      0 S   0.3  0.0   1:14.32 rcu_sched
15425 fishtest  20   0  145708   2308   1036 S   0.3  0.1   0:00.13 sshd
18643 fishtest  20   0  157712   2216   1556 R   0.3  0.1   0:00.10 top
    1 root      20   0  190740   2936   1744 S   0.0  0.1   0:39.37 systemd

```

**Comment by ppigazzini** [comment]
@tomtor @xoto10 I'm commuting towards home, I will be on line in a couple of hours

**Comment by tomtor** [comment]
One cosmetic issue is that scavenge.py does not work while a run is executed by an active worker, scavenge.py should be added to Fishserver as a periodic job.

**Comment by tomtor** [comment]
@ppigazzini Something is wrong, two jobs have the same ID: 5ab0d5bfe44b061cc1c725cf, I assume because there is an issue with reschedule when cloning a Job? (I'll have to look at that) Could you try using the New form? This results in a weird graph because the data is mixed.

**Comment by ppigazzini** [comment]
@tomtor I created the three jobs with the New form. Perhaps there is a bug if the same user create more that one test during the same session.

**Comment by ppigazzini** [comment]
@tomtor the homepage is stuck but the CPU is unloaded. I will reset the server and the test queue.

**Comment by ppigazzini** [comment]
@tomtor on my server update_user.py seems to be costly
```
top - 22:00:39 up 4 days,  2:43,  1 user,  load average: 0.91, 0.40, 0.18
Tasks: 142 total,   3 running, 139 sleeping,   0 stopped,   0 zombie
%Cpu(s): 24.8 us,  0.7 sy,  1.3 ni, 70.7 id,  2.3 wa,  0.0 hi,  0.1 si,  0.1 st
KiB Mem :  4044204 total,  1044856 free,  1680244 used,  1319104 buff/cache
KiB Swap:  8388604 total,  8346184 free,    42420 used.  1994576 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
30836 fishtest  20   0  846408 300248   9240 R  69.8  7.4   0:25.05 update_use+
30003 mongod    20   0 2043192 1.025g   8096 S  31.2 26.6   1:23.43 mongod
30042 fishtest  25   5 1955356 222420   9720 S   6.3  5.5   0:13.37 pserve
```

**Comment by tomtor** [comment]
@ppigazzini Thanks for the test, I'll try to reproduce your findings tomorrow at my server.

**Comment by tomtor** [comment]
@ppigazzini One last question, did you start with a fresh restored database?

**Comment by ppigazzini** [comment]
@tomtor steps used:
1. copied the official DB
2. deleted all the pending runs
3. created and approved the 3 SPSA runs
4. mongodump | tar -xzvf dump.tgz dump
5. first test with 3 SPSA runs clean
6. after the homepage stuck, restart of the fishtest server 

The homepage is now stuck again.
In this moment I'm restoring the DB with the 3 SPSA clean runs to test the fishtest master.

**Comment by ppigazzini** [comment]
@tomtor fishtest master has ben working fine for over 90 minutes.

**Comment by tomtor** [comment]
@ppigazzini I found a deadlock. Will fix this and add a replacement for scavenge.py. Thanks for testing.

**Comment by tomtor** [comment]
@ppigazzini OK, it's ready for some more testing. I scavenge now internally the active runs with 30 minutes. The external scavenge.py is still needed for unactive runs.

**Comment by ppigazzini** [comment]
@tomtor @xoto10 test started on my [dev server](http://94.198.98.239/tests)

I use this script to be sure to start with a clean fishtest:
```bash
#!/bin/bash
# to update a fishtest server on CentOS, simply run:
# sudo -H bash update-fishtest.sh | tee update-fishtest.sh.log
#
# to use fishtest open a browser and connect to:
# http://<ip-address>

# download and prepare fishtest
sudo -i -u fishtest << EOF
rm -rf fishtest
git clone https://github.com/glinscott/fishtest.git

# pull some PRs: mandatory for an up to date installation
# comment out if a PR will be committed upstream
# https://github.com/glinscott/fishtest/pull/43
# https://github.com/glinscott/fishtest/pull/106
cd fishtest
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
git pull --no-edit origin pull/43/head
git pull --no-edit origin pull/106/head

# add here the PRs to be tested
git pull --no-edit origin pull/183/head

EOF

# setup fishtest
cd /home/fishtest/fishtest/fishtest
python setup.py develop
```

**Comment by ppigazzini** [comment]
@tomtor @xoto10 the patch seems working without problem on the [dev server](http://94.198.98.239/tests), the CPU load is always very low

```
top - 22:09:47 up 5 days,  2:52,  1 user,  load average: 0.10, 0.20, 0.25
Tasks: 137 total,   1 running, 136 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.2 sy,  1.2 ni, 98.3 id,  0.2 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  4044204 total,   818616 free,  1637928 used,  1587660 buff/cache
KiB Swap:  8388604 total,  8342500 free,    46104 used.  2028056 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 6808 fishtest  25   5 1955348 489996   9756 S   5.6 12.1  15:10.61 pserve
 6769 mongod    20   0 2047396 1.014g   8112 S   1.3 26.3  14:04.75 mongod
    1 root      20   0  190740   2948   1752 S   0.3  0.1   1:09.55 systemd
```

**Comment by tomtor** [comment]
@ppigazzini Nice! The last remaining thing which holds us back is the slow request_task. I will make a new PR for that.

**Comment by ppigazzini** [comment]
@noobpwnftw my [dev-server](http://94.198.98.239/tests) has CPU and RAM comparable to the official server.
I would like to test if the dev server is able to scale with the number the workers thank to:
* up to date OS and packages
* this PR of @tomtor 

The official server has problem already with 200 workers, so I raised to 400 your permitted workers on the dev server.

**Comment by ppigazzini** [comment]
@tomtor update 

```
top - 07:33:13 up 5 days, 12:16,  1 user,  load average: 0.33, 0.34, 0.24
Tasks: 138 total,   1 running, 137 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.4 us,  0.5 sy,  2.6 ni, 94.8 id,  0.2 wa,  0.0 hi,  0.0 si,  1.5 st
KiB Mem :  4044204 total,   745356 free,  1626528 used,  1672320 buff/cache
KiB Swap:  8388604 total,  8342500 free,    46104 used.  2026852 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
12648 fishtest  25   5 2021596 462648   9688 S  12.0 11.4  10:53.35 pserve
 6769 mongod    20   0 2047396 1.031g   8440 S   2.0 26.7  58:09.52 mongod
  887 root      20   0  562416  11088   1488 S   0.3  0.3   1:16.49 tuned
```

**Comment by tomtor** [comment]
@ppigazzini Does http://94.198.98.239/tests also have sufficient network bandwidth for > 100 workers? I have noticed in the past some connection timeout problems even when the load was quite low.

**Comment by ppigazzini** [comment]
@tomtor from the setting of the ISP it has 1Gb/s of bandwith. As fast and dirty test I created a 1GiB file with random data (`dd if=/dev/urandom of=./test.tmp bs=4k iflag=fullblock,count_bytes count=1G`) on a couple of servers, I got 40.0MB/s and 55.4MB/s during the download of the file.
I asked support to @noobpwnftw also to test the bandwidth and the network infrastructure of my ISP cloud solution.

**Comment by tomtor** [comment]
@ppigazzini Ok, thanks for the networking info. I added the request_task rewrite to this PR, because there are some dependencies. If you could restart the test server with this version we can combine the speedup test with a functional non regression test for update_task.

**Comment by ppigazzini** [comment]
@tomtor OK, done. Started the test from a clean state (mongoDB and fishtest), the log of merge of the new PR is correct.

Top after some minutes from the start
```
top - 12:41:18 up 5 days, 17:24,  1 user,  load average: 0.31, 0.34, 0.45
Tasks: 137 total,   2 running, 135 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.3 sy,  1.7 ni, 97.6 id,  0.1 wa,  0.0 hi,  0.0 si,  0.1 st
KiB Mem :  4044204 total,   534304 free,  1430960 used,  2078940 buff/cache
KiB Swap:  8388604 total,  8332468 free,    56136 used.  2245976 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
20083 fishtest  25   5 1955320 379212   9656 S   7.6  9.4   0:25.24 pserve
20045 mongod    20   0 1900560 969052   8104 S   1.3 24.0   0:22.72 mongod
    1 root      20   0  190740   2940   1744 S   0.0  0.1   1:25.21 systemd
```

**Comment by noobpwnftw** [comment]
@ppigazzini I have redirected my workers to your dev server. Please advice.

**Comment by ppigazzini** [comment]
@noobpwnftw @tomtor @xoto10 the CPU load seems low, the home page responsive, using SPSA w/ very low time control we got 12000 games/minute

```
top - 15:25:53 up 5 days, 20:08,  1 user,  load average: 0.91, 0.95, 0.95
Tasks: 137 total,   2 running, 135 sleeping,   0 stopped,   0 zombie
%Cpu(s):  9.1 us,  1.9 sy, 12.9 ni, 74.6 id,  0.2 wa,  0.0 hi,  0.2 si,  1.1 st
KiB Mem :  4044204 total,   255760 free,  2258108 used,  1530336 buff/cache
KiB Swap:  8388604 total,  8331264 free,    57340 used.  1410984 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
20083 fishtest  25   5 2497216 1.059g   9792 S  62.1 27.5  33:25.27 pserve
20045 mongod    20   0 2047336 1.011g   8204 S  36.2 26.2  20:21.14 mongod
    1 root      20   0  190740   2940   1744 S   0.3  0.1   1:28.09 systemd
   33 root      20   0       0      0      0 S   0.3  0.0   2:51.87 rcu_sched
    2
```

I add now a SPSA run with a normal time control to check the parameters convergence.

**Comment by tomtor** [comment]
@noobpwnftw I have very good response from my workers (< 70ms), no timeouts and request_task is executed in about 900ms, but from the progress and update times on the tasks it looks as if your workers are experiencing timeouts? Is that true?

**Comment by noobpwnftw** [comment]
@tomtor My workers on dev server I do not experience any timeouts. There however are connection failures because of too many connections being made due to low TC.

**Comment by tomtor** [comment]
@noobpwnftw I see, that explains it. Thanks for your testing!

**Comment by ppigazzini** [comment]
@noobpwnftw @tomtor @xoto10 I launched also a Tom's `stress_test.sh`, the home page was responsive and I didn't viewed workers disconnections
```
:~# time bash stress-test.sh

real    2m3.379s
user    0m1.641s
sys     0m13.000s
```

```
top - 15:48:05 up 5 days, 20:31,  1 user,  load average: 2.59, 1.40, 1.06
Tasks: 137 total,   2 running, 135 sleeping,   0 stopped,   0 zombie
%Cpu(s):  9.1 us, 11.3 sy, 20.7 ni, 56.6 id,  1.6 wa,  0.0 hi,  0.4 si,  0.3 st
KiB Mem :  4044204 total,   475624 free,  2309340 used,  1259240 buff/cache
KiB Swap:  8388604 total,  8361496 free,    27108 used.  1333944 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
20083 fishtest  25   5 2497216 1.105g  10568 R 116.3 28.6  45:56.18 pserve
20045 mongod    20   0 2047336 1.016g   8204 S  23.3 26.3  26:31.89 mongod
  401 root      20   0   45032   9408   9268 S  19.3  0.2   2:10.45 systemd-jo+
```
Without `stress_test.sh`

```
top - 15:57:34 up 1 day,  2:15,  1 user,  load average: 0.76, 0.77, 0.76
Tasks:  23 total,   1 running,  22 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.0%us,  0.6%sy, 19.5%ni, 80.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   3145728k total,  2984800k used,   160928k free,        0k buffers
Swap:        0k total,        0k used,        0k free,  1041632k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
  636 fishtest  25   5 12.7g 347m 227m S 48.3 11.3   1175:50 mongod
  678 fishtest  25   5 2753m 1.7g 3156 S 11.7 55.9 280:12.67 python
    1 root      20   0 19232  552  312 S  0.0  0.0   0:00.05 init
```

**Comment by noobpwnftw** [comment]
I see a great success on the dev server, I think it is safe to try on live server.

**Comment by tomtor** [comment]
Maybe we could ask some experienced users like @snicolet and @vondele to have a look at http://94.198.98.239/tests to see if they can launch some tests and see if they spot some issues?

**Comment by noobpwnftw** [comment]
I'm moving workers to finish jobs on live server, please let me know if they are needed on dev server again.

**Comment by ppigazzini** [comment]
@noobpwnftw thank you for your help!
@tomtor I found the cause of the strange behavior of the big SPSA. I inserted the value parameters by hand, but the last two value are changed/computed by fishtest. I'm preparing a new test DB with the big SPSA using the Reschedule.

**Comment by tomtor** [comment]
@ppigazzini Yes, I saw those strange graphs, but they were also strange on master yesterday, so I was not really worried.

**Comment by vondele** [comment]
@tomtor @ppigazzini first: great work! 

the result of this test (currently running test) is really strange:
http://94.198.98.239/tests/view/5ab3dbb4e44b0606e3e2beaa
residual is very large and two workers report 100s of losses on time.
Not sure if this is a server issue. Actually, now I see the TC is very very small, so presumably that is not a real issue.

Hard to judge for me (and hard to test for you guys) if this is right or wrong. I'd suggest to sleep a night over it, and try it out on the live server watching things carefully for a while.

**Comment by ppigazzini** [comment]
@vondele to create traffic I'm running my workers with HT switched ON and concurrency=n_threads-1; with Xeon multi cores this is a very noisy condition. The server with the big number of time losses is benching only 0.45 Mnps: I hacked the min nps required to run fishtest.
When @tomtor will think that this PR is ready, I could repeat a couple of runs from the official framework resetting my workers to the default state.

**Comment by tomtor** [comment]
@ppigazzini I think it is ready. I got normal results at home and the big spsa now shows a normal result.

**Comment by ppigazzini** [comment]
@tomtor PR code resync on the dev server, set my workers to use only 15 cores and started a run currently on the official fishtest. I will check the results in 30 minutes, if they will be correct (as I'm expecting) I will merge the PR and I will update the official server.

**Comment by snicolet** [comment]
Thanks for all the work you are doing, everybody!

**Comment by ppigazzini** [comment]
@tomtor @vondele @snicolet test run on the dev server finished with a result similar to the official server. No crashes or time losses.

* dev server
```
LLR: -2.96 (-2.94,2.94) [0.00,5.00]
Total: 7260 W: 1420 L: 1515 D: 4325
```

* official server
```
LLR: -2.96 (-2.94,2.94) [0.00,5.00]
Total: 20486 W: 4207 L: 4240 D: 12039
```

**Comment by ppigazzini** [comment]
@tomtor official server updated and restarted
* before the update
```
top - 23:38:01 up 1 day,  9:55,  1 user,  load average: 1.71, 1.90, 1.85
Tasks:  23 total,   1 running,  22 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.0%us,  1.5%sy, 40.8%ni, 57.8%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   3145728k total,  3145728k used,        0k free,        0k buffers
Swap:        0k total,        0k used,        0k free,   886340k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
  636 fishtest  25   5 12.7g 370m 242m S 102.5 12.1   1510:03 mongod
  678 fishtest  25   5 2753m 1.7g 2240 S 23.3 55.9 371:16.54 python
13597 fishtest  20   0 14892 1224  996 R  0.3  0.0   0:00.11 top
```

* 15 minutes after the update
```
top - 23:52:41 up 9 min,  1 user,  load average: 0.43, 0.40, 0.21
Tasks:  21 total,   1 running,  20 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.0%us,  2.1%sy, 22.0%ni, 75.9%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   3145728k total,  1871332k used,  1274396k free,        0k buffers
Swap:        0k total,        0k used,        0k free,   642928k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
  633 fishtest  25   5 12.3g 262m 202m S 40.9  8.5   2:00.37 mongod
  661 fishtest  25   5 2190m 1.1g 7364 S 32.0 35.6   2:10.41 python
    1 root      20   0 19232 1492 1252 S  0.0  0.0   0:00.00 init
```

**Comment by ppigazzini** [comment]
@snicolet @vondele fishtest seems works very well now thanks to the great patch of @tomtor. Could you reschedule [tune_imbalance3](http://tests.stockfishchess.org/tests/view/5a9ccf220ebc590297cb6054) with STC to put pressure on fishtest?

**Comment by ppigazzini** [comment]
@tomtor I'm running [tune_imbalance3](http://tests.stockfishchess.org/tests/view/5ab451fe0ebc5902932aec75) as SPSA at 10+0.1 (the original was set to 60+0.6).
The home page is slowed down a bit but still usable, some workers had disconnected but the throughout is always very high (3456 games/minute).

```
top - 02:52:47 up  1:56,  1 user,  load average: 5.05, 5.08, 3.56
Tasks:  21 total,   2 running,  19 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.0%us,  4.1%sy, 32.7%ni, 63.2%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   3145728k total,  2925224k used,   220504k free,        0k buffers
Swap:        0k total,        0k used,        0k free,  1340784k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
  659 fishtest  25   5 2644m 1.3g 3660 R 114.2 44.8  37:50.38 python
  633 fishtest  25   5 12.7g 341m 224m S  5.0 11.1  21:25.31 mongod
    1 root      20   0 19232  932  692 S  0.0  0.0   0:00.00 init
```

**Comment by ppigazzini** [comment]
@tomtor collateral positive effect, now update_users.py is able to load the CPU and to finish in some minutes also under big pressure from the workers.
```
top - 02:58:38 up  2:02,  1 user,  load average: 6.74, 5.45, 4.13
Tasks:  23 total,   2 running,  21 sleeping,   0 stopped,   0 zombie
Cpu(s): 20.6%us,  4.2%sy, 44.8%ni, 30.3%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   3145728k total,  3145728k used,        0k free,        0k buffers
Swap:        0k total,        0k used,        0k free,  1225396k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
  659 fishtest  25   5 2644m 1.4g 3620 S 107.3 46.0  44:20.48 python
 8111 fishtest  20   0  531m 292m 7148 R 61.6  9.5   0:25.70 update_users.py
  633 fishtest  25   5 12.7g 444m 327m S 43.3 14.5  22:55.35 mongod
    1 root      20   0 19232  932  692 S  0.0  0.0   0:00.00 init
```

**Comment by ppigazzini** [comment]
@tomtor SPSA stopped, the CPU load went down immediately, throughput still very high (4040 games/minute)

```
top - 03:31:25 up  2:35,  1 user,  load average: 0.91, 0.94, 2.07
Tasks:  21 total,   1 running,  20 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.0%us,  1.2%sy,  9.6%ni, 89.2%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   3145728k total,  2859368k used,   286360k free,        0k buffers
Swap:        0k total,        0k used,        0k free,  1239672k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
  659 fishtest  25   5 2708m 1.4g 3600 S 24.0 46.1  68:54.02 python
  633 fishtest  25   5 12.7g 452m 341m S  8.7 14.7  30:18.25 mongod
    1 root      20   0 19232  928  688 S  0.0  0.0   0:00.00 init
```

**Comment by tomtor** [comment]
@ppigazzini I saw yesterday that sometimes sprt display is not updated for a long time in overview. I will fix this. It is cosmetic. Result and individual view are not effected.

**Comment by ppigazzini** [comment]
@tomtor yesterday on the dev server the workers seem to stuck always to the same run, the test was short, though. I started few 1-core workers to view if they change runs in order to add some variability.

**Comment by tomtor** [comment]
@ppigazzini I see what you mean regarding stuck runs. It doesn't pick up my new run right away.

**Comment by tomtor** [comment]
@ppigazzini It does not pickup the new job right away because the other jobs are much older. That's ok.

**Comment by ppigazzini** [comment]
@tomtor OK, thank you for checking this. Unfortunately the fishtest logic server side was never documented and the code is not easy to be read on the fly (by me).

**Pull request merged**
