### PR TITLE
Show Net info for tests

### PR DESCRIPTION
**Pull request by tomtor**
Implements https://github.com/glinscott/fishtest/issues/770

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated, I submitted 3 tests (SPRT, NumGames, SPSA), LGTM :)

**Comment by vondele** [comment]
yes, looks good. I checked with SF_11 that the absence of a net is also handled OK (None).

**Comment by tomtor** [comment]
@vondele Thanks for checking
@ppigazzini Did a small cosmetic change (reversed order of two lines) and will squash. For me its OK to merge.

**Comment by ppigazzini** [comment]
PROD updated, thank you @tomtor :)

**Comment by crossbr** [comment]
Yes, @tomtor thank you.

**Pull request merged**
