### PR TITLE
Fix broken SPSA's diff if the repo is too old

### PR DESCRIPTION
**Pull request by G-Lorenz**
Bug reported by locutus2 (as well as the bugfix):
https://discord.com/channels/435943710472011776/900771437177094156/991994320464908418

### CODE REVIEW

**Comment by G-Lorenz** [comment]
Incidentally this patch also solves the annoying issue of a comment to an spsa commit that goes in the official branch instead of the fork.
https://discord.com/channels/435943710472011776/900771437177094156/992072783066570863

**Comment by ppigazzini** [comment]
It seems to work in my local tests. I applied the PR to PROD, please check if it is working as intended.

**Comment by G-Lorenz** [comment]
Seems good to me.
SPSA's diff is working as intended (in particular here: https://tests.stockfishchess.org/tests/view/62bd347e4ab6fec5049aee44), and Disservin's bug (https://discord.com/channels/435943710472011776/813919248455827515/992381150557376572) shouldn't be related to this pr, since it occured in an sprt against master.

**Review by ppigazzini — APPROVED** [review]
I review all the code calling `master_diff_url()` or `diff_url()`.
It's fine to me.

**Comment by ppigazzini** [comment]
Merged, thank you @G-Lorenz @locutus2 :)

**Pull request merged**
