### PR TITLE
Show the pentanomial frequencies on the main test page.

### PR DESCRIPTION
**Pull request by vdbergh**
Show the pentanomial frequencies on the main test page.

### CODE REVIEW

**Comment by vdbergh** [comment]
I looked om DEV. For me the header 'Pentanomial [0-2]' is broken as 'Pentanomial [0-\n2]' which is rather ugly. I wonder how to avoid this (I did not know that html could break strings like this).

**Comment by vdbergh** [comment]
I fixed it by using a non-breaking hyphen.

**Comment by ppigazzini** [comment]
DEV updated :) Sorry, day in, I will have more time this night to review/test the PRs.

**Comment by ppigazzini** [comment]
Pentanomial PRs merged, thank you @vdbergh :)

**Comment by vdbergh** [comment]
Thanks!

**Pull request merged**
