### PR TITLE
Cache MongoDb user lookups

### PR DESCRIPTION
**Pull request by tomtor**
because threads are waiting for lookups > 50% of the time

See http://vmprof.com/#/48225b9c-d12c-4d14-96ce-bed6442eeaea?id=1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,2&view=flames (before this PR and #261 update_task takes almost 30% of the time)

and

http://vmprof.com/#/0c662771-0c65-4f67-bcc4-8483b546f2ff?id=1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,3&view=flames (now 10% of the time)

### CODE REVIEW

**Comment by ppigazzini** [comment]
dev-server and workers updated, restarted the failed Travis check by hand.

**Comment by tomtor** [comment]
@ppigazzini Thanks! Those travis build are quite unreliable in this context. This build failed in a way I had not seen before.

**Comment by tomtor** [comment]
@Stefano80 @ppigazzini @vondele I think it would be a good idea with the recent speedups and 250 chunk size to change the worker start delay from 1-30s to 1-10s

**Comment by vondele** [comment]
@tomtor I agree with the reduction in delay.... it is something I wanted to propose as well. I think with all the improvements in the infrastructure, this has become unproblematic.

**Comment by ppigazzini** [comment]
Production server updated.
Thank you @tomtor

**Pull request merged**
