### PR TITLE
Catch duplicate workers early on.

### PR DESCRIPTION
**Pull request by vdbergh**
The start of the worker is racy. So after a small delay we verify that our lock file has not been overwritten by another worker. This will immediately detect duplicate workers, except on extremely slow systems.

This can be tested with the script
```
python worker.py &
python worker.py
```
where the line `python worker.py &` can be repeated as many times as desired.

### CODE REVIEW

**Comment by ppigazzini** [comment]
I thought that this code was meant to deal (one run late) with the racy workers start. If I'm not wrong after this PR it should be never triggered, a sort of assert, so perhaps better to add a comment.

https://github.com/glinscott/fishtest/blob/33e6c3f54c9c133844d8e470063031d5ce5f0369/worker/worker.py#L392-L400

**Comment by vdbergh** [comment]
In theory it can still be triggered if for one of the workers the time between first checking the lock file and writing the lock file takes more than 0.5 seconds.

**Comment by ppigazzini** [comment]
LGTM, tonight I will test it with some workers.

**Comment by ppigazzini** [comment]
Triggered workers update, thank you @vdbergh :)

**Pull request merged**
