### PR TITLE
Fix some pymongo deprecation warnings

### PR DESCRIPTION
**Pull request by linrock**
Fixes most of those pymongo warnings when running tests, as seen here https://github.com/glinscott/fishtest/pull/589#issuecomment-613717674

a few of the warnings are fixed in https://github.com/glinscott/fishtest/pull/574 so i won't fix them here to avoid a merge conflict

### CODE REVIEW

**Comment by ppigazzini** [comment]
@linrock please rebase :)

**Comment by linrock** [comment]
no prob! merge conflict fixed and rebased

**Comment by ppigazzini** [comment]
@linrock bugs:
 - after approving a test in the test page, the test is still showed in the pending test table with the yellow icon
 - after stopping a test in the test page, the test is still showed in the pending/active test table
 - after deleting a test in the pending table, the test is still showed in the pending table

**Comment by ppigazzini** [comment]
@linrock I leave DEV with this PR in order to verify the strange behavior (master was fine). Bed is calling here :)

**Comment by linrock** [comment]
thanks for catching that. the problem was that the run updates were failing because the `replace_one` calls require an `ObjectId` instead of a string when querying by `_id`

**Comment by ppigazzini** [comment]
PROD updated, thank you @linrock :)

**Pull request merged**
