### PR TITLE
Use C locale for cutechess

### PR DESCRIPTION
**Pull request by vondele**
other locales can yield unexpected date formats.

fixes https://github.com/glinscott/fishtest/issues/685

### CODE REVIEW

**Comment by vondele** [comment]
That's an untested fix. I'm not sure this is actually Linux only, or would work for windows as well..

**Comment by tomtor** [comment]
Or

```
import locale
locale.setlocale(locale.LC_ALL, 'C')
```

Not sure if this effects the invocation of `cutechess` but it might be more portable.
I expect that your code also work on Windows.

**Comment by vondele** [comment]
meanwhile the report in the fishtest thread suggests that modifying the env doesn't work. The user is on windows.

**Comment by tomtor** [comment]
@vondele I wonder if it would not be better to change

https://github.com/glinscott/fishtest/blob/6a9242a10503a5333571178f92db78e8d04e1992/worker/worker.py#L177

to `with open(pgn_file, encoding='utf-8') as f`

because at https://github.com/glinscott/fishtest/blob/6a9242a10503a5333571178f92db78e8d04e1992/worker/worker.py#L179

we expect `utf-8` and why would we be bothered by a utf-8 PGN file?

I do not think this would impact your parsing, how do you parse? 
With Python? With a C program?
Do you interpret dates?

**Comment by vondele** [comment]
I guess that might also be a solution... I don't have strong opinions. Personally, I'm opening pgn files only with python-chess, and open them with: 
```
pgnfilein = open(filename, "r", encoding="utf-8-sig", errors="surrogateescape")
```
I'm assuming that this will be doing the right thing. Usually I don't look at the dates. 
It does mean that we have pgns where the headers can't easily be read by everybody (Фінляндія (літо) being Finland (summer time) is new for me ;-))
Nevertheless, I would be fine with this change as well.

**Comment by tomtor** [comment]
From the google discussion:

https://tests.stockfishchess.org/api/pgn/5eca3862a586eee45aa2abca-61.pgn

DOES have utf-8 content, so normally (sometimes/often?) utf-8 PGN upload succeeds.
I suspect that the failing PGN is not utf-8 but has a different encoding (a cyrillic codepage?)

**Comment by tomtor** [comment]
See google thread...

**Comment by tomtor** [comment]
Close PR but leave #685 open for now

**Pull request closed without merging**
