### PR TITLE
Add robots.txt and favicon.ico

### PR DESCRIPTION
**Pull request by tomtor**
@ppigazzini robots.txt and favicon.ico still need correct content

### CODE REVIEW

**Comment by tomtor** [comment]
@ppigazzini Added icon and robots.txt content (disallow all)

**Comment by ppigazzini** [comment]
@tomtor great! DEV updated, looks fine.

**Comment by ppigazzini** [comment]
@tomtor squash before merging :)

**Comment by tomtor** [comment]
@ppigazzini Side effect:

    Subject: Cron <fishtest@tests> ${VENV}/bin/python ${UPATH}/delta_update_users.py                                                                                                                                                                                                                        
    Traceback (most recent call last):                                                                                                                    
    File "/home/fishtest/fishtest/fishtest/utils/delta_update_users.py", line 11, in <module>                                                             
    from fishtest.views import parse_tc, delta_date                                                                                                   
    File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 39, in <module>                                                                       
    with open(os.path.join('fishtest', 'static', 'favicon.ico'), 'r') as f:                                                                         
    IOError: [Errno 2] No such file or directory: 'fishtest/static/favicon.ico' 

I will change the crontab....

**Comment by ppigazzini** [comment]
@tomtor on DEV I got this error also for `scavenge.py`, solved updating the crontab. On PROD `scavenge.py` works fine from any folder...

**Pull request merged**
