### PR TITLE
Restrict uuid_prefixes to alphanumeric _ascii_ strings.

### PR DESCRIPTION
**Pull request by vdbergh**
Currently "Štockfish" is allowed.

### CODE REVIEW

**Comment by ppigazzini** [comment]
I'm a noobie in unicode ascii etc, only wondering if `isascii()` and `isalphanum()` can do the same work:
```python
"Štockfish".isascii()
False
```

**Comment by vdbergh** [comment]
isascii unfortunately was only introduced in Python 3.7. I think that's a bit recent.

**Comment by vdbergh** [comment]
For now the worker still runs with Python 3.5.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
Triggered the workers update, thank you @vdbergh :)

**Comment by vdbergh** [comment]
:+1:

**Pull request merged**
