### PR TITLE
Dismiss fallback notifications in all tabs with one click.

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated with this PR, 4 major browsers with test opened in few tabs.
How do I test this PR?

**Comment by vdbergh** [comment]
> DEV updated with this PR, 4 major browsers with test opened in few tabs (following the test).
> If I understood correctly dismissing in a tab the notification should close the notifications in all tabs (this workerd for all 4 browsers)

This was the intention…

**Comment by ppigazzini** [comment]
Firefox now sends the notification to Windows as the other browsers

**Comment by vdbergh** [comment]
> Firefox now sends the notification to Windows as the other browsers

There used to be a problem on Linux, but I haven’t checked recently.

**Review by ppigazzini — APPROVED** [review]
Tested working with edge/chrome/opera/firefox

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
