### PR TITLE
Allow specifying bounds in normalized Elo in the SPRT calculator

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
@vdbergh looks good on DEV. I wait your "go" to merge and update PROD.

**Comment by vdbergh** [comment]
@ppigazzini I squashed the PR. For me it is ok to merge it.

**Comment by ppigazzini** [comment]
PROD updated, page working fine after a refresh, thank you @vdbergh :)

**Comment by vdbergh** [comment]
:)

**Pull request merged**
