### PR TITLE
Disable AVX512 for now.

### PR DESCRIPTION
**Pull request by vondele**
noob reports 20% slowdown compared to avx2

### CODE REVIEW

**Comment by vondele** [comment]
fixes https://github.com/glinscott/fishtest/issues/947

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
Version raised to trigger the worker update :)

**Comment by NightlyKing** [comment]
I think a better way is to have some automatic bench once to test which arch to use (e.g. after installing the worker). Alternatively we could ask the user what to use. On some CPUs (latest i9s) it gains as much as noob is losing on his xeons (which struggle quite a bit with the down clocking).

**Comment by ppigazzini** [comment]
@vondele something related to bench. I recently compared two builds with the same ARCH but different gcc version (10.2 cygwin vs. 10.3 msys2) and the bench result seems to depend strongly on depth/NNUE `bench 16 1 ${depth} default depth [NNUE]`

| depth | NNUE | 10.2 vs 10.3 speedup |
|-|-|-|
| 13 | n | 0.006041 |
| 14 | n | 0.018216 |
| 15 | n | 0.050885 |
| 16 | n | 0.033239 |
| 13 | y |  0.005921 |
| 14 | y | -0.040629 |
| 15 | y | -0.033918 |
| 16 | y | -0.020917 |

This is the result with gcc 10.3 and two different PGOs: `bench 16 1 13 default depth` vs `bench 16 1 13 default depth NNUE`

| depth | NNUE | PGO normal vs PGO NNUE speedup |
|-|-|-|
| 13 | n | -0.002464 |
| 14 | n | -0.004735 |
| 15 | n | -0.003849 |
| 13 | y | -0.000016 |
| 14 | y | 0.001413 |
| 15 | y | 0.001973 |

**Pull request merged**
