### PR TITLE
Try catch block around net download.

### PR DESCRIPTION
**Pull request by vdbergh**
In order to deal with this:

https://tests.stockfishchess.org/actions?count=1&before=1649527432.921

### CODE REVIEW

**Comment by ppigazzini** [comment]
worker | info
-- | --
Skiff84-15cores-12ff0976 | os: Windows 10; ram: 16358MiB; compiler: g++ 11.2.0; python: 3.9.11; worker: 163; arch: 64bit AVX2 SSE41 SSSE3 SSE2 POPCNT

This is the first run of the engine, so the problem should due to a not working `stockfish uci`, I'm wondering if the problem triggers this exception:
https://github.com/glinscott/fishtest/blob/78f8a09297e60280d4ba387a6b176d384f402172/worker/games.py#L247-L250


By the way:
`stockfish_<hash> uci` runs successfully without the net (tested on wsl and msys2).

The engine is built with `make profile-build` and we check for the return code:
https://github.com/glinscott/fishtest/blob/78f8a09297e60280d4ba387a6b176d384f402172/worker/games.py#L656-L670

**Comment by ppigazzini** [comment]
The worker in that test  https://tests.stockfishchess.org/tests/view/624ee7f79304f184652522d1 could have a problem during the update to v 163: 

Idx | Worker | Info | Last Updated | Played | Pentanomial [0‑2] | Crashes | Time | Residual
-- | -- | -- | -- | -- | -- | -- | -- | --
9 | Skiff84-15cores-2b2e0e59 | os: Windows 10; ram: 16358MiB; compiler: g++ 11.2.0; python: 3.9.11; worker: 162; arch: 64bit AVX2 SSE41 SSSE3 SSE2 POPCNT | 2022-04-07 14:16:39 | 072 / 072 | [0, 9, 20, 7, 0] | 0 | 0 | 0.000
192 | Skiff84-15cores-a527de64 | os: Windows 10; ram: 16358MiB; compiler: g++ 11.2.0; python: 3.9.11; worker: 162; arch: 64bit AVX2 SSE41 SSSE3 SSE2 POPCNT | 2022-04-07 23:48:21 | 072 / 072 | [1, 10, 19, 5, 1] | 0 | 0 | 0.000
363 | Skiff84-15cores-a527de64 | os: Windows 10; ram: 16358MiB; compiler: g++ 11.2.0; python: 3.9.11; worker: 162; arch: 64bit AVX2 SSE41 SSSE3 SSE2 POPCNT | 2022-04-08 08:54:42 | 072 / 072 | [0, 7, 21, 8, 0] | 0 | 0 | 0.000
577 | Skiff84-15cores-53e3dd48 | os: Windows 10; ram: 16358MiB; compiler: g++ 11.2.0; python: 3.9.11; worker: 163; arch: 64bit AVX2 SSE41 SSSE3 SSE2 POPCNT | 2022-04-09 08:03:33 | 000 / 072 | [0, 0, 0, 0, 0] | 0 | 0 | -
608 | Skiff84-15cores-71dcca1d | os: Windows 10; ram: 16358MiB; compiler: g++ 11.2.0; python: 3.9.11; worker: 163; arch: 64bit AVX2 SSE41 SSSE3 SSE2 POPCNT | 2022-04-09 10:04:33 | 000 / 072 | [0, 0, 0, 0, 0] | 0 | 0 | -
738 | Skiff84-15cores-7a1865f6 | os: Windows 10; ram: 16358MiB; compiler: g++ 11.2.0; python: 3.9.11; worker: 163; arch: 64bit AVX2 SSE41 SSSE3 SSE2 POPCNT | 2022-04-09 16:44:20 | 000 / 072 | [0, 0, 0, 0, 0] | 0 | 0 | -
772 | Skiff84-15cores-313abaef | os: Windows 10; ram: 16358MiB; compiler: g++ 11.2.0; python: 3.9.11; worker: 163; arch: 64bit AVX2 SSE41 SSSE3 SSE2 POPCNT | 2022-04-09 18:03:52 | 000 / 072 | [0, 0, 0, 0, 0] | 0 | 0 | -

**Comment by vdbergh** [comment]
> This is the first run of the engine, so the problem should due to a not working `stockfish_<hash> uci`, I'm wondering why the problem didn't triggered this exception:
> 
> 

Since there was an OSError while executing `Popen` I think `stockfish_<hash>` did not exist or was not executable. How this is possible I don't know. In this PR we print the exception so perhaps this will give more insight.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
Worker update triggered,

**Comment by vdbergh** [comment]
https://tests.stockfishchess.org/actions?count=1&before=1649815167.714

**Comment by ppigazzini** [comment]
I'm wondering what can produce "Exec format error" on a linux noob's worker.

**Pull request merged**
