### PR TITLE
download missing cutechess-cli for macos

### PR DESCRIPTION
**Pull request by RaimundHeid**
This seems to work without further ado:

...
Running simpLimitExtension vs master
Variable task sizes used. Opening offset = 108600
Downloading cutechess-cli-macos-64bit.zip ...
Obtaining version info for /Users/raimundheid/Applications/forked_fishtest/worker/testing/cutechess-cli ...
Found:  cutechess-cli 1.2.0
...

### CODE REVIEW

**Review by ppigazzini — APPROVED** [review]
Workers run fine with linux, msys2, WSL and the patch looks good to me.

**Comment by ppigazzini** [comment]
PROD updated to trigger the workers update.
Thank you @RaimundHeid :)

**Comment by vondele** [comment]
so, with this patch, the worker downloaded cutechess-cli and runs the worker on a macbook pro (so not m1), compiles with clang++, but doesn't pick the right arch (just a generic x86-64).

**Comment by ppigazzini** [comment]
Yes, this needs the proper parsing:
https://github.com/glinscott/fishtest/blob/9c5a80d2ed7c363a60f9358c70c3ac875f9728d5/worker/games.py#L466-L467

**Comment by RaimundHeid** [comment]
> so, with this patch, the worker downloaded cutechess-cli and runs the worker on a macbook pro (so not m1), compiles with clang++, but doesn't pick the right arch (just a generic x86-64).

You are right, although I assume Mx support for g++-users if of higher practical relevance. Will tackle both issues ofc.

Maybe we will have to get the clang props like it is described in https://stackoverflow.com/questions/35357659/what-flags-does-march-native-activate-with-clang - will investigate.

**Comment by ppigazzini** [comment]
Check #775 where that way to find GCC and clang props was suggested.

**Comment by ppigazzini** [comment]
Only to point out that `msys2` and `cygwin` have `/proc/cpuinfo`, so the code could be:
```python
def cpu_props():
    p = subprocess.Popen(
        ["cat", "/proc/cpuinfo"],
        stdout=subprocess.PIPE,
        universal_newlines=True,
        bufsize=1,
        close_fds=not IS_WINDOWS,
    )

    for line in iter(p.stdout.readline, ""):
        if "flags" in line:
                return {"flags": line.split()[2:]}
```

Here is the ouput:
```
new:
{'flags': ['fpu', 'vme', 'de', 'pse', 'tsc', 'msr', 'pae', 'mce', 'cx8', 'apic', 'sep', 'mtrr', 'pge', 'mca', 'cmov', 'pat', 'pse36', 'clflush', 'acpi', 'mmx', 'fxsr', 'sse', 'sse2', 'ss', 'ht', 'tm', 'pbe', 'constant_tsc', 'arch_perfmon', 'rep_good', 'nopl', 'xtopology', 'cpuid', 'aperfmperf', 'pni', 'pclmuldq', 'est', 'tm2', 'ssse3', 'cx16', 'xtpr', 'pdcm', 'pcid', 'sse4_1', 'sse4_2', 'popcnt', 'aes', 'xsave', 'avx', 'f16c', 'rdrand', 'hypervisor', 'lahf_lm', 'epb', 'fsgsbase', 'smep', 'erms', 'xsaveopt', 'dtherm', 'ida', 'pln', 'pts', 'md_clear', 'flush_l1d', 'arch_capabilities']}

master:
{'flags': ['-m128bit-long-double', '-m64', '-m80387', '-maccumulate-outgoing-args', '-maes', '-malign-double', '-malign-stringops', '-mavx', '-mavx256-split-unaligned-load', '-mavx256-split-unaligned-store', '-mcx16', '-mf16c', '-mfancy-math-387', '-mfentry', '-mfp-ret-in-387', '-mfsgsbase', '-mfxsr', '-mhard-float', '-mieee-fp', '-mlong-double-80', '-mmmx', '-mms-bitfields', '-mno-align-vector-insn', '-mpclmul', '-mpe-aligned-commons', '-mpopcnt', '-mpush-args', '-mrdrnd', '-mred-zone', '-msahf', '-msse', '-msse2', '-msse3', '-msse4', '-msse4.1', '-msse4.2', '-mssse3', '-mstack-arg-probe', '-mstackrealign', '-mvzeroupper', '-mxsave', '-mxsaveopt'], 'arch': 'ivybridge'}
```

**Comment by ppigazzini** [comment]
@vondele the CPU flags could be parsed in the Makefile.

**Pull request merged**
