### PR TITLE
Align numeric columns to right.

### PR DESCRIPTION
**Pull request by mrobaczyk**
Align numeric columns to right for easier readibility.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@mrobaczyk [dev-server](https://dfts-0.pigazzini.it) updated with this PR but the "user" page still has the values aligned to the left. Perhaps something is wrong or I haven't understood the PR. Here a snippet of the page source from chrome:

```html
<table class="table table-striped table-condensed">
 <thead>
  <tr>
   <th>Username</th>
   <th>Last active</th>
   <th>Games/Hour</th>
   <th>CPU Hours</th>
   <th>Games played</th>
   <th>Tests submitted</th>
   <th>Tests repository</th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td>ChessDBCN</td>
   <td>3 days ago</td>
   <td align="right">0</td>
   <td align="right">6060846</td>
   <td align="right">464172229</td>
   <td align="right"><a href="/tests/user/ChessDBCN">0</td>
   <td><a href="" target="_blank"></a></td>
  </tr>
  <tr>
   <td>ChessDB_CN_WorkerPool</td>
   <td>432 days ago</td>
   <td align="right">0</td>
   <td align="right">1977735</td>
   <td align="right">148731870</td>
   <td align="right"><a href="/tests/user/ChessDB_CN_WorkerPool">0</td>
   <td><a href="" target="_blank"></a></td>
  </tr>
  <tr>

...


```

**Comment by mrobaczyk** [comment]
Ok so the bootstrap.min.css is overriding this with
`
 .table th, .table td {
     padding: 8px;
     line - height: 20px;
     text - align: left;
     vertical - align: top;
     border - top: 1px solid # ddd
 }
`

I don't know what is the convention in this project for fixing these kind of things. Can someone help with this PR? We can add another css class for right-aligned td in table for example. Is it ok?

**Comment by ppigazzini** [comment]
cc to @tomtor

**Comment by tomtor** [comment]
@mrobaczyk You could/should use:

`style="text-align:right;"`

instead of

`align="right"`

Or create another css class, both are fine with me.

**Comment by mrobaczyk** [comment]
Ok thanks for help. But another thing I want to ask you @tomtor , now columns headers are looking a little bit of. What do you suggest to make this look better? Should I change columns widths?

image

**Comment by ppigazzini** [comment]
@mrobaczyk this seems to work for the dev-server

```
<table class="table table-striped table-condensed">
 <thead>
  <tr>
   <th>Username</th>
   <th>Last active</th>
   <th style="text-align:right;">Games/Hour</th>
   <th style="text-align:right;">CPU Hours</th>
   <th style="text-align:right;">Games played</th>
   <th style="text-align:right;">Tests submitted</th>
   <th>Tests repository</th>
  </tr>
 </thead>
 <tbody>
 %for user in users:
  <tr>
   <td>${user['username']}</td>
   <td>${user['last_updated']}</td>
   <td style="text-align:right;">${int(user['games_per_hour'])}</td>
   <td style="text-align:right;">${int(user['cpu_hours'])}</td>
   <td style="text-align:right;">${int(user['games'])}</td>
   <td style="text-align:right;"><a href="/tests/user/${user['username']}">${user['tests']}</td>
   <td><a href="${user['tests_repo']}" target="_blank">${user['tests_repo']}</a></td>
  </tr>

```

**Comment by mrobaczyk** [comment]
Yes we can go this way, if you think that distance between "Tests submitted" and "Tests repository" columns is ok.

**Comment by ppigazzini** [comment]
@mrobaczyk [dev-server](https://dfts-0.pigazzini.it/users) with also the second column right aligned. 

```html
<table class="table table-striped table-condensed">
 <thead>
  <tr>
   <th>Username</th>
   <th style="text-align:right;">Last active</th>
   <th style="text-align:right;">Games/Hour</th>
   <th style="text-align:right;">CPU Hours</th>
   <th style="text-align:right;">Games played</th>
   <th style="text-align:right;">Tests submitted</th>
   <th>Tests repository</th>
  </tr>
 </thead>
 <tbody>
 %for user in users:
  <tr>
   <td>${user['username']}</td>
   <td style="text-align:right;">${user['last_updated']}</td>
   <td style="text-align:right;">${int(user['games_per_hour'])}</td>
   <td style="text-align:right;">${int(user['cpu_hours'])}</td>
   <td style="text-align:right;">${int(user['games'])}</td>
   <td style="text-align:right;"><a href="/tests/user/${user['username']}">${user['tests']}</td>
   <td><a href="${user['tests_repo']}" target="_blank">${user['tests_repo']}</a></td>
  </tr>
 %endfor
 </tbody>
</table>
```

**Comment by ppigazzini** [comment]
@tomtor @mrobaczyk  it works also with `style="text-align:right"`. The semicolon is mandatory?

**Comment by ppigazzini** [comment]
> Yes we can go this way, if you think that distance between "Tests submitted" and "Tests repository" columns is ok.

IMO with this PR the table is way more readable, "Tests submitted" are numbers and "Tests repository" are links, so to me the distance is OK.

**Comment by tomtor** [comment]
> The semicolon is mandatory?

No, it is not...

**Comment by tomtor** [comment]
It looks OK for me on the test server, so merging is fine with me.

**Comment by mrobaczyk** [comment]
I've updated the PR.

**Comment by mrobaczyk** [comment]
Ah, maybe you want to me to merge this into 1 commit. Let me know.

**Comment by ppigazzini** [comment]
@mrobaczyk yes, please, squash the commits

**Comment by ppigazzini** [comment]
Production server updated, thank you @mrobaczyk !

**Pull request merged**
