### PR TITLE
Fix finding and setting failed runs

### PR DESCRIPTION
**Pull request by linrock**
@ppigazzini this should fix https://github.com/glinscott/fishtest/pull/591#issuecomment-613667898

### CODE REVIEW

**Comment by ppigazzini** [comment]
@linrock the failed runs bug is fixed.

I found another bug: when at page 1, the "prev" button is grayed out but still clickable, page=0 triggers an Internal Server Error, see:
https://dfts-0.pigazzini.it/tests/user/xoto?page=0
https://dfts-0.pigazzini.it/tests?page=0

Green and LTC go to page=0 but without error
https://dfts-0.pigazzini.it/tests/finished?page=0&success_only=1

**Comment by linrock** [comment]
thanks for finding that.. working on a fix now

**Comment by linrock** [comment]
@ppigazzini that page=0 crash is fixed. i can also fix those greyed-out links too since they should not be clickable

**Comment by linrock** [comment]
@ppigazzini ok, those disabled pagination links are no longer clickable now, so users should no longer be able to go to page=0 pages from clicking

**Comment by ppigazzini** [comment]
PROD updated, thank you @linrock :)

**Pull request merged**
