### PR TITLE
Tests run redesign

### PR DESCRIPTION
**Pull request by dav1312**
Makes the page responsive
Tests in dev are encouraged, it has lots of changes

---

#### Default
image

#### Definitions on hover
image

image

#### SPSA Selected
image

#### SPSA Autoselect information modal
image

#### Mobile
image

image

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by dav1312** [comment]
> DEV updated.

I don't see any changes

**Comment by ppigazzini** [comment]
Typo in PR number, DEV updated with PR1402 too.

**Comment by ppigazzini** [comment]
@dav1312 rn the only problem found is with SPSA, "Missing required option: base_signature"
To queue a SPSA test you need to write the test and base signature as SPRT or Games test, then select SPSA tests.

**Comment by ppigazzini** [comment]
DEV running without this PR to tests other GUI PRs.

**Comment by ppigazzini** [comment]
DEV updated. With https://github.com/glinscott/fishtest/pull/1401/commits/c04edca407d82774e4a29ea60826d558fb7baf59 "SPRT" "Games" "SPSA" buttons stopped working.

**Comment by dav1312** [comment]
U merged my branch with the book fix PR and there is a conflict and u pushed that to DEV
image

**Comment by ppigazzini** [comment]
Thank you. DEV update only with this PR.

**Comment by ppigazzini** [comment]
SPSA submitted!
https://dfts-0.pigazzini.it/tests/view/63127081f532204cdb46af02

**Comment by vondele** [comment]
two comments:
1)
image
the little up and down buttons are not needed, the field is just used for copy and paste.
2)
After rescheduling a test, certain fields (like branch name) can't be modified. I believe that these immutable fields where greyed out in the past.

**Comment by dav1312** [comment]
> I believe that these immutable fields where greyed out in the past.

The style in that regard is the same as PROD. With light theme you can't realize that they are readonly, with dark theme u can. I can make it so it's easier to realize with the light theme too.
image

image

image

image

**Comment by ppigazzini** [comment]
Book depth works fine.

**Comment by ppigazzini** [comment]
PR applied by hand to PROD to collect feedbacks.

**Comment by snicolet** [comment]
Nice work, thanks! Three small comments for feedback:

0) same as Joost, in the Test signature boxes, the arrow will bring more problems than good. They should be removed (even if that means that the boxes become pure text rather than numerics).

1)  the "Info" text box should be bigger (4 lines)

2) green buttons styling: center text in the button, and resize the buttons to make them smaller => same size of button and font as the blue button.

**Comment by vondele** [comment]
BTW, one thing to consider (maybe not easy and maybe not part of the PR). 

It would be helpful if we could have buttons for the progression test (LTC, SMP), that automatically sets the right master (SF_15 right now), book, and things. It is not very critical, but right now it is some manual work to do that.

**Comment by dav1312** [comment]
> 1. They should be removed (even if that means that the boxes become pure text rather than numerics).

It can be done without changing them back to text, dw.
I'll remove them from the test signature but keep them in other places.

> the "Info" text box should be bigger (4 lines)

Okay. Keep in mind that you can resize it if need be.

> center text in the button, and resize the buttons to make them smaller

I personally don't like it over the current one

image

> buttons for the progression test

I already explored that option a few weeks ago but not setting the right master, just test type, time control, number of threads, book etc.

https://user-images.githubusercontent.com/63931154/188280350-ffc00028-ba1a-4afb-9ebe-69a24d7d59d0.mp4

**Comment by vondele** [comment]
>  I already explored that option a few weeks ago but not setting the right master, just test type, time control, number of threads, book etc.
looks good to me, hardcoding master and its bench would be helpful (that's what I have to look up in git log), I'm not sure it is worth the trouble to do it automatic.

**Comment by vondele** [comment]
> center text in the button, and resize the buttons to make them smaller

I would agree with making the font smaller, left-aligned or centered would both work for me, probably left-aligned is a bit more logical for that part of the page.

**Comment by ppigazzini** [comment]
LGTM on DEV, PROD updated by hand.

**Comment by vondele** [comment]
maybe something that can be addressed (or noted down). If one submits a test without bench, there will be an error message (` This commit has no signature: please supply it manually.`) and all input will be forgotten. Would be nice if that error message would come, but all content would be retained.

**Comment by snicolet** [comment]
@vondele I usually used "back" to get the inputs in this situation, maybe it still works (can't test it anymore on my Mac as fishtest is broken at the moment, see https://github.com/glinscott/fishtest/issues/1412)

**Comment by peregrineshahin** [comment]
Good job!
One thing I would add is it might look better if the font inside boxes is responsive to the screen size
Because some of the text is overhidden and large in the box for smaller mobile screens,

Also the blue color of submit button is a bit out of context as a fitting color for the whole design feel.

Cool design

**Comment by dav1312** [comment]
> font inside boxes is responsive to the screen size

Very hard to do properly and the text would need to be _too_ small in some cases.

**Comment by ppigazzini** [comment]
@dav1312 not complains from PROD. I will merge as soon as you will squash the commits.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @dav1312 :)

**Pull request merged**
