### PR TITLE
Make follow/unfollow atomic on platforms supporting web locks.

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by vdbergh** [comment]
Web locks are promises. They must be since javascript cannot block. So you must `await` for the lock. However this means that if you use web locks to protect a low level shared data structure, then virtually every function in your script must become async. Nothing wrong with that but it feels a bit strange.

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by vdbergh** [comment]
To my surprise it does not work. Following/unfollowing works correctly but no notifications are generated. I am drafting this.

**Comment by vdbergh** [comment]
I tried a quick fix (I seem to have misunderstood how web locks return values).

**Comment by vdbergh** [comment]
Working!

**Comment by vdbergh** [comment]
Web locks allow for an easy, fast and robust leader election. It seems tempting to go from the current distributed model (all tabs are equivalent) to a leader model where only the leader manages the shared state, communicates with the server and creates notifications. The other tabs communicate with the leader via a form of asynchronous message passing.

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
