### PR TITLE
Index on "finished" + "username".

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Review by ppigazzini — APPROVED** [review]
LGTM :)

https://dfts-0.pigazzini.it/tests/user/snicolet?page=7
https://dfts-0.pigazzini.it/tests/user/Vizvezdenec?page=5

**Comment by vdbergh** [comment]
Indexes are magic!

**Comment by vdbergh** [comment]
https://dfts-0.pigazzini.it/tests/user/Vizvezdenec?page=773 is still slow...

**Comment by vdbergh** [comment]
I guess the issue is that skip/limit is just slow on mongod. Even if the cursor comes from an index (covered query).

**Comment by ppigazzini** [comment]
LGTM :)

https://dfts-0.pigazzini.it/tests/user/snicolet?page=7
https://dfts-0.pigazzini.it/tests/user/Vizvezdenec?page=5


> I guess the issue is that skip/limit is just slow on mongod. Even if the cursor comes from an index (covered query).

https://medium.com/swlh/mongodb-pagination-fast-consistent-ece2a97070f3

**Comment by vdbergh** [comment]
The issue is not so much the paging (which can be sped up when paging sequentially) but the fact that we want random access (`?page=xxx`). 

Still it is a bit of a mystery why the paging of the main page is fast (even going to the last page). Perhaps this is because the cursor is the full index. It is conceivable that mongo has a special case solution for this.

**Comment by vdbergh** [comment]
If there is indeed such a special case then a dirty solution would be to use extra indexes for the few prolific users (there aren't that many).

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

(not easy to follow the discussion when playing with the PROD db)

**Comment by peregrineshahin** [comment]
Very substantial PR. Thank you vdbergh!

**Pull request merged**
