### PR TITLE
Make --fleet only quit the worker when no task is available (RFC).

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by noobpwnftw** [comment]
This will make fleet less efficient. Instead of waiting/looping on some transient failures, the workers can try other tasks and check fishtest again.

**Comment by vondele** [comment]
It would be nice to figure out what is causing this `  | failed task: task_id: 95, worker:  ChessDBCN-16cores-c477cb52, reason: 'This machine is too slow (235163.0  nps / thread) to run fishtest effectively - sorry!'` this nps is about 1/5 of what should be expected.

**Comment by noobpwnftw** [comment]
Probably some hardware error.

**Comment by vdbergh** [comment]
Unfortunately, as pointed out in #1284 the event log has been flooded with such messages for several months now https://tests.stockfishchess.org/actions?action=&user=&before=1653108833.342&count=100 . The event log is an important debugging tool and it is currently unusable. IMHO a solution should be found. Personally I think transient errors are very rare, hence this PR.

**Comment by noobpwnftw** [comment]
This does not prevent log flooding. It only makes the fishtest worker not quit on client side errors.

**Comment by noobpwnftw** [comment]
OTOH, why is it necessary to regenerate UUID for every worker invocation? If they can be persistent(which is already written to a file) then it will become easier to filter/find events from the particular machine.

**Comment by vdbergh** [comment]
> This does not prevent log flooding. It only makes the fishtest worker not quit on client side errors.

Normally it should prevent it as a delay is inserted before the worker asks for a new task. The delay is small in the beginning but it gets larger if the errors repeat (i.e. if the error is non transient).

**Comment by vdbergh** [comment]
> OTOH, why is it necessary to regenerate UUID for every worker invocation? If they can be persistent(which is already written to a file) then it will become easier to filter/find events from the particular machine.

The problem with preserving the UUID is that people create new workers by just copying the worker directory. So we would soon have distinct workers having the same UUID.

Some time ago I tried to push for a "worker fingerprint" (a hash of the configfile, the ethernet address and the directory of the worker) as a means of uniquely identifying workers. It was not perfect (it did not distinguish between google colab workers) but I would still favor that solution.

**Comment by noobpwnftw** [comment]
I found 2 workers that got throttled due to CPU overheat, probably after years of running and their thermal paste dried.
I've stopped those workers, event flooding seems ended.

It does not however reproduce at every bench, so I guess a longer sleep to cool the CPU will also fix the issue.

As for UUID, why is it a problem if someone did copy the entire worker directory and ends up with the same ID for workers? I think it is perfectly fine to tell them to remove not only this file but also the entire cached compiles due to possible different CPU arch.

**Comment by ppigazzini** [comment]
> As for UUID, why is it a problem if someone did copy the entire worker directory and ends up with the same ID for workers?

If I recall correctly fishtest should consider only one worker the workers with the same UUID and cores numbers in several places: log events, chi2, residuals etc.
The `api.log` in worker folder perhaps has info that help to find the faulty worker in a fleet.

image

**Comment by noobpwnftw** [comment]
But it has nothing to do with the necessity of generating UUID every launch, obviously there are more things to clean up for people copying the entire worker folder and run things properly than just the `uuid.txt`.

**Comment by vdbergh** [comment]
> But it has nothing to do with the necessity of generating UUID every launch, obviously there are more things to clean up for people copying the entire worker folder and run things properly than just the `uuid.txt`.

Unfortunately experience has shown that some people simply ignore all good practice instructions. Since multiple workers having the same UUID would be disastrous, we cannot run this risk.

This being said, being able to identify workers across restarts remains an important problem. I am now thinking that preserving only part of UUID might be a solution. In that way we cannot have distinct workers with the same UUID, but we would still be able to identity workers across restarts in the most common scenarios.

**Comment by vdbergh** [comment]
See #1352

**Comment by vdbergh** [comment]
Closing this for now.

**Pull request closed without merging**
