### PR TITLE
Make the worker calculate the pentanomial frequencies.

### PR DESCRIPTION
**Pull request by vdbergh**
This PR contains the worker changes. There are no server changes in this patch.

The updated worker will send the pentanomial frequencies
to the server and the server will faithfully store them in
its database as it does with all information received from
the client.

The actual logic added to the worker is quite minor.
A dictionary "rounds" keeps track of the finished games. For every
finished game pair (which consists of an odd numbered game
and the next even numbered game) the pentanomial frequencies
are updated.

Since sending incorrect frequencies to the server would
be quite disastrous, a lot of sanity checking is done to
make sure that the pentanomial frequencies are consistent
with the trinomial frequencies provided by cutechess itself.

### CODE REVIEW

**Comment by vdbergh** [comment]
I do not know why Travis CI fails. It fails on a server test and there are no server changes in this PR.

```
======================================================================
ERROR: test_users (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_users
Traceback (most recent call last):
  File "/opt/python/2.7.14/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/opt/python/2.7.14/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/glinscott/fishtest/fishtest/tests/test_users.py", line 8, in <module>
    from fishtest.views import signup
  File "/home/travis/build/glinscott/fishtest/fishtest/fishtest/views.py", line 6, in <module>
    import scipy.stats
  File "/home/travis/build/glinscott/fishtest/fishtest/.eggs/scipy-1.2.0-py2.7-linux-x86_64.egg/scipy/stats/__init__.py", line 367, in <module>
    from .stats import *
  File "/home/travis/build/glinscott/fishtest/fishtest/.eggs/scipy-1.2.0-py2.7-linux-x86_64.egg/scipy/stats/stats.py", line 173, in <module>
    from . import distributions
  File "/home/travis/build/glinscott/fishtest/fishtest/.eggs/scipy-1.2.0-py2.7-linux-x86_64.egg/scipy/stats/distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "/home/travis/build/glinscott/fishtest/fishtest/.eggs/scipy-1.2.0-py2.7-linux-x86_64.egg/scipy/stats/_continuous_distns.py", line 3345
SyntaxError: Non-ASCII character '\xe2' in file /home/travis/build/glinscott/fishtest/fishtest/.eggs/scipy-1.2.0-py2.7-linux-x86_64.egg/scipy/stats/_continuous_distns.py on line 3346, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
======================================================================
ERROR: test_run (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_run
Traceback (most recent call last):
  File "/opt/python/2.7.14/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/opt/python/2.7.14/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/glinscott/fishtest/fishtest/tests/test_run.py", line 4, in <module>
    from fishtest.views import get_master_bench
  File "/home/travis/build/glinscott/fishtest/fishtest/fishtest/views.py", line 6, in <module>
    import scipy.stats
  File "/home/travis/build/glinscott/fishtest/fishtest/.eggs/scipy-1.2.0-py2.7-linux-x86_64.egg/scipy/stats/__init__.py", line 367, in <module>
    from .stats import *
  File "/home/travis/build/glinscott/fishtest/fishtest/.eggs/scipy-1.2.0-py2.7-linux-x86_64.egg/scipy/stats/stats.py", line 173, in <module>
    from . import distributions
  File "/home/travis/build/glinscott/fishtest/fishtest/.eggs/scipy-1.2.0-py2.7-linux-x86_64.egg/scipy/stats/distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "/home/travis/build/glinscott/fishtest/fishtest/.eggs/scipy-1.2.0-py2.7-linux-x86_64.egg/scipy/stats/_continuous_distns.py", line 3345
SyntaxError: Non-ASCII character '\xe2' in file /home/travis/build/glinscott/fishtest/fishtest/.eggs/scipy-1.2.0-py2.7-linux-x86_64.egg/scipy/stats/_continuous_distns.py on line 3346, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by ppigazzini** [comment]
@vdbergh in the weekend I will raise the worker version to 68 to push the bugfix #359 . Please raise the worker version for this PR to be sure that the workers joining the dev server are using the right code, something as 555 or 12345 should make the work.

**Comment by vdbergh** [comment]
@ppigazzini 

Will do when I make the last pentanomial patches (tomorrow I have my development laptop back).

**Comment by ppigazzini** [comment]
@vdbergh Ok. I'm resetting the dev-server to test the updater code. Anyway I took a backup of the db with the pentanomial tests.

**Comment by ppigazzini** [comment]
@vdbergh I tried to solve the conflict about the worker version number in order to start the dev-server with all the pentanomial PRs. The dev-server started fine, but GitHub still shows that cannot performs a "Rebase and merge".

**Comment by ppigazzini** [comment]
@vdbergh I used the GitHub web interface to resolve the conflict supposing to simply add a commit. Instead in that way I performed a merge with the master. Now the "Rebase and merge" button is disabled due to conflicts. I can only proceed with a "Merge" (but in this way the commit will be with my name) and "Squash and merge" (never performed, I don't know the result).
A solution could be to close this PR, and open a new PR (please verify that I haven't poisoned your local branch with the merge before open a new PR).

**Comment by Alayan-stk-2** [comment]
@vdbergh What's the status with these PRs ? All your pentanomial frequency code looked interesting and promising, but you've not given any update about them since february.

@ppigazzini For your information: squash and merge makes a single new commit based on all the commits in the PR. GitHub will mark you as having done the squashing but the commit will be attributed to the author of the merged commits. If there are several of them, GitHub makes a commit comment containing the commit messages. Squash and merge is the most common procedure we use to merge PRs for STK.

**Comment by vdbergh** [comment]
The PR are functionally complete (and well tested). However I started to
write documentation about the formulas that are used. Sadly work
obligations got in the way and I had to put the project aside for a while.

I plan to finish it in the summer.

**Comment by ppigazzini** [comment]
@Alayan-stk-2 I haven't deep knowledge of GitHub functions. It's better that user that opened the PR will squash the commits and will write the final commit message.

**Comment by ppigazzini** [comment]
@vdbergh let me know when the pentanomial PRs are ready to be merged. Remember also that this PR has some conflicts to be solved before a 'Rebase and Merge'

**Comment by Alayan-stk-2** [comment]
@vdbergh Any news on when you might be able to finish those ?

**Comment by ppigazzini** [comment]
@vdbergh @tomtor The pentanomial analysis will start working only with all updated workers, so this time we should raise asap the worker version at server side (ie after the noob and dew fleets update by hand) enforcing the automatic update for all workers.

@snicolet I would like to add at this worker version raise also the PRs with the new repo for books&binaries (https://github.com/glinscott/fishtest/pull/471) and the new default book for the tests (https://github.com/glinscott/fishtest/pull/472), please review the PRs at books repo:
https://github.com/official-stockfish/books/pull/1
https://github.com/official-stockfish/books/pull/2
and let me know if you want some changes.

**Pull request merged**
