### PR TITLE
Record excessive crashes and time losses in the event log.

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by vdbergh** [comment]
Looking at DEV. I am noticing that time losses in failed tasks are not taken into account. I'll make this PR draft for the time being.

**Comment by ppigazzini** [comment]
DEV updated, started some expected fail/pass tests and some good/bad workers.

**Comment by vdbergh** [comment]
It seems time losses is two words. I changed it in the latest push.

**Comment by ppigazzini** [comment]
DEV update.

**Comment by vdbergh** [comment]
I wonder how you create so many time losses. I tried with TC 0.1 (sudden death) and no adjudications and still I got almost no time losses (0.1%). I had to instrument the code to test this.

**Comment by ppigazzini** [comment]
Dual Xeon running the worker with msys2.

**Review by ppigazzini — APPROVED** [review]
LGTM

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
