### PR TITLE
Style changes

### PR DESCRIPTION
**Pull request by dav1312**
Redesign the nn upload page and make it mobile friendly
Reorder test inputs and add some placeholders

Note: in the future the tests_run page would need to be entirely redesigned too

### CODE REVIEW

**Comment by vondele** [comment]
The style changes look good to me, I wonder if this could influence the script that I use to automatically upload the nets 'bypassing' the website? If not the change is fine with me.

**Comment by ppigazzini** [comment]
@vondele Feel free to try to upload a fake net: I can delete the net from the DB and from the net server.

**Comment by vondele** [comment]
later today, I've plenty of not-so-fake nets.

**Comment by vondele** [comment]
works for me

**Comment by ppigazzini** [comment]
PROD updated, thank you @vondele for the review/test and thank you @dav1312 for the patch :)

**Pull request merged**
