### PR TITLE
Remove statistics updates

### PR DESCRIPTION
**Pull request by Chess13234**
Remove the display of "Update user statistics" in action log.
They just waste space and provide nothing useful.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor we have now the logs in the mail, so perhaps we could avoid to save this information in the DB (and clean the DB)

**Comment by ppigazzini** [comment]
@Chess13234 anyway this PR breaks
https://dfts-2.pigazzini.it/actions

```
Jan 09 11:49:32 vps1572612706 pserve[19806]: 2020-01-09 11:49:32,039 ERROR [waitress][waitress] Exception while serving /actions
Jan 09 11:49:32 vps1572612706 pserve[19806]: Traceback (most recent call last):
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
Jan 09 11:49:32 vps1572612706 pserve[19806]:     response = request.invoke_exception_view(exc_info)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 779, in invoke_exception_view
Jan 09 11:49:32 vps1572612706 pserve[19806]:     raise HTTPNotFound
Jan 09 11:49:32 vps1572612706 pserve[19806]: pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
Jan 09 11:49:32 vps1572612706 pserve[19806]: During handling of the above exception, another exception occurred:
Jan 09 11:49:32 vps1572612706 pserve[19806]: Traceback (most recent call last):
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/channel.py", line 349, in service
Jan 09 11:49:32 vps1572612706 pserve[19806]:     task.service()
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 169, in service
Jan 09 11:49:32 vps1572612706 pserve[19806]:     self.execute()
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 439, in execute
Jan 09 11:49:32 vps1572612706 pserve[19806]:     app_iter = self.channel.server.application(environ, start_response)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/proxy_headers.py", line 65, in translate_proxy_headers
Jan 09 11:49:32 vps1572612706 pserve[19806]:     return app(environ, start_response)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
Jan 09 11:49:32 vps1572612706 pserve[19806]:     response = self.execution_policy(environ, self)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 279, in default_execution_policy
Jan 09 11:49:32 vps1572612706 pserve[19806]:     return request.invoke_exception_view(reraise=True)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 778, in invoke_exception_view
Jan 09 11:49:32 vps1572612706 pserve[19806]:     reraise_(*exc_info)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Jan 09 11:49:32 vps1572612706 pserve[19806]:     raise value
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 277, in default_execution_policy
Jan 09 11:49:32 vps1572612706 pserve[19806]:     return router.invoke_request(request)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
Jan 09 11:49:32 vps1572612706 pserve[19806]:     response = handle_request(request)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
Jan 09 11:49:32 vps1572612706 pserve[19806]:     response = _error_handler(request, exc)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
Jan 09 11:49:32 vps1572612706 pserve[19806]:     reraise(*exc_info)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Jan 09 11:49:32 vps1572612706 pserve[19806]:     raise value
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
Jan 09 11:49:32 vps1572612706 pserve[19806]:     response = handler(request)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
Jan 09 11:49:32 vps1572612706 pserve[19806]:     registry, request, context, context_iface, view_name
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
Jan 09 11:49:32 vps1572612706 pserve[19806]:     response = view_callable(context, request)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
Jan 09 11:49:32 vps1572612706 pserve[19806]:     result = view(context, request)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
Jan 09 11:49:32 vps1572612706 pserve[19806]:     response = view(request)
Jan 09 11:49:32 vps1572612706 pserve[19806]:   File "/home/usr00/fishtest/fishtest/fishtest/views.py", line 222, in actions
Jan 09 11:49:32 vps1572612706 pserve[19806]:     item['run'] = action['data']['args']['new_tag']
Jan 09 11:49:32 vps1572612706 pserve[19806]: TypeError: string indices must be integers
```

**Comment by Chess13234** [comment]
@ppigazzini Sorry(i can't test fishtest locally),i assumed its purely stopping handling these updates.

 Why is it needed at all?
 It provides nothing useful for people viewing the log, it just shows just repeat messages "fishtest.system Update user statistics"?

**Comment by ppigazzini** [comment]
@Chess13234 it was used to measure the execution time of the `delta_update_users.py` scheduled script, view #393 (and following PRs). But now we have the same information with the date/time of the mail sent to the server.

In this [wiki page](https://github.com/glinscott/fishtest/wiki/Fishtest-server-setup) you find the scripts:
* to setup a development fishtest server in a VM/container
* to update the server with the branch/PR to be tested
* to run a worker with the branch/PR to be tested

**Comment by Chess13234** [comment]
@ppigazzini I use MXLinux, it has no systemd
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Comment by ppigazzini** [comment]
@Chess13234 I suggest to use a vm/container. I use lxd/lxc on ubuntu and hyper-v on windows to setup the server in an ubuntu 18.04 vm.

**Pull request closed without merging**
