### PR TITLE
PR3: Directly write to the actiondb using the new schema.

### PR DESCRIPTION
**Pull request by vdbergh**
The actiondb now has a well defined schema which is checked before insertions. This should facilitate debugging.
    
The script: utils/convert_actions.py deletes superfluous data from the actiondb. This should save a lot of space.
    
Note that the database still contains enough information to reconstruct the deleted data.
    
 No user visible changes.

### CODE REVIEW

**Comment by vdbergh** [comment]
I made this WIP since I think it needs to be refactored a bit more.

**Comment by ppigazzini** [comment]
> I made this WIP since I think it needs to be refactored a bit more.

GitHub has introduced the "draft" status. In that way nobody can erroneously merge the PR until the status is switched back to "ready for review", see:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

**Comment by vdbergh** [comment]
Thanks!

**Comment by vdbergh** [comment]
Unwipped and undrafted!

**Comment by ppigazzini** [comment]
DEV updated!

**Comment by ppigazzini** [comment]
Events seems registered correctly, logs clean.

**Comment by vdbergh** [comment]
I retested all events on DEV except `upload_nn` since I cannot generate a new nn.  But I did test this locally.

**Comment by ppigazzini** [comment]
`upload_nn` works, see https://dfts-0.pigazzini.it/actions?max_actions=1&before=1670926794.616

for future reference:
```bash
#!/bin/bash
dd if=/dev/urandom of=nn.nnue bs=1MiB count=16
nn_sha=$(sha256sum nn.nnue)
mv nn.nnue nn-${nn_sha:0:12}.nnue
```

**Comment by vdbergh** [comment]
> `upload_nn` works, see https://dfts-0.pigazzini.it/actions?max_actions=1&before=1670926794.616
> 
> for future reference:
> 
> ```shell
> #!/bin/bash
> dd if=/dev/urandom of=nn.nnue bs=1MiB count=16
> nn_sha=$(sha256sum nn.nnue)
> mv nn.nnue nn-${nn_sha:0:12}.nnue
> ```

Yes I know but I was a afraid that the fake nn would find its way to the cdn. I guess this is not the case then.

**Comment by ppigazzini** [comment]
The nn file is uploaded on DEV, courtesy of the server setup script.

```
# set secrets
sudo -i -u ${user_name} << EOF
echo '' > fishtest.secret
echo '' > fishtest.captcha.secret
echo 'http://127.0.0.1/upload_net' > fishtest.upload
```

The download of the nn is from the cdn as default, but there is a script to switch back and forth with DEV.

**Comment by vdbergh** [comment]
Ok. Thanks anyway for testing!

**Review by ppigazzini — APPROVED** [review]
`purge_run` finally tested :)
https://dfts-0.pigazzini.it/actions?max_actions=1&before=1670931593.383

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
