### PR TITLE
Prepare for PGO builds with hybrid bench

### PR DESCRIPTION
**Pull request by vondele**
Download net before building, copy from cache if possible

### CODE REVIEW

**Comment by vondele** [comment]
seems to work OK with my worker on https://dfts-0.pigazzini.it/tests/view/5f2fcdc5deeb34d9b11e4d2b

**Comment by ppigazzini** [comment]
@vondele please let me know how test the effect of this PR

**Comment by vondele** [comment]
First, workers should just behave, no crash when they run with this patch, on all tests.

Second, this needs to test on the above test which enables the hybrid bench & PGO. In that case the first step of the build (make net) should reply with
```
Default net: nn-[...].nnue
Already available.
```
What the patch does is trying to make sure it is not the `make net` part of the build that downloads the net, but the python code. The latter is smarter in that it uses the cache of nets in the testing directory, and uses the proxy of the server if the worker is configured to do so.

**Comment by vondele** [comment]
@ppigazzini if your testing looks OK, let's go for it :-)

**Comment by ppigazzini** [comment]
@noobpwnftw I merged several worker PRs and raised the version number, please update the fleet at your convenience :)

**Comment by ppigazzini** [comment]
Thank you @vondele :)

**Comment by vondele** [comment]
OK, I'll merge the PGO patch in master once @noobpwnftw has updated the fleet. After that, next RT.

**Comment by noobpwnftw** [comment]
@ppigazzini @vondele I started rolling updates, there are a few workers that are currently down and unable to update, will send people there. Looks like the fleet will be fully updated by tomorrow.

**Comment by vondele** [comment]
OK, I might start the test before, once a good fraction has updated. The only side effect is that there will be a call to the net download api without using the proxy for every new binary built. If that's no problem, all is fine.

**Comment by noobpwnftw** [comment]
@vondele That is fine as long as failed downloads will be handled. Direct connections to API is not very smooth on my workers.

**Comment by vondele** [comment]
@ppigazzini the worker fleet has been updated, time to enforce the worker level change via the server... this should take some of the strain of the dataserver, and reduce the number of downloads. Current net has been downloaded 54231 times...

**Comment by ppigazzini** [comment]
@vondele done

**Comment by ppigazzini** [comment]
@vondele however a big percentage of the workers is already updated to version 84 so we should check if the caching system is working fine.

**Comment by vondele** [comment]
yes, I agree, it is surprisingly large.

**Comment by vondele** [comment]
the number of downloads of the new default net seems very reasonable now. I think the caching system is working after the enforced worker update.

**Pull request merged**
