### PR TITLE
Use the new unzip function to refactor downloading engine files a bit

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by ppigazzini** [comment]
Triggered the workers update, thank you @vdbergh :)

ps: it's not easy to merge the PRs from the GitHub GUI (conflict for the sri.txt files and new sri.txt after raising the version), so I'm rebase-merging from the command line.

**Comment by vdbergh** [comment]
> Triggered the workers update, thank you @vdbergh :)
> 
> ps: it's not easy to merge the PRs from the GitHub GUI (conflict for the sri.txt files and new sri.txt after raising the version), so I'm rebase-merging from the command line.

I am sorry to hear this. I wonder if there is a way to make the process easier.

**Comment by ppigazzini** [comment]
It's not a problem for me. But on Discord have pointed out the force push to master to add "closes https://github.com/glinscott/fishtest/pull/1457" with "git commit --amend" (after only 30 seconds).
Usually the PR is auto closed if the commit is merged, but with the conflict this PR stayed opened.

**Comment by ppigazzini** [comment]
BTW this the process (the raise of the worker version and the new sri.txt are needed in any case):

```
git checkout master
git fetch -p upstream/master
git reset --hard upstream/master
git fetch -p vdbergh
git checkout -b zipball vdberg/zipball
# resolve conflicts with "git rebase -i master", raise the worker version, generate the sri.txt with "python3 worker.py a a --only_config --no_validation"
git commit -a -m "Raise worker version" -m "closes #1457"
# I could squash with "git rebase -i master" to make the changes yours
git diff master
git push upstream HEAD:master
```

**Pull request closed without merging**
