### PR TITLE
test params for SPSA (> 0)

### LINKED ISSUE #751: possible server issue?
https://groups.google.com/g/fishcooking/c/mIcaW7daom8/m/RlcwnACdBQAJ

also worker count indeed low.

### PR DESCRIPTION
**Pull request by tomtor**
Fix #751

### CODE REVIEW

**Comment by tomtor** [comment]
@ppigazzini I tested and applied this on prod

**Comment by ppigazzini** [comment]
@tomtor let me know if the test is ok

**Comment by tomtor** [comment]
@ppigazzini Yes, it's ok

**Comment by ppigazzini** [comment]
Tested OK also on DEV, PROD updated, thank you @tomtor :)

**Pull request merged**
