### PR TITLE
Remove the download of engine binaries

### PR DESCRIPTION
**Pull request by ppigazzini**
Remove the download of the engine binaries:
 - the central engines builder is not used anymore
 - there are simple instructions to install a compiler in windows and linux workers

 - [X] ToDo: simplify the code server side

### CODE REVIEW

**Comment by glinscott** [comment]
This would need to bump the worker version as well.

**Comment by Stefano80** [comment]
Ops, we could have add to the worker update PR.

**Comment by ppigazzini** [comment]
@Stefano80 I will check also for windows builder code on the server side.

**Comment by Stefano80** [comment]
Ok, I wait for your feedback

**Comment by ppigazzini** [comment]
@Stefano80 opened the server side clean up https://github.com/glinscott/fishtest/pull/198

**Comment by Stefano80** [comment]
Cool, did you try recently this on the dev server? If you update a file different from worker.py do we need to update the worker version?

**Comment by ppigazzini** [comment]
@Stefano80 this is a worker change, so can be tested switching thw worker.py locally and connecting the worker to the dev server or the official server.
I tested the PR 11 months ago, but to be sure I will test it it tonight with a couple of workers (linux and windows).

**Comment by ppigazzini** [comment]
@Stefano80 tested successfully

**Comment by Stefano80** [comment]
Merged. Will restart the server as soon as I have merged some more of them.

**Pull request merged**
