### PR TITLE
Remove most console.log messages.

### PR DESCRIPTION
**Pull request by vdbergh**
Also: fix possible race. Currently if the browser sleeps after fetching and before purging (unlikely, but...) then some notifications may be lost.

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
PROD updated by hand.

**Comment by vdbergh** [comment]
Thanks! Is it possible to keep it on DEV for a bit? I created a stale notification and I am waiting for it to be purged!

**Comment by ppigazzini** [comment]
Yes, I'm playing on my PC with the new pyramid configuration.

**Comment by vdbergh** [comment]
Works!

**Comment by vdbergh** [comment]
Latest push was just a small tweak.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
