### PR TITLE
Single click SMP tests

### PR DESCRIPTION
**Pull request by vondele**
add single click SMP options.
8 threads, 5+0.05, 64Mb
8 threads, 20+0.2, 256Mb

fixes https://github.com/glinscott/fishtest/issues/384

Untested.... copy&paste from similar code around, would need a careful check.

No so urgent either.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@vondele [DEV](https://dfts-0.pigazzini.it/tests) updated, it seems work fine.
Please make a double check.
user01:user01 (normal)
user00:user00 (approver)

**Comment by vondele** [comment]
@ppigazzini thanks .. functionality seem to be OK. I've added one more commit to move this up, closer to the branch. It sets more than just TC, and it is convenient to have it around. It seems a trivial change, but maybe better have a second look.

**Comment by vondele** [comment]
let me squash it first...

**Comment by ppigazzini** [comment]
DEV updated, it seems OK, please double check.

**Comment by vondele** [comment]
looks good to me.

**Comment by ppigazzini** [comment]
I will updated PROD as soon as it will be on line, thank you @vondele :)

**Pull request merged**
