### PR TITLE
Make incomplete chunks pending on modify

### PR DESCRIPTION
**Pull request by tomtor**
Without this fix stopping and restarting run by 'modify' will fail to complete unfinished tasks.

See: http://tests.stockfishchess.org/tests/view/5b003e690ebc5914abc12641

### CODE REVIEW

**Comment by ppigazzini** [comment]
dev-server and workers updated to test this.

**Comment by tomtor** [comment]
@ppigazzini It had an error, can you please redeploy it, so I can test it again?

**Comment by ppigazzini** [comment]
@tomtor redeployed with a clean copy of the DB, only this PR merged.

**Comment by tomtor** [comment]
@ppigazzini I retested locally and it works fine...

**Comment by ppigazzini** [comment]
@tomtor I rebuilded the VM, reinstalled the server using the setup script, copied a fresh DB, merged the #302, started some workers.

```
$ rpm --query centos-release
centos-release-7-5.1804.el7.centos.2.x86_64

$ mongo --version
MongoDB shell version v3.6.4
git version: d0181a711f7e7f39e60b5aeb1dc7097bf6ae5856
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel70
    distarch: x86_64
    target_arch: x86_64

$ python
Python 2.7.5 (default, Apr 11 2018, 07:36:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2

$ pip list --format freeze
backports.ssl-match-hostname==3.5.0.1
boto==2.48.0
certifi==2018.4.16
chardet==3.0.4
configobj==4.7.2
decorator==3.4.0
fishtest-server==0.1
hupper==1.2
idna==2.6
iniparse==0.4
ipaddress==1.0.16
Mako==1.0.7
MarkupSafe==1.0
nose==1.3.7
numpy==1.7.1
PasteDeploy==1.5.2
perf==0.1
pip==10.0.1
plaster==1.0
plaster-pastedeploy==0.5
pycurl==7.19.0
Pygments==2.2.0
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
pymongo==3.6.1
pyramid==1.9.2
pyramid-debugtoolbar==4.4
pyramid-mako==1.0.2
python-linux-procfs==0.4.9
pyudev==0.15
pyxattr==0.5.1
pyzmq==14.3.1
repoze.lru==0.7
requests==2.18.4
schedutils==0.4
scipy==0.12.1
setuptools==39.2.0
six==1.9.0
slip==0.4.0
slip.dbus==0.4.0
translationstring==1.3
urlgrabber==3.10
urllib3==1.22
venusian==1.1.0
waitress==1.1.0
WebOb==1.8.1
wheel==0.31.1
yum-metadata-parser==1.1.4
zope.deprecation==4.3.0
zope.interface==4.5.0
```

**Comment by ppigazzini** [comment]
@tomtor dev-server and workers updated with #300 #302 #305 #306

**Comment by tomtor** [comment]
@ppigazzini Thanks! PR is OK now...

**Pull request merged**
