### PR TITLE
Various changes to games result box

### PR DESCRIPTION
**Pull request by tomtor**
Followup to https://github.com/glinscott/fishtest/pull/225

- Make the box variable size and as small as possible without overflow
- Add some more info to Pending runs (SPRT bounds)
- Link to Live ELO page for SPRT runs

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor @Stefano80 @vondele
[dev-server](http://94.198.98.239/tests)
[official](http://tests.stockfishchess.org/tests)

**Comment by ppigazzini** [comment]
On the page of the individual test the box length seems to take always half page.

**Comment by tomtor** [comment]
@vondele Regarding the box on individual pages, we have a few options:
- Original the colored box was span4 (halve of the detail section below it which is span8)
- I made it span6 so that it is bigger (current version on dev server)
- We can make it span8, so it is as wide as the detail section
- We can drop the span so it will extend over the whole page width (span11, the menu bar on the left is span1), so it is also above the "Actions" header

I personally prefer span8 or complete width

**Comment by tomtor** [comment]
image

**Comment by tomtor** [comment]
image

This is a bit too much, so span8 (previous image) looks best?

**Comment by tomtor** [comment]
@ppigazzini Yes, that's correct, it's currently always halve the page. The last option is that I make it as small as possible...

**Comment by vondele** [comment]
my taste would be span8 (i.e. as the details section) or as small as possible. But I don't have too strong preferences.

**Comment by tomtor** [comment]
Ok, I am going for the as small as possible option for consistency with the main view. Also made some more room for the test comment section, by making TC slightly smaller and minimizing space for the approve/delete buttons. @ppigazzini Perhaps good to have this latest squashed version on the dev server for a final evaluation?

**Comment by ppigazzini** [comment]
@tomtor @Stefano80 @vondele : dev server updated. To me seems OK.
[dev-server](http://94.198.98.239/tests)
[official](http://tests.stockfishchess.org/tests)

**Comment by tomtor** [comment]
@vdbergh Hi Michel, I inspected your nice live_elo.js script which has this regexp:

        var sprt=/>LLR: [0-9\-\.]* \([0-9\-\.,]*\) \[[0-9\-\.,]*\]\s*Total: [0-9]* W: ([0-9]*) L: ([0-9]*) D: ([0-9]*)<\/pre>/g;

which will no longer match after this PR because `\s*` will not match the `<br/>` and some extra whitespace has been added.

        var sprt=/>\s*LLR: [0-9\-\.]* \([0-9\-\.,]*\) \[[0-9\-\.,]*\].*Total: [0-9]* W: ([0-9]*) L: ([0-9]*) D: ([0-9]*)\s*<\/pre>/g;

should match both old and new HTML. Could you adapt your script?

Related to this, are you interested in making your live_elo script an integral part of fishtest (by a PR) or would you object if I did that by copying your code? That would allow showing the info as part of an individual test page or showing a compact version on the main page for running tests.

**Comment by tomtor** [comment]
@vdbergh I made a branch with a copy, hope you don't mind: 

https://github.com/tomtor/fishtest/tree/LiveELO

**Comment by Stefano80** [comment]
That would be a great enhancement!

**Comment by snicolet** [comment]
Two small ideas for improvement:

• the yellow box itself could be clickable, linking to the LiveElo page. I think technically it would be sufficient to add a `<div></div>` around the yellow box, and a link around that : `<a href="blah"> <div></div> </a>`  is valid HTML5. And if we have that, we could reuse it everywhere, including from the overview page.

• For "Pending.." patches, it seems to me that the displayed delay (1 hour....) is not very useful info, maybe we could replace it with the SPRT bounds of the pending patch?

**Comment by Stefano80** [comment]
I agree with the second suggestion. For the first one we have to see how be it looks like.

**Comment by vdbergh** [comment]
@tomtor No I certainly don't mind! I have always realized that screen scraping is very fragile. However at the time I wrote live_elo.html there was no other option since fishtest development had stalled.

I have no time to maintain this now, so please make any changes you want!

**Comment by tomtor** [comment]
@vdbergh Thanks! One more question: sprt_elo.js is asm.js code generated by emscripten from a C source. Do you have link to this source?

**Comment by vdbergh** [comment]
This is the source code for the C++ version.

http://hardy.uhasselt.be/Toga/live_elo.tar.gz

If you want to run it on the server then it might also consider using the python version

http://hardy.uhasselt.be/Toga/sprt_elo.tar.gz

**Comment by Stefano80** [comment]
Is this done?

**Comment by tomtor** [comment]
Yes, it is done, but it is not evaluated on the dev server yet.

**Comment by ppigazzini** [comment]
Started the test on the dev server.

**Comment by tomtor** [comment]
@ppigazzini Strange, it looks different from my test server (missing gauge and LLR bounds from pending), but auto refresh and box size are OK:

screenshot from 2018-04-13 11-12-47

**Comment by ppigazzini** [comment]
@tomtor dev-server updated. I prefer only compact text information, but this is just me.

**Comment by tomtor** [comment]
@ppigazzini Yes, that's why it is important to get feedback first. How do you feel about the auto refresh, perhaps both should be options for the user to switch on/off?

**Comment by tomtor** [comment]
@ppigazzini In addition the box is too high when no gauge is shown. @vondele @Stefano80 What do you think about auto-refresh and gauges?

**Comment by ppigazzini** [comment]
@tomtor I am not a typical fishtest user, so my preference should not be kept in consideration on this topic.

**Comment by tomtor** [comment]
The auto refresh can be disturbing when the layout changes and you want to click somewhere. The best option would be to refresh only the active game info boxes by using a run_info API which we also need for the other big live ELO display.  I will work some more on this of there is interested in a live update in the first place on this overview...

**Comment by vondele** [comment]
@tomtor , the gauge on the main page is not really my taste (also the llr is already available, so if a gauge, I'd go for elo), will be confusing if we have 10 active tests. However, integrating the 'live_elo' page in the page of the individual test (as opposed to an extra page) would be something neat. On that page, autorefresh would be nice as well. Just my 2 cents of course.

**Comment by tomtor** [comment]
I removed the auto refresh (don't like the current restless implementation) and fixed the layout for active runs without gauge.
Regarding the gauges, I like that I can see the LLR state of various tests at a glance but without automatic updates that is a bit less usefull.

**Comment by tomtor** [comment]
Ok, I squashed and disabled the gauge. For me it is ok to merge, perhaps I will reenable it in the future with dynamic updates and eg showing (also) ELO.

**Comment by ppigazzini** [comment]
Tested working on the dev server. Official server updated.
Thank you @tomtor

**Pull request merged**
