### PR TITLE
Fixes some issues with test submission. Including #652.

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated

- this works:
https://github.com/glinscott/fishtest/blob/a4bd1fc89118c9ab12fa71c031a0e9a1ad2cd69c/fishtest/fishtest/views.py#L343-L344
- I don't know how to trigger this, please try yourself and let me know if it works:
https://github.com/glinscott/fishtest/blob/a4bd1fc89118c9ab12fa71c031a0e9a1ad2cd69c/fishtest/fishtest/views.py#L361-L363

**Comment by vdbergh** [comment]
@ppigazzini You can trigger it by for example blanking out the tc field.

**Comment by ppigazzini** [comment]
@vdbergh thank, it works.
However the true problem it's that the signature auto complete isn't working anymore in master for all test types (SPRT, Fixed, SPSA).

**Comment by vdbergh** [comment]
Actually I am getting 

`Invalid URL '/commits/master': No schema supplied. Perhaps you meant http:///commits/master?`

I have no idea where this comes from.

**Comment by vdbergh** [comment]
@ppigazzini  The latest master has no signature. So the error message you are getting is correct.

**Comment by ppigazzini** [comment]
> Actually I am getting
> 
> `Invalid URL '/commits/master': No schema supplied. Perhaps you meant http:///commits/master?`
> 
> I have no idea where this comes from.

@vdbergh I switched DEV back and forth from master and PR, perhaps this disrupted your test, try now (DEV is running the PR).
I thought that the signature was mandatory in Stockfish commits. I will check if fishtest is able to work fine without a base/test signature.

**Comment by vdbergh** [comment]
I had to logout and login again to get rid of the message 

`Invalid URL '/commits/master': No schema supplied. Perhaps you meant http:///commits/master?`

This points to another bug (but not this PR since it didn't change anything in the way the Github api is invoked).

**Comment by vdbergh** [comment]
Ah messages crossed. Perhaps it was not logout/login then that fixed it. It should still be understood though.

**Comment by tomtor** [comment]
> Ah messages crossed. Perhaps it was not logout/login then that fixed it. It should still be understood though.

You will get that message in `get_sha` when `data['tests_repo']` is empty:
https://github.com/glinscott/fishtest/blob/a4bd1fc89118c9ab12fa71c031a0e9a1ad2cd69c/fishtest/fishtest/views.py#L375

**Comment by vdbergh** [comment]
Thanks. I now catch the exception and give slightly less cryptic message.

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
@vondele for any SF commit without signature a fishtest tester takes a scare. If possible please make the signature mandatory :)

**Pull request merged**
