### PR TITLE
Add AVX-VNNI support to workers.

### PR DESCRIPTION
**Pull request by gcp**
Add AVX-VNNI support for Alder Lake and later.

Corresponding pull request for Stockfish itself:
https://github.com/official-stockfish/Stockfish/pull/3824

### CODE REVIEW

**Comment by gcp** [comment]
Not sure how to test this though.

**Comment by ppigazzini** [comment]
You can use this script (Linux, WSL2, msys2) to test with DEV https://dfts-0.pigazzini.it

The script uses `python3 -m venv`

```bash
#!/bin/bash
dir_num=${1:-'00'}
usr_pwd=${2:-'user00'}
test_folder="${HOME}/_git/__test_folder${dir_num}"
virtual_env="${test_folder}/fishtest/worker/env"
fish_host=dfts-0.pigazzini.it

rm -rf "${test_folder}"
mkdir -p "${test_folder}"
cd "${test_folder}"
git clone --single-branch --branch master https://github.com/glinscott/fishtest.git
cd "${test_folder}/fishtest"
git config user.email "you@example.com"
git config user.name "your_name"

# add here the PRs to be tested
git pull --no-edit --rebase origin pull/1178/head

cd "${test_folder}"/fishtest/worker
python3 -m venv "${virtual_env}"
"${virtual_env}"/bin/python3 -m pip install --upgrade pip setuptools wheel
"${virtual_env}"/bin/python3 -m pip install requests

"${virtual_env}"/bin/python3 worker.py ${usr_pwd} ${usr_pwd} --host ${fish_host} --concurrency 3
```

**Comment by vondele** [comment]
thanks looks good.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
Merged and triggered the workers update, thank you @gcp :)
https://github.com/glinscott/fishtest/blob/1c30a584d4680fc036ba851d0baa8b20b52d4bf8/AUTHORS#L15

**Pull request closed without merging**
