### PR TITLE
Make sure Back button reloads the tests page

### LINKED ISSUE #1405: "back" does not restore the button state
Steps to trigger

- Make sure that the default state of the "Finished" button is "Show" (i.e. the content of the corresponding div is hidden).

- Press the "Finished" button. The state now becomes "Hide" and the content of the div becomes visible.

- Click on one of the tests in the div.

- Press the browser back button. The state of the "Finished" button is again "Show" (the content of the div is hidden).

EDIT:

- If we then reload the page, the state becomes "Hide" again. So the cookie was set correctly.

### PR DESCRIPTION
**Pull request by peregrineshahin**
More details in the issue comments
Fixes #1405

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
On Windows only Edge shown the problem (Chrome, Opera, Firefox were fine).
With the PR on DEV the problem is fixed on Edge, but:
 - Edge, Chrome, Opera: the back returns with the right button state and after 1 second refresh
 - Firefox: the back returns with the right button state and there is a very fast refresh

**Comment by peregrineshahin** [comment]
I think the right button state does not return correctly before the refresh if the issue reproduces on edge for you on master

Maybe you mistyped that the button returns the correct state

If master produce wrong state on a certain browser this addition should make it only return the correct state after the refresh/reload

Regarding the speed I think a more speedup can be obtained by moving the script tag even up a bit above of the already rendered html elements (I will force push that tonight)

Note that no refreshing (if the correct state took place) has been tried by changing the state to the correct one whitout a reload and failed because we don't get the correct existing state for buttons most of the times when asking for the state of the buttons due to cache conflict with the renderer I think

Also refreshing even if you have the right state is not 100% pointless as the values of the test page when pressing back will be up-to-date

**Comment by ppigazzini** [comment]
> I think the right button state does not return correctly before the refresh if the issue reproduces on edge for you on master
> 
> Maybe you mistyped that the button returns the correct state

No. On my PC and on my Windows Sandbox, Edge returns the correct state (even with PROD) after running at least once DEV with this PR.

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
IMO this is faster. All the "back"s but the first one didn't need the refresh.

**Comment by ppigazzini** [comment]
DEV updated.

A little off topic.
Google analytics was added in https://github.com/glinscott/fishtest/commit/10a5200f4e5fd8314f5149bdb208c2cee269f5c5
I don't know if someone is still checking the analytics and if make sense to still have the script.

There is a new faster script for modern browser:
https://developers.google.com/analytics/devguides/collection/analyticsjs/

Edge with default setting stops the tracking:
image

**Comment by ppigazzini** [comment]
PROD updated by hand with this PR to collect feedbacks.

I agree to drop google analytics.

**Comment by vondele** [comment]
I agree with dropping google analytics, I'm not aware of this being used.

**Comment by ppigazzini** [comment]
DEV updated. This "back" refresh doesn't work for the user page, eg
https://dfts-0.pigazzini.it/tests/user/fauzi2

**Comment by ppigazzini** [comment]
@peregrineshahin why do you have closed the PR?

**Comment by peregrineshahin** [comment]
because I'm having too much trouble wrapping my head to squash in one commit
I pushed from backButton-my to backButton branch and boom the PR is closed automatically
At least now I can squash in one commit

**Comment by peregrineshahin** [comment]
Ready for merge/review

**Comment by ppigazzini** [comment]
DEV updated.
The refresh now work on the user page.
Unfortunately it works on the new test page too, so after a "back" the refresh cleans the written fields.

**Comment by ppigazzini** [comment]
LGTM on Edge, Chrome, Opera, Firefox (all Windows desktop).
PROD updated by hand to collect feedbacks from the users (@vdbergh)

**Comment by vdbergh** [comment]
Yes it works on firefox on Linux. There is indeed a small delay before the button shows the correct state after "back" but it is not really a problem.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin :)

**Pull request merged**
