### PR TITLE
Fix spsa tunes show as `was undefined` in notifications and some clea…

### PR DESCRIPTION
**Pull request by peregrineshahin**
…nups

### CODE REVIEW

**Comment by peregrineshahin** [comment]
just missed up appending html elements instead of creating elements them, draft for the moment

**Comment by ppigazzini** [comment]
Started on DEV some tests (SPSA, NumGames, SPRT) with expected results.

**Comment by ppigazzini** [comment]
LGTM
image

**Comment by ppigazzini** [comment]
The Non-regression tests are fine as well.

image

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin , nice clean-up :)

**Pull request merged**
