### PR TITLE
Rough fix for empty book problem

### PR DESCRIPTION
**Pull request by Stefano80**
Add a cleanup function to the worker, such that obvious problems with opening books are fixed.

Still to do: add some check for signature or hash.

### CODE REVIEW

**Comment by Stefano80** [comment]
@ppigazzini @ianfab could you give it a look? I think I covered all cases, but it would be good to have a second opinion and maybe have it checked on the dev or multivariant server. In the meanwhile, I am trying to build a local test case.

**Comment by Stefano80** [comment]
Ok, now in the folder `./test` you can find a very simple python script which try to emulate some possible cases. I would really appreciate if you would try to let it run locally and report any problems.

Enough for today.

**Comment by Stefano80** [comment]
Now that the waters have calmed, could @ppigazzini @noobpwnftw @Rocky640 give a check on this? I have a small test scripts, I would build on to go in the direction of having continuous integration for fishtest.

This is a fix for [this issue](Rocky640 ).

**Comment by noobpwnftw** [comment]
The fix makes sense and I've tested it by deleting the book files and restart my workers, I do not see any corrupted books now.

**Comment by Stefano80** [comment]
Ok, thanks. I will give this time until Tuesday then I will merge if no one complains. I am still not yet certain of whether I want to merge the test too, but I think is a basic starting point to create a CI framework here, so I am more for merging, although it is a bit temporary.

**Comment by Stefano80** [comment]
I have to skip this, I had some issues at home and I am leaving for vacation and business. Will be back in ten days.

**Comment by Stefano80** [comment]
I removed the test, this is ready to merge.

**Comment by Stefano80** [comment]
@ppigazzini : I dont feel like merging my own patches. If you think this is still needed, you can merge it now.

**Pull request merged**
