### PR TITLE
Stop the heartbeat when stopping the worker

### PR DESCRIPTION
**Pull request by noobpwnftw**
Trigger heartbeat thread exit on exceptions.

### CODE REVIEW

**Comment by vondele** [comment]
I assume that might be the fix for the workers that are seemingly stuck indefinitely?

**Comment by noobpwnftw** [comment]
Yes.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
Merged, raised the worker version to trigger the update.
Thank you @noobpwnftw :)

**Comment by vdbergh** [comment]
An obvious question however is why a worker sometimes get stuck in the first place...

**Comment by vondele** [comment]
if the fleet launches, certain things could timeout (like net download from server), which could cause an exception building the code. It would be interesting to know what it is, but it most likely is some contention/timeout issue somewhere.

**Pull request merged**
