### PR TITLE
Various style changes

### PR DESCRIPTION
**Pull request by dav1312**
Dark mode alerts

image

---

New pagination colors

image

image

---

Use color-scheme dark in dark mode

image

image

---

Use more Bootstrap variables

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
New test page, light theme, the selected option has white text.
image

**Comment by dav1312** [comment]
Oh yeah lol I forgot to update that variable hehe

**Comment by peregrineshahin** [comment]
this solves this https://github.com/glinscott/fishtest/pull/1407#issuecomment-1235706291
and white background color if you pick option from autocomplete

**Comment by ppigazzini** [comment]
PROD updated by hand to collect feedbacks.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, thank you @dav1312 :)

**Pull request merged**
