### PR TITLE
Improve readability

### PR DESCRIPTION
**Pull request by zungur**
Functionally equivalent. In preparation for some future changes to the signup function

### CODE REVIEW

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
Tested OK on DEV; PROD updated, thank you @zungur :)

**Comment by ppigazzini** [comment]
Let me know if you want also your real name in AUTHORS file.

**Comment by zungur** [comment]
Yes please, the name is Onur Zungur. Thank you :)

**Comment by ppigazzini** [comment]
Done ;)

**Pull request merged**
