### PR TITLE
PR2: Extract the event fields directly from the data base. 

### PR DESCRIPTION
**Pull request by vdbergh**
To make this work the action database should be converted using the script `utils/convert_actions.py`.

Note: this script does not delete any data. Still would be good to temporarily keep a backup of the current action database, just in case something goes wrong.

This PR has no user visible changes.

### CODE REVIEW

**Comment by vdbergh** [comment]
Made it WIP since I need to think about a possible issue.

**Comment by vdbergh** [comment]
Unwipped!

**Comment by ppigazzini** [comment]
DEV updated.

```
usr00@dfts-0:~$ sudo systemctl stop cron
usr00@dfts-0:~$ sudo systemctl stop fishtest@{6543..6544}
usr00@dfts-0:~$ ${VENV}/bin/python3 fishtest/server/utils/convert_actions.py | tee convert_actions.py.log
Starting conversion...
Actions converted: 681041.
Conversion finished in 1597.95 seconds. Time per run: 2.35ms.
usr00@dfts-0:~$ sudo systemctl start fishtest@{6543..6544}
usr00@dfts-0:~$ sudo systemctl start cron
```

**Comment by vdbergh** [comment]
Everything seems to be ok with the converted db.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
PROD updated, DB backupped, starting collection conversion.

**Comment by ppigazzini** [comment]
@vdbergh collection converted :)

**Comment by vdbergh** [comment]
Thanks! Next step!

**Pull request merged**
