### PR TITLE
Fix error for stop/delete when not logged in

### PR DESCRIPTION
**Pull request by tomtor**
Follow up to #245

### CODE REVIEW

**Comment by vondele** [comment]
somewhat related, if I press approve when not logged in, I'm redirected to login, but after logging in I'm back to the main screen, without the test being approved.

**Comment by tomtor** [comment]
@vondele Yes, I know that is hard(er) to fix...

**Comment by ppigazzini** [comment]
dev-server and workers updated.

**Comment by tomtor** [comment]
The bug behaviour is the same as in #245. I checked on the dev server, it is OK to merge.

**Comment by ppigazzini** [comment]
Production server updated.

**Pull request merged**
