### PR TITLE
Remove unused admins group code and fix Travis build

### PR DESCRIPTION
**Pull request by tomtor**
Fix also multiple appends to this group.

See https://github.com/glinscott/fishtest/pull/390#issuecomment-529240655

And fix Travis build by Python 2.7 compatible numpy/scipy

### CODE REVIEW

**Comment by ppigazzini** [comment]
@tomtor dev server (dfts-0) updated w/ this PR.
I'm not able to add a new test, the server ask my a new login.

Thanks for the Travis fix :)

**Comment by tomtor** [comment]
@ppigazzini Should work now, I forgot to remove some code...

**Comment by ppigazzini** [comment]
@tomtor I played w/ all the functions, it seems working fine.
Let me know if is OK to be merged.

**Comment by tomtor** [comment]
Thanks again for testing 👍

I am really too optimistic with small code changes and do insufficient testing and expect them to work the first time. It is great that you are much more disciplined and I will try to improve in that area 😉

Yes, please merge.

**Comment by ppigazzini** [comment]
@tomtor production server updated, hoping to have tested fine :)

**Comment by ppigazzini** [comment]
@tomtor [wiki](https://github.com/glinscott/fishtest/wiki/Fishtest-server-setup) update with scripts to be more disciplined.
Just joking :)

**Pull request merged**
