### PR TITLE
Fix illegible batch size calc

### PR DESCRIPTION
**Pull request by dubslow**
master is so hard to read that it was faster to fix it than to verify the correctness of the fix

no functional change

### CODE REVIEW

**Comment by vondele** [comment]
convention is that you format your patches with black...

**Comment by dubslow** [comment]
if the autoformatter insists on such nonsense, then better to use intermediate variables to clear it up for humans as well as silly autoformatters.

but that's a moot debate anyways, since the utility function for exactly this purpose already existed, this stupid PR only uses it where it already should have been used

**Review by ppigazzini — APPROVED** [review]
TBB (to be blackened)

**Comment by ppigazzini** [comment]
PROD updated, thank you @dubslow :)

I confess that in the past I was a bit lazy to perform the autoformatting, thanks to your periodic gentle reminders the code is always in a great shape now :)

**Pull request merged**
