### PR TITLE
Show more info on user profile page

### PR DESCRIPTION
**Pull request by tomtor**
Implements part of #293

### CODE REVIEW

**Comment by ppigazzini** [comment]
dev-server and workers updated.

**Comment by tomtor** [comment]
@ppigazzini Could you please combine the test with #295 ?

**Comment by ppigazzini** [comment]
@tomtor done

**Comment by ppigazzini** [comment]
@tomtor let me know if this is ready to be merged.

**Comment by tomtor** [comment]
@ppigazzini It is ready...

**Comment by ppigazzini** [comment]
Production server updated.
@tomtor Thank you!

**Pull request merged**
