### PR TITLE
Quick fix for #1641

### PR DESCRIPTION
**Pull request by vdbergh**
Not tested.

### CODE REVIEW

**Comment by ppigazzini** [comment]
With SPRT LTC the num_games is changed accordingly, I'm not able to reschedule that test, though. The back button to submit a new test works fine.

"
run = {'_id': ObjectId('644ce20b7f7bb4d09f0bc02d'), 'args': {'base_tag': 'master', 'new_tag': 'master', 'base_net': 'nn-e1fb1ade4432.nnue', 'new_net': 'nn-e1fb1ade4432.nnue', 'num_games': 799998, 'tc': '60+0.6', 'new_tc': '60+0.6', 'book': 'UHO_XXL_+0.90_+1.19.epd', 'book_depth': '8', 'threads': 1, 'resolved_base': '41f50b2c83a0ba36a2b9c507c1783e57c9b13485', 'resolved_new': '41f50b2c83a0ba36a2b9c507c1783e57c9b13485', 'msg_base': 'Update default net to nn-e1fb1ade4432.nnue', 'msg_new': 'Update default net to nn-e1fb1ade4432.nnue', 'base_options': 'Hash=64 Use NNUE=true', 'new_options': 'Hash=64 Use NNUE=true', 'info': '#1646 SPRT LTC', 'base_signature': '3714847', 'new_signature': '3714847', 'username': 'user01', 'tests_repo': 'https://github.com/official-stockfish/Stockfish', 'auto_purge': False, 'throughput': 100, 'itp': 100, 'priority': 10, 'adjudication': True, 'sprt': {'alpha': 0.05, 'beta': 0.05, 'elo0': 0.5, 'elo1': 2.5, 'elo_model': 'normalized', 'state': '', 'llr': 0, 'batch_size': 3, 'lower_bound': -2.9444389791664403, 'upper_bound': 2.9444389791664403, 'overshoot': {'last_update': 0, 'skipped_updates': 0, 'ref0': 0, 'm0': 0, 'sq0': 0, 'ref1': 0, 'm1': 0, 'sq1': 0}}}, 'start_time': datetime.datetime(2023, 4, 29, 9, 23, 23, 548000), 'last_updated': datetime.datetime(2023, 4, 29, 9, 23, 23, 548000), 'tc_base': 60.0, 'base_same_as_master': True, 'tasks': [], 'results': {'wins': 0, 'losses': 0, 'draws': 0, 'crashes': 0, 'time_losses': 0, 'pentanomial': [0, 0, 0, 0, 0]}, 'results_stale': False, 'approved': False, 'approver': '', 'finished': False, 'deleted': False, 'failed': False, 'is_green': False, 'is_yellow': False, 'results_info': {'style': '', 'info': ['LLR: 0.00 (-2.94,2.94) <0.50,2.50>', 'Total: 0 W: 0 L: 0 D: 0', 'Ptnml(0-2): 0, 0, 0, 0, 0']}}
"

**Comment by vdbergh** [comment]
BTW this is a bug fix! Not an enhancement!

**Comment by vdbergh** [comment]
> I'm not able to reschedule that test, though. The back button to submit a new test works fine.

I'll have a look.

**Comment by vdbergh** [comment]
There are some issues with this solution. I am going to close this and do it differently.

**Pull request closed without merging**
