### PR TITLE
Add live ELO scripts

### PR DESCRIPTION
**Pull request by tomtor**
written by Michel Van den Bergh

from http://hardy.uhasselt.be/Toga/live_elo.html

Required for #226 and future features

### CODE REVIEW

**Comment by tomtor** [comment]
@vdbergh I already removed the proxy on this PR. I will add a run_ info API at a later date for these gauges, once this is merged. 

I think many really like your live ELO page and don't consider it just a quick hack!

**Comment by tomtor** [comment]
@ppigazzini I have to fix a minor issue with the user parsing...

**Comment by ppigazzini** [comment]
@tomtor dev server updated to view the WIP

**Comment by tomtor** [comment]
@ppigazzini I did not add any new fields, estimated Elo was already there.

I fixed a minor issue just now, so if your refetch this PR on the dev server then we can test the final version.

**Comment by ppigazzini** [comment]
@tomtor dev server updated. Sorry, I wrote w/ too much syntheses. If I'm not wrong the @vdbergh page reports the same information of fishtest finished runs list, the only new information added is the estimated Elo. If my hypothesis is correct, in future we could add this new information (the estimated Elo) directly into the run box.

**Comment by tomtor** [comment]
@ppigazzini Ah, yes you are right.

**Comment by Stefano80** [comment]
Is work to do here?

**Comment by tomtor** [comment]
@Stefano80 It can be merged

**Comment by ppigazzini** [comment]
official server updated.
Thank you @tomtor

**Comment by tomtor** [comment]
@vdbergh Oops, thanks, I will fix that.

**Pull request merged**
